BEGIN;
INSERT INTO public.subjects (slug, name, description, color, sort_order)
VALUES ('g-kentei-c', 'G検定（JDLA ジェネラリスト検定） Set C',
        'JDLA G検定 対策 第3弾。シラバス2024（2024年11月試験より適用）準拠。Set A・B が扱っていないテーマを中心に構成。個人情報保護法は範囲外（保有資格のため意図的に除外）。本試験の再現ではなく学習用オリジナル。',
        '#0B5CAB', 52)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.categories (subject_id, name, color, sort_order)
SELECT s.id, v.name, v.color, v.sort_order
FROM public.subjects s
CROSS JOIN (VALUES
  ('1. 人工知能とは', '#58a6ff', 0),
  ('2. 人工知能をめぐる動向', '#79c0ff', 1),
  ('3. 機械学習の概要', '#3fb950', 2),
  ('4. ディープラーニングの概要', '#a371f7', 3),
  ('5. ディープラーニングの要素技術', '#d2a8ff', 4),
  ('6. ディープラーニングの応用例', '#f0883e', 5),
  ('7. AIの社会実装に向けて', '#e3b341', 6),
  ('8. AIに必要な数理・統計知識', '#39c5cf', 7),
  ('9. AIに関する法律と契約', '#f85149', 8),
  ('10. AI倫理・AIガバナンス', '#ff7b72', 9)
) AS v(name, color, sort_order)
WHERE s.slug = 'g-kentei-c'
ON CONFLICT (subject_id, name) DO NOTHING;
COMMIT;
BEGIN;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q1', '哲学者サールの区分で、AIは単なる道具ではなく、人間と同じように本物の意識や理解を持ちうるとする立場はどれか。', NULL, '["強いAI", "弱いAI", "特化型AI", "記号処理AI"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "AIが本物の意識や理解を持ちうるとする立場は？", "point": "「AIも本物の心・理解を持てる」とする立場なら、強いAI。", "kid": "弱いAIが「賢いフリの道具でいい」なのに対し、強いAIは「AIも人間と同じように本当に意識や理解を持てる」と考える立場。", "eg": "ロボットが「演じている」のか「本当に感じている」のか。本当に感じていると考えるのが強いAI。", "terms": [["強いAI", "AIも人間と同じ本物の意識や理解を持ちうるとする立場"], ["弱いAI", "意識は無くても、賢く振る舞う道具として役立てばよいとする立場"]], "think": "「本物の心・理解を持てる」とするなら強いAI。「道具として振る舞えれば十分」なら弱いAI。心の有無で分ける。", "vs": "弱いAIは道具として役立てばよいとする立場、特化型AIは特定の作業だけこなすAIの分類、記号処理AIは記号操作で動く古典的AIで、いずれも「本物の意識を持てるか」の立場ではない。", "usecase": "AGI(汎用人工知能)や意識をめぐる議論の出発点。AIに何をどこまで期待・懸念すべきかを整理する軸になる。", "opt": ["正解。AIも本物の意識や理解を持ちうるとするのが強いAI。", "意識は無くても道具として役立てばよいとする立場で、強いAIの逆。", "特定の作業だけこなすAIの分類で、意識の有無の立場ではない。", "記号操作で動く古典的なAIの説明で、意識を持てるかの立場ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='1. 人工知能とは'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q2', 'AIの能力段階のうち、人間が特徴を設計しなくても、データから「注目すべき特徴」そのものを自ら見つけ出して学習する最も進んだ段階はどれか。', NULL, '["特徴量そのものをデータから自ら学習する段階", "人間が設計した特徴量を使って対応を学習する段階", "入力に応じた振る舞いを人間が全て定義する段階", "決められた振る舞いしかしない単純な制御の段階"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "特徴そのものを自ら見つけて学習する、最も進んだAIの段階は？", "point": "「注目すべき特徴まで自分で見つけて学ぶ」なら、特徴表現学習（ディープラーニング相当・最上位）。", "kid": "昔のAIは「どこに注目するか(特徴)」を人間が指定していた。ディープラーニングは、その注目点まで自分でデータから見つける。人の手を最も離れた段階。", "eg": "猫を見分けるのに「ヒゲに注目して」と人が教えるのが従来。「何に注目すれば猫と分かるか」まで自分で気づくのがこの段階。", "terms": [["特徴表現学習", "データから特徴量そのものを自ら学習する段階。ディープラーニングが該当し、AIレベル分類の最上位"], ["特徴量", "予測の手がかりになる項目。従来は人が設計していた"]], "think": "「特徴量まで自分で学ぶ」なら特徴表現学習(最上位)。人が特徴を設計する段階や、決められた動きだけの制御より進んでいる。", "vs": "人が設計した特徴で学ぶ段階、振る舞いを人が全部定義する段階、決められた動きだけの制御は、いずれも特徴を自分で見つける最上位より前の段階。", "usecase": "「なぜディープラーニングが強いか」の核心。特徴設計の職人技が要らなくなり、画像・音声など生データから直接学べるようになった。", "opt": ["正解。特徴量そのものを自ら学習する最も進んだ段階。", "人が設計した特徴を使う段階で、特徴自体は自分で見つけていない。", "振る舞いを人が全部定義する段階で、学習していない。", "決められた動きだけの単純な制御で、最も単純な段階。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='1. 人工知能とは'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q3', '知能は頭の中の記号処理だけでは成り立たず、身体を通じて環境と関わる経験があってこそ育つ、という考え方を指す語はどれか。', NULL, '["身体性", "記号接地", "フレーム問題", "チューリングテスト"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "知能には身体を通じた環境との関わりが必要、とする考え方は？", "point": "「知能は身体を通じた経験があって育つ」とする考えなら、身体性。", "kid": "「甘い」「重い」を本当に理解するには、実際に舐めたり持ち上げたりする身体の経験が要る、という考え方。頭の中の記号処理だけでは足りないとする立場。", "eg": "泳ぎ方を本で読むだけでは泳げず、水に入って体で覚える必要がある、あの感覚。", "terms": [["身体性", "知能は身体を通じて環境と関わる経験があってこそ育つ、という考え方"], ["記号接地（シンボルグラウンディング）", "記号を実世界の意味に結びつけられない問題。身体性はその解決の鍵とされる"]], "think": "「身体を通じた経験が知能に要る」なら身体性。記号だけでは意味に届かないという記号接地問題と深く関わる。", "vs": "記号接地は記号と意味が結びつかない問題そのもの、フレーム問題は考える範囲を絞れない難問、チューリングテストは知能の判定方法で、いずれも身体性の考え方そのものではない。", "usecase": "ロボットやAIが実世界を本当に理解するには、センサーや身体を通じた相互作用が要る、という研究の方向づけになる。", "opt": ["正解。身体を通じた経験があって知能が育つとする考え方。", "記号と意味が結びつかない問題で、身体性という考え方そのものではない。", "考える範囲を絞れない難問で、身体性ではない。", "知能の判定方法で、身体性の考え方ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='1. 人工知能とは'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q4', '「高度な論理的思考はAIに実装しやすいのに、歩く・物をつかむといった幼児でもできる感覚運動の能力ほど実装が難しい」という逆説を指す語はどれか。', NULL, '["モラベックのパラドックス", "フレーム問題", "シンボルグラウンディング問題", "組合せ爆発"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "高度な論理はAIに簡単なのに、歩く・つかむは難しい、という逆説は？", "point": "「難しい論理は簡単、簡単な運動は難しい」という逆説なら、モラベックのパラドックス。", "kid": "チェスや計算のような「頭のいい人ほど難しい」ことはAIには意外と簡単。逆に、歩く・物をつかむような幼児でもできることほどAIには難しい。この直感と逆の現象。", "eg": "電卓は難しい計算を一瞬でこなすのに、コップを転ばさず持ち上げるロボットを作る方がずっと大変、というちぐはぐさ。", "terms": [["モラベックのパラドックス", "高度な推論はAIに実装しやすく、感覚運動の能力ほど実装が難しいという逆説"], ["身体性", "感覚運動が知能に不可欠だとする考え。この逆説と関わる"]], "think": "「論理は簡単・感覚運動は難しい」という直感と逆の話ならモラベックのパラドックス。考える範囲を絞れないフレーム問題とは別。", "vs": "フレーム問題は考える範囲を絞れない難問、シンボルグラウンディング問題は記号と意味が結びつかない問題、組合せ爆発は場合の数が急増する現象で、いずれもこの逆説ではない。", "usecase": "ロボット開発の難しさの本質を言い当てる言葉。事務作業の自動化は進んでも、身体を使う作業の自動化が遅れる理由の説明になる。", "opt": ["正解。高度な推論は簡単で、感覚運動ほど難しいという逆説。", "考える範囲を絞れない難問で、この逆説ではない。", "記号と意味が結びつかない問題で、感覚運動の逆説ではない。", "場合の数が急増する現象で、この逆説とは別。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='1. 人工知能とは'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q5', '1970年代に作られ、患者の症状から感染症を診断し、抗生物質を提案した代表的なエキスパートシステムはどれか。', NULL, '["MYCIN", "ELIZA", "AlphaGo", "word2vec"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "感染症の診断を支援した代表的なエキスパートシステムは？", "point": "「感染症の診断を助けた第2次ブームのエキスパートシステム」なら、MYCIN。", "kid": "「熱があって、この菌が疑われるなら、この抗生物質」といった医師のルールを大量に詰め込み、感染症の診断を助けた初期の専門家システム。", "eg": "ベテラン医師の判断マニュアルを一冊のプログラムにして、診断を手伝わせたようなもの。", "terms": [["MYCIN", "患者の症状から感染症を診断し治療を提案した、代表的なエキスパートシステム"], ["エキスパートシステム", "専門家の知識をルールとして詰め込み、判断をまねる仕組み"]], "think": "「感染症診断・ルールベース・第2次ブーム」ならMYCIN。おうむ返しの対話プログラムELIZAとは目的が違う。", "vs": "ELIZAはおうむ返しで対話を装った初期プログラム、AlphaGoは囲碁AI、word2vecは単語をベクトルにする手法で、いずれも感染症診断のエキスパートシステムではない。", "usecase": "専門家の知識をルール化する試みの代表例。判断根拠を説明できる強みと、知識をルール化する難しさ(知識獲得のボトルネック)の両方を示す。", "opt": ["正解。感染症の診断を支援した代表的なエキスパートシステム。", "おうむ返しで対話を装った初期プログラムで、診断システムではない。", "囲碁AIで、感染症診断のシステムではない。", "単語をベクトルにする手法で、エキスパートシステムではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q6', '探索で、必ず最適とは限らないが、経験則を使って「良さそうな方向」を優先し、効率よく答えに近づく手がかりを指す語はどれか。', NULL, '["ヒューリスティック", "ブルートフォース", "バックプロパゲーション", "アノテーション"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "経験則で「良さそうな方向」を優先し、探索を効率化する手がかりは？", "point": "「経験則で良さそうな方を優先して探索を効率化する目安」なら、ヒューリスティック。", "kid": "すべてをしらみつぶしに調べるのではなく、「たぶんこっちが近い」という経験則の目安を使って、当たりをつけて効率よく探す考え方。", "eg": "知らない町で駅を探すとき、人通りの多い方へ行けば近い、という当たりのつけ方。", "terms": [["ヒューリスティック", "必ず最適とは限らないが、経験則で良さそうな方向を優先して効率よく探す目安"], ["ブルートフォース（総当たり）", "可能性を全部調べる方法。確実だが時間がかかる"]], "think": "「経験則で当たりをつけて効率化」ならヒューリスティック。全部調べる総当たり(ブルートフォース)とは逆の発想。", "vs": "ブルートフォースは全部調べる総当たり、バックプロパゲーションはニューラルネットの学習手法、アノテーションは正解ラベルを付ける作業で、いずれも探索の経験則ではない。", "usecase": "選択肢が多すぎて全部は調べられない探索(経路探索・ゲームAIなど)で、現実的な時間で良い答えに近づくために使う。", "opt": ["正解。経験則で良さそうな方を優先し効率化する目安がヒューリスティック。", "可能性を全部調べる総当たりで、経験則で絞る発想とは逆。", "ニューラルネットの学習手法で、探索の経験則ではない。", "正解ラベルを付ける作業で、探索の目安ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q7', '概念やその関係、用語の意味を、コンピュータが扱えるように体系立てて記述したものを指す語はどれか。', NULL, '["オントロジー", "データベース", "ヒストグラム", "ハイパーパラメータ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "概念や用語の意味・関係を体系立てて記述したものは？", "point": "「概念とその関係・意味を体系立てて記述したもの」なら、オントロジー。", "kid": "「犬は動物」「しっぽは犬の一部」のように、言葉の意味や関係をきちんと整理して、コンピュータが扱えるようにした知識の体系。", "eg": "分野の用語をきれいに整理した「概念の地図・辞書」のようなもの。", "terms": [["オントロジー", "概念やその関係、用語の意味を体系的に記述したもの。知識をコンピュータで扱う土台"], ["意味ネットワーク", "概念を関係の線でつないで表す、知識表現の一形態"]], "think": "「概念と関係・意味を体系立てて記述」ならオントロジー。単にデータを表に貯めるデータベースとは目的が違う。", "vs": "データベースはデータを整理して貯める仕組み、ヒストグラムはデータの分布を棒で見る図、ハイパーパラメータは人が決める設定値で、いずれも概念の意味体系ではない。", "usecase": "医療や検索など、用語の意味をそろえて機械に理解させたい分野で使う。知識をルール化する第2次ブームの中心テーマの一つ。", "opt": ["正解。概念や用語の意味・関係を体系立てて記述したのがオントロジー。", "データを整理して貯める仕組みで、概念の意味体系ではない。", "データの分布を棒で見る図で、知識の記述ではない。", "人が決める設定値で、概念の体系ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q8', '1980年代に日本が国家プロジェクトとして推進した、論理推論を高速に行うコンピュータの開発計画はどれか。', NULL, '["第五世代コンピュータ", "ダートマス会議", "ImageNet", "GPU"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "1980年代に日本が推進した、論理推論を高速化する国家プロジェクトは？", "point": "「1980年代・日本の国家プロジェクト・論理推論の高速化」なら、第五世代コンピュータ。", "kid": "1980年代に日本が国を挙げて取り組んだ、論理的な推論を高速に行うコンピュータを作る計画。当時は大きな期待を集めた。", "eg": "国が旗を振って「次世代の頭脳マシンを作ろう」と号令をかけた、あの一大プロジェクト。", "terms": [["第五世代コンピュータ", "1980年代に日本が推進した、論理推論を高速に行うコンピュータの国家開発計画"], ["第2次AIブーム", "知識をルール化するエキスパートシステムが盛んだった時期。この計画もその流れにある"]], "think": "「1980年代・日本・論理推論の国家計画」なら第五世代コンピュータ。AIの語源となったダートマス会議(1956年・米国)とは時代も国も違う。", "vs": "ダートマス会議は1956年にAIの語が生まれた会議、ImageNetは画像認識用の大規模データセット、GPUは並列計算が得意な演算装置で、いずれも日本の国家プロジェクトではない。", "usecase": "AIの歴史で、知識ベースのアプローチに大きく投資された時代の象徴。期待と現実のギャップ(ブームの浮沈)を学ぶ題材。", "opt": ["正解。1980年代に日本が推進した論理推論の国家プロジェクト。", "1956年にAIの語が生まれた会議で、日本の計画ではない。", "画像認識用の大規模データセットで、国家プロジェクトではない。", "並列計算が得意な演算装置で、開発計画そのものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q9', '2011年にアメリカのクイズ番組で人間のチャンピオンに勝利した、IBMの質問応答システムはどれか。', NULL, '["Watson", "MYCIN", "ELIZA", "Stable Diffusion"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "クイズ番組で人間王者に勝ったIBMの質問応答システムは？", "point": "「クイズ番組で人間チャンピオンに勝ったIBMの質問応答システム」なら、Watson。", "kid": "2011年、アメリカのクイズ番組で、膨大な知識から質問に答えて人間の王者を破ったIBMのシステム。自然な言葉の質問を理解して答えるのが特徴。", "eg": "早押しクイズで、人間の名人より速く正確に答えた“超物知りの回答マシン”。", "terms": [["Watson", "2011年にクイズ番組で人間チャンピオンに勝った、IBMの質問応答システム"], ["質問応答", "自然な言葉の質問を理解し、知識から答えを返すタスク"]], "think": "「クイズ番組・IBM・質問応答」ならWatson。感染症診断のMYCINや、おうむ返しのELIZAとは目的が違う。", "vs": "MYCINは感染症診断のエキスパートシステム、ELIZAはおうむ返しの対話プログラム、Stable Diffusionは画像生成AIで、いずれもクイズで人間に勝った質問応答システムではない。", "usecase": "大量の文書から答えを探す質問応答の実力を示した例。後に医療や企業の問い合わせ対応などへの応用が試みられた。", "opt": ["正解。クイズ番組で人間王者に勝ったIBMの質問応答システム。", "感染症診断のエキスパートシステムで、クイズの質問応答ではない。", "おうむ返しの対話プログラムで、質問応答システムではない。", "画像生成AIで、クイズに答えるシステムではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q10', '2016年に囲碁のトップ棋士に勝利し、第3次AIブームを象徴する存在となった、ディープラーニングとモンテカルロ木探索を組み合わせたAIはどれか。', NULL, '["AlphaGo", "Deep Blue", "ELIZA", "BERT"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "2016年に囲碁のトップ棋士に勝った、深層学習と探索を組み合わせたAIは？", "point": "「2016年・囲碁でトップ棋士に勝利・深層学習＋モンテカルロ木探索」なら、AlphaGo。", "kid": "2016年、それまで難しいとされた囲碁で、世界トップ級の棋士に勝ったAI。盤面を見抜く目(ディープラーニング)と、先を読む探索(モンテカルロ木探索)を組み合わせている。", "eg": "「勘(深層学習で盤面を評価)」と「読み(探索で先を計算)」の両方を備えた、囲碁の超一流棋士。", "terms": [["AlphaGo", "2016年に囲碁のトップ棋士に勝ったAI。深層学習とモンテカルロ木探索を組み合わせた"], ["モンテカルロ木探索", "ランダムな試行を重ねて手の勝率を見積もる探索。AlphaGoの中核の一つ"]], "think": "「囲碁・2016年・深層学習＋探索」ならAlphaGo。チェスで勝ったDeep Blueは1997年で、囲碁でも手法も違う。", "vs": "Deep Blueは1997年にチェスで勝ったAI、ELIZAはおうむ返しの対話プログラム、BERTは文の意味を理解する言語モデルで、いずれも囲碁でトップ棋士に勝ったAlphaGoではない。", "usecase": "ディープラーニングの実力を世界に印象づけた出来事。強化学習と探索の組み合わせが、複雑な意思決定に有効だと示した。", "opt": ["正解。2016年に囲碁でトップ棋士に勝った深層学習＋探索のAI。", "1997年にチェスで勝ったAIで、囲碁のAlphaGoとは別。", "おうむ返しの対話プログラムで、囲碁AIではない。", "文の意味を理解する言語モデルで、囲碁で勝ったAIではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q11', '気温から売上のように、連続する数値そのものを予測する教師あり学習のタスクはどれか。', NULL, '["回帰", "分類", "クラスタリング", "次元削減"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "連続する数値そのものを予測する教師あり学習は？", "point": "「連続した数値そのものを予測する」なら、回帰。", "kid": "「明日の気温は何度」「この家はいくら」のように、数値そのものを当てるのが回帰。「犬か猫か」のようにグループに振り分けるのは分類。", "eg": "体重計の目盛り（数値）を当てるのが回帰、通販の「S/M/L」を当てるのが分類。", "terms": [["回帰", "連続する数値そのものを予測する教師あり学習。売上や価格の予測など"], ["分類", "どのグループ(クラス)かを当てる教師あり学習。回帰と対になる"]], "think": "「数値そのものを当てる」なら回帰、「どのグループかを当てる」なら分類。出力が数値かグループかで見分ける。", "vs": "分類はグループを当てる、クラスタリングは正解なしでまとまりを作る教師なし、次元削減は項目を減らす手法で、いずれも数値そのものを予測する回帰ではない。", "usecase": "需要予測、価格推定、来店客数の見積もりなど、「いくつになるか」を当てたい場面で使う教師あり学習の基本。", "opt": ["正解。連続する数値そのものを予測するのが回帰。", "どのグループかを当てるタスクで、数値そのものの予測ではない。", "正解なしでまとまりを作る教師なしで、数値予測ではない。", "項目を減らす手法で、数値そのものの予測ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q12', '少量の正解ラベル付きデータと、大量のラベルなしデータを組み合わせて学習する方法はどれか。', NULL, '["半教師あり学習", "教師あり学習", "強化学習", "転移学習"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "少量のラベル付きと大量のラベルなしを組み合わせて学ぶ方法は？", "point": "「少しの正解ラベル＋大量のラベルなしで学ぶ」なら、半教師あり学習。", "kid": "正解ラベルを付ける作業は大変。そこで、少しだけラベルを付けたデータと、大量のラベルなしデータを合わせて学ぶ。ラベル付けの手間を減らせる。", "eg": "数問だけ模範解答を見て、あとは大量の問題を自習して要領をつかむ、あの勉強法。", "terms": [["半教師あり学習", "少量のラベル付きデータと大量のラベルなしデータを組み合わせて学ぶ方法"], ["アノテーション", "データに正解ラベルを付ける作業。コストが高いため半教師ありが役立つ"]], "think": "「少しのラベル＋大量のラベルなし」なら半教師あり学習。全部にラベルが要る教師あり、報酬で学ぶ強化学習とは別。", "vs": "教師あり学習は全データに正解ラベルが要る、強化学習は報酬で試行錯誤する、転移学習は学んだ知識を別タスクに使い回す考え方で、いずれも「少しのラベル＋大量のラベルなし」ではない。", "usecase": "ラベル付けのコストが高い場面(医療画像など)で、少ないラベルを有効活用して精度を上げるのに役立つ。", "opt": ["正解。少しのラベル付きと大量のラベルなしを組み合わせるのが半教師あり学習。", "全データに正解ラベルが要る学習で、ラベルなしを主に使うわけではない。", "報酬で試行錯誤する学習で、ラベルの話ではない。", "学んだ知識を別タスクに使い回す考え方で、これとは別。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q13', 'データを、近いものどうしから順に少しずつまとめていき、まとまり方を樹形図（デンドログラム）で表す教師なしの手法はどれか。', NULL, '["階層的クラスタリング", "k-means法", "ロジスティック回帰", "主成分分析"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "近いものから順にまとめ、樹形図で表す教師なしの手法は？", "point": "「近いものから順にまとめ、樹形図で表す」なら、階層的クラスタリング。", "kid": "似たデータどうしを、一番近いペアから順にくっつけていって、まとまり方を枝分かれの図(樹形図)で表す。グループ数を最初に決めなくてよいのが特徴。", "eg": "家系図を逆にたどるように、近い個体から順に合流させて“系統図”を作るイメージ。", "terms": [["階層的クラスタリング", "近いものから順にまとめ、まとまり方を樹形図(デンドログラム)で表す教師なしの手法"], ["k-means法", "最初にグループ数kを決めて分ける、非階層的なクラスタリング"]], "think": "「近い順にまとめて樹形図」なら階層的クラスタリング。最初にグループ数を決めるk-meansとは分け方が違う。", "vs": "k-means法は最初にグループ数を決める非階層的な分け方、ロジスティック回帰は分類、主成分分析は次元削減で、いずれも樹形図で表す階層的クラスタリングではない。", "usecase": "グループ数が事前に分からないときに、まとまり方の全体像を樹形図で見たい場面で使う。遺伝子や顧客の分類などで役立つ。", "opt": ["正解。近いものから順にまとめ樹形図で表すのが階層的クラスタリング。", "最初にグループ数を決める非階層的な分け方で、樹形図は作らない。", "グループに振り分ける分類で、まとまりを作る教師なしではない。", "項目を減らす次元削減で、クラスタリングではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
COMMIT;
BEGIN;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q14', '数十次元のような高次元データを、点どうしの近さを保ったまま2次元の散布図に落として可視化する手法はどれか。', NULL, '["t-SNE", "線形回帰", "ブースティング", "アノテーション"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "高次元データを、近さを保って2次元に落として可視化する手法は？", "point": "「高次元データを近さを保って2次元に落として見える化する」なら、t-SNE。", "kid": "何十個もの項目を持つデータは、そのままでは絵にできない。t-SNEは、近いデータが近くに来るよう工夫して2次元の散布図に落とし、かたまり(クラスタ)を目で見えるようにする。", "eg": "立体的な模型を、影絵のように平面に写しても“近いものは近く”見えるように工夫して投影する、あのイメージ。", "terms": [["t-SNE", "高次元データを、点どうしの近さを保ちつつ2次元などに落として可視化する手法"], ["次元削減", "項目(次元)を減らす手法の総称。t-SNEは可視化に特化した一種"]], "think": "「高次元を2次元にして可視化・近さを保つ」ならt-SNE。数値を予測する回帰や、モデルを束ねるブースティングとは目的が違う。", "vs": "線形回帰は数値を予測する手法、ブースティングは学習器を順に足す手法、アノテーションは正解ラベルを付ける作業で、いずれも高次元の可視化手法ではない。", "usecase": "学習したデータや特徴量が、うまくグループに分かれているかを目で確かめたいときに使う。分析結果の見える化に役立つ。", "opt": ["正解。高次元データを近さを保って2次元に落として可視化するのがt-SNE。", "数値を予測する手法で、可視化のための次元削減ではない。", "学習器を順に足す手法で、可視化ではない。", "正解ラベルを付ける作業で、可視化手法ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q15', 'モデルの設定値（ハイパーパラメータ）の候補を組み合わせて総当たりで試し、最も成績の良い組を探す方法はどれか。', NULL, '["グリッドサーチ", "誤差逆伝播法", "データ拡張", "早期終了"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "ハイパーパラメータの候補を総当たりで試し、最良の組を探す方法は？", "point": "「設定値の候補を総当たりで試して最良を探す」なら、グリッドサーチ。", "kid": "学習の設定値(木の深さや学習率など)を、候補の組み合わせを一つずつ全部試して、一番成績の良かった組を選ぶやり方。しらみつぶしなので確実だが時間がかかる。", "eg": "料理の味付けを、塩と砂糖の量の組み合わせを表にして全部作って試し、一番おいしい配合を選ぶ、あの探し方。", "terms": [["グリッドサーチ", "ハイパーパラメータの候補を組み合わせて総当たりで試し、最良の組を探す方法"], ["ハイパーパラメータ", "学習で自動調整されず、人が事前に決める設定値。木の深さや学習率など"]], "think": "「設定値の総当たり探索」ならグリッドサーチ。学習そのものの計算(誤差逆伝播)や、データを増やすデータ拡張とは目的が違う。", "vs": "誤差逆伝播法は重みを学習する計算、データ拡張はデータの水増し、早期終了は学習を途中で止める手法で、いずれも設定値の総当たり探索ではない。", "usecase": "どの設定値がよいか見当がつかないとき、確実に良い組を見つけるために使う。候補が多いと時間がかかるので、ランダム探索と使い分ける。", "opt": ["正解。設定値の候補を総当たりで試して最良を探すのがグリッドサーチ。", "重みを学習する計算で、設定値の探索ではない。", "データを水増しする手法で、設定値の探索ではない。", "学習を途中で止める手法で、総当たり探索ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q16', '本来モデルが使えないはずの「答えにつながる情報」が訓練データに紛れ込み、検証では高得点なのに本番で急に当たらなくなる問題はどれか。', NULL, '["データリーケージ", "過学習", "勾配消失", "コールドスタート問題"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "答えにつながる情報が訓練に紛れ込み、本番で急に当たらなくなる問題は？", "point": "「答えの手がかりが訓練に漏れて、検証は高得点だが本番で崩れる」なら、データリーケージ。", "kid": "本来使えないはずの「答えに直結する情報」がこっそり訓練データに混ざると、検証では出来すぎるほど当たる。でも本番ではその情報が無く、急に当たらなくなる。カンニングがバレた状態。", "eg": "模試で答えを盗み見て満点を取っても、本番では答えが手元にないので点が取れない、あの落とし穴。", "terms": [["データリーケージ", "答えにつながる情報が訓練データに紛れ込み、評価を過大にしてしまう問題"], ["過学習", "訓練データに合わせすぎて初見で落ちる別の問題。原因が違う"]], "think": "「検証は高得点なのに本番で崩れる・答えの漏れ」ならデータリーケージ。訓練に合わせすぎる過学習とは原因が違う。", "vs": "過学習は訓練データに合わせすぎる問題、勾配消失は深い層で学習の信号が消える問題、コールドスタート問題はおすすめの初期データ不足で、いずれも答えの情報が漏れるデータリーケージではない。", "usecase": "「検証では良かったのに本番でダメ」の代表原因。前処理で未来の情報や答えを含めていないか点検する、実務の重要チェック項目。", "opt": ["正解。答えの情報が訓練に漏れて評価が過大になるのがデータリーケージ。", "訓練データに合わせすぎる問題で、答えの漏れとは原因が違う。", "深い層で学習の信号が消える問題で、この問題とは別。", "おすすめの初期データ不足の問題で、答えの漏れではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q17', '単体では精度の高くない複数のモデルを組み合わせ、全体として高い精度を得る手法の総称はどれか。', NULL, '["アンサンブル学習", "ハイパーパラメータ探索", "データクレンジング", "次元削減"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "複数のモデルを組み合わせて精度を上げる手法の総称は？", "point": "「複数のモデルを組み合わせて精度を上げる総称」なら、アンサンブル学習。", "kid": "一つのモデルは間違えることがある。そこで複数のモデルを組み合わせ、多数決や平均で全体として賢くする。バギングやブースティングはこの仲間。", "eg": "一人の予想より、何人もの予想を持ち寄って多数決した方が当たりやすい、あの発想。", "terms": [["アンサンブル学習", "複数のモデルを組み合わせて、単体より高い精度を得る手法の総称"], ["バギング／ブースティング", "アンサンブル学習の代表的なやり方。並列に束ねるか、順に足すか"]], "think": "「複数モデルを組み合わせて精度を上げる総称」ならアンサンブル学習。バギングやブースティングを含む上位の考え方。", "vs": "ハイパーパラメータ探索は設定値を探す作業、データクレンジングはデータを整える前処理、次元削減は項目を減らす手法で、いずれも複数モデルを束ねるアンサンブル学習ではない。", "usecase": "コンペや実務で精度を一段上げたいときの定番。ランダムフォレストや勾配ブースティングとして広く使われる。", "opt": ["正解。複数のモデルを組み合わせて精度を上げる総称がアンサンブル学習。", "設定値の最適な組を探す作業で、複数モデルの組み合わせではない。", "データを整える前処理で、モデルの組み合わせではない。", "項目を減らす手法で、アンサンブルではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q18', '単純パーセプトロンでは解けなかったXOR（排他的論理和）のような問題を、層を増やすことで解けるようにしたものはどれか。', NULL, '["多層パーセプトロン", "単純パーセプトロン", "サポートベクターマシン", "k近傍法"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "XORのような問題を、層を増やして解けるようにしたものは？", "point": "「層を重ねてXORのような複雑な境界も解ける」なら、多層パーセプトロン。", "kid": "一層だけの単純パーセプトロンは、直線でしか分けられずXOR(斜めに交差する分け方)が解けなかった。層を増やした多層パーセプトロンなら、曲がった境界も引けて解ける。", "eg": "まっすぐな定規1本では引けない複雑な仕切りも、線を何本も組み合わせれば描ける、あのイメージ。", "terms": [["多層パーセプトロン", "入力層と出力層の間に隠れ層を持つニューラルネット。XORなど複雑な問題も解ける"], ["単純パーセプトロン", "隠れ層のない最も単純なモデル。直線でしか分けられずXORは解けない"]], "think": "「層を増やしてXORも解ける」なら多層パーセプトロン。一層だけの単純パーセプトロンの限界を超えた、と押さえる。", "vs": "単純パーセプトロンは一層だけでXORが解けない、サポートベクターマシンは境界を学ぶ別の分類手法、k近傍法は近所の正解で多数決する手法で、いずれも層を増やした多層パーセプトロンではない。", "usecase": "ニューラルネットワークが複雑な問題を扱える理由の原点。層を深くするディープラーニングへの出発点になった。", "opt": ["正解。層を重ねてXORのような問題も解けるのが多層パーセプトロン。", "一層だけで直線でしか分けられず、XORは解けない。", "境界を学ぶ別の分類手法で、多層パーセプトロンではない。", "近所の正解で多数決する手法で、パーセプトロンではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q19', 'ニューラルネットワークの各ノードで、入力の合計を変換して出力する関数（活性化関数）を置く主な目的はどれか。', NULL, '["非線形性を加え、複雑なパターンを表せるようにする", "計算量を減らし、学習を速く進められるようにする", "重みを小さくし、過学習を抑えられるようにする", "入力の桁をそろえ、学習を安定させられるようにする"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "各ノードで入力を変換する活性化関数を置く主な目的は？", "point": "「非線形性を加えて、複雑な模様も表せるようにする」なら、活性化関数の役割。", "kid": "活性化関数がないと、層を何枚重ねても結局まっすぐな関係(直線的)しか作れない。活性化関数で“曲がり”(非線形性)を加えると、複雑な模様も表せるようになる。", "eg": "まっすぐな棒だけでは作れない曲線の形も、関節(非線形性)を入れれば自在に曲げられる、あのイメージ。", "terms": [["活性化関数", "各ノードで入力の合計を変換する関数。非線形性を加える役割を持つ"], ["非線形性", "入力と出力がまっすぐな比例でない関係。複雑な表現に不可欠"]], "think": "「非線形性を加えて複雑な表現を可能にする」が活性化関数の役割。これが無いと層を重ねても直線的な関係しか作れない。", "vs": "学習の高速化・過学習の抑制・桁をそろえる安定化は、それぞれ別の工夫(最適化・正則化・正規化)の役割で、活性化関数の主目的ではない。", "usecase": "ニューラルネットが画像や言葉のような複雑なデータを扱える根っこの仕組み。ReLUやシグモイドなど、どれを選ぶかで学習の進みも変わる。", "opt": ["正解。非線形性を加え、複雑な模様も表せるようにするのが役割。", "学習を速くするのは最適化の工夫で、活性化関数の主目的ではない。", "過学習を抑えるのは正則化の役割で、活性化関数ではない。", "桁をそろえて安定させるのは正規化の役割で、活性化関数ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q20', '最適化で、前回までの更新方向の「勢い」を引き継ぐことで、揺れを抑えつつ谷底へ速く進めるようにする工夫はどれか。', NULL, '["モメンタム", "ドロップアウト", "バッチ正規化", "早期終了"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "前回までの更新方向の勢いを引き継いで、揺れを抑え速く進める工夫は？", "point": "「前の更新の勢いを引き継いで、揺れを抑え速く収束させる」なら、モメンタム。", "kid": "学習は坂を下るイメージ。毎回まっさらに方向を決めると左右に揺れて遅い。前に進んだ勢いを引き継ぐと、揺れが打ち消され、谷底へまっすぐ速く進める。この工夫がモメンタム。", "eg": "自転車で一度こぎ出すと勢いがついて、少しの力でスイスイ進む、あの慣性。", "terms": [["モメンタム", "前回までの更新方向の勢いを引き継ぎ、揺れを抑えて収束を速める最適化の工夫"], ["Adam", "モメンタムと、方向ごとの歩幅調整(RMSProp)を組み合わせた最適化"]], "think": "「前の勢いを引き継いで揺れを抑え速く進む」ならモメンタム。ノードを休ませるドロップアウトや、値をそろえるバッチ正規化とは目的が違う。", "vs": "ドロップアウトはノードを休ませる過学習対策、バッチ正規化は各層の値をそろえる手法、早期終了は学習を途中で止める手法で、いずれも勢いを引き継ぐモメンタムではない。", "usecase": "学習が左右に揺れてなかなか収束しないときに効く。単体でも使うが、Adamの部品としても広く使われる。", "opt": ["正解。前の更新の勢いを引き継いで揺れを抑え速く進むのがモメンタム。", "ノードを休ませる過学習対策で、勢いを引き継ぐ工夫ではない。", "各層の値をそろえる手法で、勢いの話ではない。", "学習を途中で止める手法で、モメンタムではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q21', '最適化で、本当の最小ではないのに、まわりより低いために「そこが底だ」と勘違いして止まってしまう地点はどれか。', NULL, '["局所最適解", "大域最適解", "過学習", "活性化関数"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "本当の最小ではないのに、まわりより低くて止まってしまう地点は？", "point": "「本当の最小ではないのに、まわりより低くてはまり込む谷」なら、局所最適解。", "kid": "学習は「一番低い谷(最小)」を目指して坂を下る。でも、途中の小さなくぼみ(まわりより低い場所)に落ちると、そこが底だと勘違いして止まってしまう。この小さなくぼみが局所最適解。", "eg": "山下りで、本当の谷底(大域最適解)に着く前に、途中の小さなくぼみにはまって動けなくなる、あの状態。", "terms": [["局所最適解", "本当の最小ではないが、まわりより低いために止まってしまう地点"], ["大域最適解", "全体の中で本当に一番低い、目指すべき最小の地点"]], "think": "「まわりより低いだけの偽の底」なら局所最適解。全体で本当に一番低い大域最適解と区別する。", "vs": "大域最適解は本当に一番低い地点、過学習は訓練に合わせすぎる問題、活性化関数はノードで値を変換する部品で、いずれも「偽の底」を指す局所最適解ではない。", "usecase": "学習が途中の悪い所で止まる原因の一つ。勢いをつけるモメンタムやランダム性を持つSGDが、こうしたくぼみから抜けるのに役立つ。", "opt": ["正解。まわりより低いだけで、本当の最小ではない地点が局所最適解。", "全体で本当に一番低い目指すべき地点で、偽の底ではない。", "訓練に合わせすぎる問題で、最適化の地点の話ではない。", "ノードで値を変換する部品で、最適化の地点ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q22', '深いネットワークで学習の勾配が層を伝わるうちに大きくなりすぎて発散するのを防ぐため、勾配を一定の大きさで頭打ちにする手法はどれか。', NULL, '["勾配クリッピング", "ドロップアウト", "データ拡張", "アノテーション"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "勾配が大きくなりすぎて発散するのを、頭打ちにして防ぐ手法は？", "point": "「勾配が大きくなりすぎるのを一定値で頭打ちにする」なら、勾配クリッピング。", "kid": "学習の「直してね」の合図(勾配)が、層を伝わるうちに逆に大きくなりすぎると、値が振れて壊れる(勾配爆発)。そこで合図の大きさに上限を設けて頭打ちにするのが勾配クリッピング。", "eg": "音量が急に爆音になるのを、リミッターで上限を決めて抑える、あの仕組み。", "terms": [["勾配クリッピング", "勾配が大きくなりすぎたとき、一定の大きさで頭打ちにして発散を防ぐ手法"], ["勾配爆発", "勾配が層を伝わるうちに大きくなりすぎて、学習が発散してしまう問題"]], "think": "「勾配が大きくなりすぎるのを頭打ち」なら勾配クリッピング。勾配が消える勾配消失とは逆の問題への対処。", "vs": "ドロップアウトはノードを休ませる過学習対策、データ拡張はデータの水増し、アノテーションは正解ラベル付けで、いずれも勾配を頭打ちにする手法ではない。", "usecase": "RNNなど勾配が爆発しやすいネットワークの学習を安定させるのに使う。学習中に損失が突然跳ね上がるときの対処法。", "opt": ["正解。勾配を一定値で頭打ちにして発散を防ぐのが勾配クリッピング。", "ノードを休ませる過学習対策で、勾配の頭打ちではない。", "データを水増しする手法で、勾配の頭打ちではない。", "正解ラベルを付ける作業で、勾配の話ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q23', '学習の過程で自動的に決まる重みとは違い、学習を始める前に人が決めておく設定値（学習率や層の数など）を指す語はどれか。', NULL, '["ハイパーパラメータ", "パラメータ（重み）", "損失関数", "活性化関数"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "学習前に人が決めておく設定値(学習率や層の数など)を指す語は？", "point": "「学習で自動調整されず、人が事前に決める設定値」なら、ハイパーパラメータ。", "kid": "重み(パラメータ)は学習の中で自動的に決まっていく。一方、学習率や層の数などは、学習を始める前に人が決めておく必要がある。この“人が決める設定値”がハイパーパラメータ。", "eg": "料理でいえば、火加減や時間(人が決める設定＝ハイパーパラメータ)と、出来上がった味(自動的に決まる結果＝パラメータ)の違い。", "terms": [["ハイパーパラメータ", "学習で自動調整されず、人が事前に決める設定値。学習率・層の数・バッチサイズなど"], ["パラメータ（重み）", "学習の過程で自動的に決まっていく値"]], "think": "「人が事前に決める設定値」ならハイパーパラメータ。学習の中で自動的に決まる重み(パラメータ)と対で押さえる。", "vs": "パラメータ(重み)は学習で自動的に決まる値、損失関数は誤差を測る関数、活性化関数はノードで値を変換する部品で、いずれも人が事前に決める設定値そのものではない。", "usecase": "グリッドサーチなどで調整する対象。良い設定値を選べるかどうかがモデルの性能を左右するので、調整の勘所になる。", "opt": ["正解。人が事前に決める設定値がハイパーパラメータ。", "学習の中で自動的に決まる値で、人が事前に決める設定ではない。", "誤差を測る関数で、設定値そのものではない。", "ノードで値を変換する部品で、設定値ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q24', 'データを圧縮する際に、その特徴を「確率的な分布」として捉えることで、学習した特徴から新しいデータも生成できるようにしたオートエンコーダの発展形はどれか。', NULL, '["変分オートエンコーダ", "GAN", "word2vec", "決定木"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "特徴を確率分布として捉え、新しいデータも生成できるオートエンコーダの発展形は？", "point": "「特徴を確率分布で捉え、新データも生成できるオートエンコーダ」なら、変分オートエンコーダ(VAE)。", "kid": "ふつうのオートエンコーダは圧縮して復元するだけ。VAEは、圧縮した特徴を“確率のばらつき”として扱うので、その分布から少しずらして新しいデータ(似た画像など)を作り出せる。", "eg": "顔の特徴を「平均＋ばらつき」で覚えておき、そこから少し変えて“実在しない別の顔”を作れる、あのイメージ。", "terms": [["変分オートエンコーダ（VAE）", "特徴を確率分布として捉え、そこから新しいデータも生成できるオートエンコーダの発展形"], ["オートエンコーダ", "入力を圧縮し復元するよう学ぶネットワーク。VAEはその生成向けの発展形"]], "think": "「圧縮＋確率分布＋生成できる」ならVAE。生成器と識別器を競わせるGANとは、生成の仕組みが違う。", "vs": "GANは生成器と識別器を競わせる別の生成モデル、word2vecは単語をベクトルにする手法、決定木は条件分岐で予測する手法で、いずれも確率分布で生成するVAEではない。", "usecase": "画像などの生成や、異常検知(分布から外れるものを見つける)に使う。GANと並ぶ代表的な生成モデルの一つ。", "opt": ["正解。特徴を確率分布で捉え新データも生成できるのがVAE。", "生成器と識別器を競わせる別の生成モデルで、VAEとは仕組みが違う。", "単語をベクトルにする手法で、生成モデルではない。", "条件分岐で予測する手法で、生成モデルではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q25', '畳み込みでフィルタを画像上でずらしていく際の「ずらす幅」を指し、大きくするほど出力の特徴マップが小さくなるものはどれか。', NULL, '["ストライド", "パディング", "エポック", "ドロップアウト"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "畳み込みでフィルタをずらす幅を指し、大きいほど出力が小さくなるものは？", "point": "「フィルタをずらす幅で、大きいほど出力が小さくなる」なら、ストライド。", "kid": "畳み込みでは、フィルタ(小さな虫めがね)を画像の上で少しずつずらして特徴を拾う。その“ずらす幅”がストライド。幅を大きくすると拾う回数が減り、出力が小さくなる。", "eg": "写真を端から端までスタンプで押すとき、押す間隔(ストライド)を広げると、押す回数が減って全体の枚数が少なくなる、あのイメージ。", "terms": [["ストライド", "畳み込みでフィルタをずらす幅。大きくするほど出力の特徴マップが小さくなる"], ["パディング", "畳み込みで端の情報が減らないよう、入力の外側に余白を足すこと"]], "think": "「フィルタをずらす幅・大きいほど出力が縮む」ならストライド。端に余白を足すパディングとは別の設定。", "vs": "パディングは端に余白を足す設定、エポックは全データを何周するかの回数、ドロップアウトはノードを休ませる手法で、いずれもフィルタをずらす幅ストライドではない。", "usecase": "畳み込みで、どれくらい細かく特徴を拾うか・出力をどれくらい縮めるかを調整するのに使う。計算量の調整にも効く。", "opt": ["正解。フィルタをずらす幅で、大きいほど出力が縮むのがストライド。", "端に余白を足す設定で、ずらす幅そのものではない。", "全データを何周するかの回数で、ずらす幅ではない。", "ノードを休ませる手法で、ストライドではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
COMMIT;
BEGIN;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q26', '畳み込みで、フィルタを当てると画像の端の情報が失われ出力が小さくなる。これを防ぐため入力の外側に余白（多くは0）を足す操作はどれか。', NULL, '["パディング", "プーリング", "ストライド", "バッチ正規化"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "畳み込みで端の情報が減らないよう、入力の外側に余白を足す操作は？", "point": "「入力の外側に余白を足して、端の情報や出力サイズを保つ」なら、パディング。", "kid": "フィルタは画像の内側ばかり通り、端は数回しか通らないので端の情報が薄れ、出力も小さくなる。外側に余白(たいてい0)を足すと、端もしっかり拾えて出力サイズも保てる。これがパディング。", "eg": "紙の端まできれいに印刷するために、外側に“塗り足し”の余白を付けておく、あの製本の工夫。", "terms": [["パディング", "畳み込みで入力の外側に余白(多くは0)を足し、端の情報を保ち出力サイズを維持する操作"], ["ストライド", "フィルタをずらす幅。出力サイズに関わる別の設定"]], "think": "「外側に余白を足して端を保つ」ならパディング。特徴を縮めるプーリングや、ずらす幅のストライドとは別の操作。", "vs": "プーリングは特徴を粗くまとめて縮める操作、ストライドはフィルタをずらす幅、バッチ正規化は各層の値をそろえる手法で、いずれも外側に余白を足すパディングではない。", "usecase": "畳み込みを重ねても出力が小さくなりすぎないよう保ちたいときや、端の情報を大事にしたいときに使う。", "opt": ["正解。外側に余白を足して端の情報や出力サイズを保つのがパディング。", "特徴を粗くまとめて縮める操作で、余白を足すものではない。", "フィルタをずらす幅で、余白を足す操作ではない。", "各層の値をそろえる手法で、パディングではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q27', '入力の系列を一度「意味を凝縮したベクトル」にまとめ（前半）、そこから別の系列を生成する（後半）、翻訳などに使われる構造はどれか。', NULL, '["エンコーダ・デコーダ", "オートエンコーダ", "畳み込み層", "混同行列"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "入力を意味のベクトルにまとめてから、別の系列を生成する翻訳などの構造は？", "point": "「入力をベクトルに凝縮(前半)→そこから別の系列を生成(後半)」なら、エンコーダ・デコーダ。", "kid": "前半(エンコーダ)で入力文をぎゅっと「意味のかたまり(ベクトル)」にまとめ、後半(デコーダ)でそこから訳文を組み立てる。入力と出力で長さや言語が違ってもよいのが特徴。", "eg": "通訳が、話を一度“要点メモ(ベクトル)”にまとめてから、別の言語で組み立て直して話す、あの二段構え。", "terms": [["エンコーダ・デコーダ", "入力を意味のベクトルに凝縮し、そこから別の系列を生成する構造。翻訳などに使う"], ["Attention", "デコーダが入力のどこに注目するかを補い、この構造の弱点を補強する仕組み"]], "think": "「入力を凝縮→別の系列を生成」ならエンコーダ・デコーダ。入力と同じものを復元するオートエンコーダとは、出す先が違う。", "vs": "オートエンコーダは入力と同じものを復元する、畳み込み層は画像の局所特徴を拾う、混同行列は判定結果の集計表で、いずれも別の系列を生成するエンコーダ・デコーダではない。", "usecase": "機械翻訳・文章要約・対話など、入力の系列から別の系列を作るタスクの土台。Attentionと組み合わせて精度が大きく上がった。", "opt": ["正解。入力を凝縮し別の系列を生成するのがエンコーダ・デコーダ。", "入力と同じものを復元する構造で、別の系列を生成するものではない。", "画像の局所特徴を拾う層で、系列生成の構造ではない。", "判定結果の集計表で、生成の構造ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q28', '系列を前からだけでなく後ろからも読み、ある時点の判断に「前後両方の文脈」を使えるようにしたRNNはどれか。', NULL, '["双方向RNN", "単方向RNN", "畳み込みネットワーク", "オートエンコーダ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "前からと後ろからの両方向で系列を読み、前後の文脈を使えるRNNは？", "point": "「前からと後ろからの両方向で読み、前後の文脈を使う」なら、双方向RNN。", "kid": "ふつうのRNNは前から順にしか読まないので、ある単語の判断に“後ろの文脈”を使えない。双方向RNNは後ろからも読む向きを足し、前後両方の文脈を合わせて判断できる。", "eg": "穴埋め問題を、前の文だけでなく後ろの文も読んでから答える、あの解き方。", "terms": [["双方向RNN", "系列を前からと後ろからの両方向で読み、前後の文脈を使えるようにしたRNN"], ["単方向RNN", "前から一方向にしか読まない通常のRNN。後ろの文脈は使えない"]], "think": "「前後の両方向で読む」なら双方向RNN。前からしか読まない単方向RNNの弱点(後ろの文脈が使えない)を補う。", "vs": "単方向RNNは前からしか読まない、畳み込みネットワークは画像の局所特徴を拾う、オートエンコーダは圧縮して復元を学ぶ構造で、いずれも前後両方向で読む双方向RNNではない。", "usecase": "文全体を見て判断する固有表現抽出や品詞付けなど、後ろの文脈も効くタスクで精度が上がる。", "opt": ["正解。前後の両方向で読み前後の文脈を使えるのが双方向RNN。", "前から一方向にしか読まず、後ろの文脈を使えない通常のRNN。", "画像の局所特徴を拾う手法で、双方向のRNNではない。", "圧縮して復元を学ぶ構造で、双方向RNNではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q29', 'Transformerは系列を一度にまとめて処理するため語順の情報が失われる。これを補うために、各単語の位置を表す情報を足す仕組みはどれか。', NULL, '["位置エンコーディング", "自己注意", "ドロップアウト", "バッチ正規化"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "Transformerで失われる語順を補うため、位置情報を足す仕組みは？", "point": "「一度に処理して失う語順を、位置の情報を足して補う」なら、位置エンコーディング。", "kid": "Transformerは単語を一度にまとめて見るので、「何番目の単語か」という順番の情報が消えてしまう。そこで各単語に“位置を表す信号”を足して、語順が分かるようにする。これが位置エンコーディング。", "eg": "バラバラに配った資料に、あらかじめページ番号を振っておけば、まとめて配っても順番が分かる、あの工夫。", "terms": [["位置エンコーディング", "Transformerで、一度に処理して失われる語順を補うため、各単語に位置情報を足す仕組み"], ["自己注意", "単語どうしの関係を測る仕組み。それ自体は語順を持たないため位置情報の補いが要る"]], "think": "「語順を位置情報で補う」なら位置エンコーディング。単語どうしの関係を測る自己注意とは役割が違う(自己注意だけでは順番が分からない)。", "vs": "自己注意は単語どうしの関係を測る仕組み、ドロップアウトはノードを休ませる過学習対策、バッチ正規化は各層の値をそろえる手法で、いずれも語順を補う位置エンコーディングではない。", "usecase": "TransformerやLLMが「語順」を扱えるようにする土台。順番が意味を変える言語処理で不可欠な部品。", "opt": ["正解。失われる語順を位置情報で補うのが位置エンコーディング。", "単語どうしの関係を測る仕組みで、それ自体は語順を持たない。", "ノードを休ませる過学習対策で、語順を補うものではない。", "各層の値をそろえる手法で、位置情報を足すものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q30', '画像や動画から、人の関節（肩・肘・膝など）の位置を推定し、体の姿勢をとらえるタスクはどれか。', NULL, '["姿勢推定", "画像分類", "物体検出", "異常検知"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "人の関節の位置を推定して、体の姿勢をとらえるタスクは？", "point": "「人の関節の位置を推定して姿勢をとらえる」なら、姿勢推定。", "kid": "画像や動画から、肩・肘・膝といった関節がどこにあるかを点で当て、体がどんな姿勢かをとらえるタスク。棒人間の骨組みを描くようなイメージ。", "eg": "ダンスの動きを、関節に印を付けて“棒人間”として再現する、あの見立て。", "terms": [["姿勢推定", "画像や動画から人の関節の位置を推定し、体の姿勢をとらえるタスク"], ["物体検出", "物の種類と位置を枠で囲むタスク。関節点を出す姿勢推定とは出力が違う"]], "think": "「関節の位置・姿勢をとらえる」なら姿勢推定。写真全体に1ラベルの画像分類や、枠で囲む物体検出とは出力が違う。", "vs": "画像分類は写真全体に1ラベル、物体検出は種類と位置を枠で囲む、異常検知は普段と違うものを見つけるタスクで、いずれも関節点を出す姿勢推定ではない。", "usecase": "スポーツのフォーム解析、転倒検知、モーションキャプチャ、ジェスチャー操作などで使う。", "opt": ["正解。人の関節の位置を推定して姿勢をとらえるのが姿勢推定。", "写真全体に1ラベルを付けるタスクで、関節の位置は出さない。", "種類と位置を枠で囲むタスクで、関節点を出すものではない。", "普段と違うものを見つけるタスクで、姿勢推定ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q31', '画像を画素単位で塗り分けるだけでなく、同じ「人」でも一人ひとりを別個体として区別して領域を分けるタスクはどれか。', NULL, '["インスタンスセグメンテーション", "セマンティックセグメンテーション", "画像分類", "姿勢推定"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "画素を塗り分けつつ、同じ種類でも個体ごとに区別するタスクは？", "point": "「画素を塗り分け、かつ同じ種類でも個体ごとに区別する」なら、インスタンスセグメンテーション。", "kid": "「これは人、これは道路」と画素ごとに塗り分けるのがセマンティックセグメンテーション。そこからさらに「1人目・2人目」と個体まで分けるのがインスタンスセグメンテーション。より細かい。", "eg": "集合写真で、全員を「人」の色で塗るだけでなく、一人ひとりを別の色で塗り分ける、あの細かさ。", "terms": [["インスタンスセグメンテーション", "画素を塗り分けたうえで、同じ種類でも個体ごとに区別して領域を分けるタスク"], ["セマンティックセグメンテーション", "画素ごとにクラスを塗り分けるが、同じ種類の個体は区別しないタスク"]], "think": "「塗り分け＋個体の区別」ならインスタンスセグメンテーション。個体を区別しないセマンティックセグメンテーションより細かい。", "vs": "セマンティックセグメンテーションは個体を区別せず塗り分けるだけ、画像分類は写真全体に1ラベル、姿勢推定は関節の位置を当てるタスクで、いずれも個体まで分けるインスタンスセグメンテーションではない。", "usecase": "混み合った場面で人や物を一つずつ数えたい・追跡したいときに使う。自動運転や店舗の人数把握などで役立つ。", "opt": ["正解。画素を塗り分け、かつ個体ごとに区別するのがインスタンスセグメンテーション。", "画素を塗り分けるが、同じ種類の個体は区別しない。", "写真全体に1ラベルを付けるだけで、画素の塗り分けではない。", "関節の位置を当てるタスクで、領域の塗り分けではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q32', '文を単語ごとに置き換えるのではなく、文全体を一度「意味のベクトル」にまとめてから別の言語の文を生成する翻訳方式はどれか。', NULL, '["ニューラル機械翻訳", "ルールベース翻訳", "形態素解析", "音声合成"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "文全体を意味のベクトルにまとめてから訳す翻訳方式は？", "point": "「文全体を意味のベクトルにまとめてから訳文を生成する」なら、ニューラル機械翻訳。", "kid": "単語を一つずつ辞書で置き換えるのではなく、文全体を一度“意味のかたまり(ベクトル)”にしてから、別の言語の文を組み立てる。前後のつながりを踏まえた自然な訳になりやすい。", "eg": "逐語訳ではなく、文の意味を一度理解してから訳し直す、あの通訳のやり方。", "terms": [["ニューラル機械翻訳", "文全体を意味のベクトルにまとめてから訳文を生成する、ニューラルネットによる翻訳"], ["エンコーダ・デコーダ", "入力を凝縮し別の系列を生成する構造。ニューラル機械翻訳の土台"]], "think": "「文全体を意味にしてから訳す」ならニューラル機械翻訳。単語や文法規則を人が書くルールベース翻訳とは仕組みが違う。", "vs": "ルールベース翻訳は人が書いた規則で訳す方式、形態素解析は文を単語に区切る前処理、音声合成は文字から声を作るタスクで、いずれもニューラル機械翻訳ではない。", "usecase": "今の翻訳サービスの主流。前後の文脈を踏まえるので、逐語訳より自然で滑らかな訳が出せる。", "opt": ["正解。文全体を意味にまとめてから訳すのがニューラル機械翻訳。", "人が書いた規則で訳す古い方式で、意味のベクトルは使わない。", "文を単語に区切る前処理で、翻訳方式そのものではない。", "文字から声を作るタスクで、翻訳ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q33', '画像を入力として、その内容を説明する文章を自動で作り出すタスクはどれか。', NULL, '["画像キャプション生成", "画像スタイル変換", "セマンティックセグメンテーション", "超解像"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "画像を入力に、その内容を説明する文章を作るタスクは？", "point": "「画像を見て、その内容を説明する文章を作る」なら、画像キャプション生成。", "kid": "写真を入れると「犬が芝生で走っている」のような説明文を自動で作るタスク。画像を見る力(CNN)と文を書く力(RNN/Transformer)を組み合わせる。", "eg": "目の見えない人に写真の内容を言葉で伝える、あの説明を自動化したもの。", "terms": [["画像キャプション生成", "画像を入力に、その内容を説明する文章を生成するタスク。画像認識と言語生成の組み合わせ"], ["マルチモーダル", "画像と言葉など種類の違う情報を扱うこと。画像キャプション生成もその一種"]], "think": "「画像→説明文を作る」なら画像キャプション生成。画像を加工・変換する他のタスクとは、出力が“文章”である点が違う。", "vs": "画像スタイル変換は絵柄を別の画風に変える、セマンティックセグメンテーションは画素を塗り分ける、超解像は画像を高解像度化するタスクで、いずれも説明文を作る画像キャプション生成ではない。", "usecase": "画像の自動タグ付け、視覚障害者向けの読み上げ、大量画像の検索用テキスト付けなどで役立つ。", "opt": ["正解。画像を見て説明文を作るのが画像キャプション生成。", "絵柄を別の画風に変えるタスクで、説明文は作らない。", "画素を塗り分けるタスクで、文章を作るものではない。", "画像を高解像度化するタスクで、説明文の生成ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q34', '文章を読んで、その内容が肯定的か否定的か（あるいは怒り・喜びなど）を判定する自然言語処理のタスクはどれか。', NULL, '["感情分析", "形態素解析", "音声認識", "異常検知"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "文章が肯定的か否定的かを判定する自然言語処理のタスクは？", "point": "「文章が肯定的か否定的か(気持ち)を判定する」なら、感情分析。", "kid": "口コミやSNSの文章を読んで、「褒めている(肯定)」のか「けなしている(否定)」のかを判定するタスク。喜び・怒りなどの感情に分けることもある。", "eg": "レビューをざっと読んで「これは高評価」「これは不満」と仕分けする、あの読み取り。", "terms": [["感情分析", "文章が肯定的か否定的か、あるいはどんな感情かを判定する自然言語処理のタスク"], ["形態素解析", "文を単語に区切り品詞を付ける前処理。感情分析の前段で使われることがある"]], "think": "「文章の肯定/否定・感情を判定」なら感情分析。文を単語に区切る形態素解析(前処理)とは役割が違う。", "vs": "形態素解析は文を単語に区切る前処理、音声認識は音声を文字にするタスク、異常検知は普段と違うものを見つけるタスクで、いずれも文章の気持ちを判定する感情分析ではない。", "usecase": "商品レビューやSNSの評判分析、問い合わせの緊急度判定などで使う。大量の声を素早く仕分けできる。", "opt": ["正解。文章が肯定的か否定的かを判定するのが感情分析。", "文を単語に区切る前処理で、気持ちの判定そのものではない。", "音声を文字にするタスクで、感情の判定ではない。", "普段と違うものを見つけるタスクで、感情分析ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q35', '大量の正常なデータのパターンを学び、そこから大きく外れるものを「異常」として見つけ出す仕組みはどれか。', NULL, '["異常検知", "画像分類", "感情分析", "データ拡張"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "正常なパターンから大きく外れるものを見つけ出す仕組みは？", "point": "「正常のパターンを学び、そこから大きく外れるものを見つける」なら、異常検知。", "kid": "普段の正常な状態をたくさん学んでおき、それと大きく違うものが来たら「おかしい」と気づく仕組み。異常なデータは少なくてよく、正常データだけでも学べるのが利点。", "eg": "いつもの体調を知っている人が、少しの変化で「今日はおかしい」と気づく、あの感覚。", "terms": [["異常検知", "正常なデータのパターンを学び、そこから大きく外れるものを異常として見つける仕組み"], ["オートエンコーダ", "正常データを圧縮・復元するよう学び、うまく復元できないものを異常とする代表手法"]], "think": "「正常を学んで、外れるものを見つける」なら異常検知。あらかじめ全種類を教える画像分類とは違い、異常の例が少なくても使える。", "vs": "画像分類は写真全体に1ラベルを付ける、感情分析は文章の気持ちを判定する、データ拡張はデータを水増しする手法で、いずれも外れ値を見つける異常検知ではない。", "usecase": "工場の設備故障の予兆、クレジットカードの不正利用、ネットワークの侵入検知など、「めったに起きない異常」を捉えたい場面で使う。", "opt": ["正解。正常のパターンから外れるものを見つけるのが異常検知。", "写真全体に1ラベルを付けるタスクで、外れ値を見つけるものではない。", "文章の気持ちを判定するタスクで、異常検知ではない。", "データを水増しする手法で、異常検知ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q36', '生成AIの出力に対して人間が「どちらが好ましいか」を評価し、その好みに沿うようにモデルを調整する手法はどれか。', NULL, '["RLHF", "教師なし事前学習", "バッチ正規化", "データ拡張"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "人間の好みの評価に沿うよう、生成AIを調整する手法は？", "point": "「人間の好みの評価を報酬にして、生成AIを人に沿うよう調整する」なら、RLHF。", "kid": "生成AIの答えを人間が「こっちが好ましい」と評価し、その好みを“ごほうび”にして調整する。これで、事実として正しいだけでなく、人にとって使いやすい・安全な答えに近づく。", "eg": "弟子の受け答えに師匠が「そっちの方がいい」と好みを伝え続け、師匠好みに仕上げていく、あの育て方。", "terms": [["RLHF", "人間のフィードバック(好みの評価)を報酬にして、生成AIを人の好みに沿うよう調整する手法"], ["強化学習", "報酬を手がかりに試行錯誤で行動を学ぶ方法。RLHFの土台"]], "think": "「人間の好みを報酬に調整」ならRLHF。データを増やすデータ拡張や、広く学ぶ事前学習とは目的が違う。", "vs": "教師なし事前学習は正解なしで広く学ぶ段階、バッチ正規化は各層の値をそろえる手法、データ拡張はデータの水増しで、いずれも人間の好みで調整するRLHFではない。", "usecase": "ChatGPTなどの対話AIを、より役立ち・安全で・人に沿った応答にするために使われた重要な仕上げ工程。", "opt": ["正解。人間の好みの評価を報酬にして生成AIを調整するのがRLHF。", "正解なしで広く学ぶ事前学習の段階で、好みで調整する工程ではない。", "各層の値をそろえる手法で、RLHFではない。", "データを水増しする手法で、好みで調整するものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q37', '生のデータから、予測に効きやすい項目（例：日付から「曜日」や「祝日か」を作る）を人が設計・加工する作業はどれか。', NULL, '["特徴量エンジニアリング", "ハイパーパラメータ探索", "データ拡張", "デプロイ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "予測に効く項目を、生データから人が設計・加工する作業は？", "point": "「予測に効く項目を、生データから人が設計・加工する」なら、特徴量エンジニアリング。", "kid": "生のデータをそのまま使うより、「日付から曜日や祝日を取り出す」など、予測に効きそうな項目を人が工夫して作る方が精度が上がる。この“項目づくり”が特徴量エンジニアリング。", "eg": "料理で、素材をそのまま出すより、下ごしらえで切り方や下味を工夫すると味が引き立つ、あの手間。", "terms": [["特徴量エンジニアリング", "生データから予測に効く項目(特徴量)を人が設計・加工する作業"], ["特徴表現学習", "特徴量そのものを自動で学ぶディープラーニングの段階。人手の設計を減らす"]], "think": "「予測に効く項目を人が作る」なら特徴量エンジニアリング。設定値を探すハイパーパラメータ探索や、データを増やすデータ拡張とは目的が違う。", "vs": "ハイパーパラメータ探索は設定値を探す作業、データ拡張はデータを水増しする手法、デプロイはモデルを本番で動かすことで、いずれも項目を設計する特徴量エンジニアリングではない。", "usecase": "表形式データの機械学習で精度を左右する重要工程。良い特徴を作れるかどうかが結果を大きく変える(ディープラーニングでは自動化が進む領域)。", "opt": ["正解。予測に効く項目を生データから設計・加工するのが特徴量エンジニアリング。", "設定値を探す作業で、項目を設計するものではない。", "データを水増しする手法で、項目づくりではない。", "モデルを本番で動かすことで、特徴量の設計ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='7. AIの社会実装に向けて'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q38', '運用しているうちに世の中の傾向やデータの性質が変化し、以前は正確だったモデルの精度がだんだん落ちていく現象はどれか。', NULL, '["コンセプトドリフト", "過学習", "勾配消失", "データ拡張"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "時間とともにデータの傾向が変わり、モデルの精度が落ちていく現象は？", "point": "「運用中に世の中やデータの傾向が変わり、モデルが当たらなくなる」なら、コンセプトドリフト。", "kid": "モデルは作った時点のデータに合わせて学ぶ。でも世の中の流行や状況は変わるので、時間が経つと当時の“正解”が今の実態とずれ、精度がだんだん落ちる。この“ずれていく”現象。", "eg": "去年のヒット予測が、流行が変わった今年には当たらなくなる、あの時代遅れ。", "terms": [["コンセプトドリフト", "時間とともにデータの傾向が変化し、以前は正確だったモデルの精度が落ちていく現象"], ["再学習", "新しいデータでモデルを学習し直すこと。コンセプトドリフトへの対処"]], "think": "「運用中に傾向が変わって精度が落ちる」ならコンセプトドリフト。作った時点で訓練に合わせすぎる過学習とは、原因も時間軸も違う。", "vs": "過学習は訓練データに合わせすぎる問題、勾配消失は深い層で学習の信号が消える問題、データ拡張はデータの水増しで、いずれも時間とともにずれるコンセプトドリフトではない。", "usecase": "「本番のモデルを定期的に監視し、精度が落ちたら再学習する」というMLOpsの必要性の根拠。運用を続ける限りつきまとう課題。", "opt": ["正解。時間とともに傾向が変わり精度が落ちるのがコンセプトドリフト。", "訓練データに合わせすぎる問題で、時間による劣化とは別。", "深い層で学習の信号が消える問題で、この現象とは違う。", "データを水増しする手法で、精度が落ちる現象ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='7. AIの社会実装に向けて'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
COMMIT;
BEGIN;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q39', '誰でも自由に使い、再配布や加工もできる形で公開されているデータを指す語はどれか。', NULL, '["オープンデータ", "アノテーション", "データリーケージ", "メタデータ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "誰でも自由に使え、再配布や加工もできる公開データを指す語は？", "point": "「誰でも自由に使い、加工・再配布もできる形で公開されたデータ」なら、オープンデータ。", "kid": "国や自治体、企業などが「誰でも自由に使っていいですよ」と公開しているデータ。使うだけでなく、加工や再配布もできるのが特徴。", "eg": "図書館の本のように、誰でも借りて使える“みんなのための”データ。", "terms": [["オープンデータ", "誰でも自由に使い、再配布や加工もできる形で公開されたデータ"], ["アノテーション", "データに正解ラベルを付ける作業。集めたデータを学習用に加工する工程"]], "think": "「誰でも自由に使える公開データ」ならオープンデータ。正解ラベルを付ける作業のアノテーションとは別のもの。", "vs": "アノテーションは正解ラベルを付ける作業、データリーケージは答えが訓練に漏れる問題、メタデータはデータの説明情報(いつ・誰が等)で、いずれも自由に使える公開データのオープンデータではない。", "usecase": "自前のデータが足りないときに、学習や分析の材料として活用できる。行政の統計や地図データなどが代表例。", "opt": ["正解。誰でも自由に使え加工・再配布できる公開データがオープンデータ。", "正解ラベルを付ける作業で、公開データそのものではない。", "答えが訓練に漏れる問題で、データの種類ではない。", "データの説明情報で、公開データそのものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='7. AIの社会実装に向けて'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q40', '100人中1人だけが陽性の検査で、全員を「陰性」と答えるだけのモデルでも正解率は99%になる。この例が示す注意点はどれか。', NULL, '["クラスが偏ると、正解率は実力を過大に見せうる", "正解率は、どんなデータでも実力を正しく表す", "正解率が高ければ、見落としも必ず少ない", "正解率は、回帰の予測にだけ使う指標だ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "全員を陰性と答えても正解率99%になる例が示す注意点は？", "point": "「クラスが偏ると、正解率だけでは実力を過大に見せる」ことに注意。", "kid": "100人中1人だけ陽性なら、全員「陰性」と答えるだけで99%当たる。でもこのモデルは陽性を1人も見つけられていない。正解率は、偏ったデータでは“優秀に見える罠”がある。", "eg": "ほとんど晴れの地域で「毎日晴れ」と予報すれば的中率は高いが、肝心の雨の日は当てられない、あの見かけ倒し。", "terms": [["正解率（Accuracy）", "全体のうち正しく判定できた割合。クラスが偏ると誤解を招きやすい"], ["適合率・再現率", "偏ったデータでも実力を測れる指標。正解率の弱点を補う"]], "think": "「偏ったデータでは正解率が高くても実力とは限らない」が要点。こういう場面では適合率・再現率やF値で測る。", "vs": "「どんなデータでも正しく表す」は誤りで偏りに弱い、「高ければ見落としも少ない」も誤りで見落としだらけでも高くなりうる、「回帰にだけ使う」も誤りで正解率は分類の指標。", "usecase": "不正検知や病気の検査など、陽性がまれな不均衡データの評価で必須の注意。正解率だけを見て安心しないための基本。", "opt": ["正解。クラスが偏ると正解率は実力を過大に見せうる。", "偏ったデータでは誤解を招くので、常に正しく表すとはいえない。", "見落としだらけでも正解率は高くなりうるので、誤り。", "正解率は分類の指標で、回帰専用ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='8. AIに必要な数理・統計知識'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q41', 'データが平均のまわりにどれだけ散らばっているかの大きさを表す指標はどれか。', NULL, '["標準偏差", "中央値", "相関係数", "最頻値"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "データが平均のまわりにどれだけ散らばっているかを表す指標は？", "point": "「平均からの散らばりの大きさ」を表すなら、標準偏差(や分散)。", "kid": "同じ平均点でも、みんなが平均近くに固まっているか、上下に大きくばらけているかは違う。その“ばらけ具合”の大きさを表すのが標準偏差(その二乗が分散)。", "eg": "的当てで、矢が中心近くに集まっているか、広く散らばっているか。その散らばり具合を数値にしたもの。", "terms": [["標準偏差", "データが平均からどれだけ散らばっているかを表す指標。分散の平方根"], ["分散", "散らばりを表すもう一つの指標。標準偏差を二乗した値"]], "think": "「平均からの散らばりの大きさ」なら標準偏差・分散。真ん中を表す中央値や、関係の強さを表す相関係数とは測るものが違う。", "vs": "中央値は真ん中の値、相関係数は2つの量の関係の強さ、最頻値は最も多く現れる値で、いずれも散らばりの大きさを表す標準偏差ではない。", "usecase": "品質のばらつき管理や、正規分布の68-95-99.7則(平均±1σに約68%)など、データの安定度・外れ値の判断の土台になる。", "opt": ["正解。平均からの散らばりの大きさを表すのが標準偏差。", "真ん中の値を表す指標で、散らばりの大きさではない。", "2つの量の関係の強さを表す指標で、散らばりではない。", "最も多く現れる値で、散らばりの大きさではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='8. AIに必要な数理・統計知識'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q42', '「もともとの確率」に「新しく得られた証拠」を反映して、確率を更新していく考え方はどれか。', NULL, '["ベイズの定理", "正規分布", "中心極限定理", "大数の法則"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "もとの確率に新しい証拠を反映して、確率を更新する考え方は？", "point": "「もとの確率を、新しい証拠で更新していく」考え方なら、ベイズの定理。", "kid": "最初に持っている見込み(事前確率)に、新しく分かった手がかり(証拠)を反映して、見込みを更新する(事後確率)。証拠が増えるほど、より確からしい確率に近づく。", "eg": "「たぶん風邪」と思っていたところに検査結果が出て、「やっぱり風邪の可能性が高い」と見込みを更新する、あの考え方。", "terms": [["ベイズの定理", "もとの確率(事前確率)に新しい証拠を反映して、更新後の確率(事後確率)を求める考え方"], ["事前確率／事後確率", "証拠を得る前の見込みと、得た後に更新した見込み"]], "think": "「もとの確率を証拠で更新」ならベイズの定理。データの分布を表す正規分布などとは、扱っているものが違う。", "vs": "正規分布はデータのばらつきの形、中心極限定理は平均の分布が正規分布に近づく法則、大数の法則は試行を重ねると割合が理論値に近づく法則で、いずれも確率を更新するベイズの定理ではない。", "usecase": "迷惑メール判定(ナイーブベイズ)や、証拠を積み重ねて診断・推定する場面で使う。データが増えるたびに判断を更新する土台。", "opt": ["正解。もとの確率を新しい証拠で更新するのがベイズの定理。", "データのばらつきの形を表す分布で、確率の更新の考え方ではない。", "平均の分布が正規分布に近づく法則で、更新の考え方ではない。", "試行を重ねると割合が理論値に近づく法則で、ベイズの定理ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='8. AIに必要な数理・統計知識'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q43', '2つの量の「直線的な関係の強さと向き」を、-1から+1の範囲の数値で表す指標はどれか。', NULL, '["相関係数", "標準偏差", "決定木", "混同行列"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "2つの量の直線的な関係の強さを-1〜+1で表す指標は？", "point": "「2つの量の直線的な関係の強さと向きを-1〜+1で表す」なら、相関係数。", "kid": "一方が増えると他方も増える(正の関係)か、減る(負の関係)か、その強さを-1〜+1の数値で表す。+1に近いほど右上がり、-1に近いほど右下がり、0に近いと関係が弱い。", "eg": "気温とアイスの売上のように「一緒に動くか」を一つの数値で表した、関係の強さのものさし。", "terms": [["相関係数", "2つの量の直線的な関係の強さと向きを-1〜+1で表す指標"], ["相関と因果", "相関があっても、一方が他方の原因とは限らない点に注意"]], "think": "「2つの量の関係の強さを-1〜+1で」なら相関係数。ただし相関が強くても、それが原因-結果(因果)とは限らない点に注意。", "vs": "標準偏差は散らばりの大きさ、決定木は条件分岐で予測する手法、混同行列は分類結果の集計表で、いずれも2つの量の関係の強さを表す相関係数ではない。", "usecase": "どの項目が予測に効きそうかの目星をつけたり、似た動きをする項目を見つけたりするのに使う。因果と混同しないのが肝心。", "opt": ["正解。2つの量の関係の強さと向きを-1〜+1で表すのが相関係数。", "データの散らばりの大きさを表す指標で、2量の関係ではない。", "条件分岐で予測する手法で、関係の強さの指標ではない。", "分類結果の集計表で、相関の指標ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='8. AIに必要な数理・統計知識'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q44', '生成AIに簡単な指示（プロンプト）を与えて出力させた画像の著作権について、現状の考え方として最も適切なものはどれか。', NULL, '["人の創作的な関与が乏しいと、著作物と認められにくい", "出力した瞬間に、必ず利用者の著作物になる", "AIの開発会社に、自動的に著作権が帰属する", "生成物には一切の権利が発生しないと法律にある"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "プロンプトで出させた生成物の著作権について、現状の考え方は？", "point": "「人の創作的な関与が乏しいと、生成物は著作物と認められにくい」。", "kid": "著作権は「人が創作的に表現したもの」を守る仕組み。簡単な指示を入れただけで出た生成物は、人の創作の工夫が乏しいと見なされやすく、著作物として保護されにくい。", "eg": "自動販売機のボタンを押して出てきた飲み物に、押した人の“作品”としての権利は生まれない、あの感覚に近い。", "terms": [["著作物", "人が思想や感情を創作的に表現したもの。著作権で保護される対象"], ["創作的寄与", "人がどれだけ創作的に関わったか。生成物の著作物性を判断する鍵"]], "think": "判断の軸は「人の創作的な関与があるか」。指示を入れただけでは関与が乏しく、著作物と認められにくい。会社への自動帰属や一律発生といった決めつけは誤り。", "vs": "「必ず利用者のもの」「開発会社に自動帰属」は決めつけで誤り、「一切権利が発生しないと法律に明記」も誤りで、人の創作的関与の程度で個別に判断される。", "usecase": "生成AIで作ったコンテンツを商用利用・権利主張したいときの前提知識。関与の度合いによって扱いが変わる、と押さえておく。", "opt": ["正解。人の創作的な関与が乏しいと著作物と認められにくい。", "出力しただけで必ず利用者のものになるとはいえず、決めつけは誤り。", "開発会社に自動帰属するというのも決めつけで、誤り。", "一律に権利が発生しないと法律に明記されているわけではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='9. AIに関する法律と契約'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q45', '会員などの特定の相手に提供するために、一定の管理のもとで蓄積されたデータを、不正な取得や使用から守る不正競争防止法上の枠組みはどれか。', NULL, '["限定提供データ", "営業秘密", "特許権", "著作権"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "特定の相手に提供する、管理されたデータを守る不正競争防止法の枠組みは？", "point": "「特定の相手に提供する、管理された有用なデータを守る枠組み」なら、限定提供データ。", "kid": "「秘密」とまではいかないが、会員など決まった相手にだけ提供するために管理して蓄積したデータ。これを勝手に取得・使用されないよう守るのが、不正競争防止法の限定提供データ。", "eg": "会員限定で配布する有料データベースを、部外者が抜き取って悪用するのを法律で止められる、あの仕組み。", "terms": [["限定提供データ", "特定の相手に提供するため一定管理のもとで蓄積したデータを、不正な取得・使用から守る枠組み"], ["営業秘密", "秘密管理・有用・非公知の3要件で守る枠組み。限定提供データより秘密性が高い"]], "think": "「特定の相手に提供・管理されたデータの保護」なら限定提供データ。完全に秘密にして守る営業秘密とは、公開の程度が違う。", "vs": "営業秘密は秘密のまま守る枠組み(秘密性が高い)、特許権は発明を守る権利、著作権は表現を守る権利で、いずれも共有前提のデータを守る限定提供データではない。", "usecase": "有料で提供するデータセットや、業界で共有するデータを、営業秘密にはできないが保護したいときの枠組み。データ流通を後押しする。", "opt": ["正解。特定の相手に提供する管理されたデータを守るのが限定提供データ。", "秘密のまま守る枠組みで、共有前提の限定提供データとは秘密性が違う。", "発明を守る権利で、データを守る枠組みではない。", "表現を守る権利で、限定提供データではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='9. AIに関する法律と契約'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q46', '公表された他人の著作物を、出所を明示し、自分の文章が主で引用が従となる形などの要件を満たして使う場合、許諾なく利用できる。この仕組みはどれか。', NULL, '["引用", "私的複製", "職務著作", "二次的著作物"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "出所明示・主従関係などの要件を満たせば許諾なく使える仕組みは？", "point": "「出所明示・自分が主で引用が従などの要件を満たせば許諾不要」なら、引用。", "kid": "他人の文章や図を、条件を守れば許可なく使える仕組みが引用。条件は「出所を書く」「自分の文が主で、引用は補助的(従)」「必要な範囲だけ」など。批評や研究で使える。", "eg": "レポートで他人の意見を「〜と述べている(出典)」と示しつつ、自分の主張の裏付けに少し借りる、あの使い方。", "terms": [["引用", "出所明示・主従関係などの要件を満たせば、公表された著作物を許諾なく使える仕組み"], ["著作権法30条の4", "機械学習の解析目的など、味わう目的でない利用を許諾なく認める別の規定"]], "think": "「出所明示・主従関係などの要件を満たして許諾なく使う」なら引用。要件を外れると単なる無断利用になる点に注意。", "vs": "私的複製は個人で楽しむための複製、職務著作は従業員が職務で作った著作物の権利の話、二次的著作物は原作を翻案して作った作品で、いずれも要件を満たして使う引用ではない。", "usecase": "論文・記事・プレゼンで他人の著作物を適法に使うための基本ルール。要件を守れば許諾交渉なしで使えるので実務で重要。", "opt": ["正解。出所明示や主従関係などの要件を満たせば許諾なく使えるのが引用。", "個人で楽しむための複製で、引用の要件の話ではない。", "従業員が職務で作った著作物の権利の話で、引用ではない。", "原作を翻案して作った作品のことで、引用の仕組みではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='9. AIに関する法律と契約'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q47', '生成AIが、事実に反する内容を、あたかも正しいかのようにもっともらしく出力してしまう現象はどれか。', NULL, '["ハルシネーション", "ディープフェイク", "フィルターバブル", "敵対的サンプル"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "生成AIが事実に反する内容を、もっともらしく出力する現象は？", "point": "「生成AIが、事実でないことをもっともらしく答えてしまう」なら、ハルシネーション。", "kid": "生成AIは、それらしい言葉を続ける仕組みなので、事実を確認しているわけではない。だから、存在しない出典や間違った事実を、自信ありげに“それっぽく”出してしまうことがある。これがハルシネーション。", "eg": "よく知らないことを聞かれても、自信満々でそれらしく答えてしまう人、あの調子の良さ。", "terms": [["ハルシネーション", "生成AIが事実に反する内容を、もっともらしく出力してしまう現象"], ["RAG（検索拡張生成）", "外部の正しい情報を参照させて答えさせ、ハルシネーションを減らす工夫"]], "think": "「事実でないことをもっともらしく」ならハルシネーション。偽の映像を作るディープフェイクとは、起きる場面が違う(こちらは生成AIの出力の誤り)。", "vs": "ディープフェイクは本物そっくりの偽映像を作る技術、フィルターバブルは好みの情報に囲まれる現象、敵対的サンプルは入力を細工して誤らせる攻撃で、いずれも事実に反する出力のハルシネーションではない。", "usecase": "生成AIを業務で使う際の最大の注意点。事実確認や、外部情報を参照させる工夫(RAG)で被害を抑える、リスク管理の要。", "opt": ["正解。事実に反する内容をもっともらしく出すのがハルシネーション。", "本物そっくりの偽映像を作る技術で、生成AIの出力の誤りではない。", "好みの情報に囲まれる現象で、事実誤りの出力ではない。", "入力を細工して誤らせる攻撃で、ハルシネーションではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='10. AI倫理・AIガバナンス'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q48', '「1人を犠牲にすれば5人を救えるとき、どちらを選ぶべきか」のように、自動運転などで避けられない選択を迫られる倫理的ジレンマを指す語はどれか。', NULL, '["トロッコ問題", "フレーム問題", "中国語の部屋", "囚人のジレンマ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "「1人か5人か」のような、避けられない選択を迫る倫理的ジレンマは？", "point": "「誰かを犠牲にする選択を迫られる倫理的ジレンマ」なら、トロッコ問題。", "kid": "「このままだと5人が犠牲になるが、進路を変えれば別の1人が犠牲になる。どちらを選ぶ?」という、どちらも正解と言い切れない究極の選択。自動運転の事故回避の判断などで議論される。", "eg": "暴走するトロッコの進路を、5人のいる線路か1人のいる線路か、レバーで選ばされる、あの究極の二択。", "terms": [["トロッコ問題", "誰かを犠牲にする選択を迫られる倫理的ジレンマ。自動運転の判断などで論じられる"], ["AI倫理", "AIの判断が人の生命や権利に関わるときの、善悪や責任の考え方"]], "think": "「どちらも避けられない中での犠牲の選択」ならトロッコ問題。考える範囲を絞れないフレーム問題(技術的難問)とは種類が違う。", "vs": "フレーム問題は考える範囲を絞れない難問、中国語の部屋は理解と処理の分離を示す思考実験、囚人のジレンマは協力か裏切りかのゲーム理論の問題で、いずれも犠牲の選択を迫るトロッコ問題ではない。", "usecase": "自動運転車が事故を避けられないとき「誰を守るよう設計するか」という、答えの出しにくい倫理・責任の議論で引き合いに出される。", "opt": ["正解。誰かを犠牲にする選択を迫られる倫理的ジレンマがトロッコ問題。", "考える範囲を絞れない技術的な難問で、倫理の選択ではない。", "理解と処理の分離を示す思考実験で、犠牲の選択ではない。", "協力か裏切りかのゲーム理論の問題で、トロッコ問題ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='10. AI倫理・AIガバナンス'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q49', '日本で、AIに関わる主体を「開発者・提供者・利用者」に分け、それぞれが取り組むべき事項を示した指針はどれか。', NULL, '["AI事業者ガイドライン", "人間中心のAI社会原則", "著作権法30条の4", "ムーアの法則"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "AIの主体を開発者・提供者・利用者に分け、取り組むべき事項を示した指針は？", "point": "「開発者・提供者・利用者の3者に分けて、取り組む事項を示した指針」なら、AI事業者ガイドライン。", "kid": "AIに関わる人を「作る人(開発者)」「提供する人(提供者)」「使う人(利用者)」の3つに分け、それぞれが何に気をつけて取り組むべきかをまとめた、実務向けの指針。", "eg": "立場ごとに役割分担を書いた“業務マニュアル”のようなもの。作る側・売る側・使う側で気をつける点が違う。", "terms": [["AI事業者ガイドライン", "AIの開発者・提供者・利用者の3者に分け、取り組むべき事項を示した日本の指針"], ["人間中心のAI社会原則", "AIと社会の基本的な理念を示した、より上位の原則"]], "think": "「開発者・提供者・利用者の3分類で実務指針」ならAI事業者ガイドライン。理念を示す人間中心のAI社会原則より、具体的で実務寄り。", "vs": "人間中心のAI社会原則は基本理念を示す上位の原則、著作権法30条の4は機械学習の著作物利用の規定、ムーアの法則は半導体の性能向上の経験則で、いずれも3者に分けた実務指針ではない。", "usecase": "企業がAIを開発・提供・利用する際、自分の立場で何をすべきかを確認する拠り所。AIガバナンス整備の実務の土台。", "opt": ["正解。開発者・提供者・利用者の3者に分け取り組む事項を示すのがAI事業者ガイドライン。", "AIと社会の基本理念を示す上位の原則で、3者向けの実務指針ではない。", "機械学習の著作物利用の規定で、事業者向けの行動指針ではない。", "半導体の性能向上の経験則で、AIの指針ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='10. AI倫理・AIガバナンス'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-c-q50', '近年、AIの倫理・社会的課題として、大規模なモデルの学習が引き起こす問題が指摘されている。その一つはどれか。', NULL, '["大量の電力を消費し、環境に負荷をかける", "学習に必要なデータが年々減っていく", "モデルのサイズが自動で小さくなっていく", "計算コストが年々かからなくなっていく"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "大規模モデルの学習が引き起こす、倫理・社会的な問題の一つは？", "point": "「大規模モデルの学習が大量の電力を消費し、環境に負荷をかける」問題。", "kid": "巨大なモデルを学習させるには、膨大な計算＝大量の電力が要る。その分、二酸化炭素の排出など環境への負荷が大きくなる。これがAIの倫理・社会課題の一つ(環境保護)。", "eg": "超高性能なマシンを何日もフル稼働させ続ける“電気の大食い”。その電気を作る分だけ環境に負担がかかる。", "terms": [["AIの環境負荷", "大規模モデルの学習が大量の電力を消費し、二酸化炭素排出など環境に負担をかける問題"], ["省エネ・軽量化", "小さく効率的なモデルにして、環境負荷や計算コストを抑える取り組み"]], "think": "「大規模学習＝大量の電力＝環境負荷」が要点。モデルは大きくするほど計算も電力も増えるので、データやコストが減るという選択肢は逆。", "vs": "「データが減る」「サイズが自動で小さくなる」「コストがかからなくなる」は、いずれもモデルの大規模化の実態と逆で、環境負荷という指摘に当たらない。", "usecase": "AI開発で「性能を上げるほど電力も増える」トレードオフを意識する根拠。省エネや軽量化、再生可能エネルギー利用が課題になる。", "opt": ["正解。大量の電力を消費し、環境に負荷をかける点が問題。", "大規模化でデータはむしろ多く要るので、減るというのは逆。", "大規模化でサイズは大きくなる傾向で、自動で小さくはならない。", "大規模化で計算コストは増える傾向で、かからなくなるは逆。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-c' AND c.name='10. AI倫理・AIガバナンス'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
COMMIT;
