BEGIN;
INSERT INTO public.subjects (slug, name, description, color, sort_order)
VALUES ('g-kentei-b', 'G検定（JDLA ジェネラリスト検定） Set B',
        'JDLA G検定 対策 第2弾。シラバス2024（2024年11月試験より適用）準拠。Set A が扱っていないテーマを中心に構成。個人情報保護法は範囲外（保有資格のため意図的に除外）。本試験の再現ではなく学習用オリジナル。',
        '#0B5CAB', 51)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.categories (subject_id, name, color, sort_order)
SELECT s.id, v.name, v.color, v.sort_order
FROM public.subjects s
CROSS JOIN (VALUES
  ('1. 人工知能とは', '#58a6ff', 0),
  ('2. 人工知能をめぐる動向', '#79c0ff', 1),
  ('3. 機械学習の概要', '#3fb950', 2),
  ('4. ディープラーニングの概要', '#a371f7', 3),
  ('5. ディープラーニングの要素技術', '#d2a8ff', 4),
  ('6. ディープラーニングの応用例', '#f0883e', 5),
  ('7. AIの社会実装に向けて', '#e3b341', 6),
  ('8. AIに必要な数理・統計知識', '#39c5cf', 7),
  ('9. AIに関する法律と契約', '#f85149', 8),
  ('10. AI倫理・AIガバナンス', '#ff7b72', 9)
) AS v(name, color, sort_order)
WHERE s.slug = 'g-kentei-b'
ON CONFLICT (subject_id, name) DO NOTHING;
COMMIT;
BEGIN;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q1', '機械に知能があるかを、人間の判定者が会話相手を人間と見分けられるかどうかで判断する方法はどれか。', NULL, '["チューリングテスト", "中国語の部屋", "フレーム問題", "シンボルグラウンディング問題"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "会話で人間と見分けられなければ知能ありとみなす、その判定方法の名前は？", "point": "「会話して人間と区別できなければ知能あり」とするテストなら、チューリングテスト。", "kid": "相手が人間か機械かを、文字のやり取りだけで当てさせる。見分けられなければ「その機械には知能があるとしよう」と決める判定方法。", "eg": "カーテン越しにチャットして、相手が人か機械か当てるゲーム。当てられなければ機械の勝ち＝知能ありと認める。", "terms": [["チューリングテスト", "会話して人間か機械か見分けられなければ、知能があると認める判定方法"], ["中国語の部屋", "正しく受け答えできても意味は理解していない、と反論する思考実験"]], "think": "「会話で人間と区別できるか」で知能を測るならチューリングテスト。中身の理解ではなく、外から見た振る舞いで判断する点がポイント。", "vs": "中国語の部屋はこのテストへの反論(受け答えできても理解とは限らない)、フレーム問題は考える範囲を絞れない難問、シンボルグラウンディング問題は記号と実物が結びつかない難問。どれも知能の判定方法ではない。", "usecase": "「AIが人間らしいか」を測る発想の原点。今のチャットAIの自然さを語るときの基準としてよく引き合いに出される。", "opt": ["正解。会話で人間と区別できなければ知能ありとみなす判定方法。", "受け答えできても意味は理解していないと反論する思考実験で、判定方法ではない。", "考える範囲を絞れない難問で、知能の判定方法ではない。", "記号と実物の意味が結びつかない難問で、判定方法ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='1. 人工知能とは'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q2', '「人工知能（Artificial Intelligence）」という言葉が初めて使われたとされる、1956年の研究者の集まりはどれか。', NULL, '["ダートマス会議", "第五世代コンピュータプロジェクト", "ロボット工学三原則の発表", "ILSVRC（画像認識コンテスト）"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "「人工知能」という言葉が初めて使われた1956年の集まりの名前は？", "point": "「人工知能(AI)」の語が生まれた1956年の会議なら、ダートマス会議。", "kid": "1956年、研究者が集まって「これからは“人工知能”という分野をやろう」と名付けた会議。AIという言葉が生まれた場。", "eg": "新しい学問に名前をつけた“旗揚げ集会”のようなもの。ここで「人工知能」という看板が初めて掲げられた。", "terms": [["ダートマス会議", "1956年、マッカーシーらが開いた会議。ここで「人工知能」という言葉が初めて使われた"], ["第1次AIブーム", "この会議の後に始まった、探索や推論で問題を解く最初のブーム"]], "think": "「AIという言葉の始まり・1956年」ならダートマス会議。技術そのものではなく、分野の名付けの出来事だと押さえる。", "vs": "第五世代コンピュータは1980年代の日本の国家プロジェクト、ロボット工学三原則はSF作家アシモフの創作、ILSVRCは2010年代の画像認識コンテスト。どれもAIの語源となった会議ではない。", "usecase": "AIの歴史の出発点。ブームの流れ(第1次→第2次→第3次)を語るときの起点として押さえる。", "opt": ["正解。1956年、「人工知能」という言葉が初めて使われた会議。", "1980年代の日本の国家プロジェクトで、AIの語源の会議ではない。", "SF作家が作った創作上の原則で、実在の会議ではない。", "2010年代の画像認識コンテストで、AIの語源とは時代が違う。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='1. 人工知能とは'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q3', '第1次AIブームの限界を象徴する言葉で、迷路やパズルのように単純化された問題は解けても、複雑な現実の問題には歯が立たなかったことを指す語はどれか。', NULL, '["トイ・プロブレム", "フレーム問題", "組合せ爆発", "次元の呪い"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "単純化された問題は解けても現実の複雑な問題は解けなかった、第1次ブームの限界を指す語は？", "point": "「おもちゃのように単純化した問題しか解けなかった」なら、トイ・プロブレム。", "kid": "迷路や積み木のように、きれいに単純化された問題なら解ける。でも現実のごちゃごちゃした問題には歯が立たない。この限界を「おもちゃの問題」と呼んだ。", "eg": "教科書の練習問題は解けるのに、実際の仕事の複雑な課題になると手も足も出ない、あの状態。", "terms": [["トイ・プロブレム", "迷路やパズルのように単純化された問題。第1次ブームのAIはこれしか解けなかった"], ["組合せ爆発", "選択肢が増えると調べる場合の数が爆発的に増え、計算が追いつかなくなる現象"]], "think": "「単純化された問題は解けたが現実は無理」という第1次ブームの限界ならトイ・プロブレム。原因の一つが組合せ爆発。", "vs": "フレーム問題は考える範囲を絞れない難問、組合せ爆発は場合の数が急増する現象、次元の呪いは項目が多すぎてデータがスカスカになる問題。どれも「おもちゃの問題」そのものではない。", "usecase": "「なぜ最初のAIブームが冷めたか」の説明に使う。単純な世界と現実の複雑さのギャップを示す言葉。", "opt": ["正解。単純化された問題しか解けなかった第1次ブームの限界を指す。", "考える範囲を絞れない難問で、単純化された問題という意味ではない。", "場合の数が急増する現象で、限界そのものを指す言葉ではない。", "項目が多すぎてデータがスカスカになる別の問題。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='1. 人工知能とは'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q4', 'AIが自分自身を上回るAIを作り出せるようになり、技術の進歩が予測不能なほど加速するとされる転換点を指す語はどれか。', NULL, '["シンギュラリティ（技術的特異点）", "ムーアの法則", "AI効果", "チューリングポイント"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "AIが自分を超えるAIを生み、進歩が予測不能に加速するとされる転換点は？", "point": "「AIが人間の知能を超え、進歩が爆発的に加速する未来の分岐点」なら、シンギュラリティ。", "kid": "AIが「自分より賢いAI」を作れるようになると、賢さがねずみ算式に跳ね上がる。その先は人間には予測できない——その転換点のこと。未来予測の概念で、まだ起きていない。", "eg": "雪だるまが坂を転がり始めると一気に巨大化して止められなくなる、あのイメージ。賢さが自己増殖する分岐点。", "terms": [["シンギュラリティ（技術的特異点）", "AIが自分を超えるAIを生み、知能が爆発的に伸びるとされる未来の転換点"], ["ムーアの法則", "半導体の性能がほぼ一定ペースで向上するという経験則"]], "think": "「AIが人間を超えて進歩が加速する未来の分岐点」ならシンギュラリティ。実在の技術ではなく将来予測の概念。", "vs": "ムーアの法則は半導体の性能向上の経験則、AI効果は仕組みが分かると知能扱いされなくなる心理、チューリングポイントは正式な用語ではない造語。", "usecase": "AIの将来リスクや期待を語るときの中心的な言葉。過度な期待や不安を切り分けるのに、概念として知っておく。", "opt": ["正解。AIが人間を超え進歩が爆発的に加速するとされる転換点。", "半導体の性能向上の経験則で、知能の転換点の話ではない。", "仕組みが分かると知能扱いされなくなる心理で、未来の転換点ではない。", "正式な用語ではない造語で、この転換点を指さない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='1. 人工知能とは'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q5', '探索木をたどるとき、まず出発点に近い節点をすべて調べ、次に一段深い節点をすべて調べる、というように浅い方から順に探す方法はどれか。', NULL, '["幅優先探索", "深さ優先探索", "山登り法", "焼きなまし法"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "浅いところから順に、同じ深さを全部調べてから次へ進む探索方法は？", "point": "「近いところから順に、同じ深さを全部調べてから次へ」なら、幅優先探索。", "kid": "出発点から近い場所を全部調べ、次に一歩遠い場所を全部調べる…と、輪を広げるように浅い方から探すやり方。", "eg": "池に石を落としたときの波紋のように、中心から一枚ずつ外側へ調べていく探し方。", "terms": [["幅優先探索", "出発点に近い順に、同じ深さの節点を全部調べてから次の深さへ進む方法"], ["深さ優先探索", "一本道をとことん奥まで進み、行き止まったら戻る逆の方法"]], "think": "「浅い層を全部見てから次の層へ」なら幅優先。「まず深く潜って行き止まりで戻る」なら深さ優先。進む順で見分ける。", "vs": "深さ優先探索は深く潜る逆のやり方、山登り法は今より良くなる方へ進み続ける最適化、焼きなまし法はわざと悪い方へも動いて局所解を抜ける最適化。どれも浅い順に全部調べる探索ではない。", "usecase": "一番近い(手数の少ない)解を確実に見つけたいときに使う。迷路の最短手数や、SNSで「何人たどれば繋がるか」などで効く。", "opt": ["正解。浅い層を全部調べてから次の層へ進むのが幅優先探索。", "一本道を深く潜る逆のやり方で、浅い順ではない。", "今より良くなる方へ進み続ける最適化で、木を網羅する探索ではない。", "わざと悪い方へも動く最適化で、浅い順に調べる探索ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q6', 'ゲームの先読みで、探索しても結果に影響しないと分かった枝を途中で切り捨て、無駄な計算を減らす手法はどれか。', NULL, '["αβ法（アルファ・ベータ枝刈り）", "誤差逆伝播法", "主成分分析", "ブートストラップ法"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "先読みで、調べても無駄と分かった枝を途中で切り捨てて計算を減らす手法は？", "point": "「先読みで、明らかに無駄な枝を途中で切って計算を減らす」なら、αβ法（枝刈り）。", "kid": "将棋やチェスの先読みで、「この手はどう転んでも損」と分かった枝は、それ以上調べずに切り捨てる。無駄な計算を省いて速くする工夫。", "eg": "買い物で「この店は明らかに高い」と分かった時点で、棚を全部見ずに次の店へ行く、あの判断。見るだけ無駄な所を飛ばす。", "terms": [["αβ法（アルファ・ベータ枝刈り）", "ゲーム木の探索で、結果に影響しない枝を早めに切り捨てて計算量を減らす手法"], ["ミニマックス法", "相手が最善を尽くす前提で、自分の最善手を選ぶ先読みの基本"]], "think": "「先読みで無駄な枝を切る」ならαβ法。全部読むミニマックス法の計算を減らす改良、と押さえる。", "vs": "誤差逆伝播法はニューラルネットの学習手法、主成分分析は次元削減、ブートストラップ法は重複ありでデータを選び直す方法。どれもゲーム木の枝刈りではない。", "usecase": "将棋・チェス・オセロなどのゲームAIで、限られた時間により深く読むために使う。無駄を省いて先読みを深める土台。", "opt": ["正解。結果に影響しない枝を切り捨てて計算を減らすのがαβ法。", "ニューラルネットの学習手法で、ゲーム木の枝刈りではない。", "次元削減の手法で、探索の枝刈りとは関係ない。", "重複ありでデータを選び直す方法で、枝刈りではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q7', '囲碁AIのAlphaGoでも使われた、次の手をランダムに何度も試して勝率を見積もり、有望な手を選ぶ探索手法はどれか。', NULL, '["モンテカルロ木探索", "深さ優先探索", "k近傍法", "サポートベクターマシン"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "ランダムな試行を繰り返して手の勝率を見積もり、有望な手を選ぶ探索手法は？", "point": "「ランダムに何度も試して勝率で手を評価する」なら、モンテカルロ木探索。", "kid": "この手を打ったら勝てるか？を、その先をランダムに何回も打ちきってみて勝率で見積もる。勝率の高い手を選ぶ、という探索のやり方。", "eg": "サイコロを何千回も振って出目の傾向をつかむように、ランダムな試行を大量に重ねて「良さそうな手」を見つける。", "terms": [["モンテカルロ木探索", "手の先をランダムに多数シミュレーションし、勝率で手の良さを見積もる探索手法"], ["AlphaGo", "この手法と深層学習を組み合わせ、プロ棋士に勝った囲碁AI"]], "think": "「ランダム試行を大量に重ねて勝率で評価」ならモンテカルロ木探索。全部を律儀に読むのではなく、サンプルで見積もるのが特徴。", "vs": "深さ優先探索は一本道を深く潜る探索、k近傍法は近所の正解で多数決する分類、サポートベクターマシンは分ける線を学ぶ分類。どれもランダム試行で勝率を見積もる探索ではない。", "usecase": "囲碁のように選択肢が多すぎて全部読めないゲームで力を発揮した。AlphaGoの中核技術の一つ。", "opt": ["正解。ランダムな試行を重ねて勝率で手を評価するのがモンテカルロ木探索。", "一本道を深く潜る探索で、ランダム試行で勝率を見積もる手法ではない。", "近所の正解で多数決する分類で、ゲームの探索ではない。", "分ける線を学ぶ分類で、勝率を見積もる探索ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q8', '「鳥は動物である」「ペンギンは鳥である」のように、概念どうしの関係を線でつないで知識を表す方法はどれか。', NULL, '["意味ネットワーク", "ニューラルネットワーク", "決定木", "混同行列"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "概念どうしの関係を線でつないで知識を表す方法は？", "point": "「概念を『〜は〜である』の関係で線でつないで知識を表す」なら、意味ネットワーク。", "kid": "「鳥は動物」「ペンギンは鳥」のように、言葉どうしを“〜は〜である”の矢印でつないで、知識を図にする方法。第2次ブームの知識表現の一つ。", "eg": "家系図のように、概念どうしを線でつないで「誰が誰の仲間か」を一目で分かるようにした図。", "terms": [["意味ネットワーク", "概念(ノード)を「is-a(〜である)」などの関係(リンク)でつないで知識を表す方法"], ["ニューラルネットワーク", "脳の神経細胞をまねた、数値の重みで学習する別物のネットワーク"]], "think": "「概念を関係でつないで知識を図にする」なら意味ネットワーク。名前が似たニューラルネットワーク(学習の仕組み)と混同しない。", "vs": "ニューラルネットワークは重みを学習する仕組み、決定木は条件分岐で予測する手法、混同行列は判定結果の集計表。どれも概念の関係を表す知識表現ではない。", "usecase": "知識をコンピュータに持たせる古典的な方法。今のナレッジグラフ(検索やレコメンドで使う知識の網)の考え方の源流。", "opt": ["正解。概念を関係の線でつないで知識を表すのが意味ネットワーク。", "重みを学習する脳まねのネットワークで、知識を図にする方法ではない。", "条件分岐で予測する手法で、概念の関係を表すものではない。", "判定結果の集計表で、知識表現ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q9', '人間なら誰でも知っている一般常識を、膨大なルールとして書き込もうとした1984年開始の長期プロジェクトはどれか。', NULL, '["Cyc（サイク）プロジェクト", "AlphaGo", "ImageNet", "GPT"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "一般常識を膨大なルールとして書き込もうとした長期プロジェクトは？", "point": "「一般常識を人手で大量のルールにする長期プロジェクト」なら、Cyc。", "kid": "「水は濡れている」「人は死ぬ」のような、人間には当たり前すぎる常識を、ひたすら手作業でルールに書き込もうとした長い長いプロジェクト。", "eg": "巨大な“常識の辞書”を、一項目ずつ手書きで延々と書き足していくような試み。", "terms": [["Cyc（サイク）プロジェクト", "1984年開始。人間の一般常識を膨大なルールとして記述しようとした長期プロジェクト"], ["知識獲得のボトルネック", "知識を人手でルールにする作業が重すぎて詰まる、という第2次ブームの壁"]], "think": "「常識を人手でルール化する長期の試み」ならCyc。知識獲得のボトルネック(手作業の限界)を体現した例。", "vs": "AlphaGoは囲碁AI、ImageNetは画像認識用の大規模データセット、GPTは文章生成の言語モデル。どれも常識をルール化する古典的プロジェクトではない。", "usecase": "「常識を全部ルールで書くのは無理」という知識獲得のボトルネックを示す代表例。データから学ぶ機械学習へ流れが変わった背景として押さえる。", "opt": ["正解。一般常識を膨大なルールにしようとした長期プロジェクト。", "囲碁AIで、常識をルール化するプロジェクトではない。", "画像認識用の大規模データセットで、常識のルール化ではない。", "文章生成の言語モデルで、常識を手作業でルール化する試みではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q10', '2012年の画像認識コンテストで、ディープラーニングを使ったモデルが従来手法に大差をつけて優勝し、第3次AIブームの火付け役となった。このモデルはどれか。', NULL, '["AlexNet", "ELIZA", "MYCIN", "Deep Blue"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "2012年の画像認識コンテストで圧勝し、第3次ブームの火付け役になったディープラーニングのモデルは？", "point": "「2012年の画像認識コンテストでディープラーニングが圧勝→第3次ブーム」の主役なら、AlexNet。", "kid": "2012年、画像を見分ける大会で、ディープラーニングを使ったAlexNetが2位に大差をつけて優勝。「ディープラーニングはすごい」と世界が気づき、今のAIブーム(第3次)が始まった。", "eg": "無名の新人が大会でいきなり圧勝して、その競技のやり方を一変させた、あの衝撃。", "terms": [["AlexNet", "2012年のILSVRC(画像認識コンテスト)でディープラーニングを使い圧勝したモデル。第3次ブームの契機"], ["ILSVRC", "大量の画像を何のクラスか当てさせる、画像認識の有名なコンテスト"]], "think": "「2012年・画像認識・ディープラーニングで圧勝」ならAlexNet。第3次ブームの起点の出来事として押さえる。", "vs": "ELIZAは1960年代の対話プログラム、MYCINは第2次ブームの医療エキスパートシステム、Deep Blueはチェスでチャンピオンに勝ったAIで画像認識ではない。", "usecase": "「なぜ2010年代からAIが急に流行ったか」の答え。ディープラーニングの実力が証明された歴史的な出来事。", "opt": ["正解。2012年の画像認識コンテストでディープラーニングを使い圧勝したモデル。", "1960年代の対話プログラムで、画像認識で優勝したモデルではない。", "第2次ブームの医療エキスパートシステムで、画像認識ではない。", "チェスでチャンピオンに勝ったAIで、画像認識コンテストの優勝モデルではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q11', '正解を一つずつ教えるのではなく、行動の結果として与えられる「報酬」を手がかりに、試行錯誤を通じて良い行動を学ぶ学習はどれか。', NULL, '["強化学習", "教師あり学習", "教師なし学習", "転移学習"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "報酬を手がかりに、試行錯誤で良い行動を学ぶ学習の種類は？", "point": "「正解ではなく報酬(ごほうび)を頼りに、試行錯誤で行動を学ぶ」なら、強化学習。", "kid": "「これが正解」と一つずつ教える代わりに、うまくいったら“ごほうび”を与える。AIはごほうびが増えるよう、試行錯誤で良い動き方を自分で見つけていく。", "eg": "犬のしつけと同じ。うまくできたらおやつ。何が良い行動かを、ごほうびの多い少ないから犬が自分で学ぶ。", "terms": [["強化学習", "行動の結果もらえる報酬を最大にするよう、試行錯誤で良い行動を学ぶ方法"], ["報酬", "行動が良かったかを示す点数。強化学習が手がかりにする"]], "think": "「報酬を頼りに試行錯誤で行動を学ぶ」なら強化学習。1問ずつ正解を教える教師あり、正解なしで構造を見つける教師なしと区別する。", "vs": "教師あり学習は入力と正解のセットで学ぶ、教師なし学習は正解なしでまとまりを見つける、転移学習は学んだ知識を別タスクに使い回す考え方。どれも報酬による試行錯誤ではない。", "usecase": "ゲームAI(AlphaGo)、ロボットの歩行、広告や在庫の最適化など、「一連の行動の良し悪しを結果で判断する」場面で使う。", "opt": ["正解。報酬を手がかりに試行錯誤で良い行動を学ぶのが強化学習。", "入力と正解のセットで学ぶ方法で、報酬による試行錯誤ではない。", "正解なしでデータのまとまりを見つける方法で、報酬の話ではない。", "学んだ知識を別タスクに使い回す考え方で、学習の種類そのものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q12', '「年齢は30歳以上か」「年収は500万円以上か」のように、条件で枝分かれさせて予測する、判断の流れが目で追える手法はどれか。', NULL, '["決定木", "サポートベクターマシン", "ニューラルネットワーク", "主成分分析"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "条件で枝分かれさせて予測する、判断の流れが目で追える手法は？", "point": "「条件のYes/Noで枝分かれし、判断の流れが目で追える」なら、決定木。", "kid": "「30歳以上？→Yesならこっち、Noならあっち」と、質問で枝分かれしていって答えにたどり着く。なぜその結論かを図で追えるのが強み。", "eg": "健康診断のフローチャートや、動物図鑑の「はい/いいえで進む見分け方」と同じ形。", "terms": [["決定木", "条件で枝分かれさせて予測する手法。判断の道すじが人に見えて解釈しやすい"], ["ランダムフォレスト", "たくさんの決定木を作って多数決し、精度を上げた発展形"]], "think": "「条件で枝分かれ・判断が目で追える」なら決定木。中身が見えにくいニューラルネットとは対照的に、理由を説明しやすいのが特徴。", "vs": "サポートベクターマシンは分ける線を学ぶ手法、ニューラルネットワークは中身が見えにくい重みの学習、主成分分析は次元削減。どれも条件分岐で判断を可視化する手法ではない。", "usecase": "与信や医療など「なぜその判断か」を説明したい場面に向く。単体は精度が出にくいので、束ねたランダムフォレストがよく使われる。", "opt": ["正解。条件で枝分かれし、判断の流れが目で追えるのが決定木。", "分ける線を学ぶ手法で、条件分岐で判断を可視化するものではない。", "中身が見えにくい重みの学習で、判断の流れを追いにくい。", "次元削減の手法で、条件分岐による予測ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q13', 'たくさんの決定木をそれぞれ少しずつ違うデータで作り、その多数決で予測する手法はどれか。', NULL, '["ランダムフォレスト", "ロジスティック回帰", "k-means法", "オートエンコーダ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "たくさんの決定木を作って多数決で予測する手法は？", "point": "「たくさんの決定木を作って多数決」なら、ランダムフォレスト。", "kid": "1本の決定木は間違えやすい。そこで少しずつ違うデータで木をたくさん作り、みんなの多数決で決める。1本より安定して当たる。", "eg": "一人の意見より、たくさんの人に別々に聞いて多数決した方が外れにくい、あの発想。木がたくさんで“森”。", "terms": [["ランダムフォレスト", "少しずつ違うデータで多数の決定木を作り、多数決(や平均)で予測する手法"], ["バギング", "データを重複ありで選び直して並列に学習器を作り、多数決する考え方。ランダムフォレストの土台"]], "think": "「決定木をたくさん・並列に作って多数決」ならランダムフォレスト(バギングの代表)。前の間違いを直しながら順番に足すブースティングとは作り方が逆。", "vs": "ロジスティック回帰は確率でグループ分けする分類、k-means法は正解なしのグループ分け、オートエンコーダは圧縮して復元を学ぶネットワーク。どれも決定木の多数決ではない。", "usecase": "表形式データの予測で、手軽に高い精度が出る定番。どの項目が効いたか(重要度)も分かるので実務で使いやすい。", "opt": ["正解。多数の決定木を作って多数決で予測するのがランダムフォレスト。", "確率でグループ分けする分類で、決定木の多数決ではない。", "正解なしのグループ分けで、決定木を束ねる手法ではない。", "圧縮して復元を学ぶネットワークで、予測の多数決ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q14', '2つのグループを分ける境界線を引くとき、境界と最も近いデータとの余白（マージン）ができるだけ広くなるように引く手法はどれか。', NULL, '["サポートベクターマシン（SVM）", "k-means法", "主成分分析", "ナイーブベイズ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "2グループを分ける境界を、余白(マージン)が最大になるように引く手法は？", "point": "「境界と一番近いデータとの余白(マージン)を最大にして分ける」なら、SVM。", "kid": "2つのグループの間に線を引くとき、どちらのグループからもなるべく離れた“真ん中”に引く。余白を広く取るほど、新しいデータでも間違えにくい。", "eg": "2つのチームの間に道を作るとき、どちらの陣地にもギリギリ寄らず、一番広く空いた真ん中に引く、あの引き方。", "terms": [["サポートベクターマシン（SVM）", "境界と最も近いデータとの余白(マージン)が最大になるよう分ける分類手法"], ["マージン", "境界と、一番近いデータとの間の余白。これを最大にするのがSVMの狙い"]], "think": "「余白(マージン)を最大にして分ける」ならSVM。ただ分ければよいのではなく、“一番安全な真ん中”に境界を引く点がポイント。", "vs": "k-means法は正解なしのグループ分け、主成分分析は次元削減、ナイーブベイズは確率で分類する別手法。どれもマージン最大化で境界を引くものではない。", "usecase": "データが少なめでも高い精度が出しやすく、文字認識や文書分類などで長く使われてきた定番の分類手法。", "opt": ["正解。余白(マージン)を最大にして分けるのがSVM。", "正解なしのグループ分けで、余白を最大化する境界の話ではない。", "次元削減の手法で、分類の境界を引くものではない。", "確率で分類する別手法で、マージン最大化ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q15', 'モデルが単純すぎて的外れになる誤りと、複雑すぎてデータのブレに振り回される誤りは、一方を抑えると他方が増えやすい。この関係を指す語はどれか。', NULL, '["バイアスとバリアンスのトレードオフ", "次元の呪い", "データリーケージ", "コールドスタート問題"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "単純すぎる誤り(バイアス)と複雑すぎる誤り(バリアンス)は両立しにくい、この関係の名前は？", "point": "「単純すぎる誤りと複雑すぎる誤りが、あちらを立てればこちらが立たず」なら、バイアスとバリアンスのトレードオフ。", "kid": "モデルが単純すぎると的外れ(バイアス大＝未学習)。複雑すぎるとデータの偶然のブレまで拾って本番に弱い(バリアンス大＝過学習)。片方を抑えるともう片方が増えがちで、ちょうど良い所を探す。", "eg": "服のサイズ選び。大きすぎ(ゆるゆる)も小さすぎ(きつきつ)もダメで、ちょうど良い所を探すのと同じ。", "terms": [["バイアス", "モデルが単純すぎて的を外す誤り。大きいと未学習"], ["バリアンス", "モデルが複雑すぎてデータのブレに振り回される誤り。大きいと過学習"]], "think": "「単純すぎ(バイアス)と複雑すぎ(バリアンス)のどちらも誤りで、両立しにくい」ならこのトレードオフ。未学習と過学習を同じ軸で捉えた見方。", "vs": "次元の呪いは項目が多すぎてデータがスカスカになる問題、データリーケージは答えが訓練に漏れる失敗、コールドスタート問題はおすすめの初期データ不足。どれも2種類の誤りの綱引きではない。", "usecase": "モデルの複雑さをどこまで上げるか(木の深さ、層の数など)を決める指針。「未学習でも過学習でもない所」を狙う調整の土台。", "opt": ["正解。単純すぎる誤りと複雑すぎる誤りが両立しにくい関係を指す。", "項目が多すぎてデータがスカスカになる問題で、2種類の誤りの綱引きではない。", "答えが訓練に漏れる失敗で、この関係とは別。", "おすすめの初期データ不足の問題で、この関係とは関係ない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q16', '手元のデータを「訓練用」と「テスト用」に一度だけ分け、訓練用で学習し、テスト用で成績を測る、最もシンプルな評価方法はどれか。', NULL, '["ホールドアウト検証", "k分割交差検証", "グリッドサーチ", "アンサンブル学習"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "データを訓練用とテスト用に一度だけ分けて評価する、最もシンプルな方法は？", "point": "「訓練用とテスト用に一度だけ分けて評価する」なら、ホールドアウト検証。", "kid": "手元のデータを「練習用」と「本番テスト用」に一回だけ分ける。練習用で覚えさせ、テスト用で初見の成績を測る。一番シンプルな評価のやり方。", "eg": "問題集を「練習ページ」と「模試ページ」に分けて、模試ページで実力を測る、あの方式。", "terms": [["ホールドアウト検証", "データを訓練用とテスト用に一度だけ分けて評価する方法"], ["k分割交差検証", "分け方を変えて何度も測り平均する、より信頼性の高い方法"]], "think": "「一度だけ訓練とテストに分けて終わり」ならホールドアウト。分け直して何度も測り平均するk分割交差検証より手軽だが、分け方のたまたまに左右されやすい。", "vs": "k分割交差検証は分け直して平均する方法、グリッドサーチは設定の組合せを総当たりする方法、アンサンブル学習は複数モデルを組み合わせる方法。どれも一度きりの分割による評価そのものではない。", "usecase": "データが十分ある場合の手軽な評価に使う。少ないデータで安定して測りたいときは、より丁寧なk分割交差検証を選ぶ。", "opt": ["正解。訓練用とテスト用に一度だけ分けて評価するのがホールドアウト検証。", "分け直して何度も測り平均する方法で、一度きりではない。", "設定の組合せを総当たりする方法で、評価の分け方そのものではない。", "複数モデルを組み合わせる方法で、データの分割による評価ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q17', '身長(cm)と体重(kg)のように単位も桁も違う項目を、そのまま使うと桁の大きい項目に結果が引っ張られる。これを防ぐため各項目のスケールをそろえる前処理はどれか。', NULL, '["標準化（スケールをそろえる正規化）", "アノテーション", "データ拡張", "次元削減"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "単位も桁も違う項目のスケールをそろえて、桁の大きい項目に引っ張られないようにする前処理は？", "point": "「桁や単位の違う項目のスケールをそろえる前処理」なら、標準化(正規化)。", "kid": "身長(150〜180)と体重(50〜80)をそのまま混ぜると、数字の大きい身長ばかり効いてしまう。だから各項目を同じものさしにそろえてから使う。この下ごしらえが標準化。", "eg": "各教科の点数を、満点も難易度も違うまま合計せず、偏差値にそろえてから比べる、あの発想。", "terms": [["標準化", "各項目を平均0・ばらつき1くらいにそろえ、桁の違いで結果が偏らないようにする前処理"], ["特徴量", "モデルに入れる各項目(身長・体重など)のこと"]], "think": "「桁や単位の違いをそろえる下ごしらえ」なら標準化(正規化)。距離や大きさを使う手法(k近傍法・SVMなど)ほど、やらないと結果が偏る。", "vs": "アノテーションは正解ラベルを付ける作業、データ拡張はデータを水増しする手法、次元削減は項目の数を減らす手法。どれもスケールをそろえる前処理そのものではない。", "usecase": "距離や大きさで判断する手法の前にほぼ必須の下ごしらえ。やるだけで精度が安定することが多い、地味だが効く工程。", "opt": ["正解。桁や単位の違う項目のスケールをそろえる前処理。", "正解ラベルを付ける作業で、スケールをそろえる前処理ではない。", "データを水増しする手法で、スケール調整ではない。", "項目の数を減らす手法で、スケールをそろえる処理とは別。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q18', '入力がマイナスなら0、プラスならそのまま通す、というシンプルな活性化関数で、勾配消失を起こしにくく深い層でよく使われるものはどれか。', NULL, '["ReLU", "シグモイド関数", "ソフトマックス関数", "ステップ関数"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "マイナスは0・プラスはそのまま通す、勾配消失を起こしにくい活性化関数は？", "point": "「マイナスは0、プラスはそのまま。勾配消失を起こしにくい」なら、ReLU。", "kid": "各層で通す値を加工する部品(活性化関数)の一つ。マイナスは0にし、プラスはそのまま素通し。傾きが痩せないので、深い層でも学習の「直してね」の合図が消えにくい。", "eg": "水道の逆止弁のように、マイナス方向は止めてプラス方向はそのまま通す、シンプルな弁。", "terms": [["ReLU", "入力がマイナスなら0、プラスならそのまま通す活性化関数。勾配消失に強い"], ["シグモイド", "出力を0〜1に押し込む活性化関数。傾きが小さく深い層で勾配が消えやすい"]], "think": "「マイナスは0・プラスは素通しで勾配が消えにくい」ならReLU。傾きが痩せて勾配消失を起こしやすいシグモイドの代わりに使う、と押さえる。", "vs": "シグモイドは0〜1に押し込む活性化関数(勾配が消えやすい)、ソフトマックスは出口で合計100%の確率にする関数、ステップ関数は0か1に切り替えるだけで学習に使いにくい。どれもReLUではない。", "usecase": "今のディープラーニングの中間層で最も標準的に使われる。深いネットワークが学習できるようになった立役者の一つ。", "opt": ["正解。マイナスは0・プラスは素通しで勾配が消えにくいのがReLU。", "0〜1に押し込む関数で、傾きが小さく勾配が消えやすい。", "出口で合計100%の確率にする関数で、中間層の素通しとは役割が違う。", "0か1に切り替えるだけで、学習の勾配が得られず使いにくい。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q19', '各層に入ってくる値のばらつきを層ごとにそろえることで、学習を安定させ速くする手法はどれか。', NULL, '["バッチ正規化", "ドロップアウト", "データ拡張", "早期終了"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "各層に入る値のばらつきをそろえて、学習を安定・高速にする手法は？", "point": "「各層に入る値のばらつきを層ごとにそろえて学習を安定させる」なら、バッチ正規化。", "kid": "層を通るうちに、入ってくる値の大きさやばらつきがバラバラになると学習しにくい。そこで層ごとに値を整えて(平均やばらつきをそろえて)、学習を安定させ速くする工夫。", "eg": "リレーで各走者にバトンを毎回同じ高さで渡すように、各層への“渡し方”を一定にそろえて流れを乱さない、あの発想。", "terms": [["バッチ正規化", "各層に入る値を、まとまり(バッチ)ごとに平均やばらつきをそろえて学習を安定させる手法"], ["内部共変量シフト", "学習中に各層への入力の分布がずれていく現象。バッチ正規化が抑えるとされる"]], "think": "「各層に入る値のばらつきをそろえる」ならバッチ正規化。ノードを休ませるドロップアウト(過学習対策)とは目的が違う。", "vs": "ドロップアウトはノードをランダムに休ませる過学習対策、データ拡張はデータを水増しする手法、早期終了は成績が悪化し始めたら学習を止める手法。どれも各層の値をそろえる正規化ではない。", "usecase": "深いネットワークの学習を安定させ、学習率を大きめにして速く進めるのに効く。今の多くのモデルで標準的に組み込まれる。", "opt": ["正解。各層に入る値のばらつきをそろえて学習を安定させるのがバッチ正規化。", "ノードをランダムに休ませる過学習対策で、値をそろえる正規化ではない。", "データを水増しする手法で、層の値をそろえるものではない。", "学習を途中で止める手法で、値の正規化ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q20', '全データではなく、一部を小分け（ミニバッチ）にして少しずつ重みを更新していく、基本的な最適化のやり方はどれか。', NULL, '["確率的勾配降下法（SGD）", "主成分分析", "k近傍法", "焼きなまし法"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "データを小分け(ミニバッチ)にして少しずつ重みを更新する、基本の最適化は？", "point": "「データを小分けにして少しずつ重みを更新する」なら、確率的勾配降下法(SGD)。", "kid": "AIの学習は「成績が一番良くなる場所へ坂を下る」イメージ。全データで一歩ずつだと重いので、データを小分け(ミニバッチ)にして、こまめに何度も一歩を進める。これがSGD。", "eg": "全教科まとめて復習してから直すのではなく、少しずつ小テストしては直す、を高速で繰り返す、あの進め方。", "terms": [["確率的勾配降下法（SGD）", "データを小分けにして、少しずつ何度も重みを更新する基本の最適化"], ["ミニバッチ", "一度の更新に使うデータの小さなかたまり"]], "think": "「データを小分けにしてこまめに更新」ならSGD。AdamなどはこのSGDに勢いや歩幅調整を足した発展形。", "vs": "主成分分析は次元削減、k近傍法は近所の正解で多数決する分類、焼きなまし法はわざと悪い方へも動く別の最適化。どれもミニバッチで重みを更新する基本の最適化ではない。", "usecase": "ディープラーニングの学習の土台。大量データでも現実的な速さで学習を進められる。Adamなどの発展形もこの上に乗る。", "opt": ["正解。データを小分けにして少しずつ重みを更新するのがSGD。", "次元削減の手法で、重みを更新する最適化ではない。", "近所の正解で多数決する分類で、最適化ではない。", "わざと悪い方へも動く別の最適化で、ミニバッチ更新ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q21', '一回の更新で重みをどれだけ大きく動かすかを決める値で、大きすぎると答えを飛び越して発散し、小さすぎると学習が遅い。この値はどれか。', NULL, '["学習率", "バッチサイズ", "エポック数", "正則化係数"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "一回の更新で重みをどれだけ動かすか(歩幅)を決める値は？", "point": "「一回の更新で重みをどれだけ動かすか(歩幅)を決める値」なら、学習率。", "kid": "学習は坂を下るイメージ。その“一歩の大きさ”が学習率。大きすぎると谷を飛び越えて行ったり来たり(発散)、小さすぎるとなかなか下りきらない(遅い)。ちょうど良い歩幅が大事。", "eg": "山を下りるときの歩幅。大股すぎると転げ落ち、ちょこちょこ過ぎると日が暮れる。", "terms": [["学習率", "一回の更新で重みをどれだけ動かすかを決める値(歩幅)"], ["発散", "学習率が大きすぎて、答えに近づくどころか値が振れて壊れてしまうこと"]], "think": "「更新の歩幅・大きすぎると発散、小さすぎると遅い」なら学習率。何回データを回すか(エポック)や小分けの大きさ(バッチサイズ)とは別物。", "vs": "バッチサイズは一度の更新に使うデータ量、エポック数は全データを何周するか、正則化係数は過学習をどれだけ抑えるかの強さ。どれも一歩の歩幅を決める学習率ではない。", "usecase": "学習がうまくいかないとき最初に見直す設定。大きすぎ(発散)・小さすぎ(停滞)を避け、適切な歩幅に調整するのが学習成功の鍵。", "opt": ["正解。更新の歩幅を決めるのが学習率。", "一度の更新に使うデータ量のことで、歩幅そのものではない。", "全データを何周するかの回数で、一歩の大きさではない。", "過学習を抑える強さで、更新の歩幅ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q22', '学習を続けるうちに、訓練データの成績は上がり続けても検証データの成績が悪化し始めたら、そこで学習を打ち切る過学習対策はどれか。', NULL, '["早期終了（early stopping）", "ドロップアウト", "バッチ正規化", "データ拡張"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "検証データの成績が悪化し始めたら学習を打ち切る過学習対策は？", "point": "「検証データの成績が下がり始めた所で学習を止める」なら、早期終了。", "kid": "学習を続けすぎると、訓練データを丸暗記して初見に弱くなる(過学習)。そこで、別に取っておいた検証データの成績が下がり始めたら「ここが潮時」と学習を止める。", "eg": "筋トレのやりすぎで逆に調子を崩す前に切り上げるように、伸びが止まった瞬間にやめる、あの見極め。", "terms": [["早期終了（early stopping）", "検証データの成績が悪化し始めた時点で学習を打ち切り、過学習を防ぐ手法"], ["過学習", "訓練データに合わせすぎて、初見のデータで成績が落ちる状態"]], "think": "「検証成績が悪化し始めたら止める」なら早期終了。ノードを休ませる(ドロップアウト)や値をそろえる(バッチ正規化)とは、やり方が違う過学習対策。", "vs": "ドロップアウトはノードをランダムに休ませる、バッチ正規化は各層の値をそろえる、データ拡張はデータを水増しする。どれも「悪化し始めたら止める」早期終了ではない。", "usecase": "追加のコストなしで過学習を防げる手軽な方法。学習の回しすぎによる劣化を避けるため、広く併用される。", "opt": ["正解。検証成績が悪化し始めた所で学習を止めるのが早期終了。", "ノードをランダムに休ませる別の過学習対策で、学習を止めるものではない。", "各層の値をそろえる手法で、学習を打ち切るものではない。", "データを水増しする手法で、早期終了とは別。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q23', '分類問題で、モデルが出した確率が正解からどれだけずれているかを測り、学習の目印にする代表的な誤差（損失関数）はどれか。', NULL, '["交差エントロピー誤差", "平均二乗誤差", "マンハッタン距離", "コサイン類似度"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "分類で、出した確率が正解からどれだけずれているかを測る代表的な誤差は？", "point": "「分類で、確率が正解からどれだけずれたかを測る誤差」なら、交差エントロピー誤差。", "kid": "学習は「間違いの大きさ(誤差)」を小さくする方向に進む。分類では、モデルが出した確率が正解からどれだけ外れているかを測る“交差エントロピー”をその誤差に使うのが定番。", "eg": "テストの採点で、正解に自信満々で外したときほど大きく減点する、あの厳しめの採点方式。", "terms": [["交差エントロピー誤差", "分類で、予測確率が正解からどれだけずれているかを測る誤差。学習の目印にする"], ["平均二乗誤差", "予測した数値と正解の差を二乗して測る誤差。数値予測(回帰)で使う"]], "think": "「分類で確率のずれを測る誤差」なら交差エントロピー。数値そのものを当てる回帰では平均二乗誤差、と用途で使い分ける。", "vs": "平均二乗誤差は数値予測(回帰)用の誤差、マンハッタン距離やコサイン類似度は2つの近さを測る指標で、分類の学習誤差として標準で使うものではない。", "usecase": "画像分類や文章分類など、確率で答えるモデルの学習でほぼ標準の誤差。学習が「何を小さくしようとしているか」を決める重要な部品。", "opt": ["正解。分類で確率のずれを測る誤差が交差エントロピー。", "数値予測(回帰)で使う誤差で、分類の確率のずれには標準で使わない。", "2点の近さを測る距離で、分類の学習誤差ではない。", "2つの向きの近さを測る指標で、分類の学習誤差ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q24', '前の時点の出力を次の時点の入力に回して、順番のあるデータ（文章や時系列）を先頭から順に処理していく層はどれか。', NULL, '["回帰結合層（RNN）", "畳み込み層", "全結合層", "プーリング層"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "前の出力を次に回して、順番のあるデータを先頭から順に処理する層は？", "point": "「前の時点の出力を次に回して、順番のあるデータを順に処理する」なら、回帰結合層(RNN)。", "kid": "文章や時系列のように順番が大事なデータを、先頭から一つずつ読む。そのとき「さっきまでの内容」を次の処理に持ち越すので、前後のつながりを扱える。この仕組みが回帰結合層(RNN)。", "eg": "本を1ページずつ読みながら、前のページの記憶を持ち越して話を理解していく、あの読み方。", "terms": [["回帰結合層（RNN）", "前の時点の出力を次の入力に回し、順番のあるデータを順に処理する層"], ["LSTM", "RNNに記憶の門を足して、長い系列でも前の情報を保てるようにした改良版"]], "think": "「前の出力を次に持ち越して、順番のあるデータを順に処理」なら回帰結合層(RNN)。画像の局所特徴を拾う畳み込み層とは扱うデータも仕組みも違う。", "vs": "畳み込み層は画像の局所特徴を拾う、全結合層は全部の入力をまとめてつなぐ、プーリング層は特徴を粗くまとめて縮める。どれも順番を持ち越して系列を処理する層ではない。", "usecase": "文章・音声・株価など「順番と前後関係」が意味を持つデータの土台。長い文脈が要る場面ではLSTMやTransformerに発展した。", "opt": ["正解。前の出力を次に回して系列を順に処理するのが回帰結合層(RNN)。", "画像の局所特徴を拾う層で、系列を順に処理するものではない。", "全ての入力をまとめてつなぐ層で、前後を持ち越す仕組みではない。", "特徴を粗くまとめて縮める層で、系列処理そのものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q25', '層をいくつか飛び越えて入力をそのまま先の層へ足し込む近道を作り、非常に深いネットワークでも学習できるようにした仕組みはどれか。', NULL, '["残差接続（スキップ結合）", "ドロップアウト", "プーリング", "データ拡張"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "層を飛び越えて入力を先へ足し込む近道を作り、深いネットワークを学習可能にした仕組みは？", "point": "「層を飛び越えて入力を先へ足し込む“近道”で、深くても学習できる」なら、残差接続(スキップ結合)。", "kid": "層をたくさん重ねると、学習の「直してね」の合図が奥まで届かず学べなくなる。そこで、途中をショートカットして入力をそのまま先へ足す“近道”を作ると、合図が消えずに届き、とても深いネットワークでも学習できる。", "eg": "長い階段の横にエレベーター(近道)を付けるように、遠い層へ信号がそのまま届く抜け道を用意する。", "terms": [["残差接続（スキップ結合）", "層を飛び越えて入力を先の層へ足す近道。深いネットワークの学習を可能にした"], ["ResNet", "残差接続を使い、100層を超える深さでも学習できるようにした画像認識モデル"]], "think": "「層を飛び越える近道で深くても学習できる」なら残差接続。勾配消失(信号が奥まで届かない)を、経路を足すことで和らげる工夫。", "vs": "ドロップアウトはノードを休ませる過学習対策、プーリングは特徴を縮める操作、データ拡張はデータの水増し。どれも層を飛び越える近道ではない。", "usecase": "超深層のネットワークを実現した鍵で、画像認識のResNetが代表。今の多くの大規模モデルにも取り入れられている。", "opt": ["正解。層を飛び越える近道で深くても学習できるのが残差接続。", "ノードを休ませる過学習対策で、層を飛び越える近道ではない。", "特徴を縮める操作で、近道を作る仕組みではない。", "データを水増しする手法で、残差接続とは別。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
COMMIT;
BEGIN;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q26', '手元の画像を回転・反転・拡大などで少しずつ変形させ、学習用データを水増しして過学習を抑える手法はどれか。', NULL, '["データ拡張（Data Augmentation）", "転移学習", "アノテーション", "次元削減"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "画像を回転・反転などで変形して学習データを水増しする手法は？", "point": "「手元のデータを変形して水増しし、過学習を抑える」なら、データ拡張。", "kid": "データが少ないと丸暗記(過学習)しやすい。そこで、同じ画像を少し回したり反転したりして“別の一枚”を作り、水増しする。見え方の違いに強いモデルになる。", "eg": "一枚の写真を、傾けたり左右反転したりして「いろんな角度から見た別の写真」に増やす、あの発想。", "terms": [["データ拡張（Data Augmentation）", "既存データを回転・反転などで変形し、学習データを水増しして過学習を抑える手法"], ["過学習", "訓練データに合わせすぎて、初見のデータで成績が落ちる状態"]], "think": "「既存データを変形して水増し」ならデータ拡張。学習済みモデルを流用する転移学習や、正解を付けるアノテーションとは別のアプローチ。", "vs": "転移学習は学習済みの知識を別タスクに使い回す考え方、アノテーションは正解ラベルを付ける作業、次元削減は項目の数を減らす手法。どれもデータを変形して水増しする手法ではない。", "usecase": "画像認識で少ないデータを補うほぼ定番の手法。回転や色変えに強い、頑丈なモデルを作れる。", "opt": ["正解。既存データを変形して水増しし過学習を抑えるのがデータ拡張。", "学習済みの知識を別タスクに使い回す考え方で、水増しそのものではない。", "正解ラベルを付ける作業で、データの変形ではない。", "項目の数を減らす手法で、データの水増しではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q27', '前の層の全てのノードと、次の層の全てのノードを一つ残らずつなぎ、入力全体をまとめて処理する層はどれか。', NULL, '["全結合層", "畳み込み層", "プーリング層", "回帰結合層"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "前の層と次の層の全ノードを残らずつなぎ、入力全体をまとめて処理する層は？", "point": "「前後の層の全ノードを一つ残らずつなぐ」なら、全結合層。", "kid": "前の層の出力を全部、次の層の全部のノードにつなぐ層。入力のどこも見落とさずまとめて扱えるが、つなぎが多い分だけ計算や覚える数(重み)も多くなる。", "eg": "全員が全員と握手する懇親会のように、片側の全員をもう片側の全員につなぐ、あの密なつなぎ方。", "terms": [["全結合層", "前の層の全ノードを次の層の全ノードにつなぐ層。入力全体をまとめて扱う"], ["畳み込み層", "小さなフィルタを使い回して局所の特徴だけを拾う、つなぎを絞った層"]], "think": "「全ノードを残らずつなぐ」なら全結合層。フィルタを使い回して一部だけつなぐ畳み込み層とは、つなぎ方が対照的。", "vs": "畳み込み層はフィルタで局所だけを拾う層、プーリング層は特徴を縮める操作、回帰結合層は系列を順に処理する層。どれも全ノードを残らずつなぐ全結合層ではない。", "usecase": "分類の出口など「集めた特徴を最終的にまとめて判断する」段で使う。画像では畳み込みで特徴を絞った後、最後に全結合層で判定することが多い。", "opt": ["正解。前後の層の全ノードを残らずつなぐのが全結合層。", "フィルタで局所だけを拾う層で、全ノードをつなぐわけではない。", "特徴を縮める操作で、全ノードをつなぐ層ではない。", "系列を順に処理する層で、全結合とは仕組みが違う。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q28', '翻訳などで、出力する単語を決めるたびに、入力文のどの単語に注目すべきかを重み付けして参照する仕組みはどれか。', NULL, '["注意機構（Attention）", "プーリング", "ドロップアウト", "バッチ正規化"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "出力のたびに、入力のどの単語に注目すべきかを重み付けして参照する仕組みは？", "point": "「出力するたび、入力のどこに注目すべきかを重み付けして選ぶ」なら、注意機構(Attention)。", "kid": "翻訳で「次の単語」を出すたびに、入力文のどの単語が今いちばん関係あるかに“注目”して、そこを重点的に見る。関係の薄い所は軽く見る。この注目の重み付けがAttention。", "eg": "長文を訳すとき、今書いている部分に関係する原文の箇所を指でなぞりながら訳す、あの目の動き。", "terms": [["注意機構（Attention）", "出力のたびに入力のどこに注目すべきかを重み付けし、関係の深い部分を重点的に見る仕組み"], ["自己注意（Self-Attention）", "同じ文の中で単語どうしの関係を測るAttention。Transformerの中核"]], "think": "「出力のたびに入力のどこを見るか重み付け」ならAttention。同じ文の中の単語どうしを見るのが自己注意、入力と出力の間で見るのがこのソース・ターゲット型。", "vs": "プーリングは特徴を縮める操作、ドロップアウトはノードを休ませる過学習対策、バッチ正規化は各層の値をそろえる手法。どれも注目先を重み付けするAttentionではない。", "usecase": "機械翻訳の精度を大きく上げ、長い文でも関係する箇所を捉えられるようにした。Transformerや今のLLMの土台になった考え方。", "opt": ["正解。出力のたび入力のどこに注目するか重み付けするのがAttention。", "特徴を縮める操作で、注目先を重み付けする仕組みではない。", "ノードを休ませる過学習対策で、Attentionではない。", "各層の値をそろえる手法で、注目の重み付けではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q29', 'LSTMと同じく長い系列の情報を保てるが、内部の門（ゲート）を減らして構造を簡単にし、計算を軽くした手法はどれか。', NULL, '["GRU", "CNN", "SVM", "PCA"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "LSTMを簡単にして門を減らし、計算を軽くした系列処理の手法は？", "point": "「LSTMの門を減らして構造を簡単にし、計算を軽くした」なら、GRU。", "kid": "LSTMは「覚える・忘れる・思い出す」の門で長い情報を保つが、部品が多め。GRUは門を減らして仕組みを簡単にし、似た効果を保ちつつ計算を軽くした改良版。", "eg": "多機能リモコンのボタンを減らして、必要な機能はそのままに使いやすくした簡易版、あのイメージ。", "terms": [["GRU", "LSTMより門(ゲート)を減らして簡単にした、系列を扱う手法。計算が軽い"], ["LSTM", "門と記憶で長い系列の情報を保つ、RNNの改良版"]], "think": "「LSTMを簡単に・門が少なく・軽い」ならGRU。長い系列を扱う狙いはLSTMと同じで、構造を絞った点が違い。", "vs": "CNNは画像の局所特徴を拾う畳み込みのネットワーク、SVMは分ける線を学ぶ分類、PCAは次元削減。どれも系列を扱うLSTMの簡易版ではない。", "usecase": "LSTMより軽いので、計算資源が限られる場面や、まず手早く試したいときに向く。系列データの選択肢の一つ。", "opt": ["正解。LSTMの門を減らして簡単・軽くしたのがGRU。", "画像の局所特徴を拾うネットワークで、系列の簡易版ではない。", "分ける線を学ぶ分類で、系列処理の手法ではない。", "次元削減の手法で、LSTMの簡易版ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q30', '一枚の画像に対して「これは猫」「これは犬」のように、画像全体を表す一つのラベルを答えるタスクはどれか。', NULL, '["画像分類", "物体検出", "セマンティックセグメンテーション", "姿勢推定"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "画像全体に一つのラベルを答えるタスクは？", "point": "「画像全体に一つのラベルを答える(場所は出さない)」なら、画像分類。", "kid": "写真を一枚見せて「これは何?」に一言で答えるタスク。「猫」とだけ答え、どこにいるか(場所)は出さない。CNNの一番基本的な使い道。", "eg": "写真を見て「これは猫の写真」とアルバムに一枚だけタグを付ける、あの作業。", "terms": [["画像分類", "画像全体が何かを一つのラベルで答えるタスク。場所は出さない"], ["物体検出", "何が・どこにあるかを枠で囲んで同時に答える、一段細かいタスク"]], "think": "「画像全体に一つのラベル・場所は出さない」なら画像分類。枠で位置も出すのは物体検出、画素ごとに塗り分けるのはセグメンテーション。", "vs": "物体検出は種類と位置(枠)を同時に出す、セマンティックセグメンテーションは画素ごとにラベルを塗り分ける、姿勢推定は関節の位置を当てる。どれも画像全体への一ラベルではない。", "usecase": "不良品かどうかの判定、写真の自動タグ付けなど、「一枚が何か」を答えれば済む場面で使う。CNNの応用の入り口。", "opt": ["正解。画像全体に一つのラベルを答えるのが画像分類。", "種類と位置(枠)を同時に出すタスクで、一ラベルだけではない。", "画素ごとに塗り分けるタスクで、画像全体への一ラベルではない。", "関節の位置を当てるタスクで、画像全体の分類ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q31', '人が話した音声の波形を受け取り、その内容を文字（テキスト）に書き起こすタスクはどれか。', NULL, '["音声認識", "音声合成", "画像認識", "異常検知"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "話した音声を文字に書き起こすタスクは？", "point": "「音声を受け取って文字に書き起こす」なら、音声認識。", "kid": "マイクに入った声(音の波)を聞き取って、「おはよう」のような文字に直すタスク。声→文字の向き。逆に文字→声はまた別のタスク。", "eg": "会議の録音を聞きながら、文字起こしをしてくれる書記のような役割。", "terms": [["音声認識", "音声(音の波)を受け取り、内容を文字に書き起こすタスク。声→文字"], ["音声合成", "文字から人の声を作り出すタスク。音声認識と向きが逆"]], "think": "「音声を文字にする(声→文字)」なら音声認識。文字から声を作る音声合成とは向きが逆、と押さえる。", "vs": "音声合成は文字から声を作る(向きが逆)、画像認識は画像を扱う、異常検知はいつもと違うデータを見つける。どれも音声を文字に起こすタスクではない。", "usecase": "スマートスピーカーへの話しかけ、会議の自動文字起こし、音声入力などで使う身近な技術。", "opt": ["正解。音声を受け取って文字に書き起こすのが音声認識。", "文字から声を作るタスクで、向きが逆。", "画像を扱うタスクで、音声を文字にするものではない。", "いつもと違うデータを見つけるタスクで、音声の書き起こしではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q32', '試行錯誤で良い行動を学ぶ強化学習に、ディープラーニングを組み合わせ、囲碁AIのAlphaGoやゲーム攻略で成果を上げた手法はどれか。', NULL, '["深層強化学習", "教師あり学習", "主成分分析", "データ拡張"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "強化学習にディープラーニングを組み合わせた手法は？", "point": "「試行錯誤で行動を学ぶ強化学習＋ディープラーニング」なら、深層強化学習。", "kid": "ごほうび(報酬)を頼りに試行錯誤で行動を学ぶのが強化学習。そこに、状況を見て判断する目としてディープラーニングを組み合わせたのが深層強化学習。囲碁やゲームで人間超えを果たした。", "eg": "「経験から学ぶ勘(強化学習)」に「複雑な盤面を見抜く目(ディープラーニング)」を足した、あの組み合わせ。", "terms": [["深層強化学習", "強化学習(報酬で試行錯誤)とディープラーニングを組み合わせた手法"], ["強化学習", "行動の結果もらえる報酬を最大にするよう、試行錯誤で行動を学ぶ方法"]], "think": "「強化学習＋ディープラーニング」なら深層強化学習。報酬で学ぶ点は強化学習、複雑な状況を捉える目がディープラーニング、と分けて捉える。", "vs": "教師あり学習は入力と正解のセットで学ぶ、主成分分析は次元削減、データ拡張はデータの水増し。どれも強化学習にディープラーニングを組み合わせた手法ではない。", "usecase": "囲碁のAlphaGo、テレビゲームの攻略、ロボットの制御など、複雑な状況で一連の行動を学ぶ場面で成果を上げた。", "opt": ["正解。強化学習とディープラーニングを組み合わせたのが深層強化学習。", "入力と正解のセットで学ぶ方法で、報酬による試行錯誤ではない。", "次元削減の手法で、強化学習との組み合わせではない。", "データの水増しで、深層強化学習とは別。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q33', '大きくて重い高性能モデルの判断を、小さなモデルにまねさせて学習させ、性能を保ちつつ軽くする手法はどれか。', NULL, '["蒸留（知識蒸留）", "データ拡張", "アノテーション", "交差検証"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "大きなモデルの判断を小さなモデルにまねさせて軽くする手法は？", "point": "「大きなモデルの判断を小さなモデルにまねさせて軽くする」なら、蒸留(知識蒸留)。", "kid": "高性能だけど重いモデルは、スマホなどでは動かしにくい。そこで、その大きなモデルの答え方を“先生”として小さなモデルにまねさせ、性能を保ったまま軽くする。これが蒸留。", "eg": "名人の技を弟子が見て盗み、名人ほど大掛かりでなくても同じ味を出せるようにする、あの継承。", "terms": [["蒸留（知識蒸留）", "大きなモデルの出力を教師にして小さなモデルを学習させ、性能を保ちつつ軽くする手法"], ["モデルの軽量化", "蒸留・量子化・枝刈りなどで、モデルを小さく速くする取り組みの総称"]], "think": "「大モデルの判断を小モデルにまねさせて軽くする」なら蒸留。データを水増しするデータ拡張や、正解を付けるアノテーションとは目的が違う。", "vs": "データ拡張はデータを水増しする手法、アノテーションは正解ラベルを付ける作業、交差検証は評価の方法。どれもモデルを小さく軽くする蒸留ではない。", "usecase": "スマホや組み込み機器など、計算資源が限られる場所で高性能モデルを動かしたいときに使う。速度と性能の両立の一手。", "opt": ["正解。大モデルの判断を小モデルにまねさせて軽くするのが蒸留。", "データを水増しする手法で、モデルを軽くするものではない。", "正解ラベルを付ける作業で、軽量化ではない。", "評価の方法で、モデルを軽くする手法ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q34', '画像と、それを説明する文章のように、種類の違う情報を一緒に扱えるようにしたAIを指す語はどれか。', NULL, '["マルチモーダル", "ユニモーダル", "アンサンブル", "オートエンコーダ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "画像と文章のように種類の違う情報を一緒に扱うAIを指す語は？", "point": "「画像・文章・音声など複数種類の情報を一緒に扱う」なら、マルチモーダル。", "kid": "これまでのAIは画像なら画像だけ、と一種類が普通だった。画像と文章を同時に結びつけて扱えるように、複数の種類(モード)の情報をまたいで扱うのがマルチモーダル。", "eg": "目(画像)と耳と言葉(文章)を同時に使って状況を理解する、人間のような情報の受け取り方。", "terms": [["マルチモーダル", "画像・文章・音声など、種類の違う情報を組み合わせて扱うこと"], ["CLIP", "画像と説明文を結びつけて学習した代表的なマルチモーダルモデル"]], "think": "「複数の種類(画像＋文章など)を一緒に扱う」ならマルチモーダル。一種類だけ扱うのがユニモーダル、と対で押さえる。", "vs": "ユニモーダルは一種類の情報だけを扱うこと、アンサンブルは複数モデルを組み合わせる手法、オートエンコーダは圧縮して復元を学ぶネットワーク。どれも複数種類の情報をまたいで扱うことそのものではない。", "usecase": "「写真に合う説明文を作る」「文章から画像を生成する」など、種類をまたぐAIの土台。今の生成AIの多くがこの方向に進んでいる。", "opt": ["正解。種類の違う情報を組み合わせて扱うのがマルチモーダル。", "一種類の情報だけを扱うことで、複数種類をまたぐ話ではない。", "複数モデルを組み合わせる手法で、情報の種類の話ではない。", "圧縮して復元を学ぶネットワークで、複数種類を扱うことそのものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q35', '大量のデータであらかじめ広く学習しておき、その後さまざまな用途に少しの調整で使い回せる、大規模で汎用的なモデルを指す語はどれか。', NULL, '["基盤モデル（ファウンデーションモデル）", "エキスパートシステム", "決定木", "混同行列"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "大量データで広く事前学習し、さまざまな用途に使い回せる大規模で汎用的なモデルを指す語は？", "point": "「大量データで広く事前学習し、少しの調整で多用途に使い回せる大規模モデル」なら、基盤モデル。", "kid": "まず大量のデータで幅広く“基礎学力”をつけておく。あとは翻訳でも要約でも、少しの追加調整でいろんな仕事に使い回せる。この土台となる大規模モデルが基盤モデル。", "eg": "何にでも応用できる基礎学力を先につけておき、あとは各仕事に合わせて少し慣らすだけで働ける人材、あのイメージ。", "terms": [["基盤モデル（ファウンデーションモデル）", "大量データで広く事前学習し、微調整で多用途に使い回せる大規模モデル。GPTなどが代表"], ["ファインチューニング", "基盤モデルを土台に、特定タスク向けに少し追加学習して調整すること"]], "think": "「大量データで事前学習・多用途に使い回す土台」なら基盤モデル。個別に作り込む古いエキスパートシステムとは発想が逆。", "vs": "エキスパートシステムは人がルールを書く古典的な仕組み、決定木は条件分岐で予測する手法、混同行列は判定結果の集計表。どれも大規模で汎用的な基盤モデルではない。", "usecase": "GPTなどの大規模言語モデルが代表。ゼロから作らず基盤モデルを土台にすれば、少ないデータ・短い時間で多くの応用を作れる。", "opt": ["正解。広く事前学習して多用途に使い回せる大規模モデルが基盤モデル。", "人がルールを書く古典的な仕組みで、汎用の土台モデルではない。", "条件分岐で予測する手法で、基盤モデルではない。", "判定結果の集計表で、モデルの種類ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q36', '大規模言語モデルに、例を一つも見せずに指示文だけで新しいタスクをこなさせるやり方を指す語はどれか。', NULL, '["ゼロショット（zero-shot）", "アノテーション", "データ拡張", "ホールドアウト"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "例を見せず指示文だけで新しいタスクをこなさせるやり方は？", "point": "「例を一つも見せず、指示だけでタスクをこなさせる」なら、ゼロショット。", "kid": "ふつうは「こういう時はこう」という例をいくつか見せて覚えさせる。ゼロショットは、例をひとつも見せずに「〜して」と指示するだけでこなさせるやり方。例を数個見せる版はフューショット。", "eg": "お手本なしで「いい感じに要約して」と頼むだけで、それらしくやってくれる、あの器用さ。", "terms": [["ゼロショット（zero-shot）", "例を見せず、指示文だけで新しいタスクをこなさせるやり方"], ["フューショット（few-shot）", "例を数個だけ見せてタスクをこなさせるやり方"]], "think": "「例ゼロ・指示だけ」ならゼロショット。「例を数個見せる」ならフューショット、と例の数で見分ける。", "vs": "アノテーションは正解ラベルを付ける作業、データ拡張はデータの水増し、ホールドアウトは評価の分け方。どれも例なしで指示だけこなすやり方ではない。", "usecase": "大規模言語モデルに、追加学習なしでプロンプト(指示文)だけで多様な仕事をさせる使い方。手早く試せるので実務で多用される。", "opt": ["正解。例を見せず指示だけでこなさせるのがゼロショット。", "正解ラベルを付ける作業で、指示だけこなすやり方ではない。", "データの水増しで、ゼロショットとは別。", "評価の分け方で、タスクのこなし方ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q37', 'データ分析プロジェクトを「業務理解→データ理解→データ準備→モデル作成→評価→展開」という段階で進める、代表的な進め方の型はどれか。', NULL, '["CRISP-DM", "MLOps", "PoC", "スクラム"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "データ分析プロジェクトを決まった段階で進める、代表的な型は？", "point": "「データ分析を業務理解から展開まで、決まった段階で進める型」なら、CRISP-DM。", "kid": "データ分析を行き当たりばったりでなく、「まず業務を理解、データを見る、準備、モデル作成、評価、展開」と決まった順番で進める、標準的な段取りの型。", "eg": "料理のレシピのように「下ごしらえ、調理、味見、提供」と手順を決めておき、迷わず進められるようにしたもの。", "terms": [["CRISP-DM", "データ分析プロジェクトを6段階で進める代表的な標準プロセス"], ["PoC", "本開発の前に小さく試して実現性を確かめる工程。CRISP-DMより手前の位置づけ"]], "think": "「データ分析を決まった段階で進める型」ならCRISP-DM。運用を継続的に回すMLOpsとは、指す範囲が違う。", "vs": "MLOpsは運用しながら継続的に回す実践、PoCは本開発前の小さな検証、スクラムはソフト開発の進め方(アジャイル)。どれもデータ分析専用の6段階プロセスそのものではない。", "usecase": "データ分析プロジェクトの計画・見積もりの共通言語として使う。どの段階にいるか・次に何をするかを関係者で揃えられる。", "opt": ["正解。データ分析を6段階で進める代表的な型がCRISP-DM。", "運用を継続的に回す実践で、分析の進め方の型そのものではない。", "本開発前の小さな検証で、全体の進め方の型ではない。", "ソフト開発の進め方で、データ分析専用の型ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='7. AIの社会実装に向けて'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q38', '収集したデータに含まれる、欠けている値・明らかな誤り・重複などを整えて、分析や学習に使える状態にする作業はどれか。', NULL, '["データクレンジング（データの前処理）", "デプロイ", "ハイパーパラメータ探索", "バックプロパゲーション"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "欠損・誤り・重複を整えて、データを使える状態にする作業は？", "point": "「欠けた値・誤り・重複を整えてデータを使える状態にする」なら、データクレンジング。", "kid": "集めたデータには、空欄や打ち間違い、同じ行の重複などが混じっている。そのままだと学習が歪むので、きれいに整える下ごしらえ。これがデータクレンジング。", "eg": "料理の前に野菜を洗って、傷んだ所や汚れを取り除く下ごしらえ、あの作業。", "terms": [["データクレンジング", "欠損値・誤り・重複などを整え、データを分析や学習に使える状態にする作業"], ["欠損値", "本来あるべき値が抜けている箇所。埋めるか除くかの判断が要る"]], "think": "「欠損や誤りを整える下ごしらえ」ならデータクレンジング。作ったモデルを動かすデプロイや、学習そのものとは別の工程。", "vs": "デプロイは作ったモデルを本番で動かすこと、ハイパーパラメータ探索は設定値の調整、バックプロパゲーションは学習の計算手法。どれもデータを整える前処理ではない。", "usecase": "「データの質が悪いと結果も悪い」を防ぐ、分析・学習の土台となる工程。実務では作業時間の大半を占めることも多い。", "opt": ["正解。欠損や誤り・重複を整えてデータを使える状態にするのがデータクレンジング。", "作ったモデルを本番で動かすことで、データを整える作業ではない。", "設定値の調整で、データの前処理ではない。", "学習の計算手法で、データを整えることではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='7. AIの社会実装に向けて'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q39', '大量の画像へのラベル付けなどの作業を、インターネットを通じて不特定多数の人に少しずつ分担してもらう仕組みはどれか。', NULL, '["クラウドソーシング", "クラウドコンピューティング", "エッジコンピューティング", "フェデレーテッドラーニング"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "大量の作業を、ネット経由で不特定多数に分担してもらう仕組みは？", "point": "「作業を、ネットで不特定多数に少しずつ分担してもらう」なら、クラウドソーシング。", "kid": "何万枚もの画像に「これは猫」と印を付ける作業は、一人では大変。そこで、ネットを通じて大勢の人に少しずつ分担してもらう。この人手の集め方がクラウドソーシング。", "eg": "大掃除を一人でやらず、大勢に「一区画ずつお願い」と呼びかけて手分けする、あの集め方。", "terms": [["クラウドソーシング", "作業を、ネットを通じて不特定多数の人に少しずつ分担してもらう仕組み"], ["アノテーション", "データに正解ラベルを付ける作業。クラウドソーシングで集められることが多い"]], "think": "「作業を大勢の人に分担」ならクラウドソーシング。似た名前のクラウドコンピューティング(計算をネット越しに借りる)と混同しない。", "vs": "クラウドコンピューティングは計算資源をネット越しに借りること、エッジコンピューティングは手元の端末側で処理すること、フェデレーテッドラーニングはデータを持ち寄らず各端末で学習する方法。どれも人手を分担する仕組みではない。", "usecase": "教師あり学習に欠かせない大量のラベル付け(アノテーション)を、現実的なコストと時間で集めるのに使う。", "opt": ["正解。作業をネットで不特定多数に分担してもらうのがクラウドソーシング。", "計算資源をネット越しに借りることで、人手の分担ではない。", "手元の端末側で処理することで、作業の分担とは別。", "各端末で学習する方法で、人手を集める仕組みではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='7. AIの社会実装に向けて'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q40', '迷惑メール判定で「大事な正常メールを誤って迷惑メール扱いする」ことを特に避けたい。このとき重視すべき指標はどれか。', NULL, '["適合率（Precision）", "再現率（Recall）", "学習率", "エポック数"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "誤検知(正常を誤って弾く)を特に避けたい場面で重視する指標は？", "point": "「誤検知(空振りで正常を弾く)を減らしたい」なら、適合率を高める。", "kid": "迷惑メール判定で怖いのは、大事な正常メールを誤って迷惑扱いすること(誤検知)。「迷惑と判定したもののうち、本当に迷惑だった割合」＝適合率を高めれば、この誤検知を減らせる。", "eg": "詐欺の通報で、無実の人を犯人扱いしないことを最優先する、あの慎重さ。誤って疑う“空振り”を減らす。", "terms": [["適合率（Precision）", "陽性と判定したうち、本当に陽性だった割合。誤検知(空振り)の少なさを表す"], ["再現率（Recall）", "本当に陽性のうち、正しく拾えた割合。見落としの少なさを表す"]], "think": "「誤検知(空振り)を減らしたい」なら適合率、「見落としを減らしたい」なら再現率。何を恐れる場面かで選ぶ。ここは正常メールを弾きたくない＝適合率。", "vs": "再現率は見落としを減らす指標(この場面の主役ではない)、学習率とエポック数は学習の設定値で、そもそも成績を測る指標ではない。", "usecase": "「間違って弾くと困る」場面(正常メール、健全な利用者の誤ブロックなど)で重視する。再現率とどちらを優先するか、場面で決める。", "opt": ["正解。誤検知(空振り)の少なさを表す適合率を高める。", "見落としを減らす指標で、誤検知を避けたい場面の主役ではない。", "学習の歩幅を決める設定で、成績を測る指標ではない。", "全データを何周するかの回数で、評価指標ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='8. AIに必要な数理・統計知識'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q41', '分類結果を「正解が陽性/陰性」×「予測が陽性/陰性」の4マスに集計し、当たり外れの内訳を一目で見られるようにした表はどれか。', NULL, '["混同行列", "相関行列", "ROC曲線", "ヒストグラム"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "分類の当たり外れの内訳を4マスに集計した表は？", "point": "「正解×予測の4マスで当たり外れの内訳を集計した表」なら、混同行列。", "kid": "分類の成績を「正解が陽性か陰性か」×「予測が陽性か陰性か」の4マスに数えて並べた表。どこで当たり、どこで外したか(見落としか誤検知か)が一目で分かる。適合率や再現率もここから計算する。", "eg": "テストの答え合わせを「合ってた/間違えた」×「自信あり/なし」の4マスに整理して、弱点を見える化する、あの表。", "terms": [["混同行列", "正解と予測を陽性/陰性で掛け合わせた4マスの表。当たり外れの内訳を示す"], ["適合率・再現率", "混同行列の4マスの数から計算する評価指標"]], "think": "「4マスで当たり外れの内訳を集計」なら混同行列。項目どうしの相関を並べる相関行列とは別物、と名前で混同しない。", "vs": "相関行列は項目どうしの相関を並べた表、ROC曲線は判定の線を動かしたときの成績の曲線、ヒストグラムはデータの分布を棒で見る図。どれも分類の4マス集計ではない。", "usecase": "分類モデルが「どのタイプの間違いをしているか(見落とし多め/誤検知多め)」を把握し、適合率・再現率を計算する土台。", "opt": ["正解。正解×予測の4マスで内訳を集計するのが混同行列。", "項目どうしの相関を並べた表で、分類の当たり外れの集計ではない。", "判定の線を動かしたときの成績の曲線で、4マスの表ではない。", "データの分布を棒で見る図で、分類結果の集計ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='8. AIに必要な数理・統計知識'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q42', '「アイスの売上が増えると水難事故も増える」というデータの関係について、最も適切な解釈はどれか。', NULL, '["同時に増えても、一方が他方の原因とは限らない", "アイスの売上が事故を直接引き起こしている", "水難事故が増えたことが売上を押し上げている", "二つの数字の間には全く関係が見られない"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "2つが一緒に増減しても、一方が他方の原因とは限らない。この考え方は？", "point": "「一緒に動いても、一方が他方の原因とは限らない」＝相関は因果ではない。", "kid": "アイスの売上と水難事故が同時に増えるのは、どちらも「暑さ」という共通の原因のせい。売上が事故を起こすわけではない。一緒に動くこと(相関)と、原因-結果(因果)は別、という話。", "eg": "背が高い人ほど足も大きいが、背が伸びたから足が大きいわけではなく、どちらも「成長」という共通の原因による、あの関係。", "terms": [["相関", "2つの量が一緒に増減する関係。原因-結果とは限らない"], ["因果", "一方が他方を引き起こす原因-結果の関係"]], "think": "「一緒に動く」だけでは因果とは言えない。隠れた共通の原因(この例では暑さ)がないか疑う、が判断のポイント。", "vs": "「一方が他方の直接の原因」と決めつける解釈は共通の原因を見落としている。「全く関係がない」も誤りで、相関自体はある。相関の有無と因果の有無は別々に考える。", "usecase": "データ分析で最も陥りやすい誤り。「相関があるから効果がある」と早合点しないための、意思決定の基本の心得。", "opt": ["正解。一緒に増減しても一方が他方の原因とは限らない。", "共通の原因(暑さ)を見落とした決めつけで、直接の原因とは言えない。", "因果の向きを逆にした決めつけで、これも直接の原因ではない。", "相関自体はあるので、全く関係がないとするのは誤り。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='8. AIに必要な数理・統計知識'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q43', '少数の極端に大きい値（外れ値）が混じったデータで、その影響を受けにくく、全体の「真ん中」をよく表すのはどれか。', NULL, '["中央値", "平均値", "合計値", "最大値"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "極端な外れ値の影響を受けにくく、真ん中をよく表すのは？", "point": "「極端な外れ値の影響を受けにくい“真ん中”」なら、中央値。", "kid": "平均は、一人だけ極端に大きい値があると、そちらへ引っ張られてしまう。中央値は「小さい順に並べた真ん中」なので、そういう極端な値に振り回されにくい。", "eg": "10人の年収に一人だけ億万長者が混じると、平均は跳ね上がるが、真ん中(中央値)はほぼ変わらない、あの差。", "terms": [["中央値", "データを小さい順に並べた真ん中の値。外れ値の影響を受けにくい"], ["平均値", "全部を足して個数で割った値。極端な外れ値に引っ張られやすい"]], "think": "「外れ値に強い真ん中」なら中央値。全部を足して割る平均値は、極端な値があると代表値としてずれる。データに外れ値がないか見て使い分ける。", "vs": "平均値は外れ値に引っ張られやすい、合計値はただの総和で真ん中を表さない、最大値は一番大きい値で真ん中ではない。どれも外れ値に強い真ん中ではない。", "usecase": "年収・地価など一部に極端な値があるデータで、実感に近い“真ん中”を示すのに使う。平均だけ見て誤解しないための基本。", "opt": ["正解。小さい順の真ん中で、外れ値の影響を受けにくいのが中央値。", "極端な値に引っ張られやすく、外れ値があると代表値がずれる。", "ただの総和で、真ん中を表す指標ではない。", "一番大きい値で、真ん中ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='8. AIに必要な数理・統計知識'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q44', '新しい技術的な発明について、出願して認められると、一定期間その発明を独占的に使える権利はどれか。', NULL, '["特許権", "営業秘密", "著作権", "商標権"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "発明を出願・登録して、一定期間独占的に使える権利は？", "point": "「発明を出願・公開して、一定期間の独占権をもらう」なら、特許権。", "kid": "新しい発明を国に出願して認められると、一定期間(原則20年)、その発明を独り占めで使える権利がもらえる。代わりに発明の中身は公開される。「公開して守ってもらう」制度。", "eg": "新しい料理法を役所に登録して「一定期間はうちだけ」と認めてもらう代わりに、レシピは公開する、あの取り引き。", "terms": [["特許権", "発明を出願・公開する代わりに、一定期間その発明を独占できる権利"], ["営業秘密", "公開せず秘密のまま守る枠組み。特許とは逆の発想"]], "think": "「出願・公開して独占権をもらう」なら特許権。秘密のまま守る営業秘密とは正反対、と押さえる。", "vs": "営業秘密は公開せず秘密のまま守る枠組み(逆の発想)、著作権は表現を守る権利、商標権は商品やサービスの目印を守る権利。どれも発明の独占権である特許権ではない。", "usecase": "AIの新しいアルゴリズムや技術を、公開してでも独占して守りたいときの選択肢。秘密のまま守る営業秘密と、どちらで守るかを選ぶ。", "opt": ["正解。発明を出願・公開して一定期間独占できるのが特許権。", "公開せず秘密のまま守る枠組みで、出願・公開する特許とは逆。", "表現を守る権利で、発明の独占権ではない。", "商品やサービスの目印を守る権利で、特許権ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='9. AIに関する法律と契約'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q45', '巨大なIT企業が持つ大量のデータや市場での強い立場を使って、公正な競争を妨げる行為を規制する法律はどれか。', NULL, '["独占禁止法", "著作権法", "不正競争防止法", "特許法"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "強い立場を使って公正な競争を妨げる行為を規制する法律は？", "point": "「公正な競争を妨げる行為(市場の独占など)を規制する」なら、独占禁止法。", "kid": "一社が強すぎる立場やデータを使って、他社が入れないようにしたり不当に取引を縛ったりすると、競争が働かず利用者が損をする。それを防ぐのが独占禁止法。", "eg": "大人が一人で遊具を独り占めして他の子を入れないのを、先生が「みんなで公平に」と止める、あのルール。", "terms": [["独占禁止法", "市場の独占や不当な取引制限など、公正な競争を妨げる行為を規制する法律"], ["不正競争防止法", "営業秘密の侵害やまね(模倣)など、不正な競争行為を規制する別の法律"]], "think": "「公正な競争を妨げる行為(独占・不当な取引制限)の規制」なら独占禁止法。データやプラットフォームの独占が問題になる文脈で問われる。", "vs": "著作権法は表現を守る法律、不正競争防止法は営業秘密の侵害などを規制する法律、特許法は発明を守る法律。どれも公正な競争そのものを守る独占禁止法ではない。", "usecase": "大量データを握る巨大IT企業(プラットフォーマー)の振る舞いを問題にするときの根拠。AIとデータ独占をめぐる議論で登場する。", "opt": ["正解。公正な競争を妨げる行為を規制するのが独占禁止法。", "表現を守る法律で、競争を守るものではない。", "営業秘密の侵害などを規制する法律で、市場の独占規制そのものではない。", "発明を守る法律で、公正な競争を守るものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='9. AIに関する法律と契約'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q46', '企業がAIサービスを外部に提供する契約で、出力の精度について実務上とられる考え方として最も適切なものはどれか。', NULL, '["精度は100%保証せず、責任の範囲を契約で定めておくのが一般的", "提供者が常に100%の精度を保証する義務を負うとされる", "精度に関する取り決めは法律で一律に決められている", "利用者は出力の結果に一切責任を負わなくてよい"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "AIサービス提供契約で、出力の精度についての実務上の考え方は？", "point": "「AIは確率的だから精度は100%保証せず、責任範囲を契約で定める」が実務。", "kid": "AIの出力は必ず当たるとは限らない(確率的)。だから提供する側は「精度は保証しません」「使い方はこの範囲で」と、責任の線引きを契約(利用規約)で決めておくのがふつう。", "eg": "天気予報サービスが「予報が外れても責任は負いません」と最初に断っておく、あの取り決めに近い。", "terms": [["AIサービス提供契約", "AIを外部提供する際に、精度の非保証や責任の範囲などを定める契約(利用規約)"], ["確率的", "AIの出力は必ず正しいとは限らず、確率的に外れることがある性質"]], "think": "「精度は保証しない・責任は契約で線引き」が実務の考え方。100%保証や、法律で一律に決まるという思い込みを外す。", "vs": "「常に100%保証する義務」は非現実的で誤り、「法律で一律に決まる」も誤り(契約で定める)、「利用者は一切責任を負わない」も誤りで、使い方次第で利用者側の責任もある。", "usecase": "AIサービスを作って提供する・導入する双方で、トラブル時の責任をあらかじめ決めておくために重要。過度な精度期待を避ける線引き。", "opt": ["正解。精度は保証せず、責任の範囲を契約で定めておくのが実務。", "AIは確率的に外れるため、常に100%保証する義務とするのは非現実的。", "精度の取り決めは契約で定めるもので、法律で一律ではない。", "使い方次第で利用者側の責任もあり、一切負わないは誤り。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='9. AIに関する法律と契約'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q47', '過去の採用データで学習したAIが、そのデータに含まれていた男女の偏りをそのまま引き継ぎ、特定の性別を不利に扱ってしまう問題を指す語はどれか。', NULL, '["バイアス（学習データの偏りによる不公平）", "ハルシネーション", "過学習", "次元の呪い"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "学習データの偏りを引き継いで、特定の属性を不利に扱ってしまう問題は？", "point": "「学習データの偏りを引き継いで、特定の属性に不公平になる」なら、バイアス(公平性の問題)。", "kid": "AIは過去のデータをまねて学ぶ。だから、過去に男性ばかり採用していたデータで学べば「女性を低く評価する」偏りまで引き継いでしまう。この不公平がAIのバイアス。", "eg": "偏った先輩のやり方をそのまま覚えた新人が、同じ偏見で判断してしまう、あの引き継ぎ。", "terms": [["バイアス（公平性）", "学習データに含まれる偏りをAIが引き継ぎ、特定の属性に不公平な判断をする問題"], ["公平性", "性別や人種などで不当に差をつけない、というAI倫理の重要な価値"]], "think": "「データの偏りを引き継いで不公平になる」ならバイアス(公平性の問題)。事実に反する出力(ハルシネーション)や、訓練に合わせすぎる過学習とは別の論点。", "vs": "ハルシネーションは事実に反する出力をする現象、過学習は訓練データに合わせすぎる状態、次元の呪いは項目が多すぎてデータがスカスカになる問題。どれも学習データの偏りによる不公平ではない。", "usecase": "採用・与信・司法などAIの判断が人生に関わる場面で、差別を生まないために対策が必須。学習データの偏りの点検や、公平性の評価につながる。", "opt": ["正解。学習データの偏りを引き継いで不公平な判断をするのがバイアス。", "事実に反する出力をする現象で、偏りによる不公平とは別。", "訓練データに合わせすぎる状態で、公平性の問題ではない。", "項目が多すぎてデータがスカスカになる問題で、偏りの引き継ぎではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='10. AI倫理・AIガバナンス'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q48', '学習に使うデータにあらかじめ悪意のある例を紛れ込ませ、モデルを学習の段階から狂わせる攻撃はどれか。', NULL, '["データポイズニング", "敵対的サンプル", "ディープフェイク", "フィルターバブル"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "学習データに悪意ある例を紛れ込ませ、学習の段階からモデルを狂わせる攻撃は？", "point": "「学習データを汚して、学習の段階からモデルを狂わせる」なら、データポイズニング。", "kid": "AIは学習データをまねる。だから、そのデータにこっそり悪意ある例(毒)を混ぜておくと、モデルは最初から間違った覚え方をしてしまう。この“学習を汚す”攻撃がデータポイズニング。", "eg": "教科書に嘘のページを紛れ込ませて、生徒が最初から間違って覚えるように仕向ける、あの妨害。", "terms": [["データポイズニング", "学習データに悪意ある例を混ぜ、学習の段階からモデルを汚染する攻撃"], ["敵対的サンプル", "学習後、使うときの入力に小さなノイズを混ぜて誤らせる別の攻撃"]], "think": "「学習データを汚す(学習の段階の攻撃)」ならデータポイズニング。使うとき(推論時)の入力を細工する敵対的サンプルとは、狙う段階が違う。", "vs": "敵対的サンプルは使うときの入力を細工する攻撃、ディープフェイクは本物そっくりの偽コンテンツを作る技術、フィルターバブルは好みの情報に囲まれる現象。どれも学習データを汚す攻撃ではない。", "usecase": "ネットから集めたデータで学習するときのリスク。データの出所の確認や検査が防御になる、AIの安全性の論点。", "opt": ["正解。学習データを汚して学習の段階からモデルを狂わせるのがデータポイズニング。", "使うときの入力を細工する攻撃で、学習データを汚すのとは段階が違う。", "本物そっくりの偽コンテンツを作る技術で、学習を汚す攻撃ではない。", "好みの情報に囲まれる現象で、攻撃ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='10. AI倫理・AIガバナンス'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q49', '日本政府が示した、AIを社会で使う上での基本的な考え方をまとめた原則で、「AIは人間の尊厳を大切にし、人間が主体であるべき」といった方針を掲げるものはどれか。', NULL, '["人間中心のAI社会原則", "ムーアの法則", "ロボット工学三原則", "ベイズの定理"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "日本政府が示した、AIを社会で使う上での基本方針をまとめた原則は？", "point": "「日本政府が示した、人間が主体・人間の尊厳を大切に、というAIの基本原則」なら、人間中心のAI社会原則。", "kid": "AIをどう社会で使うべきかについて、日本政府が「AIは人間の尊厳を守り、人間が主役であるべき」といった考え方をまとめた指針。技術の話ではなく、社会での向き合い方の原則。", "eg": "学校の「みんなが安心して過ごすための約束ごと」のような、AIと社会のための基本ルール集。", "terms": [["人間中心のAI社会原則", "日本政府が示した、AIを社会で使う上での基本原則。人間の尊厳や主体性を重んじる"], ["AI事業者ガイドライン", "開発者・提供者・利用者それぞれの取るべき行動を示した、より実務寄りの指針"]], "think": "「日本政府・AIと社会・人間が主体」なら人間中心のAI社会原則。技術法則(ムーアの法則)やSFの創作(ロボット工学三原則)とは種類が違う。", "vs": "ムーアの法則は半導体の性能向上の経験則、ロボット工学三原則はSF作家アシモフの創作、ベイズの定理は確率を更新する数学の定理。どれも日本政府のAI社会原則ではない。", "usecase": "企業や行政がAIを導入する際の、倫理・ガバナンスの拠り所。「人間が主体」という軸を、方針づくりの土台にできる。", "opt": ["正解。日本政府が示した、人間を主体に置くAIの基本原則。", "半導体の性能向上の経験則で、社会原則ではない。", "SF作家の創作上の原則で、政府の社会原則ではない。", "確率を更新する数学の定理で、AIの社会原則ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='10. AI倫理・AIガバナンス'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-b-q50', 'SNSなどで、自分と同じ意見の人ばかりとつながるうちに、その意見だけが繰り返し響いて、まるで世の中全体がそう考えているかのように感じてしまう現象はどれか。', NULL, '["エコーチェンバー", "フィルターバブル", "フレーム問題", "シンギュラリティ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "同じ意見の人ばかりとつながり、その意見だけが響いて世の中全体がそう思っていると錯覚する現象は？", "point": "「同じ意見の人ばかりの中で、その意見だけが反響して増幅される」なら、エコーチェンバー。", "kid": "SNSで同じ意見の人ばかりフォローしていると、その意見だけが何度も返ってくる。すると、まるで世の中みんながそう考えているように錯覚してしまう。閉じた部屋で声が反響するイメージから、エコーチェンバー(反響室)と呼ぶ。", "eg": "洞窟の中で叫ぶと自分の声ばかり跳ね返ってきて、それが正しいと錯覚する、あの反響。", "terms": [["エコーチェンバー", "同じ意見の人ばかりの空間で、その意見が反響し増幅され、偏りが強まる現象"], ["フィルターバブル", "おすすめの仕組みが好みの情報ばかり見せ、視野が狭まる似た現象"]], "think": "「同じ意見どうしで反響して増幅」ならエコーチェンバー。おすすめ機能に囲い込まれるのがフィルターバブルで、原因が「人のつながり」か「おすすめの仕組み」かで区別すると分かりやすい。", "vs": "フィルターバブルはおすすめが好みの情報で囲い込む現象(似ているが原因が推薦の仕組み側)、フレーム問題は考える範囲を絞れない難問、シンギュラリティはAIが人間を超える未来。後ろ2つは情報の偏りの現象ですらない。", "usecase": "SNSでの意見の分断や過激化を説明する言葉。健全な情報環境の設計や、多様な意見に触れる工夫を考えるときの論点。", "opt": ["正解。同じ意見どうしで反響し増幅されるのがエコーチェンバー。", "おすすめが好みの情報で囲い込む似た現象で、原因が推薦の仕組み側。", "考える範囲を絞れない難問で、情報の偏りの現象ではない。", "AIが人間を超える未来のことで、情報の偏りとは関係ない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-b' AND c.name='10. AI倫理・AIガバナンス'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
COMMIT;
