BEGIN;
INSERT INTO public.subjects (slug, name, description, color, sort_order)
VALUES ('g-kentei-d', 'G検定（JDLA ジェネラリスト検定） Set D',
        'JDLA G検定 対策 第4弾。シラバス2024（2024年11月試験より適用）準拠。Set A・B・C が扱っていないテーマを中心に構成。個人情報保護法は範囲外（保有資格のため意図的に除外）。本試験の再現ではなく学習用オリジナル。',
        '#0B5CAB', 53)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.categories (subject_id, name, color, sort_order)
SELECT s.id, v.name, v.color, v.sort_order
FROM public.subjects s
CROSS JOIN (VALUES
  ('1. 人工知能とは', '#58a6ff', 0),
  ('2. 人工知能をめぐる動向', '#79c0ff', 1),
  ('3. 機械学習の概要', '#3fb950', 2),
  ('4. ディープラーニングの概要', '#a371f7', 3),
  ('5. ディープラーニングの要素技術', '#d2a8ff', 4),
  ('6. ディープラーニングの応用例', '#f0883e', 5),
  ('7. AIの社会実装に向けて', '#e3b341', 6),
  ('8. AIに必要な数理・統計知識', '#39c5cf', 7),
  ('9. AIに関する法律と契約', '#f85149', 8),
  ('10. AI倫理・AIガバナンス', '#ff7b72', 9)
) AS v(name, color, sort_order)
WHERE s.slug = 'g-kentei-d'
ON CONFLICT (subject_id, name) DO NOTHING;
COMMIT;
BEGIN;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q1', '特定の作業だけでなく、人間のように幅広い課題に柔軟に対応できるとされる、まだ実現していないAIを指す語はどれか。', NULL, '["汎用人工知能（AGI）", "特化型AI", "エキスパートシステム", "強化学習エージェント"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "幅広い課題に柔軟に対応できる、まだ実現していないAIを指す語は？", "point": "「特定作業に限らず、人間のように幅広くこなす(まだ未実現の)AI」なら、汎用人工知能(AGI)。", "kid": "今のAIは「翻訳だけ」「囲碁だけ」と一つの作業に特化している。人間のように何でも柔軟にこなせるAIが汎用人工知能(AGI)。まだ実現していない目標。", "eg": "一芸に秀でた専門家(今のAI)に対して、何でもそつなくこなす“万能な人”を目指す、あのイメージ。", "terms": [["汎用人工知能（AGI）", "特定の作業に限らず、人間のように幅広い課題に対応できるとされるAI。まだ実現していない"], ["特化型AI", "特定の作業だけに特化したAI。現状のAIの大半がこれ"]], "think": "「幅広く柔軟・人間並み・まだ未実現」なら汎用人工知能(AGI)。一つの作業だけの特化型AIと対で押さえる。", "vs": "特化型AIは特定作業専用の現状のAI、エキスパートシステムは知識をルール化した古典的AI、強化学習エージェントは報酬で学ぶ仕組みで、いずれも幅広くこなす汎用人工知能ではない。", "usecase": "AIの最終目標としてよく語られる概念。今のAIがどこまで来ているか、何が足りないかを議論する基準になる。", "opt": ["正解。幅広い課題に柔軟に対応できるとされる未実現のAIが汎用人工知能。", "特定作業だけに特化した現状のAIで、幅広くこなす汎用ではない。", "知識をルール化した古典的AIで、汎用人工知能ではない。", "報酬で学ぶ仕組みで、幅広くこなす汎用AIそのものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='1. 人工知能とは'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q2', 'AIの能力段階のうち、人間が与えたデータから入力と出力の対応ルールそのものを学習して獲得する（機械学習を取り入れた）段階はどれか。', NULL, '["対応のルールをデータから学習する段階", "決められた振る舞いしかしない制御の段階", "対応関係を人間がすべて定義する段階", "特徴量そのものまで自ら学習する段階"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "入力と出力の対応ルールを、データから学習する(機械学習を取り入れた)段階は？", "point": "「対応のルールをデータから自分で学ぶ(機械学習を取り入れた)」なら、レベル3。", "kid": "人が対応を全部決める段階(レベル2)より一歩進み、データから「こういう入力にはこう返す」というルール自体を学ぶ段階。機械学習を取り入れたAIがこれにあたる。ただし注目する特徴は人が用意する。", "eg": "大量の例題を解くうちに「解き方のパターン」を自分でつかむ、あの学び方。ただしどの手がかりに注目するかは先生が示す。", "terms": [["レベル3", "入力と出力の対応ルールをデータから学習する段階。機械学習を取り入れたAI"], ["レベル4", "注目すべき特徴量まで自ら学習する最上位の段階。ディープラーニング相当"]], "think": "「対応ルールをデータから学ぶ・特徴は人が用意」ならレベル3。特徴まで自分で学ぶレベル4の一歩手前。", "vs": "決められた動きだけの制御は最も単純な段階、対応を人が全部定義するのは一つ手前の段階、特徴量まで自ら学ぶのは最上位の段階で、いずれも機械学習を取り入れたレベル3そのものではない。", "usecase": "「機械学習を使うAI」がどの段階かを整理する軸。特徴を人が設計する従来の機械学習と、特徴も学ぶディープラーニングの違いを捉える土台。", "opt": ["正解。対応ルールをデータから学習する、機械学習を取り入れた段階。", "決められた動きだけの最も単純な段階で、学習していない。", "対応を人が全部定義する段階で、ルールを学んでいない。", "特徴量まで自ら学ぶ最上位の段階で、レベル3の一つ上。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='1. 人工知能とは'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q3', 'AIの2大アプローチのうち、脳の神経回路をまねてデータから学習させる立場（ニューラルネットワークなど）を指す語はどれか。', NULL, '["結合主義", "記号主義", "行動主義", "経験主義"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "脳の神経回路をまねてデータから学習させるAIの立場は？", "point": "「脳をまねてデータから学習させる(ニューラルネット的)立場」なら、結合主義。", "kid": "AIには2つの大きな流派がある。人が知識をルールで書き込む「記号主義」と、脳の神経回路をまねてデータから学ばせる「結合主義」。今のディープラーニングは結合主義の流れ。", "eg": "料理でいえば、レシピを全部文字で書き起こす流派(記号主義)と、たくさん食べ比べて舌で覚える流派(結合主義)の違い。", "terms": [["結合主義（コネクショニズム）", "脳の神経回路をまねてデータから学習させる立場。ニューラルネットワークが代表"], ["記号主義（シンボリズム）", "知識を記号やルールで表して推論させる立場。エキスパートシステムが代表"]], "think": "「脳をまねてデータから学ぶ」なら結合主義、「ルールで知識を書き込む」なら記号主義。学ぶか書き込むかで分ける。", "vs": "記号主義はルールで知識を書き込む立場、行動主義や経験主義は心理学・哲学の立場で、いずれも脳をまねて学ぶ結合主義ではない。", "usecase": "ディープラーニング(結合主義)と、エキスパートシステム(記号主義)がなぜ性質が違うのかを、根っこの考え方から理解できる。", "opt": ["正解。脳をまねてデータから学習させる立場が結合主義。", "知識をルールで書き込む立場で、データから学ぶ結合主義とは逆。", "心理学の立場で、AIの学習アプローチそのものではない。", "哲学の立場で、AIのアプローチそのものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='1. 人工知能とは'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q4', '囲碁・翻訳・画像認識のように、決められた一つの作業に特化して能力を発揮する、現状の大半を占めるAIを指す語はどれか。', NULL, '["特化型AI", "汎用人工知能", "エキスパートシステム", "強いAI"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "決められた一つの作業に特化して能力を発揮する、現状の大半のAIは？", "point": "「一つの決まった作業に特化した(現状の大半の)AI」なら、特化型AI。", "kid": "今のAIは、囲碁なら囲碁、翻訳なら翻訳と、一つの作業に絞って力を発揮する。何でもこなせるわけではない。この“一芸特化”が特化型AIで、現状のAIの大半がこれ。", "eg": "どんな料理も作れる万能シェフ(汎用AI)ではなく、寿司だけを極めた職人(特化型AI)のイメージ。", "terms": [["特化型AI", "決められた一つの作業に特化して力を発揮するAI。現状の大半がこれ"], ["汎用人工知能（AGI）", "幅広い課題に柔軟に対応できるとされるAI。まだ実現していない"]], "think": "「一つの作業に特化・現状の大半」なら特化型AI。幅広くこなす汎用人工知能(未実現)と対で押さえる。", "vs": "汎用人工知能は幅広くこなす未実現のAI、エキスパートシステムは知識をルール化した古典的AI、強いAIは本物の意識を持てるとする立場で、いずれも一芸特化の特化型AIそのものではない。", "usecase": "「AIはすごい」と一括りにせず、実際は一つの作業に特化していると理解するための基本。過度な期待を避ける現実的な視点になる。", "opt": ["正解。一つの作業に特化して力を発揮する現状の大半のAIが特化型AI。", "幅広くこなす未実現のAIで、一芸特化とは逆。", "知識をルール化した古典的AIで、特化型AIの分類そのものではない。", "本物の意識を持てるとする立場で、能力範囲の分類ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='1. 人工知能とは'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q5', 'AIへの過度な期待が実際の成果に届かず、研究への関心や資金が急速に冷え込んだ時期を指す語はどれか。', NULL, '["AIの冬", "シンギュラリティ", "ムーアの法則", "AI効果"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "期待が成果に届かず、関心や資金が冷え込んだ時期を指す語は？", "point": "「ブームが去り、研究への関心や資金が冷え込んだ時期」なら、AIの冬。", "kid": "AIは何度も「すごい」と期待されてブームになったが、期待ほどの成果が出ないと、関心も研究資金も急に冷え込んだ。この冷え込みの時期をAIの冬と呼ぶ。ブームと冬を繰り返してきた。", "eg": "大ブームで盛り上がった商品が、期待外れと分かった途端に売れ行きも投資も一気に冷える、あの反動。", "terms": [["AIの冬", "AIへの期待が成果に届かず、研究への関心や資金が冷え込んだ時期"], ["AIブーム", "AIへの期待が高まり研究が盛んになる時期。冬と交互に繰り返してきた"]], "think": "「期待外れで関心・資金が冷え込んだ時期」ならAIの冬。AIが人間を超える未来のシンギュラリティとは正反対の局面。", "vs": "シンギュラリティはAIが人間を超える未来、ムーアの法則は半導体の性能向上の経験則、AI効果は仕組みが分かると知能扱いされなくなる心理で、いずれも研究が冷え込むAIの冬ではない。", "usecase": "AIの歴史がブームと冬の繰り返しだと理解する鍵。今のブームも過度な期待には注意、という教訓を読み取れる。", "opt": ["正解。期待が成果に届かず関心や資金が冷え込んだ時期がAIの冬。", "AIが人間を超える未来を指す語で、冷え込む局面とは逆。", "半導体の性能向上の経験則で、AIの盛衰の話ではない。", "仕組みが分かると知能扱いされなくなる心理で、冬とは別。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q6', '大学入試の突破を目標に掲げた日本のAIプロジェクトで、文章の意味理解の難しさという限界を示したものはどれか。', NULL, '["東ロボくん", "AlphaGo", "Watson", "ELIZA"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "大学入試突破を目標に、文章の意味理解の限界を示した日本のAIプロジェクトは？", "point": "「大学入試の突破を目指し、読解の限界を示した日本のプロジェクト」なら、東ロボくん。", "kid": "「AIは東大に合格できるか」に挑んだ日本のプロジェクト。暗記や計算は得意でも、文章の“意味”を理解する読解が壁となり、難関大の合格には届かなかった。AIの意味理解の難しさを示した。", "eg": "暗記科目は高得点なのに、文章の意図を読み取る国語でつまずく受験生、あの得意不得意。", "terms": [["東ロボくん", "大学入試突破を目標にした日本のAIプロジェクト。文章の意味理解の限界を示した"], ["意味理解", "文章が指す本当の意味を捉えること。AIには依然として難しい課題"]], "think": "「大学入試・日本・読解の限界」なら東ロボくん。囲碁のAlphaGoやクイズのWatsonとは、扱う課題が違う。", "vs": "AlphaGoは囲碁のAI、Watsonはクイズの質問応答システム、ELIZAはおうむ返しの対話プログラムで、いずれも大学入試に挑んだ東ロボくんではない。", "usecase": "「AIは計算は得意でも意味理解は苦手」という限界を示す代表例。AIに何を任せ、何を任せにくいかを考える材料になる。", "opt": ["正解。大学入試突破を目指し読解の限界を示した日本のプロジェクトが東ロボくん。", "囲碁で人に勝ったAIで、大学入試のプロジェクトではない。", "クイズの質問応答システムで、大学入試に挑んだものではない。", "おうむ返しの対話プログラムで、東ロボくんではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q7', '1958年に考案された、脳の神経細胞をまねて入力に重みを掛けて足し合わせ、しきい値で出力を決める、ニューラルネットワークの起源となったモデルはどれか。', NULL, '["パーセプトロン", "サポートベクターマシン", "決定木", "ランダムフォレスト"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "脳の神経細胞をまねた、ニューラルネットワークの起源となった1958年のモデルは？", "point": "「入力に重みを掛けて足し、しきい値で出力を決める、ニューラルネットの起源」なら、パーセプトロン。", "kid": "脳の神経細胞をまねて、入力に重み(効き具合)を掛けて足し合わせ、その合計がしきい値を超えたら反応する、という最初期のモデル。今のニューラルネットワークの出発点。", "eg": "複数の情報に「重要度」を付けて足し算し、合計がある基準を超えたら「YES」と判断する、あのシンプルな決め方。", "terms": [["パーセプトロン", "入力に重みを掛けて足し、しきい値で出力を決めるモデル。ニューラルネットワークの起源"], ["多層パーセプトロン", "隠れ層を加えてXORなど複雑な問題も解けるようにした発展形"]], "think": "「重み付き和＋しきい値・ニューラルネットの起源・1958年」ならパーセプトロン。データを2分する境界を学ぶSVMなど後の手法とは別。", "vs": "サポートベクターマシンは余白を最大化して分ける後発の手法、決定木は条件分岐で予測する手法、ランダムフォレストは決定木を束ねる手法で、いずれもニューラルネットの起源パーセプトロンではない。", "usecase": "ニューラルネットワーク、ひいてはディープラーニングの原点。ここから層を深くする流れが今のAIにつながっている。", "opt": ["正解。重み付き和としきい値で出力を決める、ニューラルネットの起源がパーセプトロン。", "余白を最大化して分ける後発の分類手法で、起源のモデルではない。", "条件分岐で予測する手法で、パーセプトロンではない。", "決定木を束ねる手法で、ニューラルネットの起源ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q8', '単純な計算を大量に同時並行でこなすのが得意で、ディープラーニングの学習を高速化し、その普及を支えた演算装置はどれか。', NULL, '["GPU", "SSD", "RAM", "ルーター"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "単純計算を大量に並列でこなし、ディープラーニングの学習を高速化した装置は？", "point": "「単純計算を大量に並列でこなし、DLの学習を高速化した装置」なら、GPU。", "kid": "ディープラーニングは、同じような掛け算・足し算を膨大に繰り返す。GPUはその単純計算を一度に大量にこなすのが得意で、学習を大幅に速くした。だからディープラーニングが実用になった。", "eg": "一人の天才(CPU)が難問を順に解くより、大勢のアルバイト(GPU)が単純作業を一斉に片付ける方が速い、あの分業。", "terms": [["GPU", "単純な計算を大量に同時並行でこなす演算装置。ディープラーニングの学習を高速化した"], ["CPU", "複雑な処理を順にこなす汎用の演算装置。並列の単純計算はGPUが得意"]], "think": "「単純計算を大量に並列・DLを高速化」ならGPU。データを保存するSSDや、作業用メモリのRAMとは役割が違う。", "vs": "SSDはデータを保存する記憶装置、RAMは作業用の一時メモリ、ルーターはネットワークを中継する機器で、いずれも並列計算でDLを速くするGPUではない。", "usecase": "ビッグデータと並ぶ、ディープラーニング普及の立役者。大規模モデルの学習にはGPU(やその発展形)が欠かせない。", "opt": ["正解。単純計算を大量に並列でこなしDLを高速化したのがGPU。", "データを保存する記憶装置で、計算を速くする装置ではない。", "作業用の一時メモリで、並列計算の装置ではない。", "ネットワークを中継する機器で、計算装置ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q9', 'インターネットの普及などで大量・多様なデータが集まるようになったことは、ディープラーニング普及の大きな一因とされる。この大量のデータを指す語はどれか。', NULL, '["ビッグデータ", "オープンデータ", "メタデータ", "データリーケージ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "大量・多様に集まるようになり、DL普及を支えたデータを指す語は？", "point": "「大量・多様に集まった、DL普及を支えたデータ」なら、ビッグデータ。", "kid": "ディープラーニングは、たくさんのデータで学ぶほど賢くなる。インターネットやスマホの普及で大量・多様なデータが集まるようになったことが、ディープラーニングが花開いた一因。この大量のデータがビッグデータ。", "eg": "大量の練習問題が手に入ったから、たくさん解いて実力を伸ばせた、あの環境の変化。", "terms": [["ビッグデータ", "量・種類・発生速度の大きい、大量で多様なデータ。ディープラーニング普及の一因"], ["GPU", "大量の計算を並列でこなす装置。ビッグデータと並ぶDL普及の立役者"]], "think": "「大量・多様なデータ・DL普及の一因」ならビッグデータ。自由に使える公開データのオープンデータとは、指すものが違う。", "vs": "オープンデータは誰でも自由に使える公開データ、メタデータはデータの説明情報、データリーケージは答えが訓練に漏れる問題で、いずれも大量・多様なデータを指すビッグデータではない。", "usecase": "「なぜ2010年代にディープラーニングが実用化したか」の答えの一つ。GPU(計算力)とビッグデータ(データ量)がそろったことが大きい。", "opt": ["正解。大量・多様に集まったデータで、DL普及を支えたのがビッグデータ。", "誰でも自由に使える公開データで、量の大きさを指す語ではない。", "データの説明情報で、大量のデータそのものではない。", "答えが訓練に漏れる問題で、データの種類ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q10', '第1次AIブームで中心となった、問題をルールに従って場合分けし、ゴールへの道筋を筋道立てて探し出す取り組みを指す語はどれか。', NULL, '["推論と探索", "機械学習", "ディープラーニング", "知識の蒸留"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "第1次ブームの中心だった、場合分けしてゴールへの道筋を探す取り組みは？", "point": "「問題を場合分けして、ゴールへの道筋を筋道立てて探す(第1次ブームの中心)」なら、推論と探索。", "kid": "第1次AIブームでは、迷路やパズルのように、ルールに従って場合分けし、ゴールまでの道筋を一つずつ探し出す方法が中心だった。この筋道立てて答えを探す取り組みが推論と探索。", "eg": "迷路で分かれ道を一つずつ試し、行き止まりなら戻ってゴールまでの道を探す、あの探し方。", "terms": [["推論と探索", "ルールに従って場合分けし、ゴールへの道筋を探し出す取り組み。第1次AIブームの中心"], ["トイ・プロブレム", "単純化された問題。推論と探索は現実の複雑な問題には歯が立たなかった"]], "think": "「場合分けして道筋を探す・第1次ブーム」なら推論と探索。データから学ぶ機械学習(第3次ブーム中心)とは時代も発想も違う。", "vs": "機械学習はデータから学ぶ手法、ディープラーニングは特徴まで学ぶ手法、知識の蒸留はモデルを軽くする手法で、いずれも第1次ブームの推論と探索ではない。", "usecase": "AIの歴史の最初の柱。単純な問題は解けても現実の複雑さに届かなかった限界(トイ・プロブレム)が、次の時代への課題になった。", "opt": ["正解。場合分けして道筋を探す第1次ブームの取り組みが推論と探索。", "データから学ぶ手法で、第1次ブームの推論と探索ではない。", "特徴まで学ぶ手法で、第1次ブームの取り組みではない。", "モデルを軽くする手法で、推論と探索とは別。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='2. 人工知能をめぐる動向'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q11', '各特徴が互いに独立だと単純化した仮定を置き、確率を計算して分類する、迷惑メール判定などで使われる手法はどれか。', NULL, '["ナイーブベイズ", "k-means法", "主成分分析", "ランダムフォレスト"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "特徴が独立と仮定して確率で分類する、迷惑メール判定などの手法は？", "point": "「特徴が互いに独立と単純化して、確率で分類する」なら、ナイーブベイズ。", "kid": "「この単語があるとスパムっぽい」といった手がかりを、それぞれ独立とみなして確率を掛け合わせ、どのクラスの確率が高いかで分類する。単純な仮定だが、迷惑メール判定などで意外とよく効く。", "eg": "複数の目撃証言を、それぞれ独立とみなして「犯人らしさ」を掛け合わせ、一番怪しい人を選ぶ、あの推理。", "terms": [["ナイーブベイズ", "各特徴が独立と仮定し、ベイズの定理で確率を計算して分類する手法"], ["ベイズの定理", "もとの確率に証拠を反映して確率を更新する考え方。ナイーブベイズの土台"]], "think": "「特徴が独立と仮定・確率で分類」ならナイーブベイズ。正解なしでまとめるk-meansや、次元を減らすPCAとは目的が違う。", "vs": "k-means法は正解なしのグループ分け、主成分分析は次元削減、ランダムフォレストは決定木を束ねる手法で、いずれも独立仮定で確率分類するナイーブベイズではない。", "usecase": "迷惑メール判定や文書のカテゴリ分けで定番。計算が軽く、データが少なくても動くので、手早く試すベースラインに向く。", "opt": ["正解。特徴が独立と仮定して確率で分類するのがナイーブベイズ。", "正解なしでまとめるグループ分けで、確率分類ではない。", "次元削減の手法で、分類手法ではない。", "決定木を束ねる手法で、独立仮定の確率分類ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q12', '学習の段階ではデータを覚えておくだけで、予測するときに「近くにある学習データ」を見て多数決する、怠惰学習とも呼ばれる手法はどれか。', NULL, '["k近傍法（k-NN）", "ロジスティック回帰", "サポートベクターマシン", "オートエンコーダ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "予測時に近くの学習データを見て多数決する、怠惰学習とも呼ばれる手法は？", "point": "「学習時は覚えるだけ、予測時に近くのデータを多数決する」なら、k近傍法(k-NN)。", "kid": "ふつうの手法は学習でモデルを作り込む。k近傍法は学習時はデータを覚えておくだけで、予測するときに「近くにある学習データ」を見て多数決する。予測時まで判断を先送りするので怠惰学習と呼ばれる。", "eg": "引っ越し先で自分の好みが分からないとき、ご近所さんの多数派に合わせて決める、あの決め方。", "terms": [["k近傍法（k-NN）", "予測時に近くのk個の学習データの多数決で分類する手法。怠惰学習とも呼ばれる"], ["怠惰学習", "学習時にはモデルを作らず、予測時に計算する方式。k-NNが代表"]], "think": "「学習時は覚えるだけ・予測時に近くを多数決」ならk近傍法。学習でモデルを作り込むロジスティック回帰やSVMとは、判断のタイミングが違う。", "vs": "ロジスティック回帰は学習で境界を作り込む、サポートベクターマシンも学習で境界を作る、オートエンコーダは圧縮・復元を学ぶ構造で、いずれも予測時に多数決するk近傍法ではない。", "usecase": "少数のデータで手早く分類したいときや、基準となる簡単な手法として使う。データが増えると予測が重くなる点が弱み。", "opt": ["正解。予測時に近くのデータを多数決するのがk近傍法。", "学習で境界を作り込む手法で、予測時に多数決するのとは違う。", "学習で境界を作る手法で、怠惰学習ではない。", "圧縮・復元を学ぶ構造で、多数決の分類ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q13', '「赤・青・緑」のような、大小関係のないカテゴリの項目を、機械学習で扱えるよう、各カテゴリに対応する1か所だけを1にしたベクトルへ変換する方法はどれか。', NULL, '["ワンホットエンコーディング", "ラベルエンコーディング", "ミニマックス正規化", "ブートストラップ法"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "大小関係のないカテゴリを、1か所だけ1のベクトルに変換する方法は？", "point": "「カテゴリを、各値に対応する1か所だけ1のベクトルにする」なら、ワンホットエンコーディング。", "kid": "「赤・青・緑」を1・2・3という数字にすると、機械が「緑は赤の3倍」と勝手に大小をつけてしまう。そこで「赤＝(1,0,0)」のように、対応する1か所だけを1にしたベクトルにして、順序の誤解を防ぐ。これがワンホットエンコーディング。", "eg": "出席簿のチェック欄のように、「あてはまる欄だけにチェック(1)、他は空欄(0)」で表す、あの方式。", "terms": [["ワンホットエンコーディング", "大小関係のないカテゴリを、対応する1か所だけ1にしたベクトルへ変換する方法"], ["ラベルエンコーディング", "カテゴリを整数に置き換える方法。順序があると誤解される場合があり注意"]], "think": "「カテゴリを1か所だけ1のベクトルに・順序の誤解を防ぐ」ならワンホットエンコーディング。桁をそろえる標準化とは目的が違う前処理。", "vs": "ラベルエンコーディングはカテゴリを整数に置き換える(順序の誤解が起きうる)、ミニマックス正規化は数値を0〜1に収める、ブートストラップ法は重複ありでデータを選び直す方法で、いずれもワンホットエンコーディングではない。", "usecase": "色・地域・種別などカテゴリの項目を機械学習に入れる前の定番の前処理。順序の無い項目に不要な大小関係を持ち込まないために使う。", "opt": ["正解。カテゴリを1か所だけ1のベクトルにするのがワンホットエンコーディング。", "カテゴリを整数に置き換える方法で、順序の誤解が起きうる別の方法。", "数値を0〜1に収める正規化で、カテゴリのベクトル化ではない。", "重複ありでデータを選び直す方法で、カテゴリの変換ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
COMMIT;
BEGIN;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q14', 'データに含まれる、値が抜けている箇所（欠損値）を、平均値や中央値などで埋めて分析や学習に使えるようにする処理はどれか。', NULL, '["欠損値の補完", "データ拡張", "次元削減", "アノテーション"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "抜けている値を平均値などで埋めて、使えるようにする処理は？", "point": "「抜けている値(欠損値)を平均などで埋める」なら、欠損値の補完。", "kid": "集めたデータには、記入漏れなどで値が抜けている箇所(欠損値)がある。多くの手法は欠損があると動かないので、平均値や中央値などで埋めて使えるようにする。この穴埋めが欠損値の補完。", "eg": "アンケートの空欄を、全体の平均的な回答で埋めて集計に使えるようにする、あの穴埋め。", "terms": [["欠損値の補完", "抜けている値(欠損値)を、平均値・中央値などで埋めて使えるようにする処理"], ["欠損値", "本来あるべき値が抜けている箇所。埋めるか、その行を除くかを判断する"]], "think": "「抜けた値を埋める」なら欠損値の補完。データを増やすデータ拡張や、項目を減らす次元削減とは目的が違う前処理。", "vs": "データ拡張はデータを水増しする手法、次元削減は項目の数を減らす手法、アノテーションは正解ラベルを付ける作業で、いずれも欠損値を埋める補完ではない。", "usecase": "現実のデータには欠損がつきもの。埋め方(平均・中央値・別の値の予測など)を選ぶことが、分析や学習の質を左右する下ごしらえ。", "opt": ["正解。抜けている値を平均などで埋めるのが欠損値の補完。", "データを水増しする手法で、欠損を埋める処理ではない。", "項目の数を減らす手法で、欠損の穴埋めではない。", "正解ラベルを付ける作業で、欠損値の補完ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q15', '陽性がごくわずかしかない偏ったデータで、少数派のデータを水増しして数のバランスを整える対処はどれか。', NULL, '["オーバーサンプリング", "アンダーサンプリング", "標準化", "正則化"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "少数派を水増しして偏りを整える対処は？", "point": "「少数派を水増しして数のバランスを整える」なら、オーバーサンプリング。", "kid": "陽性1%のような偏ったデータをそのまま学ぶと、AIは「全部陰性」と答えるだけで済んでしまう。そこで少数派(陽性)を水増しして数のバランスを整えるのがオーバーサンプリング。逆に多数派を減らすのがアンダーサンプリング。", "eg": "少人数の意見が埋もれないよう、その分のコピーを増やして多数派と釣り合わせる、あの調整。", "terms": [["オーバーサンプリング", "少数派のデータを水増しして、多数派との数のバランスを整える対処"], ["アンダーサンプリング", "多数派のデータを減らして、少数派との数のバランスを整える対処"]], "think": "「少数派を増やす」ならオーバーサンプリング、「多数派を減らす」ならアンダーサンプリング。どちらも不均衡データの偏りを整える対処。", "vs": "アンダーサンプリングは多数派を減らす逆の対処、標準化は数値の桁をそろえる前処理、正則化は過学習を抑える手法で、いずれも少数派を水増しするオーバーサンプリングではない。", "usecase": "不正検知や病気の検査など、陽性がまれで偏ったデータの学習で使う。偏りを整えて、少数派をちゃんと拾えるモデルにする。", "opt": ["正解。少数派を水増しして数のバランスを整えるのがオーバーサンプリング。", "多数派を減らす逆の対処で、少数派を増やすものではない。", "数値の桁をそろえる前処理で、数のバランス調整ではない。", "過学習を抑える手法で、不均衡データの対処そのものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q16', '学習時に、重みが大きくなりすぎることへのペナルティを加えて、モデルが訓練データに過剰に適合するのを抑える手法の総称はどれか。', NULL, '["正則化", "標準化", "次元削減", "データ拡張"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "重みが大きくなりすぎるのにペナルティを課し、過学習を抑える手法の総称は？", "point": "「重みが大きくなりすぎるのにペナルティを課して過学習を抑える」なら、正則化。", "kid": "モデルは訓練データに合わせようと、一部の重み(効き具合)を極端に大きくしがち。すると丸暗記(過学習)になる。そこで「重みが大きいほど罰点」を加えて、ほどよく抑えるのが正則化。L1・L2などがある。", "eg": "テストで奇をてらった暗記に頼りすぎないよう、あえて“シンプルな解答”に加点する、あの制約。", "terms": [["正則化", "重みが大きくなりすぎることにペナルティを課し、過学習を抑える手法の総称。L1・L2など"], ["過学習", "訓練データに合わせすぎて初見で落ちる状態。正則化で抑える対象"]], "think": "「重みへのペナルティで過学習を抑える総称」なら正則化。桁をそろえる標準化や、データを増やすデータ拡張とは目的が違う。", "vs": "標準化は数値の桁をそろえる前処理、次元削減は項目を減らす手法、データ拡張はデータの水増しで、いずれも重みにペナルティを課す正則化ではない。", "usecase": "過学習を抑える最も基本的な対策の一つ。L1(不要な重みを0に)、L2(全体をなだらかに小さく)など、目的に応じて使い分ける。", "opt": ["正解。重みへのペナルティで過学習を抑える総称が正則化。", "数値の桁をそろえる前処理で、過学習を抑える正則化ではない。", "項目を減らす手法で、重みへのペナルティではない。", "データの水増しで、正則化ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q17', 'モデルが単純すぎて、訓練データにすら十分に当てはめられず、訓練でも本番でも精度が低い状態はどれか。', NULL, '["未学習", "過学習", "データリーケージ", "勾配消失"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "モデルが単純すぎて訓練でも本番でも精度が低い状態は？", "point": "「モデルが単純すぎて、訓練データにすら当てはまらない」なら、未学習。", "kid": "モデルが単純すぎると、訓練データのパターンすら捉えられず、訓練でも本番でも成績が悪い。この“当てはめ不足”が未学習(アンダーフィッティング)。逆に、訓練だけできて本番でダメなのが過学習。", "eg": "練習問題すらろくに解けない“準備不足”の状態、あの手応えのなさ。", "terms": [["未学習（アンダーフィッティング）", "モデルが単純すぎて、訓練データにすら十分当てはまらない状態"], ["過学習", "訓練データに合わせすぎて、初見で精度が落ちる逆の状態"]], "think": "「訓練でもダメ」なら未学習、「訓練は良いが本番でダメ」なら過学習。訓練の成績で見分ける。未学習はモデルを複雑にする・特徴を増やすなどで改善する。", "vs": "過学習は訓練だけできて本番で落ちる逆の状態、データリーケージは答えが漏れて過大評価される問題、勾配消失は学習の信号が消える問題で、いずれも当てはめ不足の未学習ではない。", "usecase": "訓練の成績も伸びないときに疑う。モデルを複雑にする、特徴量を増やす、学習を長くするなどで改善を図る、という診断の入り口。", "opt": ["正解。単純すぎて訓練データにすら当てはまらないのが未学習。", "訓練は良いが本番で落ちる逆の状態で、当てはめ不足ではない。", "答えが漏れて評価が過大になる問題で、当てはめ不足ではない。", "学習の信号が消える問題で、未学習とは別。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='3. 機械学習の概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q18', '1つの値を0から1の範囲に押し込んで出力する関数で、「陽性である確率」のように二値分類の出力に使われるものはどれか。', NULL, '["シグモイド関数", "ソフトマックス関数", "ReLU関数", "ステップ関数"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "1つの値を0〜1に押し込み、二値分類の確率出力に使う関数は？", "point": "「1つの値を0〜1に押し込み、二値分類の確率に使う」なら、シグモイド関数。", "kid": "入力を0〜1のなめらかな値に押し込む関数。0.8なら「陽性である確率80%」のように、イエス/ノーの二択(二値分類)の出力として使える。", "eg": "どんな大きさの入力も、0%〜100%の“確率メーター”の針の位置に変換する、あの目盛り。", "terms": [["シグモイド関数", "1つの値を0〜1に押し込む関数。二値分類の確率出力に使う。深い層では勾配が消えやすい"], ["ソフトマックス関数", "複数の出力を合計1の確率に変える関数。3つ以上のクラス(多クラス)の出力に使う"]], "think": "「1つの値を0〜1に・二択の確率」ならシグモイド。3つ以上を合計100%にするソフトマックスとは、扱うクラス数が違う。", "vs": "ソフトマックスは多クラスを合計1の確率にする、ReLUはマイナスを0にする中間層向けの関数、ステップ関数は0か1に切り替えるだけで学習に使いにくく、いずれも二値の確率を出すシグモイドではない。", "usecase": "迷惑メール判定や病気の陽性判定など、イエス/ノーを確率で出したい二値分類の出力で使う。ただし深い層では勾配消失を起こしやすい点に注意。", "opt": ["正解。1つの値を0〜1に押し込み二値の確率に使うのがシグモイド。", "多クラスを合計1の確率にする関数で、二値の1値の確率ではない。", "マイナスを0にする中間層向けの関数で、確率出力ではない。", "0か1に切り替えるだけで、なめらかな確率は出せない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q19', '入力を-1から+1の範囲に変換する活性化関数で、出力の中心が0になるためシグモイドより扱いやすいとされるものはどれか。', NULL, '["tanh関数", "ソフトマックス関数", "交差エントロピー", "平均二乗誤差"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "入力を-1〜+1に変換し、中心が0で扱いやすい活性化関数は？", "point": "「入力を-1〜+1に変換し、中心が0」なら、tanh関数。", "kid": "入力を-1〜+1の範囲に変換する活性化関数。出力の中心が0(プラスにもマイナスにも振れる)なので、0〜1に偏るシグモイドより学習が進みやすいとされる。中間層で使われる。", "eg": "温度計のように、0を中心にプラス側・マイナス側の両方へ振れる目盛りに変換する、あのイメージ。", "terms": [["tanh関数", "入力を-1〜+1に変換する活性化関数。出力の中心が0で、シグモイドより扱いやすいとされる"], ["シグモイド関数", "入力を0〜1に押し込む関数。出力が0寄りに偏る"]], "think": "「-1〜+1・中心が0の活性化関数」ならtanh。0〜1に押し込むシグモイドと、範囲と中心が違う。", "vs": "ソフトマックスは多クラスを確率にする出力関数、交差エントロピーと平均二乗誤差は誤差を測る損失関数で、いずれも-1〜+1に変換する活性化関数tanhではない。", "usecase": "ニューラルネットの中間層の活性化関数として使う。出力が0を中心に振れるため学習が偏りにくいのが利点(今はReLUも広く使われる)。", "opt": ["正解。入力を-1〜+1に変換し中心が0なのがtanh。", "多クラスを確率にする出力関数で、活性化のtanhではない。", "誤差を測る損失関数で、活性化関数ではない。", "回帰の誤差を測る損失関数で、活性化関数ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q20', '学習を始めるときに各重みへ与える最初の値の決め方で、これが不適切だと勾配消失などで学習が進みにくくなるものはどれか。', NULL, '["重みの初期化", "データ拡張", "早期終了", "アノテーション"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "学習開始時に各重みへ与える最初の値の決め方は？", "point": "「学習開始時に各重みへ与える最初の値の決め方」なら、重みの初期化。", "kid": "学習は各重み(効き具合)を少しずつ直していくが、その“スタート地点”の値を決めるのが重みの初期化。全部同じ値や大きすぎ・小さすぎだと、勾配が消えたりして学習が進まない。だから適切に散らして初期化する。", "eg": "山下りのスタート地点。変な場所から始めると谷底にたどり着きにくいので、良い出発点を選んでおく、あの準備。", "terms": [["重みの初期化", "学習開始時に各重みへ与える最初の値の決め方。不適切だと学習が進みにくい"], ["Xavier初期化／He初期化", "勾配消失などを避けるためによく使われる、代表的な重み初期化の方法"]], "think": "「学習開始時の重みの最初の値の決め方」なら重みの初期化。データを増やすデータ拡張や、学習を止める早期終了とは役割が違う。", "vs": "データ拡張はデータの水増し、早期終了は学習を途中で止める手法、アノテーションは正解ラベル付けで、いずれも学習開始時の重みの決め方(初期化)ではない。", "usecase": "深いネットワークが最初からうまく学習できるかを左右する。XavierやHeといった、活性化関数に合った初期化を選ぶのが定石。", "opt": ["正解。学習開始時に各重みへ与える最初の値の決め方が重みの初期化。", "データの水増しで、重みの初期値の決め方ではない。", "学習を途中で止める手法で、初期化ではない。", "正解ラベルを付ける作業で、重みの初期化ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q21', '学習において、用意した訓練データ全体をひととおり使い切ることを1回と数える単位はどれか。', NULL, '["エポック", "バッチサイズ", "学習率", "ミニバッチ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "訓練データ全体をひととおり使い切ることを1回と数える単位は？", "point": "「訓練データ全体を1周使い切ることを1回と数える」なら、エポック。", "kid": "学習では同じ訓練データを何度も繰り返し使う。その「データ全体を1周使い切った」ことを1エポックと数える。10エポックなら、全データを10周学習したという意味。", "eg": "問題集を1冊まるごと解き終えるのを“1周”と数え、「3周した」と言う、あの数え方。", "terms": [["エポック", "訓練データ全体をひととおり使い切ることを1回と数える単位"], ["ミニバッチ／バッチサイズ", "1回の更新に使うデータの小さなかたまりと、その大きさ"]], "think": "「データ全体を1周＝1回」ならエポック。1回の更新に使う小分けの量(バッチサイズ)や、更新の歩幅(学習率)とは別の概念。", "vs": "バッチサイズは1回の更新に使うデータ量、学習率は更新の歩幅、ミニバッチは更新に使うデータの小さなかたまりで、いずれもデータ全体の周回を数えるエポックではない。", "usecase": "学習をどれくらい繰り返すかの目安。少なすぎると未学習、多すぎると過学習になりやすく、早期終了と組み合わせて適切な回数を選ぶ。", "opt": ["正解。訓練データ全体を1周使い切ることを1回と数えるのがエポック。", "1回の更新に使うデータ量で、全体の周回数ではない。", "更新の歩幅を決める値で、周回数ではない。", "更新に使うデータの小さなかたまりで、周回の単位ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q22', '最適化で、勾配の大きさに応じて、パラメータの方向ごとに学習率（更新の歩幅）を自動で調整する工夫はどれか。', NULL, '["RMSProp", "ドロップアウト", "データ拡張", "バッチ正規化"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "勾配の大きさに応じて、方向ごとに学習率を自動調整する工夫は？", "point": "「方向ごとに、勾配の大きさに応じて歩幅を自動調整する」なら、RMSProp。", "kid": "学習の歩幅(学習率)は、方向によって適した大きさが違う。RMSPropは、よく動く方向は歩幅を小さく、あまり動かない方向は大きく、と勾配の大きさに応じて方向ごとに自動調整する工夫。", "eg": "坂の急な所は小股、なだらかな所は大股、と地形に合わせて歩幅を変える、あの歩き方。", "terms": [["RMSProp", "勾配の大きさに応じて、方向ごとに学習率(歩幅)を自動調整する最適化の工夫"], ["Adam", "モメンタム(勢い)とRMSProp(歩幅調整)を組み合わせた最適化"]], "think": "「方向ごとに歩幅を自動調整」ならRMSProp。勢いを引き継ぐモメンタムと組み合わせたのがAdam、と押さえる。", "vs": "ドロップアウトはノードを休ませる過学習対策、データ拡張はデータの水増し、バッチ正規化は各層の値をそろえる手法で、いずれも歩幅を自動調整するRMSPropではない。", "usecase": "方向ごとに適した歩幅で学習を進められるので、収束が安定・高速になる。モメンタムと合わせたAdamの部品としても広く使われる。", "opt": ["正解。方向ごとに勾配の大きさに応じて歩幅を自動調整するのがRMSProp。", "ノードを休ませる過学習対策で、歩幅の調整ではない。", "データの水増しで、最適化の工夫ではない。", "各層の値をそろえる手法で、歩幅の自動調整ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q23', '誤差が小さくなる方向（勾配の逆向き）へ重みを少しずつ動かして、モデルの誤差を減らしていく最適化の基本的な考え方はどれか。', NULL, '["勾配降下法", "主成分分析", "k近傍法", "決定木"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "誤差が小さくなる方向へ重みを少しずつ動かす、最適化の基本は？", "point": "「誤差が小さくなる方向へ重みを少しずつ動かす」なら、勾配降下法。", "kid": "学習は「誤差(間違いの大きさ)を最小にする」のが目標。勾配降下法は、誤差が減る方向(坂を下る向き)へ重みを少しずつ動かして、谷底(誤差最小)を目指す、最適化の一番の基本。", "eg": "霧の中で山を下るとき、足元の一番急な下り坂の向きへ一歩ずつ下りていく、あの進み方。", "terms": [["勾配降下法", "誤差が小さくなる方向へ重みを少しずつ動かし、誤差を減らす最適化の基本"], ["確率的勾配降下法（SGD）", "データを小分けにして勾配降下を行う、実用的な発展形"]], "think": "「誤差が減る方向へ重みを少しずつ・坂を下る」なら勾配降下法。ニューラルネット学習の最適化の土台。SGDやAdamはこの発展形。", "vs": "主成分分析は次元削減、k近傍法は近くの正解で多数決する分類、決定木は条件分岐で予測する手法で、いずれも誤差を減らす最適化の勾配降下法ではない。", "usecase": "ニューラルネットワークの学習の根っこ。この基本の上に、小分けにするSGDや歩幅・勢いを工夫したAdamなどが乗っている。", "opt": ["正解。誤差が減る方向へ重みを少しずつ動かすのが勾配降下法。", "次元削減の手法で、誤差を減らす最適化ではない。", "近くの正解で多数決する分類で、最適化ではない。", "条件分岐で予測する手法で、勾配降下法ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='4. ディープラーニングの概要'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q24', 'Transformerで、1種類の注意だけでなく、複数の異なる観点の注意を同時に計算して組み合わせる仕組みはどれか。', NULL, '["マルチヘッドアテンション", "位置エンコーディング", "バッチ正規化", "ドロップアウト"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "複数の異なる観点の注意を同時に計算して組み合わせるTransformerの仕組みは？", "point": "「複数の観点の注意を同時に計算して組み合わせる」なら、マルチヘッドアテンション。", "kid": "自己注意は「どの単語に注目するか」を計算する。マルチヘッドアテンションは、それを1種類でなく、複数の異なる観点(文法的な関係・意味的な関係など)で同時に計算し、まとめて使う。多面的に文脈をとらえられる。", "eg": "一人の視点だけでなく、複数の専門家がそれぞれの観点で同じ文を読み、意見を持ち寄る、あの多面チェック。", "terms": [["マルチヘッドアテンション", "複数の異なる観点の注意を同時に計算して組み合わせる、Transformerの中核の仕組み"], ["自己注意", "同じ文の中で単語どうしの関係を測る仕組み。その1つの観点版"]], "think": "「複数の観点の注意を同時に」ならマルチヘッドアテンション。1つの注意を多面化した仕組みで、ノードを休ませるドロップアウトなどとは役割が違う。", "vs": "位置エンコーディングは語順を補う仕組み、バッチ正規化は各層の値をそろえる手法、ドロップアウトはノードを休ませる過学習対策で、いずれも複数観点の注意を計算するマルチヘッドアテンションではない。", "usecase": "Transformerや今のLLMの表現力を支える中核。多面的に単語の関係をとらえられるので、複雑な文脈理解に効く。", "opt": ["正解。複数の観点の注意を同時に計算して組み合わせるのがマルチヘッドアテンション。", "語順を補う仕組みで、複数観点の注意ではない。", "各層の値をそろえる手法で、注意の仕組みではない。", "ノードを休ませる過学習対策で、マルチヘッドアテンションではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q25', '単語やカテゴリなどを、意味の近さを反映した密なベクトルに変換し、その変換自体も学習で獲得する層はどれか。', NULL, '["埋め込み層", "プーリング層", "畳み込み層", "全結合層"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "単語などを意味の近さを反映した密なベクトルに変換し、その変換も学習する層は？", "point": "「単語などを、意味を反映した密なベクトルに変換し、その変換も学習する」なら、埋め込み層。", "kid": "単語をワンホット(1か所だけ1の疎なベクトル)にすると、意味の近さが表せない。埋め込み層は、単語を意味の近い語が近くに来る密なベクトルに変換する。しかもその変換の仕方も学習で獲得する。", "eg": "言葉を「意味の座標」に配置し直す係。使ううちに配置がどんどん的確になっていく、あの学習。", "terms": [["埋め込み層（Embedding層）", "単語などを、意味の近さを反映した密なベクトルに変換する層。変換自体も学習する"], ["分散表現", "意味の近さが距離に表れる密なベクトル表現。埋め込み層が作り出す"]], "think": "「意味を反映した密なベクトルに変換・変換も学習」なら埋め込み層。特徴を縮めるプーリングや、局所特徴を拾う畳み込みとは役割が違う。", "vs": "プーリング層は特徴を粗くまとめて縮める、畳み込み層は画像の局所特徴を拾う、全結合層は全ノードをつなぐ層で、いずれも単語を意味ベクトルに変換する埋め込み層ではない。", "usecase": "言語モデルや推薦システムの入り口で、単語やIDを意味を持つベクトルに変える定番の層。word2vecの考え方をネットワークに組み込んだもの。", "opt": ["正解。単語などを意味を反映した密なベクトルに変換し学習するのが埋め込み層。", "特徴を粗くまとめて縮める層で、意味ベクトルへの変換ではない。", "画像の局所特徴を拾う層で、埋め込み層ではない。", "全ノードをつなぐ層で、意味ベクトルへの変換ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
COMMIT;
BEGIN;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q26', '畳み込みとは逆に、小さな特徴マップを引き伸ばして大きな画像を作り出す（アップサンプリングする）操作で、画像生成などに使われるものはどれか。', NULL, '["転置畳み込み", "プーリング", "バッチ正規化", "ドロップアウト"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "小さな特徴マップを引き伸ばして大きな画像を作る操作は？", "point": "「特徴マップを引き伸ばして大きくする(アップサンプリング)」なら、転置畳み込み。", "kid": "ふつうの畳み込みやプーリングは画像を小さくしていく。転置畳み込みはその逆で、小さな特徴マップを引き伸ばして大きな画像に戻す。画像を生成したり、画素単位で塗り分けたりするときに使う。", "eg": "縮小したサムネイルから、元の大きさへ拡大して描き直す、あの引き伸ばし。", "terms": [["転置畳み込み", "小さな特徴マップを引き伸ばして大きくする操作。アップサンプリングに使う"], ["アップサンプリング", "解像度を上げて大きくすること。生成やセグメンテーションで必要になる"]], "think": "「小さいものを大きく引き伸ばす」なら転置畳み込み。特徴を縮めるプーリングとはちょうど逆向きの操作。", "vs": "プーリングは特徴を縮める逆の操作、バッチ正規化は各層の値をそろえる手法、ドロップアウトはノードを休ませる過学習対策で、いずれも引き伸ばす転置畳み込みではない。", "usecase": "画像生成(GANや拡散モデルのデコーダ)や、画素ごとに塗り分けるセグメンテーションで、小さな特徴を元の大きさに戻すのに使う。", "opt": ["正解。小さな特徴マップを引き伸ばして大きくするのが転置畳み込み。", "特徴を縮める逆の操作で、引き伸ばすものではない。", "各層の値をそろえる手法で、引き伸ばしではない。", "ノードを休ませる過学習対策で、転置畳み込みではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q27', '未知語や活用の多い言語に対応するため、単語をさらに小さな共通部品（例：「playing」を「play」＋「ing」）に分割する方法はどれか。', NULL, '["サブワード分割", "ワンホットエンコーディング", "データ拡張", "正規化"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "単語をさらに小さな共通部品に分けて、未知語に対応する方法は？", "point": "「単語をさらに小さな共通部品に分けて、未知語にも対応する」なら、サブワード分割。", "kid": "単語をそのまま扱うと、辞書にない未知語が出るたびに困る。そこで単語を「play＋ing」のような小さな共通部品(サブワード)に分けると、未知語も部品の組み合わせで表せる。これがサブワード分割。", "eg": "知らない言葉も、漢字やパーツに分ければ意味が推測できる、あの分解の発想。", "terms": [["サブワード分割", "単語をさらに小さな共通部品(サブワード)に分けて、未知語にも対応する方法。BPEなど"], ["形態素解析", "文を単語(形態素)に区切る前処理。サブワードはさらに細かい単位"]], "think": "「単語を小さな共通部品に分けて未知語に対応」ならサブワード分割。カテゴリをベクトル化するワンホットエンコーディングとは目的が違う。", "vs": "ワンホットエンコーディングはカテゴリを1か所だけ1のベクトルにする、データ拡張はデータの水増し、正規化は数値の範囲をそろえる処理で、いずれも単語を部品に分けるサブワード分割ではない。", "usecase": "今の言語モデル(BERTやGPTなど)がほぼ共通で使う入力の処理。未知語に強く、語彙の数を抑えられるのが利点。", "opt": ["正解。単語を小さな共通部品に分けて未知語に対応するのがサブワード分割。", "カテゴリをベクトルにする前処理で、単語を部品に分けるものではない。", "データの水増しで、単語の分割ではない。", "数値の範囲をそろえる処理で、サブワード分割ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q28', '1つのサンプルの中の特徴どうしをそろえて正規化する方法で、バッチの大きさに左右されにくく、系列データやTransformerで使われるものはどれか。', NULL, '["レイヤー正規化", "バッチ正規化", "ドロップアウト", "データ拡張"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "1サンプル内の特徴どうしをそろえて正規化し、Transformerで使われる方法は？", "point": "「1サンプルの中の特徴どうしをそろえて正規化する」なら、レイヤー正規化。", "kid": "バッチ正規化は「まとまり(バッチ)全体」で値をそろえるため、バッチが小さいと不安定。レイヤー正規化は「1つのサンプルの中の特徴どうし」でそろえるので、バッチの大きさに左右されない。系列やTransformerと相性がよい。", "eg": "クラス全体の平均でそろえる(バッチ正規化)のではなく、一人ひとりの答案の中で配点をそろえる(レイヤー正規化)、あの違い。", "terms": [["レイヤー正規化", "1つのサンプル内の特徴どうしをそろえて正規化する方法。バッチの大きさに左右されにくい"], ["バッチ正規化", "まとまり(バッチ)全体で値をそろえる方法。バッチが小さいと不安定になりやすい"]], "think": "「1サンプル内でそろえる・バッチに左右されない」ならレイヤー正規化。バッチ全体でそろえるバッチ正規化と、そろえる範囲が違う。", "vs": "バッチ正規化はバッチ全体で値をそろえる、ドロップアウトはノードを休ませる過学習対策、データ拡張はデータの水増しで、いずれも1サンプル内でそろえるレイヤー正規化ではない。", "usecase": "系列データやTransformerのように、バッチの大きさが揺れたり系列長が違ったりする場面で使う。今のLLMの標準的な部品。", "opt": ["正解。1サンプル内の特徴どうしをそろえて正規化するのがレイヤー正規化。", "バッチ全体で値をそろえる方法で、そろえる範囲が違う。", "ノードを休ませる過学習対策で、正規化ではない。", "データの水増しで、正規化ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q29', '画像認識で使う畳み込みニューラルネットワーク（CNN）の典型的な構成として、最も適切なものはどれか。', NULL, '["畳み込みとプーリングで特徴を抽出し、全結合層で分類する", "全結合層だけを何層も積み重ねて画像を処理する構成", "系列を前から1時点ずつ処理する回帰結合層だけで構成する", "入力をそのまま出力するだけの層を並べた構成"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "画像認識で使うCNNの典型的な構成は？", "point": "「畳み込みとプーリングで特徴を抽出→全結合層で分類」なら、CNNの典型構成。", "kid": "CNNは、畳み込み層(線や角などの特徴を拾う)とプーリング層(縮めて位置ずれに強くする)を交互に重ねて特徴を抽出し、最後に全結合層でまとめて「何の画像か」を分類する。この流れが基本。", "eg": "まず素材の特徴を下ごしらえ(畳み込み・プーリング)して、最後に全部を合わせて味を決める(全結合層で判定)、あの調理の流れ。", "terms": [["CNN（畳み込みニューラルネットワーク）", "畳み込み層・プーリング層で特徴を抽出し、全結合層で分類する、画像認識向けのネットワーク"], ["畳み込み層／プーリング層", "特徴を拾う層と、縮めて位置ずれに強くする層"]], "think": "「畳み込み＋プーリングで特徴抽出→全結合で分類」がCNNの基本構成。全結合だけ・回帰結合だけ、では画像の特徴をうまく拾えない。", "vs": "全結合層だけでは局所特徴を効率よく拾えず、回帰結合層だけは系列向けで画像には不向き、入力をそのまま出す層だけでは何も学べず、いずれもCNNの典型構成ではない。", "usecase": "画像分類・物体検出・顔認証など、画像を扱うAIの基本形。この構成を土台に、より深い・工夫された構造へ発展した。", "opt": ["正解。畳み込みとプーリングで特徴を抽出し、全結合層で分類するのがCNN。", "全結合層だけでは局所特徴を効率よく拾えず、画像向けの構成ではない。", "回帰結合層は系列向けで、画像認識の典型構成ではない。", "入力をそのまま出すだけでは何も学べず、CNNではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='5. ディープラーニングの要素技術'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q30', '低い解像度のぼやけた画像から、細部を補って高い解像度の鮮明な画像を作り出すタスクはどれか。', NULL, '["超解像", "画像分類", "異常検知", "感情分析"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "低解像度のぼやけた画像を、高解像度の鮮明な画像にするタスクは？", "point": "「ぼやけた低解像度画像を、鮮明な高解像度画像にする」なら、超解像。", "kid": "ぼやけて粗い画像から、失われた細部を推測して補い、くっきりした高解像度の画像を作り出すタスク。古い写真の高画質化などに使う。", "eg": "粗い証明写真を、細部を補ってくっきり引き伸ばす、あの高画質化。", "terms": [["超解像", "低解像度の画像から細部を補い、高解像度の鮮明な画像を作り出すタスク"], ["転置畳み込み", "小さな特徴を引き伸ばす操作。超解像の中で使われることがある"]], "think": "「ぼやけを鮮明に高解像度化」なら超解像。写真全体に1ラベルの画像分類や、外れ値を見つける異常検知とは目的が違う。", "vs": "画像分類は写真全体に1ラベルを付ける、異常検知は普段と違うものを見つける、感情分析は文章の気持ちを判定するタスクで、いずれも画像を高解像度化する超解像ではない。", "usecase": "古い写真や監視カメラ映像の高画質化、医療画像の鮮明化などで使う。細部を推測して補うので、無い情報を作る点には注意。", "opt": ["正解。低解像度の画像を高解像度の鮮明な画像にするのが超解像。", "写真全体に1ラベルを付けるタスクで、高解像度化ではない。", "普段と違うものを見つけるタスクで、超解像ではない。", "文章の気持ちを判定するタスクで、画像の高解像度化ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q31', '写真の「内容（何が写っているか）」はそのままに、有名絵画などの「画風」だけを移して別の絵のように変換するタスクはどれか。', NULL, '["スタイル変換", "物体検出", "セグメンテーション", "超解像"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "内容はそのままに、画風だけを別の絵に移すタスクは？", "point": "「内容はそのまま、画風だけを別の絵に移す」なら、スタイル変換。", "kid": "写真に写っているもの(内容)は変えずに、ゴッホ風・水彩風といった「画風(スタイル)」だけを移し替えて、別の絵のように見せるタスク。", "eg": "同じ風景写真を、油絵風・アニメ風など、絵のタッチだけ変えて描き直す、あの加工。", "terms": [["スタイル変換", "画像の内容はそのままに、別の画像の画風(スタイル)だけを移すタスク"], ["超解像", "解像度を上げて鮮明にする別のタスク。画風は変えない"]], "think": "「内容そのまま・画風だけ変える」ならスタイル変換。物を枠で囲む物体検出や、鮮明化する超解像とは目的が違う。", "vs": "物体検出は種類と位置を枠で囲む、セグメンテーションは画素を塗り分ける、超解像は解像度を上げるタスクで、いずれも画風だけを移すスタイル変換ではない。", "usecase": "写真アプリの画風フィルタや、イラスト制作の補助などで使う。生成AIの表現の幅を広げる応用の一つ。", "opt": ["正解。内容はそのままに画風だけを別の絵に移すのがスタイル変換。", "種類と位置を枠で囲むタスクで、画風を移すものではない。", "画素を塗り分けるタスクで、スタイル変換ではない。", "解像度を上げるタスクで、画風は変えない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q32', '文字（テキスト）を入力として、人の声のような音声を作り出すタスクはどれか。', NULL, '["音声合成", "音声認識", "画像生成", "形態素解析"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "文字を入力に、人の声のような音声を作り出すタスクは？", "point": "「文字から人の声を作り出す」なら、音声合成。", "kid": "「おはよう」という文字を入れると、人の声で「おはよう」と読み上げる音声を作るタスク。文字→声の向き。逆の、声→文字は音声認識。", "eg": "書いた文章を、人の声で読み上げてくれる、あの読み上げ機能。", "terms": [["音声合成", "文字を入力に、人の声のような音声を作り出すタスク。文字→声"], ["音声認識", "音声を受け取り文字に書き起こすタスク。音声合成と向きが逆"]], "think": "「文字から声を作る(文字→声)」なら音声合成。声を文字にする音声認識とは向きが逆、と押さえる。", "vs": "音声認識は声を文字にする(向きが逆)、画像生成は画像を作るタスク、形態素解析は文を単語に区切る前処理で、いずれも文字から声を作る音声合成ではない。", "usecase": "読み上げアプリ、カーナビや駅の案内放送、バーチャルアシスタントの発話などで使う身近な技術。", "opt": ["正解。文字から人の声を作り出すのが音声合成。", "声を文字にするタスクで、向きが逆。", "画像を作るタスクで、音声の合成ではない。", "文を単語に区切る前処理で、音声合成ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q33', '文章の中から、人名・地名・組織名・日付といった特定の種類の語句を見つけ出してラベルを付けるタスクはどれか。', NULL, '["固有表現抽出", "感情分析", "機械翻訳", "音声認識"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "文中から人名・地名・日付などを見つけてラベルを付けるタスクは？", "point": "「文中から人名・地名・組織名・日付などを抜き出す」なら、固有表現抽出。", "kid": "文章の中から「人名」「地名」「会社名」「日付」といった、特定の種類の言葉を見つけ出して印を付けるタスク。「山田さんが東京で…」なら山田＝人名、東京＝地名、と抜き出す。", "eg": "契約書に蛍光ペンで、人名・会社名・金額・日付だけをマークしていく、あの作業の自動化。", "terms": [["固有表現抽出", "文中から人名・地名・組織名・日付などの特定種類の語句を見つけ、ラベルを付けるタスク"], ["自然言語処理", "言葉をコンピュータで扱う分野。固有表現抽出はその代表タスクの一つ"]], "think": "「特定種類の語句を文中から抜き出す」なら固有表現抽出。文全体の気持ちを判定する感情分析とは、出力の粒度が違う。", "vs": "感情分析は文章の気持ちを判定する、機械翻訳は別の言語に訳す、音声認識は声を文字にするタスクで、いずれも特定語句を抜き出す固有表現抽出ではない。", "usecase": "契約書や医療記録からの情報抽出、ニュースの自動整理、検索の精度向上などで使う。大量の文書から必要な項目を拾える。", "opt": ["正解。文中から人名・地名などを見つけてラベルを付けるのが固有表現抽出。", "文章の気持ちを判定するタスクで、語句の抜き出しではない。", "別の言語に訳すタスクで、固有表現抽出ではない。", "声を文字にするタスクで、語句の抽出ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q34', '利用者の過去の行動や、好みの似た他の利用者の行動をもとに、その人が気に入りそうな商品や動画を推薦する仕組みはどれか。', NULL, '["レコメンデーション", "異常検知", "固有表現抽出", "データ拡張"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "好みの似た人の行動などから、気に入りそうなものを推薦する仕組みは？", "point": "「過去の行動や似た利用者から、気に入りそうなものを推薦する」なら、レコメンデーション。", "kid": "あなたが見た・買った履歴や、あなたと好みの似た人が気に入ったものをもとに、「これも好きでは?」とおすすめする仕組み。通販や動画サイトの「あなたへのおすすめ」がこれ。", "eg": "気の合う友達が「これ良かったよ」と勧めてくれる、あのおすすめを自動でやる仕組み。", "terms": [["レコメンデーション", "利用者の行動や、好みの似た利用者の行動から、気に入りそうなものを推薦する仕組み"], ["協調フィルタリング", "似た好みの利用者の行動をもとに推薦する、代表的なレコメンドの方式"]], "think": "「行動履歴や似た人からおすすめ」ならレコメンデーション。外れ値を見つける異常検知や、語句を抜き出す固有表現抽出とは目的が違う。", "vs": "異常検知は普段と違うものを見つける、固有表現抽出は文中の特定語句を抜き出す、データ拡張はデータの水増しで、いずれもおすすめするレコメンデーションではない。", "usecase": "通販・動画・音楽・ニュースなどで「あなたへのおすすめ」を出すのに使う。売上や満足度を高める一方、フィルターバブルの一因にもなる。", "opt": ["正解。行動履歴や似た利用者から気に入りそうなものを推薦するのがレコメンデーション。", "普段と違うものを見つけるタスクで、おすすめではない。", "文中の特定語句を抜き出すタスクで、レコメンデーションではない。", "データの水増しで、推薦の仕組みではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q35', '印刷物や手書きの画像の中に写っている文字を読み取り、編集できるテキストデータに変換する技術はどれか。', NULL, '["OCR", "音声認識", "画像生成", "感情分析"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "画像中の文字を読み取って、編集できるテキストにする技術は？", "point": "「画像の中の文字を読み取ってテキストにする」なら、OCR。", "kid": "紙の書類や看板の写真に写っている文字を、機械が読み取って、コピーや検索ができるテキストデータに変換する技術。スキャンした書類の文字起こしなどに使う。", "eg": "紙の資料をスマホで撮ると、中の文字を読み取ってそのままコピーできる、あの機能。", "terms": [["OCR（光学的文字認識）", "画像中の文字を読み取り、編集できるテキストデータに変換する技術"], ["音声認識", "音声を文字にする別のタスク。OCRは画像から文字を読み取る"]], "think": "「画像の中の文字を読み取ってテキストに」ならOCR。声を文字にする音声認識とは、入力が画像か音声かで違う。", "vs": "音声認識は声を文字にする、画像生成は画像を作る、感情分析は文章の気持ちを判定するタスクで、いずれも画像中の文字を読み取るOCRではない。", "usecase": "紙の書類の電子化、名刺や領収書の読み取り、車のナンバー認識などで使う。大量の紙情報をデータ化するのに役立つ。", "opt": ["正解。画像中の文字を読み取ってテキストにするのがOCR。", "声を文字にするタスクで、画像中の文字を読むものではない。", "画像を作るタスクで、文字の読み取りではない。", "文章の気持ちを判定するタスクで、OCRではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q36', '「夕焼けの海辺を走る犬」のような文章による指示から、その内容に合った画像を新しく作り出すタスクはどれか。', NULL, '["テキストからの画像生成", "画像からの説明文生成", "画像のスタイル変換", "画像の高解像度化"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "文章の指示から、その内容に合った画像を新しく作るタスクは？", "point": "「文章の指示から、内容に合った画像を新しく作る」なら、テキストからの画像生成。", "kid": "「夕焼けの海辺を走る犬」のような文章を入れると、その内容の画像を新しく描き起こすタスク。文章(テキスト)→画像の向き。Stable DiffusionやDALL-Eが代表。", "eg": "注文(文章)を伝えると、その通りの絵を描いてくれる絵描きさん、あのイメージ。", "terms": [["テキストからの画像生成", "文章の指示から、その内容に合った画像を新しく生成するタスク。text-to-image"], ["拡散モデル", "ノイズを取り除いて画像を作る手法。テキストからの画像生成の主流"]], "think": "「文章から画像を新しく作る」ならテキストからの画像生成。逆の「画像から説明文」は画像キャプション生成で、向きが逆。", "vs": "画像からの説明文生成は画像から文章で向きが逆、スタイル変換は画風だけ変える、高解像度化は鮮明にするタスクで、いずれも文章から画像を作るテキストからの画像生成ではない。", "usecase": "イラスト・デザイン・広告素材の制作などで使う、今の生成AIの代表的な応用。拡散モデルの発展で急速に実用化した。", "opt": ["正解。文章の指示から内容に合った画像を新しく作るのがテキストからの画像生成。", "画像から説明文を作るタスクで、向きが逆。", "画風だけを変えるタスクで、新しく作るのとは違う。", "画像を鮮明にするタスクで、文章からの生成ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='6. ディープラーニングの応用例'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q37', '新しいモデルや施策を、一部の利用者にだけ従来のものと出し分け、成果を比べてどちらが良いかを判断する方法はどれか。', NULL, '["A/Bテスト", "交差検証", "グリッドサーチ", "データ拡張"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "新モデルを一部の利用者に出し分け、成果を比べて判断する方法は？", "point": "「一部の利用者に出し分けて、成果を比べてどちらが良いか判断する」なら、A/Bテスト。", "kid": "新しいモデルや施策が本当に良いかは、実際に試さないと分からない。そこで一部の利用者にだけ新しい方を出し、残りには従来の方を出して、成果(クリック率や売上など)を比べる。これがA/Bテスト。", "eg": "2種類のチラシを別々のお客に配って、どちらが反応が良かったか比べる、あの実地テスト。", "terms": [["A/Bテスト", "新しい案を一部の利用者に出し分け、従来の案と成果を比べて良い方を選ぶ方法"], ["オフライン評価", "過去データだけで測る評価。A/Bテストは実際の利用者で確かめる点が違う"]], "think": "「実際の利用者に出し分けて成果を比較」ならA/Bテスト。過去データで測る交差検証や、設定値を探すグリッドサーチとは、確かめる場が違う。", "vs": "交差検証は過去データでモデルを評価する方法、グリッドサーチは設定値を探す方法、データ拡張はデータの水増しで、いずれも実際の利用者で比べるA/Bテストではない。", "usecase": "新モデルを本番に出す前後で「本当に効果があるか」を実地で確かめるのに使う。思い込みでなくデータで判断する運用の要。", "opt": ["正解。一部の利用者に出し分けて成果を比べるのがA/Bテスト。", "過去データでモデルを評価する方法で、実利用者での比較ではない。", "設定値を探す方法で、成果の出し分け比較ではない。", "データの水増しで、A/Bテストではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='7. AIの社会実装に向けて'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q38', 'AIにすべてを任せきりにせず、重要な判断には人間が関与・確認して、AIと人が協力して進める仕組みはどれか。', NULL, '["ヒューマン・イン・ザ・ループ", "エンドツーエンド学習", "フルオートメーション", "バッチ処理"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "重要な判断に人間が関与・確認して、AIと人が協力して進める仕組みは？", "point": "「重要な判断に人が関与・確認し、AIと人が協力する」なら、ヒューマン・イン・ザ・ループ。", "kid": "AIに全部任せると、間違いをそのまま実行してしまう危険がある。そこで大事な判断には人間が入って確認・修正し、AIと人が協力して進める。この人が関わる仕組みがヒューマン・イン・ザ・ループ。", "eg": "自動運転でも最終的にドライバーが確認・介入できるようにしておく、あの“人が最後の砦”の考え方。", "terms": [["ヒューマン・イン・ザ・ループ", "重要な判断に人間が関与・確認し、AIと人が協力して進める仕組み"], ["自動化のトレードオフ", "全自動は速いが誤りを止めにくい。人が関わると安全だが手間が増える"]], "think": "「重要な判断に人が関与・AIと協力」ならヒューマン・イン・ザ・ループ。人を挟まず全自動にするフルオートメーションとは考え方が逆。", "vs": "エンドツーエンド学習は入力から出力まで一気に学ぶ手法、フルオートメーションは人を挟まない全自動、バッチ処理はまとめて一括処理する方式で、いずれも人が関与するヒューマン・イン・ザ・ループではない。", "usecase": "医療診断・与信・採用など、誤りが重大な場面で使う。AIが候補を出し、最終判断は人が行うことで、精度と責任のバランスを取る。", "opt": ["正解。重要な判断に人が関与しAIと協力するのがヒューマン・イン・ザ・ループ。", "入力から出力まで一気に学ぶ手法で、人の関与の仕組みではない。", "人を挟まない全自動で、人が関与する考え方とは逆。", "まとめて一括処理する方式で、人の関与の仕組みではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='7. AIの社会実装に向けて'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
COMMIT;
BEGIN;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q39', '学習済みのモデルに新しいデータを入れて、実際に予測や判断の結果を出す段階を指す語はどれか。', NULL, '["推論", "学習", "アノテーション", "デプロイ"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "学習済みモデルに新しいデータを入れて、予測結果を出す段階は？", "point": "「学習済みモデルを使って、実際に予測結果を出す段階」なら、推論。", "kid": "モデル作りには2つの段階がある。データからパターンを覚える「学習」と、覚えたモデルに新しいデータを入れて実際に答えを出す「推論」。運用中に毎回行うのは推論の方。", "eg": "教科書で勉強するのが学習、本番の試験で問題に答えるのが推論、あの区別。", "terms": [["推論（インファレンス）", "学習済みモデルに新しいデータを入れ、予測や判断の結果を出す段階"], ["学習（トレーニング）", "データからパターンを学び、モデルを作る段階。推論の前段"]], "think": "「学習済みモデルで実際に答えを出す」なら推論。データから覚える学習とは、段階が違う。運用で繰り返すのは推論。", "vs": "学習はモデルを作る段階、アノテーションは正解ラベルを付ける作業、デプロイはモデルを本番に配置することで、いずれも予測結果を出す推論そのものではない。", "usecase": "運用中のAIが毎回行う処理。推論を速く・安く行えるかが、実用サービスの応答速度やコストを左右する(だからモデルの軽量化が重要)。", "opt": ["正解。学習済みモデルで実際に予測結果を出す段階が推論。", "データからパターンを学びモデルを作る段階で、結果を出す推論ではない。", "正解ラベルを付ける作業で、推論ではない。", "モデルを本番に配置することで、予測を出す推論そのものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='7. AIの社会実装に向けて'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q40', '回帰モデルの評価で、予測値と正解値の差を二乗して平均した、値が小さいほど良い誤差指標はどれか。', NULL, '["平均二乗誤差", "混同行列", "ROC曲線とAUC", "交差エントロピー誤差"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "回帰で、予測と正解の差を二乗して平均した、小さいほど良い誤差指標は？", "point": "「回帰で、予測と正解の差を二乗して平均した誤差」なら、平均二乗誤差(MSE)。", "kid": "回帰(数値予測)の成績を測るとき、予測と正解のズレを二乗して平均する。二乗するので大きな外れを重く見る。値が小さいほど良い。これが平均二乗誤差。", "eg": "射的で、的の中心からの外れ具合を二乗して平均し、外れが大きいほど大きく減点する、あの採点。", "terms": [["平均二乗誤差（MSE）", "予測と正解の差を二乗して平均した、回帰の誤差指標。小さいほど良い"], ["決定係数（R²）", "回帰モデルがデータの動きをどれだけ説明できるかを表す指標。1に近いほど良い"]], "think": "「回帰・差を二乗して平均・小さいほど良い」なら平均二乗誤差。分類の成績を測る正解率や適合率とは、対象(数値予測か分類か)が違う。", "vs": "混同行列は分類結果の集計表、ROC曲線とAUCは分類の性能曲線、交差エントロピー誤差は分類の損失で、いずれも回帰の誤差を測る平均二乗誤差ではない。", "usecase": "売上や価格などの数値予測モデルの評価・学習の目印に使う。大きな外れを重く見るので、外れ値に敏感な点に注意。", "opt": ["正解。予測と正解の差を二乗して平均した回帰の誤差が平均二乗誤差。", "分類結果の集計表で、回帰の誤差指標ではない。", "分類の性能曲線と面積で、回帰の誤差ではない。", "分類の損失で、回帰の誤差そのものではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='8. AIに必要な数理・統計知識'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q41', '回帰モデルが、データの動き（ばらつき）をどれくらいうまく説明できているかを、1に近いほど良いとして表す指標はどれか。', NULL, '["決定係数", "再現率", "混同行列", "標準偏差"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "回帰モデルがデータの動きをどれだけ説明できるかを1に近いほど良いと表す指標は？", "point": "「回帰で、データの動きをどれだけ説明できるかを1に近いほど良いと表す」なら、決定係数(R²)。", "kid": "回帰モデルが、データのばらつき(動き)をどれくらい言い当てられているかを表す指標。1に近いほど「よく説明できている」、0に近いと「ほとんど説明できていない」。", "eg": "テストの点のばらつきを、勉強時間でどれだけ説明できるか。ぴったり説明できれば1に近い、あの当てはまり具合。", "terms": [["決定係数（R²）", "回帰モデルがデータの動き(ばらつき)をどれだけ説明できるかを表す指標。1に近いほど良い"], ["平均二乗誤差（MSE）", "予測と正解の差を二乗して平均した誤差。小さいほど良い"]], "think": "「回帰・当てはまりの良さ・1に近いほど良い」なら決定係数。誤差の大きさを測る平均二乗誤差とは、見る角度が違う(説明力か、ズレの大きさか)。", "vs": "再現率は分類で見落としの少なさを表す指標、混同行列は分類結果の集計表、標準偏差はデータの散らばりの大きさで、いずれも回帰の説明力を表す決定係数ではない。", "usecase": "回帰モデルの「当てはまりの良さ」を一目で伝えるのに使う。ただし項目を増やすと見かけ上上がりやすい点には注意が要る。", "opt": ["正解。回帰の当てはまりの良さを1に近いほど良いと表すのが決定係数。", "分類で見落としの少なさを表す指標で、回帰の説明力ではない。", "分類結果の集計表で、決定係数ではない。", "データの散らばりの大きさで、当てはまりの良さではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='8. AIに必要な数理・統計知識'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q42', '2つのベクトルが「同じ向きをどれだけ向いているか」で、文書や単語の似ている度合いを測る指標はどれか。', NULL, '["コサイン類似度", "平均二乗誤差", "混同行列", "学習率"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "2つのベクトルの向きの近さで、文書や単語の似ている度合いを測る指標は？", "point": "「2つのベクトルの向きの近さで似ている度合いを測る」なら、コサイン類似度。", "kid": "文書や単語を数値のベクトルにしたとき、その2つが「同じ向きを向いているか」で似ている度合いを測る。向きがそろうほど1に近く(似ている)、直角なら0(無関係)。長さより向きを重視する。", "eg": "2本の矢印が同じ方向を指していれば「似ている」、直角なら「無関係」と判断する、あの向きの比べ方。", "terms": [["コサイン類似度", "2つのベクトルのなす角度(向きの近さ)で、似ている度合いを測る指標。1に近いほど似ている"], ["分散表現", "単語などを意味を反映したベクトルにしたもの。コサイン類似度で近さを測れる"]], "think": "「ベクトルの向きの近さで類似度」ならコサイン類似度。誤差を測る平均二乗誤差や、分類の集計表の混同行列とは目的が違う。", "vs": "平均二乗誤差は回帰の誤差指標、混同行列は分類結果の集計表、学習率は更新の歩幅で、いずれもベクトルの向きの近さを測るコサイン類似度ではない。", "usecase": "検索・レコメンド・文書分類で、単語や文書の似ている度合いを測るのに使う。長さの影響を受けにくいのが利点。", "opt": ["正解。2つのベクトルの向きの近さで似ている度合いを測るのがコサイン類似度。", "回帰の誤差指標で、ベクトルの向きの近さではない。", "分類結果の集計表で、類似度の指標ではない。", "更新の歩幅を決める値で、類似度ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='8. AIに必要な数理・統計知識'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q43', '起こりうる結果の値それぞれに、その起こりやすさ（確率）で重みをつけて足し合わせた、平均的に見込まれる値を指す語はどれか。', NULL, '["期待値", "中央値", "標準偏差", "最頻値"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "起こりうる値に確率で重みをつけて足した、平均的に見込まれる値は？", "point": "「起こりうる値に確率で重みをつけて足した、平均的に見込まれる値」なら、期待値。", "kid": "サイコロで出る目は1〜6。それぞれ1/6の確率で起きる。値×確率を全部足すと「平均的にどれくらいの値が見込めるか」が分かる。これが期待値。ギャンブルの損得計算などに使う。", "eg": "宝くじの「1枚あたり平均でいくら戻ってくるか」を、当選金×当たる確率を足して見積もる、あの計算。", "terms": [["期待値", "起こりうる値に、その確率で重みをつけて足し合わせた、平均的に見込まれる値"], ["確率", "ある結果の起こりやすさ。期待値の重みになる"]], "think": "「値×確率を足した平均的な見込み」なら期待値。データを並べた真ん中の中央値や、散らばりの標準偏差とは意味が違う。", "vs": "中央値はデータを並べた真ん中の値、標準偏差は散らばりの大きさ、最頻値は最も多く現れる値で、いずれも確率で重みづけした期待値ではない。", "usecase": "リスクとリターンの見積もり、保険や投資の判断、強化学習で「その行動で見込める報酬」を測るときなどに使う、意思決定の基礎。", "opt": ["正解。値に確率で重みをつけて足した平均的な見込みが期待値。", "データを並べた真ん中の値で、確率で重みづけした見込みではない。", "散らばりの大きさで、平均的な見込みではない。", "最も多く現れる値で、期待値ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='8. AIに必要な数理・統計知識'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q44', '著作権が保護する対象について正しいのはどれか。', NULL, '["アイデアそのものでなく、具体的な表現を保護する", "アイデアも表現も、区別なくすべて保護する", "表現ではなく、アイデアそのものを保護する", "公表されたものは、著作権では保護されない"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "著作権が保護する対象は？", "point": "「著作権は、アイデアそのものでなく、具体的に表現されたものを守る」（アイデア・表現二分論）。", "kid": "著作権は「作品として具体的に表現されたもの」を守るが、その背後にある「アイデアや作風・手法そのもの」は守らない。だから同じテーマでも、表現が違えば別々に著作権が認められる。", "eg": "「猫を主役にした物語を書く」というアイデアは誰でも使えるが、実際に書き上げた文章そのものは、その人の著作物として守られる、あの線引き。", "terms": [["アイデア・表現二分論", "著作権はアイデアそのものでなく、具体的に表現されたものを保護するという考え方"], ["著作物", "人が思想や感情を創作的に表現したもの。著作権の保護対象"]], "think": "判断の軸は「アイデアか、具体的な表現か」。守られるのは表現の方。アイデアや手法そのものは自由に使える、が原則。", "vs": "「アイデアも表現もすべて保護」「アイデアそのものを保護」はいずれも誤りで、守るのは表現の方。「公表されたものは保護されない」も誤りで、公表の有無に関わらず表現は保護される。", "usecase": "AIの学習や、似たテーマの作品を作るときに「どこまでが自由で、どこからが侵害か」を判断する土台。アイデアの共有と表現の保護を分けて考える。", "opt": ["正解。アイデアそのものでなく、具体的な表現を保護する。", "アイデアは保護対象外なので、区別なくすべて保護するのは誤り。", "守るのは表現の方で、アイデアそのものを保護するのは誤り。", "公表の有無に関わらず表現は保護されるので、誤り。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='9. AIに関する法律と契約'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q45', '会社の従業員が、職務として会社名義で作成した著作物について、原則として著作者となるのは誰か（職務著作）。', NULL, '["会社（法人）", "作成した従業員個人", "委託先のベンダ", "国"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "従業員が職務で会社名義で作った著作物の、原則の著作者は？", "point": "「従業員が職務として会社名義で作った著作物は、原則として会社が著作者」なら、職務著作。", "kid": "会社員が、仕事として会社の名義で作った文章やプログラムなどは、原則としてその会社が著作者になる。作った本人ではなく会社に権利がある、という決まり(一定の要件あり)。", "eg": "会社の広報担当が作った社内資料は、担当者個人でなく会社のもの、あの扱い。", "terms": [["職務著作", "従業員が職務として会社名義で作った著作物は、原則として会社が著作者になる制度"], ["著作者", "著作物を創作した者。通常は作った本人だが、職務著作では会社になる"]], "think": "「職務・会社名義で作成」なら原則として会社が著作者。作った本人が当然に著作者になるとは限らない点がポイント。", "vs": "作成した従業員個人は、職務著作の要件を満たす場合は原則として著作者にならない。委託先のベンダや国も、この場面で自動的に著作者になるわけではない。", "usecase": "企業でAI関連の成果物や資料を作るとき、権利が会社にあるのか個人にあるのかを判断する基本。契約や社内規程の前提知識になる。", "opt": ["正解。職務として会社名義で作った著作物は、原則として会社が著作者。", "職務著作の要件を満たせば、作った本人は原則として著作者にならない。", "委託先のベンダが自動的に著作者になるわけではない。", "国が著作者になる場面ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='9. AIに関する法律と契約'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q46', '完成物を最初に約束しにくいAI開発の特性をふまえ、アセスメント・PoC・開発・追加学習といった段階に分けて契約を進める考え方はどれか。', NULL, '["探索的段階型の開発方式", "完成保証型の一括請負", "著作権の集中管理", "オープンソースライセンス"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "AI開発を、段階に分けて契約を進める考え方は？", "point": "「完成を最初に約束しにくいAI開発を、段階に分けて契約する」なら、探索的段階型の開発方式。", "kid": "AI開発は、やってみないと精度や実現性が読めない。だから最初に完成物を固く約束するのでなく、「調査→小さく試す(PoC)→開発→追加学習」と段階に分け、各段階の結果を見て次に進むか決める契約にする。", "eg": "家を建てる前に、まず地質調査→模型で検討→本工事、と段階を踏んで、都度判断する、あの進め方。", "terms": [["探索的段階型の開発方式", "AI開発を、アセスメント・PoC・開発・追加学習などの段階に分けて契約を進める考え方"], ["PoC", "本開発の前に小さく試して実現性を確かめる工程。この段階の一つ"]], "think": "「最初に完成を約束せず、段階に分けて進める」なら探索的段階型。成果を固く約束する一括請負とは、AIの不確実性への向き合い方が逆。", "vs": "完成保証型の一括請負は成果を最初に固く約束する方式でAIには馴染みにくい、著作権の集中管理は権利の管理の話、オープンソースライセンスはソフトの利用条件で、いずれも段階に分けて進める探索的段階型ではない。", "usecase": "AI開発を発注・受注するときの契約設計の考え方。不確実性の高いAIで、途中の結果を見ながらリスクを抑えて進めるのに使う。", "opt": ["正解。段階に分けて契約を進めるのが探索的段階型の開発方式。", "成果を最初に固く約束する方式で、AIの不確実性には馴染みにくい。", "権利の管理の話で、開発の進め方の契約方式ではない。", "ソフトの利用条件で、AI開発の契約方式ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='9. AIに関する法律と契約'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q47', 'AIがどのようなデータで作られ、どのような仕組みで判断しているかを、利用者や社会に対して開示し、検証できるようにするAI倫理上の考え方はどれか。', NULL, '["透明性", "公平性", "頑健性", "効率性"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "AIの作られ方や判断の仕組みを開示し、検証できるようにする考え方は？", "point": "「AIの作られ方や判断の仕組みを開示し、検証できるようにする」なら、透明性。", "kid": "AIが「どんなデータで、どういう仕組みで判断しているか」を、利用者や社会に分かるように開示すること。中身がブラックボックスのままだと信頼できないので、見えるようにする。これが透明性。", "eg": "料理店が、使う食材や調理法をきちんと開示して、客が安心して選べるようにする、あの姿勢。", "terms": [["透明性", "AIの作られ方や判断の仕組みを開示し、利用者や社会が検証できるようにする考え方"], ["説明可能なAI（XAI）", "判断根拠を人に分かる形で示す技術。透明性を支える"]], "think": "「作られ方や仕組みを開示・検証可能に」なら透明性。差別をしない公平性や、攻撃に強い頑健性とは、別の価値。", "vs": "公平性は特定の属性に不当な差をつけないこと、頑健性は攻撃や外乱に強いこと、効率性は少ない資源で動くことで、いずれも仕組みを開示する透明性ではない。", "usecase": "AIガバナンスの基本原則の一つ。特に人の権利に関わる判断で、開示と検証ができることが信頼と受け入れの前提になる。", "opt": ["正解。作られ方や判断の仕組みを開示し検証できるようにするのが透明性。", "特定の属性に不当な差をつけないことで、開示の話ではない。", "攻撃や外乱に強いことで、透明性とは別の価値。", "少ない資源で動くことで、開示の考え方ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='10. AI倫理・AIガバナンス'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q48', 'AIの判断によって問題が起きたとき、その責任の所在を明確にし、関係者が説明できるようにしておくべきだ、というAIガバナンス上の考え方はどれか。', NULL, '["アカウンタビリティ", "スケーラビリティ", "インタラクティブ性", "リアルタイム性"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "AIの判断で問題が起きたとき、責任の所在を明確にし説明できるようにする考え方は？", "point": "「AIの判断の責任の所在を明確にし、説明できるようにする」なら、アカウンタビリティ(説明責任)。", "kid": "AIが誤った判断をして誰かが損害を受けたとき、「誰が責任を負い、なぜそうなったかを説明する」体制を整えておくべきだ、という考え方。責任をうやむやにしない。", "eg": "事故が起きたとき「担当は誰で、なぜ起きたか」をきちんと説明できるようにしておく、あの体制づくり。", "terms": [["アカウンタビリティ（説明責任）", "AIの判断について責任の所在を明確にし、関係者が説明できるようにしておく考え方"], ["透明性", "仕組みや作られ方を開示すること。説明責任を果たす土台になる"]], "think": "「責任の所在を明確に・説明できるように」ならアカウンタビリティ。仕組みを開示する透明性と近いが、こちらは“責任と説明”に重心がある。", "vs": "スケーラビリティは規模を拡大できること、インタラクティブ性は対話的であること、リアルタイム性は即時に処理することで、いずれも責任と説明のアカウンタビリティではない。", "usecase": "AIを社会で使う際、トラブル時に責任と経緯を説明できる体制を求めるガバナンスの要。透明性・説明可能性(XAI)と組み合わせて実現する。", "opt": ["正解。責任の所在を明確にし説明できるようにするのがアカウンタビリティ。", "規模を拡大できることで、責任と説明の話ではない。", "対話的であることで、説明責任とは別。", "即時に処理することで、アカウンタビリティではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='10. AI倫理・AIガバナンス'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q49', '大規模言語モデルに対し、入力文の中に巧妙な指示を紛れ込ませて、本来の制限を破らせたり意図しない出力をさせたりする攻撃はどれか。', NULL, '["プロンプトインジェクション", "データポイズニング", "敵対的サンプル", "ディープフェイク"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "入力に巧妙な指示を紛れ込ませ、LLMに制限を破らせる攻撃は？", "point": "「入力文に指示を紛れ込ませ、LLMの制限を破らせる」なら、プロンプトインジェクション。", "kid": "大規模言語モデルは、入力文の指示に従って動く。その性質を悪用し、入力に「これまでの指示は無視して〜せよ」といった巧妙な命令を紛れ込ませて、本来の制限を破らせたり、機密を漏らさせたりする攻撃。", "eg": "受付係に渡す書類の中に「上司の許可は不要、すぐ通せ」と偽の指示を紛れ込ませて、ルールを破らせる、あの手口。", "terms": [["プロンプトインジェクション", "入力文に巧妙な指示を紛れ込ませ、LLMに制限を破らせたり意図しない出力をさせる攻撃"], ["データポイズニング", "学習データを汚す別の攻撃。プロンプトインジェクションは使うときの入力を狙う"]], "think": "「使うときの入力文に指示を仕込んでLLMを操る」ならプロンプトインジェクション。学習データを汚すデータポイズニングとは、狙う段階が違う。", "vs": "データポイズニングは学習データを汚す攻撃、敵対的サンプルは入力に微小なノイズを混ぜて誤判定させる攻撃、ディープフェイクは偽コンテンツを作る技術で、いずれも指示を仕込むプロンプトインジェクションではない。", "usecase": "LLMを組み込んだサービスの新しいセキュリティリスク。入力の検査や、外部データを鵜呑みにしない設計などの対策が必要になる。", "opt": ["正解。入力文に指示を紛れ込ませてLLMの制限を破らせるのがプロンプトインジェクション。", "学習データを汚す攻撃で、使うときの入力を狙うのとは段階が違う。", "入力に微小なノイズを混ぜて誤判定させる攻撃で、指示の注入ではない。", "偽コンテンツを作る技術で、プロンプトインジェクションではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='10. AI倫理・AIガバナンス'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
INSERT INTO public.questions (subject_id, category_id, source_ref, question_text, code, options, correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, 'g-kentei-d-q50', 'AIの用途をリスクの高さで分類し、許容できないリスクの用途は禁止、高リスクの用途には厳しい義務を課すという形で規制する、EUの法規制はどれか。', NULL, '["EU AI Act", "人間中心のAI社会原則", "著作権法30条の4", "ムーアの法則"]'::jsonb, 0, '[0]'::jsonb, 'single', '', '{"asked": "AIの用途をリスクの高さで分類し、段階的に規制するEUの法規制は？", "point": "「AIの用途をリスクの高さで分類し、段階的に規制するEUの法律」なら、EU AI Act。", "kid": "EUが作ったAIの法規制。AIの用途を「許容できないリスク(禁止)」「高リスク(厳しい義務)」などにリスクの高さで分け、危険なほど厳しく規制する。リスクに応じて扱いを変えるのが特徴。", "eg": "危険度に応じて薬を「市販OK」「処方箋が必要」「使用禁止」と分ける、あの段階規制のAI版。", "terms": [["EU AI Act", "AIの用途をリスクの高さで分類し、段階的に規制するEUの法規制。リスクベースアプローチ"], ["リスクベースアプローチ", "リスクの高さに応じて規制の強さを変える考え方。EU AI Actの基本"]], "think": "「AIをリスクの高さで分類・段階的に規制・EUの法律」ならEU AI Act。理念を示す人間中心のAI社会原則(日本)とは、拘束力も国も違う。", "vs": "人間中心のAI社会原則は日本の理念的な原則、著作権法30条の4は機械学習の著作物利用の規定、ムーアの法則は半導体の性能向上の経験則で、いずれもリスクで段階規制するEU AI Actではない。", "usecase": "AIを世界で提供する企業が意識すべき代表的な法規制。用途のリスク区分に応じて、満たすべき義務が変わる。", "opt": ["正解。AIの用途をリスクの高さで分類し段階的に規制するEUの法律がEU AI Act。", "日本の理念的な原則で、拘束力のあるEUの法規制ではない。", "機械学習の著作物利用の規定で、リスクで段階規制するものではない。", "半導体の性能向上の経験則で、AIの法規制ではない。"]}'::jsonb, 1
FROM public.subjects s JOIN public.categories c ON c.subject_id=s.id
WHERE s.slug='g-kentei-d' AND c.name='10. AI倫理・AIガバナンス'
ON CONFLICT (subject_id, source_ref) DO NOTHING;
COMMIT;
