BEGIN;

INSERT INTO public.questions
  (subject_id, category_id, source_ref, question_text, code, options,
   correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, v.source_ref, v.question_text, v.code, v.options::jsonb,
       v.correct_index, v.correct_indices::jsonb, v.question_type, '', v.explanation_data::jsonb, 1
FROM public.subjects s
JOIN public.categories c ON c.subject_id = s.id
JOIN (VALUES

  ('linux-q155', 'リンクという考え方',
   'ハードリンクとシンボリックリンクの根本的な違いは何か。',
   NULL::text,
   '["ハードリンクは同じ実体(inode)を指す別名で、シンボリックリンクは行き先のパスを書いた別のファイルである","ハードリンクは行き先のパスを書いた別のファイルで、シンボリックリンクは同じ実体(inode)を指す別名である","どちらも同じ実体(inode)を指す別名であり、仕組み上の違いは無い","ハードリンクもシンボリックリンクも、実体は複製されたコピーである"]',
   0, '[0]', 'single',
   '{"asked":"ハードリンクとシンボリックリンクの仕組みの違いを問う問題。","why_asked":"「どちらもショートカットのようなもの」と一括りにされがちだが、仕組みが根本的に違うのでこれを見分けられるかが定番の論点。","kid":"ハードリンクは「同じ中身を指す、もう1つの名前」。シンボリックリンクは「行き先のパスを書いたメモ」で、中身そのものは別。","eg":"たとえるなら、ハードリンクは同じ人物に付いた「あだ名」。本人は1人。シンボリックリンクは「あの人はあっちにいます」と書かれた案内板。案内板自体は本人とは別物。","terms":[["inode","ファイルの実体(中身・場所などの情報)を表す番号。ファイル名とは別に存在する"],["ハードリンク","ファイル名は違っても、同じinodeを指す別名"],["シンボリックリンク","行き先のパスを文字として書いた、別の小さなファイル"]],"think":"見分け方は「実体を共有しているか、案内板でしかないか」。ハードリンクは同じinodeに複数の名前が結び付いているだけなので、どちらの名前からアクセスしても中身はまったく同じ。シンボリックリンクは自分自身が独立した小さなファイルで、その中身に「本当の行き先」のパスが文字列として書かれているだけなので、案内板を経由して本体にたどり着く形になる。","vs":"「どちらもショートカットだから同じ」という誤解に注意。ハードリンクは実体そのものへの別名だが、シンボリックリンクは実体とは別の、行き先を指すだけの独立したファイルという違いがある。","opt":["正解。ハードリンクは同じ実体(inode)への別名、シンボリックリンクは行き先のパスを書いた別ファイルという違いがある。","説明が入れ替わっている。行き先のパスを書いた別ファイルなのはシンボリックリンクの方。","ハードリンクとシンボリックリンクは仕組みが異なり、同じではない。","どちらも実体を複製するわけではない。ハードリンクは同じ実体を共有し、シンボリックリンクは行き先を指すだけ。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">ハードリンク：同じ実体(inode)を指す名前</text>\n<rect x=\"40\" y=\"40\" width=\"90\" height=\"40\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"85\" y=\"64\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">name.txt</text>\n<rect x=\"210\" y=\"40\" width=\"90\" height=\"40\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"255\" y=\"64\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">name2.txt</text>\n<defs><marker id=\"ah99a0e9\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#6ab08d\"/></marker></defs><line x1=\"130\" y1=\"60\" x2=\"175\" y2=\"60\" stroke=\"#6ab08d\" marker-end=\"url(#ah99a0e9)\"/>\n<defs><marker id=\"ah7irsqz\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#6ab08d\"/></marker></defs><line x1=\"210\" y1=\"60\" x2=\"165\" y2=\"60\" stroke=\"#6ab08d\" marker-end=\"url(#ah7irsqz)\"/>\n<rect x=\"145\" y=\"90\" width=\"50\" height=\"30\" rx=\"6\" fill=\"#1a2e26\" stroke=\"#6ab08d\"/>\n<text x=\"170\" y=\"109\" font-size=\"10\" fill=\"#6ab08d\" text-anchor=\"middle\" font-weight=\"normal\">inode</text>\n<line x1=\"90\" y1=\"80\" x2=\"150\" y2=\"90\" stroke=\"#6ab08d\" />\n<line x1=\"255\" y1=\"80\" x2=\"190\" y2=\"90\" stroke=\"#6ab08d\" />\n<text x=\"170\" y=\"130\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">2つの名前が同じ中身(inode)を指している</text>\n</svg>"}'),

  ('linux-q156', 'リンクという考え方',
   'シンボリックリンクのファイルの中身には、具体的に何が入っているか。',
   NULL::text,
   '["行き先のファイルやディレクトリを示すパスの文字列","行き先のファイルの内容そのものの完全なコピー","行き先のファイルのinode番号を表す数値だけ","何も入っておらず、常に空である"]',
   0, '[0]', 'single',
   '{"asked":"シンボリックリンクの中身に何が入っているかを問う問題。","why_asked":"シンボリックリンクを「実体そのもの」だと誤解しやすいので、中身が単なる文字列であることを確認させる。","kid":"シンボリックリンクというファイルを開いてみると、中には「/home/yuu/real-file.txt」のような、行き先を示す文字がただ書かれているだけ。","eg":"たとえるなら、シンボリックリンクは住所だけが書かれたメモ用紙。メモ用紙自体には荷物は入っていない。","terms":[["パス","ファイルやディレクトリの場所を示す文字列"],["シンボリックリンク","行き先のパスを中身として持つ、小さな独立したファイル"]],"think":"「中身＝行き先の住所（パス文字列）」という一点を押さえておけばよい。シンボリックリンクを開くプログラムは、この文字列を読み取って行き先へたどり着く動きをする。","vs":"ハードリンクと混同しやすいが、ハードリンクは行き先のinodeを直接共有するので「住所を書いたメモ」のような中間ファイルは存在しない。","opt":["正解。シンボリックリンクの中身は、行き先を示すパスの文字列である。","内容そのもののコピーが入っているわけではない。コピーだと元を書き換えても追従できなくなる。","inode番号ではなく、人間が読めるパスの文字列が入っている。","中身は空ではなく、行き先を示す文字列が入っている。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">シンボリックリンクの中身</text>\n<rect x=\"30\" y=\"40\" width=\"100\" height=\"40\" rx=\"6\" fill=\"none\" stroke=\"#c9a04a\"/>\n<text x=\"80\" y=\"58\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">link</text>\n<text x=\"80\" y=\"72\" font-size=\"8\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">(中身は文字列)</text>\n<defs><marker id=\"ahguhg49\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#c9a04a\"/></marker></defs><line x1=\"130\" y1=\"60\" x2=\"200\" y2=\"60\" stroke=\"#c9a04a\" marker-end=\"url(#ahguhg49)\"/>\n<rect x=\"210\" y=\"40\" width=\"100\" height=\"40\" rx=\"6\" fill=\"none\" stroke=\"#2a2f3f\"/>\n<text x=\"260\" y=\"64\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">\"/path/to/real\"</text>\n<text x=\"170\" y=\"100\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ファイルの中身に、行き先のパスが文字として</text>\n<text x=\"170\" y=\"115\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">書かれているだけ</text>\n</svg>"}'),

  ('linux-q157', 'リンクという考え方',
   'ハードリンクを1つ削除しても、もう一方の名前から見た元のファイルの中身が消えない理由は何か。',
   NULL::text,
   '["各inodeが「参照している名前の数」を数えており、0になるまで実体は残るから","ハードリンクを消すと、システムが自動でバックアップとして複製を作成するから","ファイルシステムが全てのハードリンクの中身を常に同期して複製し続けているから","削除操作はディレクトリの一覧表示から名前を隠すだけで、実体は何も変化しないから"]',
   0, '[0]', 'single',
   '{"asked":"ハードリンクを1つ削除しても中身が消えない仕組みを問う問題。","why_asked":"「削除＝実体が消える」という直感がハードリンクでは崩れる。この崩れ方（リンクカウント）を理解しているか問う。","kid":"inodeは「今、自分は何個の名前から呼ばれているか」を数えている。1つの名前を消しても、まだ他の名前から呼ばれていれば、その数字が0になっていないので中身は残る。","eg":"たとえるなら、1人の人物に「あだ名A」と「あだ名B」の2つがあるとき、あだ名Aを使うのをやめても、あだ名Bで呼ばれ続けている限りその人自身は消えない。","terms":[["リンクカウント","そのinodeが、いくつの名前(ハードリンク)から参照されているかを数えた数字"],["inode","ファイルの実体を表す情報のかたまり"]],"think":"ファイルの「削除」という操作は、実は「その名前とinodeの結びつきを1つ外す」操作にすぎない。inode側はリンクカウントを持っていて、名前が外れるたびにその数を1つ減らす。カウントが0になった時点で初めて、ファイルシステムはそのinode（実体）を本当に消してよいと判断する。だから、まだ他の名前が残っていればカウントは0にならず、中身は生き続ける。","vs":"シンボリックリンクと混同しやすいが、シンボリックリンクの元ファイルを消すと即座にリンク切れになる。ハードリンクにはこの「カウントが0になるまで残る」という仕組みがある点が違う。","opt":["正解。inodeはリンクカウントを持ち、名前を1つ消してもカウントが0になるまで実体は残る。","自動でバックアップや複製が作られる仕組みではない。同じ実体を複数の名前が共有しているだけ。","ハードリンク同士は複製ではなく、そもそも同じ実体を指しているので同期の必要が無い。","削除は名前とinodeの結びつきを外す実際の操作であり、表示を隠しているだけではない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">リンクカウント</text>\n<rect x=\"140\" y=\"35\" width=\"60\" height=\"34\" rx=\"6\" fill=\"#1a2e26\" stroke=\"#6ab08d\"/>\n<text x=\"170\" y=\"56\" font-size=\"10\" fill=\"#6ab08d\" text-anchor=\"middle\" font-weight=\"normal\">inode</text>\n<text x=\"170\" y=\"27\" font-size=\"9\" fill=\"#6ab08d\" text-anchor=\"middle\" font-weight=\"normal\">カウント=2</text>\n<rect x=\"40\" y=\"85\" width=\"80\" height=\"30\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"80\" y=\"104\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">a.txt</text>\n<rect x=\"220\" y=\"85\" width=\"80\" height=\"30\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"260\" y=\"104\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">b.txt</text>\n<line x1=\"80\" y1=\"85\" x2=\"155\" y2=\"62\" stroke=\"#8892a4\" />\n<line x1=\"260\" y1=\"85\" x2=\"185\" y2=\"62\" stroke=\"#8892a4\" />\n<text x=\"170\" y=\"128\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">a.txtを消してもb.txtが残っていればinodeは消えない</text>\n</svg>"}'),

  ('linux-q158', 'リンクという考え方',
   'シンボリックリンクが指している元のファイルを削除すると、そのシンボリックリンク自体はどうなるか。',
   NULL::text,
   '["シンボリックリンクのファイル自体は残るが、開こうとしても行き先が無くリンク切れになる","シンボリックリンクのファイルも自動的に一緒に削除される","シンボリックリンクが自動的に別の似た名前のファイルを指すよう更新される","削除は失敗し、元のファイルもシンボリックリンクも両方残り続ける"]',
   0, '[0]', 'single',
   '{"asked":"元ファイルを消したときにシンボリックリンクがどうなるかを問う問題。","why_asked":"シンボリックリンクは「案内板」にすぎないという理解が固まっているかを確認する、定番の確認ポイント。","kid":"シンボリックリンクは行き先の住所を書いたメモなので、行き先そのものが無くなっても、メモ自体はそのまま残る。ただしメモの通りに行っても何も無い状態になる。","eg":"たとえるなら、「あの店はここです」という案内板が立っているのに、その店が閉店してしまった状態。案内板そのものは撤去されずに残るが、案内板通りに行っても目的の店は無い。","terms":[["リンク切れ(dangling link)","シンボリックリンクの行き先が存在しなくなり、たどれなくなった状態"]],"think":"シンボリックリンクは元ファイルとは完全に別の、独立した小さなファイルである。だから元ファイルが消えるかどうかは、シンボリックリンクというファイル自体の存在には影響しない。ただし、シンボリックリンクの「中身（行き先のパス）」が指す先が無くなるので、実際に開こうとするとエラーになる。この状態をリンク切れと呼ぶ。","vs":"ハードリンクと混同しやすいが、ハードリンクは実体そのものを共有しているので「元を消したらもう一方も使えなくなる」ということは起きない。シンボリックリンクは案内板でしかないので、行き先が消えると案内が無意味になる点が違う。","opt":["正解。シンボリックリンク自体は残るが、行き先が無いためリンク切れになる。","シンボリックリンクは独立したファイルなので、元ファイルの削除と連動して自動削除されることはない。","行き先を自動で探して更新するような仕組みは無い。リンク切れのままになる。","元ファイルの削除自体は通常どおり行われる。シンボリックリンクの存在が削除を妨げることはない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">シンボリックリンクの元を消すと</text>\n<rect x=\"30\" y=\"40\" width=\"90\" height=\"36\" rx=\"6\" fill=\"none\" stroke=\"#c9a04a\"/>\n<text x=\"75\" y=\"62\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">link</text>\n<defs><marker id=\"ahucogpt\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#c47070\"/></marker></defs><line x1=\"120\" y1=\"58\" x2=\"195\" y2=\"58\" stroke=\"#c47070\" marker-end=\"url(#ahucogpt)\"/>\n<rect x=\"205\" y=\"40\" width=\"90\" height=\"36\" rx=\"6\" fill=\"#2e1a1a\" stroke=\"#c47070\"/>\n<text x=\"250\" y=\"58\" font-size=\"9\" fill=\"#c47070\" text-anchor=\"middle\" font-weight=\"normal\">(消えた)</text>\n<text x=\"170\" y=\"100\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">リンク切れ(dangling link)。</text>\n<text x=\"170\" y=\"115\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">linkファイル自体は残るが、開けなくなる</text>\n</svg>"}'),

  ('linux-q159', 'リンクという考え方',
   'なぜディレクトリに対しては、通常ハードリンクを作ることができないのか。',
   NULL::text,
   '["ディレクトリ同士が親子関係を作り合うと、たどる経路が輪になって無限ループしてしまう恐れがあるから","ディレクトリはファイルと違ってinodeを持たないため、リンクカウントの仕組みが使えないから","ディレクトリは常に空でなければならず、リンクを作ると中身が壊れてしまうから","ディレクトリのハードリンクは技術的には作れるが、単に誰も使ったことがないから"]',
   0, '[0]', 'single',
   '{"asked":"ディレクトリのハードリンクが通常禁止されている理由を問う問題。","why_asked":"「ファイルにハードリンクを作れるなら、ディレクトリにも作れるはず」という素朴な疑問への回答として定番。","kid":"ディレクトリはフォルダの中にフォルダが入る「木」のような形をしている。もしディレクトリ同士でハードリンクを作れてしまうと、AがBの中にあり、BもAの中にある、というぐるぐる回る形ができてしまうことがある。","eg":"たとえるなら、「Aさんの部下はBさん」で「Bさんの部下はAさん」という組織図を作ってしまうと、上司をたどっていくと永遠にAとBの間をぐるぐる回り続けてしまう。ディレクトリの木構造でこれが起きると、たどる処理が止まらなくなる。","terms":[["木構造","根っこ(ルート)から枝分かれしていく、輪にならない形のデータの並べ方"],["ハードリンク","同じ実体を指す別の名前"]],"think":"ファイルシステムがディレクトリをたどる処理（例えば「このディレクトリの下を全部調べる」）は、木構造であることを前提にしている。木構造は「上から下へ一方向にしか進まない」という性質があるから安全にたどれる。もしディレクトリ同士のハードリンクを自由に許してしまうと、あるディレクトリが自分自身の子孫になってしまうような輪ができ得る。輪ができると、たどる処理がいつまでも終わらない無限ループに陥ってしまう。だから多くのファイルシステムは、この危険を避けるためにディレクトリのハードリンクを制限している。","vs":"ファイルのハードリンクと混同しやすいが、ファイルは木構造の枝分かれには関わらないため輪ができる心配が無く、複数のハードリンクが自由に許されている。","opt":["正解。ディレクトリ同士でハードリンクを作ると、木構造が輪になり無限ループの恐れがあるため制限されている。","ディレクトリもinodeを持っており、それ自体が制限の理由ではない。","ディレクトリは中身を持てないわけではなく、この説明は誤り。","技術的な理由（輪ができる危険）があって制限されており、単に使われていないだけではない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"10.5\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">ディレクトリのハードリンクを禁止する理由</text>\n<rect x=\"60\" y=\"40\" width=\"80\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"100\" y=\"61\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">dir-A</text>\n<rect x=\"200\" y=\"40\" width=\"80\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"240\" y=\"61\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">dir-B</text>\n<defs><marker id=\"ahow5pcq\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#c47070\"/></marker></defs><line x1=\"140\" y1=\"57\" x2=\"195\" y2=\"57\" stroke=\"#c47070\" marker-end=\"url(#ahow5pcq)\"/>\n<defs><marker id=\"ah80gg4a\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#c47070\"/></marker></defs><line x1=\"200\" y1=\"70\" x2=\"145\" y2=\"70\" stroke=\"#c47070\" marker-end=\"url(#ah80gg4a)\"/>\n<text x=\"170\" y=\"105\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">互いが親になり合うと木構造が輪になり、</text>\n<text x=\"170\" y=\"118\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">たどる処理が無限ループしてしまう</text>\n</svg>"}'),

  ('linux-q160', 'リンクという考え方',
   'アプリケーションのバージョンを切り替える運用で、シンボリックリンクがよく使われるのはなぜか。',
   NULL::text,
   '["「現在使うバージョン」という名前の指し先を差し替えるだけで、瞬時に切り替えができるから","シンボリックリンクを使うと、複数バージョンの中身が自動的に1つにまとめられるから","シンボリックリンクを使わないと、そもそも複数のバージョンを同じディスクに置けないから","シンボリックリンクは中身を圧縮して保存するため、ディスク容量を大きく節約できるから"]',
   0, '[0]', 'single',
   '{"asked":"バージョン切り替えでシンボリックリンクが使われる理由を問う問題。","why_asked":"仕組みの理解を実務的な使いどころに接続できているかを確認する。QAが関わるテスト環境の切り替えとも接点がある。","kid":"「current」という名前のシンボリックリンクを用意しておき、その指し先を「v1」から「v2」に書き換えるだけで、プログラムから見た「今使っているバージョン」を一瞬で切り替えられる。","eg":"たとえるなら、案内板の矢印の向きを変えるだけで、「今日のお店はこちら」を切り替えるようなもの。お店(バージョン)そのものを作り直したり移動したりする必要が無い。","terms":[["シンボリックリンク","行き先のパスを書いた案内役のファイル。指し先を書き換えるだけで切り替えができる"]],"think":"バージョンを切り替えるとき、もし本体のファイル自体を毎回コピーしたり移動したりしていたら時間がかかるし、途中でエラーが起きると中途半端な状態になりかねない。シンボリックリンクなら、指し先の文字列を書き換えるだけで済むので、切り替えが一瞬で終わり、途中状態が発生しにくい。だから「currentという名前は今どのバージョンを指しているか」という管理の仕組みとして、シンボリックリンクが好まれる。","vs":"コピーして置き換える方法と混同しやすいが、コピーは時間がかかり容量も余分に使う。シンボリックリンクは指し先を変えるだけなので、速く安全に切り替えられる点が違う。","opt":["正解。指し先を差し替えるだけで、瞬時にバージョンを切り替えられるから。","複数バージョンの中身を1つにまとめる機能はシンボリックリンクには無い。それぞれ別々のまま置かれている。","複数バージョンを同じディスクに置くこと自体は、シンボリックリンクが無くても可能。","シンボリックリンクは中身を圧縮する仕組みではなく、単に行き先を指す小さなファイルである。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">シンボリックリンクの使いどころ</text>\n<rect x=\"30\" y=\"40\" width=\"80\" height=\"32\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"70\" y=\"60\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">app-v1</text>\n<rect x=\"30\" y=\"78\" width=\"80\" height=\"32\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"70\" y=\"98\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">app-v2</text>\n<rect x=\"170\" y=\"58\" width=\"90\" height=\"32\" rx=\"6\" fill=\"none\" stroke=\"#60a5fa\"/>\n<text x=\"215\" y=\"78\" font-size=\"10\" fill=\"#60a5fa\" text-anchor=\"middle\" font-weight=\"normal\">current</text>\n<defs><marker id=\"ah8vq4ht\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"170\" y1=\"74\" x2=\"115\" y2=\"60\" stroke=\"#60a5fa\" marker-end=\"url(#ah8vq4ht)\"/>\n<text x=\"170\" y=\"122\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">currentの向き先を差し替えるだけで</text>\n<text x=\"170\" y=\"135\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">バージョンを一瞬で切り替えられる</text>\n</svg>"}'),

  ('linux-q161', 'リンクという考え方',
   '「別のディスク（別のパーティション）をまたいでリンクを作れるか」という点で、ハードリンクとシンボリックリンクにはどんな違いがあるか。',
   NULL::text,
   '["シンボリックリンクは別ディスクもまたげるが、ハードリンクは同じディスク内でしか作れない","ハードリンクは別ディスクもまたげるが、シンボリックリンクは同じディスク内でしか作れない","どちらも別ディスクを自由にまたいでリンクを作ることができる","どちらも同じディスク内でしかリンクを作ることができない"]',
   0, '[0]', 'single',
   '{"asked":"ハードリンクとシンボリックリンクが別ディスクをまたげるかどうかの違いを問う問題。","why_asked":"inodeの仕組みを理解していれば導ける実務的な制約。単なる暗記ではなく因果から導けるかを試す。","kid":"ハードリンクは同じinode番号を指す名前なので、そのinode番号が管理されているディスクの中でしか意味を持たない。シンボリックリンクはただの文字列（パス）なので、どこのディスクの場所でも自由に書ける。","eg":"たとえるなら、ハードリンクは「同じ会員番号を指す2つの会員証」のようなもの。会員番号は1つの管理システム（ディスク）の中でしか通用しない。シンボリックリンクは「住所を書いたメモ」なので、どの都道府県の住所でも自由に書ける。","terms":[["inode番号","そのディスク(ファイルシステム)の中だけで通用する、ファイルの実体を表す番号"],["パス","どのディスクの場所でも表せる、住所のような文字列"]],"think":"ハードリンクが指しているのは「このディスクのこのinode番号」という、そのディスクの中でしか意味を持たない番号である。別のディスクには同じ番号のinodeが別の目的で存在しているかもしれないので、ディスクをまたいでハードリンクを作ることはできない。一方シンボリックリンクは、行き先を人間にも読める文字列のパスとして持っているだけなので、そのパスがどのディスク上のものであっても関係なく指し示すことができる。","vs":"「リンクはどちらも同じ制約を持つ」という誤解に注意。中身の仕組み（inode番号を共有するか、文字列で指すだけか）の違いが、そのままこの制約の違いに直結している。","opt":["正解。シンボリックリンクは別ディスクもまたげるが、ハードリンクは同じディスク内でしか作れない。","説明が入れ替わっている。ディスクをまたげないのはハードリンクの方。","ハードリンクはディスクをまたいで作ることができない。","シンボリックリンクは文字列でしかないため、別ディスクを自由にまたぐことができる。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">パーティションをまたげるか</text>\n<rect x=\"20\" y=\"40\" width=\"130\" height=\"60\" rx=\"6\" fill=\"none\" stroke=\"#2a2f3f\"/>\n<text x=\"85\" y=\"34\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ディスクA</text>\n<rect x=\"190\" y=\"40\" width=\"130\" height=\"60\" rx=\"6\" fill=\"none\" stroke=\"#2a2f3f\"/>\n<text x=\"255\" y=\"34\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ディスクB</text>\n<rect x=\"45\" y=\"55\" width=\"60\" height=\"25\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"75\" y=\"71\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">file</text>\n<rect x=\"215\" y=\"55\" width=\"80\" height=\"25\" rx=\"6\" fill=\"none\" stroke=\"#c9a04a\"/>\n<text x=\"255\" y=\"71\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">symlink</text>\n<defs><marker id=\"ah9dl0pk\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#c9a04a\"/></marker></defs><line x1=\"215\" y1=\"67\" x2=\"165\" y2=\"67\" stroke=\"#c9a04a\" marker-end=\"url(#ah9dl0pk)\"/>\n<text x=\"170\" y=\"118\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">シンボリックリンクは別ディスクもまたげるが、</text>\n<text x=\"170\" y=\"130\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ハードリンクは同じディスク内でしか作れない</text>\n</svg>"}'),

  ('linux-q162', 'DNSの仕組み',
   'コンピュータ同士の通信は本来IPアドレスで行われるのに、なぜ普段はドメイン名(example.comのような文字列)を使うのか。',
   NULL::text,
   '["数字の羅列であるIPアドレスより、意味のある文字列の方が人間にとって覚えやすく扱いやすいから","ドメイン名を使わないと、そもそもコンピュータ同士が通信できない仕組みになっているから","ドメイン名の方がIPアドレスより通信速度が速くなるから","IPアドレスは一度使うと二度と使えなくなるため、代わりにドメイン名を使う必要があるから"]',
   0, '[0]', 'single',
   '{"asked":"ドメイン名を使う理由を問う問題。","why_asked":"DNSの仕組みを学ぶ前に、そもそも何のためにドメイン名という仕組みがあるのかという動機を確認する。","kid":"コンピュータ同士は結局「203.0.113.5」のような数字で通信しているけれど、その数字を人間が全部覚えるのは大変。だから「example.com」のような、意味の分かる名前を代わりに使えるようにしている。","eg":"たとえるなら、電話番号を全部暗記する代わりに、電話帳に「お母さん」のような名前を登録しておくようなもの。実際にかかる先は番号だが、人間が扱うのは名前でよい。","terms":[["IPアドレス","コンピュータが通信するときに実際に使う、数字の並びでできた住所"],["ドメイン名","人間が読みやすいように付けられた、IPアドレスの代わりの名前"]],"think":"通信そのものは今も昔もIPアドレスという数字で行われている。この事実は変わっていない。ただ、人間がその数字をいちいち覚えて入力するのは現実的でないので、覚えやすい名前とIPアドレスを結びつける仕組みが後から作られた。この「名前と数字を結びつける」という考え方が、この後に学ぶDNSの土台になる。","vs":"「ドメイン名の方が新しい通信方式」という誤解に注意。通信の実体は今もIPアドレスであり、ドメイン名はあくまで人間向けの言い換えでしかない。","opt":["正解。数字の並びより、意味のある文字列の方が人間には覚えやすく扱いやすいから。","ドメイン名が無くてもIPアドレスを直接指定すれば通信自体は可能。人間の利便性のための仕組みである。","通信速度そのものはIPアドレスで決まり、ドメイン名を使うかどうかとは関係ない。","IPアドレスが使い捨てになるという事実は無い。ドメイン名の存在理由とは無関係。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">なぜドメイン名を使うのか</text>\n<text x=\"85\" y=\"55\" font-size=\"12\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">203.0.113.5</text>\n<text x=\"85\" y=\"72\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">(覚えにくい)</text>\n<text x=\"255\" y=\"55\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">example.com</text>\n<text x=\"255\" y=\"72\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">(覚えやすい)</text>\n<defs><marker id=\"ahvhh8yr\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"140\" y1=\"55\" x2=\"195\" y2=\"55\" stroke=\"#60a5fa\" marker-end=\"url(#ahvhh8yr)\"/>\n<text x=\"170\" y=\"105\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">同じ行き先でも、人間には名前の方が</text>\n<text x=\"170\" y=\"119\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">扱いやすい</text>\n</svg>"}'),

  ('linux-q163', 'DNSの仕組み',
   'ドメイン名からIPアドレスを調べる仕組み全体を何と呼ぶか。',
   NULL::text,
   '["名前解決","ポートフォワーディング","ロードバランシング","パケットフィルタリング"]',
   0, '[0]', 'single',
   '{"asked":"ドメイン名→IPアドレスの変換の仕組みの名前を問う問題。","why_asked":"この後の内容（DNSサーバー、キャッシュなど）を理解するうえで欠かせない基本用語。","kid":"「example.comって、実際は何番のIPアドレスなの？」と調べて答えを見つけることを、名前解決と呼ぶ。","eg":"たとえるなら、電話帳を引いて「お母さん」という名前から実際の電話番号を調べる作業のようなもの。この「調べる」という行為全体に名前が付いている。","terms":[["名前解決","ドメイン名から対応するIPアドレスを調べる一連の仕組み"]],"think":"この後に出てくる「DNSサーバー」「キャッシュ」といった仕組みは、すべて「名前解決」という1つの目的（ドメイン名からIPアドレスを見つけ出すこと）のために存在している。まずこの言葉と目的を結びつけておくと、以降の話が繋がりやすくなる。","vs":"他の選択肢（ポートフォワーディング、ロードバランシング、パケットフィルタリング）はいずれもネットワークの別の仕組みで、ドメイン名からIPアドレスを調べる作業そのものを指す言葉ではない。","opt":["正解。ドメイン名からIPアドレスを調べる仕組み全体を名前解決と呼ぶ。","ポートフォワーディングは、あるポート宛の通信を別の場所へ転送する仕組みで、名前を調べる仕組みではない。","ロードバランシングは複数のサーバーに通信を振り分ける仕組みで、名前を調べる仕組みではない。","パケットフィルタリングは通信を通す/通さないを判断する仕組みで、名前を調べる仕組みではない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">名前解決の流れ</text>\n<rect x=\"20\" y=\"45\" width=\"80\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"60\" y=\"66\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ブラウザ</text>\n<defs><marker id=\"ahadwdwl\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"100\" y1=\"62\" x2=\"145\" y2=\"62\" stroke=\"#60a5fa\" marker-end=\"url(#ahadwdwl)\"/>\n<rect x=\"150\" y=\"45\" width=\"90\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#60a5fa\"/>\n<text x=\"195\" y=\"62\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">DNSサーバー</text>\n<defs><marker id=\"ah5jx663\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"240\" y1=\"62\" x2=\"285\" y2=\"62\" stroke=\"#60a5fa\" marker-end=\"url(#ah5jx663)\"/>\n<rect x=\"255\" y=\"45\" width=\"65\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"287\" y=\"62\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">IP</text>\n<text x=\"170\" y=\"105\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ドメイン名→IPアドレスへの変換を</text>\n<text x=\"170\" y=\"119\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">「名前解決」と呼ぶ</text>\n</svg>"}'),

  ('linux-q164', 'DNSの仕組み',
   '利用しているDNSサーバーが見つからない・応答しないとき、何が起きるか。',
   NULL::text,
   '["ドメイン名に対応するIPアドレスが分からず、接続先を特定できなくなる","すでに確立していた通信のすべてが、その瞬間に強制的に切断されてしまう","コンピュータの中にあるすべてのファイルが、読み書きできなくなってしまう","IPアドレスを直接指定して接続する方法まで含めて、通信が一切できなくなる"]',
   0, '[0]', 'single',
   '{"asked":"DNSサーバーが応答しないとどうなるかを問う問題。","why_asked":"「ページが表示されない」というトラブルの原因の1つとして、DNSの障害を切り分けられるかを問う実務的な論点。","kid":"DNSサーバーに「このドメイン名のIPアドレスは何？」と聞いても答えが返ってこないと、そもそも「どこに接続すればいいか」が分からないままになってしまう。","eg":"たとえるなら、電話帳が使えなくなった状態。相手の名前は分かっていても、電話番号が分からなければ電話をかけられない。","terms":[["名前解決エラー","ドメイン名からIPアドレスへの変換に失敗し、接続先が特定できない状態"]],"think":"ブラウザなどが通信を始めるには、まず「どのIPアドレスに接続すればいいか」を知る必要がある。この最初のステップである名前解決がDNSサーバーの不調によって失敗すると、そこから先の通信そのものが始められない。ただし、これはあくまで「名前からIPアドレスを調べる」ステップの失敗であり、もしIPアドレスを直接知っていてそれを指定すれば、DNSを介さずに接続すること自体は可能である。","vs":"「DNSが落ちるとインターネット全体が使えなくなる」という誤解に注意。実際に失われるのは「名前からIPアドレスを調べる手段」であり、IPアドレスを直接指定する通信までは妨げられない。","opt":["正解。ドメイン名に対応するIPアドレスが分からなくなり、接続先を特定できなくなる。","すでに確立している通信が名前解決の失敗だけで即座に切断されるとは限らない。","ファイルの読み書きはDNSの仕組みとは別の話であり、直接の影響は無い。","IPアドレスを直接指定する通信までは妨げられない。DNSはあくまで名前をIPアドレスに変換する手段。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">DNSサーバーが応答しないと</text>\n<rect x=\"20\" y=\"45\" width=\"80\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"60\" y=\"66\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ブラウザ</text>\n<defs><marker id=\"ah1m5thu\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#c47070\"/></marker></defs><line x1=\"100\" y1=\"62\" x2=\"150\" y2=\"62\" stroke=\"#c47070\" marker-end=\"url(#ah1m5thu)\"/>\n<rect x=\"155\" y=\"45\" width=\"90\" height=\"34\" rx=\"6\" fill=\"#2e1a1a\" stroke=\"#c47070\"/>\n<text x=\"200\" y=\"62\" font-size=\"10\" fill=\"#c47070\" text-anchor=\"middle\" font-weight=\"normal\">応答なし</text>\n<text x=\"170\" y=\"105\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">IPアドレスが分からず接続先を</text>\n<text x=\"170\" y=\"119\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">特定できない＝名前解決エラー</text>\n</svg>"}'),

  ('linux-q165', 'DNSの仕組み',
   '`/etc/hosts` というファイルは、名前解決の中でどんな役割を持っているか。',
   NULL::text,
   '["DNSに問い合わせる前に見る、手元のドメイン名とIPアドレスの対応表","DNSサーバーそのものの本体プログラムが、まるごと保存されているファイル","ネットワークに接続されている全ての機器の一覧を、自動で記録し続けるファイル","過去に一度も名前解決の場面で使われたことのない、単なる予備用のファイル"]',
   0, '[0]', 'single',
   '{"asked":"/etc/hostsの役割を問う問題。","why_asked":"DNSサーバーへの問い合わせが必ずしも唯一の名前解決手段ではないことを理解しているか確認する。","kid":"DNSサーバーに聞きに行く前に、まず自分のコンピュータの中にある「対応表メモ」を見る。そのメモが/etc/hostsというファイル。","eg":"たとえるなら、電話帳（DNS）を引く前に、自分の手元にある小さなメモ帳（/etc/hosts）を先に確認するようなもの。よく使う番号はそこに書いておける。","terms":[["/etc/hosts","ドメイン名とIPアドレスの対応を手元に直接書いておけるファイル"],["DNSサーバー","/etc/hostsに答えが無かったときに問い合わせる、外部の名前解決サービス"]],"think":"名前解決はいつもDNSサーバーに問い合わせるとは限らない。多くのシステムは、まず自分のコンピュータの中にある小さな対応表(/etc/hosts)を確認し、そこに答えがあればそれをそのまま使う。答えが無かった場合に初めて、外部のDNSサーバーへ問い合わせに行く、という順番で動く。","vs":"DNSサーバーと混同しやすいが、/etc/hostsは自分のコンピュータの中に置かれたローカルな対応表であり、外部のサーバーではない点が違う。","opt":["正解。DNSサーバーに問い合わせる前に参照する、手元の対応表である。","DNSサーバーの本体プログラムではなく、あくまで対応表のデータが書かれたファイルである。","ネットワーク機器を自動で記録する機能は無く、内容は人が手で書いておくものである。","実際に名前解決の最初の確認先として使われる、現役の仕組みである。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">/etc/hosts と DNS</text>\n<rect x=\"20\" y=\"45\" width=\"100\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"70\" y=\"63\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">/etc/hosts</text>\n<text x=\"70\" y=\"76\" font-size=\"8\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">(手元の対応表)</text>\n<defs><marker id=\"ahog3lro\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#8892a4\"/></marker></defs><line x1=\"120\" y1=\"62\" x2=\"165\" y2=\"62\" stroke=\"#8892a4\" marker-end=\"url(#ahog3lro)\"/>\n<text x=\"142\" y=\"55\" font-size=\"8\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">無ければ</text>\n<rect x=\"170\" y=\"45\" width=\"90\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#60a5fa\"/>\n<text x=\"215\" y=\"63\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">DNSサーバー</text>\n<text x=\"170\" y=\"112\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">まず自分の手元の対応表を見て、</text>\n<text x=\"170\" y=\"126\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">無ければDNSに問い合わせる</text>\n</svg>"}'),

  ('linux-q166', 'DNSの仕組み',
   '一度調べた名前解決の結果を、一定時間覚えておく仕組み（キャッシュ）があるのはなぜか。',
   NULL::text,
   '["毎回DNSサーバーに問い合わせに行く手間と時間を省き、素早く再利用できるようにするため","キャッシュを使わないと、同じドメイン名を二度と調べられなくなってしまうため","DNSサーバー側の記録容量を減らすため、利用者側に記録を肩代わりさせているため","キャッシュに保存すると、IPアドレスの数字自体がより短くなるため"]',
   0, '[0]', 'single',
   '{"asked":"名前解決の結果をキャッシュしておく理由を問う問題。","why_asked":"「毎回律儀に問い合わせている」という誤解を解き、キャッシュの動機（効率化）を理解しているか確認する。","kid":"一度「example.comのIPアドレスはこれ」と調べたら、しばらくの間はその答えを覚えておいて、また同じ名前が出てきたときにすぐ使い回す。毎回DNSサーバーに聞きに行く必要が無くなる。","eg":"たとえるなら、よく電話する相手の番号を一度調べたら、その場でメモして手元に置いておくようなもの。次にかけるときは電話帳を引き直さなくてよい。","terms":[["キャッシュ","一度調べた結果をしばらく手元に覚えておき、同じ問い合わせを省略できるようにする仕組み"]],"think":"DNSサーバーへの問い合わせは、外部のサーバーとやり取りする分だけ時間がかかる。もし同じドメイン名に接続するたびに毎回律儀に問い合わせていたら、そのたびに余分な待ち時間が発生してしまう。そこで、一度調べた答えを一定時間だけ手元に覚えておき、同じ名前が再び出てきたらその覚えている答えをそのまま使い回すことで、通信全体を速くしている。","vs":"「毎回サーバーに聞きに行くのが正確で安全」という思い込みに注意。キャッシュは有効期限付きで管理されており、古くなれば自動的に再度問い合わせに行くので、速さと正確さのバランスを取っている。","opt":["正解。毎回問い合わせに行く手間と時間を省き、素早く再利用するため。","キャッシュが無くても、その都度DNSサーバーに問い合わせれば名前解決自体はできる。","DNSサーバー側の容量を直接減らすことが主目的ではなく、利用者側の効率化が主な目的。","IPアドレスの数字の長さが変わることはない。あくまで問い合わせの手間を省く仕組み。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">キャッシュがある理由</text>\n<rect x=\"20\" y=\"40\" width=\"90\" height=\"30\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"65\" y=\"59\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">1回目</text>\n<defs><marker id=\"ah4m99j0\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"115\" y1=\"55\" x2=\"150\" y2=\"55\" stroke=\"#60a5fa\" marker-end=\"url(#ah4m99j0)\"/>\n<rect x=\"155\" y=\"40\" width=\"90\" height=\"30\" rx=\"6\" fill=\"none\" stroke=\"#60a5fa\"/>\n<text x=\"200\" y=\"59\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">DNSに問合せ</text>\n<rect x=\"20\" y=\"85\" width=\"90\" height=\"30\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"65\" y=\"104\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">2回目以降</text>\n<defs><marker id=\"ahrymqoj\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#6ab08d\"/></marker></defs><line x1=\"115\" y1=\"100\" x2=\"150\" y2=\"100\" stroke=\"#6ab08d\" marker-end=\"url(#ahrymqoj)\"/>\n<rect x=\"155\" y=\"85\" width=\"90\" height=\"30\" rx=\"6\" fill=\"#1a2e26\" stroke=\"#6ab08d\"/>\n<text x=\"200\" y=\"104\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">手元のキャッシュ</text>\n<text x=\"170\" y=\"132\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">毎回問い合わせず、覚えておいて再利用する</text>\n</svg>"}'),

  ('linux-q167', 'DNSの仕組み',
   '`www.example.com` のようなドメイン名は、どちらの向きから区分が絞り込まれていく構造になっているか。',
   NULL::text,
   '["一番右側（.comなど）が大きな区分で、左へ進むほど細かい区分になっていく","一番左側（wwwなど）が大きな区分で、右へ進むほど細かい区分になっていく","ドット(.)で区切られた各部分に上下関係はなく、順序に意味は無い","常に真ん中の部分が最も大きな区分を表している"]',
   0, '[0]', 'single',
   '{"asked":"ドメイン名の階層構造の読み方を問う問題。","why_asked":"DNSの名前解決を人が読み解くときに必要な、階層の向きの基本ルールを確認する。","kid":"ドメイン名は右から読むと分かりやすい。一番右の「.com」が一番大きなくくりで、そこから左へ向かって「example」「www」と、だんだん細かい場所に絞り込まれていく。","eg":"たとえるなら、住所を「日本、東京都、渋谷区」の順で大きい方から書くのに似ている。ドメイン名は逆に、大きい区分（.com）が一番右に来て、そこから左へ細かくなっていく。","terms":[["ドメイン名の階層","右側ほど大きなくくり、左側ほど細かい場所を表す並び方"]],"think":"「.com」のような一番右の部分は、非常に多くの組織が共有している大きなくくりである。そこから1つ左の「example」は、その大きなくくりの中の特定の1つの組織を指す。さらに左の「www」は、その組織が持つサーバーの中の特定の1台を指す、というように、右から左へ進むほど対象がどんどん絞り込まれていく構造になっている。","vs":"住所の書き方（大きい方から先に書く）と向きが逆になる点に注意。ドメイン名は一番右が最も大きなくくりで、左へ進むほど細かくなる。","opt":["正解。一番右側が大きな区分で、左へ進むほど細かい区分になっていく。","向きが逆になっている。大きな区分は左側ではなく右側にある。","区切られた各部分には大小の階層関係があり、順序には意味がある。","真ん中に特別な意味は無く、右から左への階層関係で決まる。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">ドメイン名は右から絞り込む</text>\n<text x=\"50\" y=\"60\" font-size=\"13\" fill=\"#e8eaf0\" text-anchor=\"start\" font-weight=\"normal\">.com</text>\n<defs><marker id=\"ah7eilqm\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"90\" y1=\"55\" x2=\"130\" y2=\"55\" stroke=\"#60a5fa\" marker-end=\"url(#ah7eilqm)\"/>\n<text x=\"135\" y=\"60\" font-size=\"13\" fill=\"#e8eaf0\" text-anchor=\"start\" font-weight=\"normal\">example</text>\n<defs><marker id=\"ahqopu65\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"210\" y1=\"55\" x2=\"250\" y2=\"55\" stroke=\"#60a5fa\" marker-end=\"url(#ahqopu65)\"/>\n<text x=\"255\" y=\"60\" font-size=\"13\" fill=\"#e8eaf0\" text-anchor=\"start\" font-weight=\"normal\">www</text>\n<text x=\"170\" y=\"100\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">一番右が大きな区分、左へ行くほど</text>\n<text x=\"170\" y=\"114\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">細かい住所になる</text>\n</svg>"}'),

  ('linux-q168', 'viエディタの考え方',
   'viエディタに「ノーマルモード」「インサートモード」のような、モードという考え方があるのはなぜか。',
   NULL::text,
   '["同じキー入力を「命令」として実行するか「文字」として入力するかを、モードで区別する必要があるから","モードを設定しないと、そもそもファイルを開くことができない仕組みになっているから","モードごとに使えるキーボードの種類が物理的に変わるから","モードは見た目の色を変えるためだけの、機能とは無関係な飾りだから"]',
   0, '[0]', 'single',
   '{"asked":"viにモードという考え方がある理由を問う問題。","why_asked":"viが初見で戸惑われやすい最大の理由（モード）を、暗記ではなく仕組みとして理解できているか確認する。","kid":"普通のエディタは文字を打てばそのまま入力されるけれど、viでは「今は命令を聞く時間なのか、文字を入力する時間なのか」を分けて考える。この「今どちらか」を表すのがモード。","eg":"たとえるなら、同じ「d」というキーが、命令として聞かれているときは「1行消して」という指示になり、文字として聞かれているときはただの「d」という文字になる。どちらの意味かを区別するために、今どちらのモードにいるかを決めておく。","terms":[["ノーマルモード","キー入力を移動や削除などの命令として受け取るモード"],["インサートモード","キー入力をそのまま文字として受け取るモード"]],"think":"普通の文字入力用アプリでは、キーボードのキーはほぼすべて「その文字を入力する」という1つの意味しか持たない。しかしviは、限られたキーの数で「移動する」「削除する」「入力する」といった多くの操作をこなす必要があった。もし全部のキーが常に文字入力の意味しか持たないとすると、命令のための特別なキー（Ctrlなど）を毎回押す必要が出てくる。そこでviは「今は命令を聞く時間」と「今は文字を打つ時間」を切り替えるモードという考え方を導入し、同じキーに複数の役割を持たせられるようにした。","vs":"「モードは古い時代の名残で今は不要」という誤解に注意。モードがあることで、修飾キーを押さずに多くの命令をキーボードだけで完結できるという実務上の利点が今も残っている。","opt":["正解。同じキー入力を「命令」として扱うか「文字」として扱うかを区別する必要があるから。","モードの設定自体はファイルを開く条件ではない。開いた後の入力の扱い方を決めるものである。","モードによって物理的なキーボードの種類が変わるわけではない。同じキーボードのまま解釈だけが変わる。","モードは見た目だけでなく、キー入力の解釈そのものを切り替える実際の機能である。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">なぜモードがあるのか</text>\n<rect x=\"30\" y=\"40\" width=\"120\" height=\"40\" rx=\"6\" fill=\"none\" stroke=\"#60a5fa\"/>\n<text x=\"90\" y=\"58\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ノーマルモード</text>\n<text x=\"90\" y=\"72\" font-size=\"8\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">(命令として読む)</text>\n<rect x=\"190\" y=\"40\" width=\"120\" height=\"40\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"250\" y=\"58\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">インサートモード</text>\n<text x=\"250\" y=\"72\" font-size=\"8\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">(文字として書く)</text>\n<text x=\"170\" y=\"105\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">同じキーが「命令」にも「文字」にもなり得るので、</text>\n<text x=\"170\" y=\"118\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">今どちらとして読むかをモードで区別する</text>\n</svg>"}'),

  ('linux-q169', 'viエディタの考え方',
   'ノーマルモードとインサートモードの違いは何か。',
   NULL::text,
   '["ノーマルモードはキー入力を移動・削除などの命令として扱い、インサートモードは文字入力として扱う","ノーマルモードは文字入力として扱い、インサートモードは移動・削除などの命令として扱う","ノーマルモードでは保存ができず、インサートモードでのみ保存ができる","両モードの違いは画面の色だけで、キー入力の扱われ方は同じである"]',
   0, '[0]', 'single',
   '{"asked":"ノーマルモードとインサートモードの役割の違いを問う問題。","why_asked":"viの2大モードの役割を取り違えると、意図せず文字がコマンドとして実行されてしまう混乱の原因になる。","kid":"ノーマルモードは「命令を聞くモード」。カーソルを動かしたり、行を消したりする。インサートモードは「文字を書き込むモード」。ここで初めて普通のエディタのように文字が打てる。","eg":"たとえるなら、ノーマルモードは「指示を出している時間」、インサートモードは「実際に手を動かして書いている時間」。同じ現場でも、指示を出している間と作業している間では、同じ言葉でも意味が変わる。","terms":[["ノーマルモード","起動直後のモード。キーは命令として解釈される"],["インサートモード","「i」などのキーで切り替える、文字をそのまま入力できるモード"]],"think":"viはノーマルモードで起動する。この状態でキーを打つと、それは文字ではなく「カーソルを動かす」「1行削除する」といった命令として実行される。文字を実際に書き込みたいときは、意識してインサートモードに切り替える必要がある。この切り替えを忘れたまま文字のつもりでキーを打つと、次々と命令が実行されてしまい、思わぬ形でファイルが変わってしまうことがある。","vs":"「viは常に文字入力できる」という思い込みに注意。デフォルトはノーマルモード（命令モード）であり、文字入力にはインサートモードへの切り替えが必要という点が他の多くのエディタと違う。","opt":["正解。ノーマルモードは命令として、インサートモードは文字入力として扱う。","説明が入れ替わっている。命令として扱うのはノーマルモードの方。","保存はどちらのモードから行うかという操作の話であり、モードそのものの定義とは別。","キー入力の解釈がモードごとに大きく異なる。色だけの違いではない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">モードの状態遷移</text>\n<rect x=\"50\" y=\"50\" width=\"100\" height=\"40\" rx=\"6\" fill=\"none\" stroke=\"#60a5fa\"/>\n<text x=\"100\" y=\"74\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ノーマル</text>\n<rect x=\"210\" y=\"50\" width=\"100\" height=\"40\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"260\" y=\"74\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">インサート</text>\n<defs><marker id=\"ahkqjlny\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#6ab08d\"/></marker></defs><line x1=\"150\" y1=\"60\" x2=\"205\" y2=\"60\" stroke=\"#6ab08d\" marker-end=\"url(#ahkqjlny)\"/>\n<text x=\"178\" y=\"52\" font-size=\"9\" fill=\"#6ab08d\" text-anchor=\"middle\" font-weight=\"normal\">i</text>\n<defs><marker id=\"ahkwz7e7\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"205\" y1=\"82\" x2=\"150\" y2=\"82\" stroke=\"#60a5fa\" marker-end=\"url(#ahkwz7e7)\"/>\n<text x=\"178\" y=\"96\" font-size=\"9\" fill=\"#60a5fa\" text-anchor=\"middle\" font-weight=\"normal\">Esc</text>\n</svg>"}'),

  ('linux-q170', 'viエディタの考え方',
   'viがほぼすべてのLinuxサーバーに標準で最初から入っていることが多いのはなぜか。',
   NULL::text,
   '["GUIも無いような最小構成のサーバーでも動く、軽量で昔から使われ続けているエディタだから","viはLinuxのカーネルの一部として組み込まれており、削除できない仕組みになっているから","viが最新の高機能なエディタとして、他のエディタより優れているから","viはネットワーク経由でしか動作せず、ローカルにインストールする必要が無いから"]',
   0, '[0]', 'single',
   '{"asked":"viが最小構成のサーバーにも標準で入っている理由を問う問題。","why_asked":"「なぜよりによってviを覚える必要があるのか」という素朴な疑問に、実務上の理由から答える。","kid":"サーバーの中には、画面も無く最低限の機能しか入っていないものがある。そういう場所でも、ファイルの中身を確認したり直したりする最低限の手段としてviが用意されていることが多い。","eg":"たとえるなら、キャンプ場に最低限の道具しか無いとき、それでも使える「万能ナイフ」のような存在。豪華な道具は無くても、viさえあれば何とかなる。","terms":[["最小構成","GUIや追加のソフトを入れていない、必要最低限の機能だけのシステム"],["vi","昔から広く使われ、多くのLinux/Unix系システムに標準で入っているテキストエディタ"]],"think":"サーバーは、必要なソフトだけを入れて余計なものを省いた「最小構成」で運用されることが多い。トラブルが起きたときに設定ファイルを直接編集する必要が出てくるが、そのときにGUIの高機能なエディタが入っていないことがある。viは古くから存在し、多くのシステムに最初から入っている（あるいは入れやすい）という実績があるため、「どんな環境でもとりあえず使える」共通の道具として広く使われ続けている。","vs":"「新しいエディタの方が優れているから使われている」という誤解に注意。viが選ばれる理由は機能の豊富さではなく、最小限の環境でも使える可用性の高さにある。","opt":["正解。最小構成のサーバーでも動く、軽量で昔から使われ続けているエディタだから。","カーネルの一部ではなく、独立したアプリケーションとして提供されている。","高機能さを競う文脈ではなく、どこでも使えるという可用性が重視されている。","viはネットワークが無くてもローカルで動作するアプリケーションである。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">viがどこにでもある理由</text>\n<rect x=\"20\" y=\"40\" width=\"90\" height=\"60\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"65\" y=\"60\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">最小構成</text>\n<text x=\"65\" y=\"75\" font-size=\"10\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">のサーバー</text>\n<rect x=\"230\" y=\"40\" width=\"90\" height=\"60\" rx=\"6\" fill=\"#1a2e26\" stroke=\"#6ab08d\"/>\n<text x=\"275\" y=\"65\" font-size=\"14\" fill=\"#6ab08d\" text-anchor=\"middle\" font-weight=\"normal\">vi</text>\n<text x=\"275\" y=\"82\" font-size=\"8\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">標準搭載</text>\n<text x=\"170\" y=\"118\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">GUIも無い最小限の環境でも、viだけは</text>\n<text x=\"170\" y=\"131\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">最初から入っていることが多い</text>\n</svg>"}'),

  ('linux-q171', 'viエディタの考え方',
   'インサートモードのつもりで文字を打ったつもりが、実はノーマルモードのままだった場合、何が起きるか。',
   NULL::text,
   '["打った文字が命令として解釈され、意図しない移動や削除などが実行されてしまう","打った文字はすべて無視され、画面には何も変化が起きない","viが自動的にエラーを検知し、インサートモードへ切り替えてくれる","ファイル自体が自動的に閉じられ、保存されずに終了してしまう"]',
   0, '[0]', 'single',
   '{"asked":"モードの勘違いで起きる混乱の具体的な内容を問う問題。","why_asked":"viの初学者がつまずく典型的な場面を、「モードという考え方」の理解に結びつける。","kid":"ノーマルモードのまま文字を打つと、その文字は「入力する文字」ではなく「命令」として実行されてしまう。例えば「d」を2回打つと、1行削除という命令になってしまうことがある。","eg":"たとえるなら、上司に「メモを取って」と言われたと思って話し始めたら、実は「指示を出してください」と言われていた場面。同じ言葉のやり取りでも、役割の勘違いで結果が変わってしまう。","terms":[["ノーマルモード","キー入力を命令として扱うモード"]],"think":"前の設問までで確認したとおり、ノーマルモードではキー入力はすべて命令として解釈される。もし今どちらのモードにいるかを勘違いしたまま文字を打ち続けると、打ったキーの組み合わせ次第で「行を削除する」「カーソルを大きく移動する」といった命令が次々に実行されてしまう。viが自動でモードの勘違いを察知してくれるわけではないので、今どちらのモードにいるかを利用者自身が意識しておく必要がある。","vs":"「打っても無視されるだけで安全」という思い込みに注意。ノーマルモードでのキー入力は、無視されるどころか、意図しない削除や移動といった実害のある命令として実行される。","opt":["正解。打った文字が命令として解釈され、意図しない移動や削除などが実行されてしまう。","無視されるのではなく、命令として積極的に実行されてしまう点が問題になる。","viが自動でモードの勘違いを察知して切り替える機能は無い。","ファイルが自動的に閉じられるわけではない。命令として様々な操作が実行される。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">モード違いで起きる混乱</text>\n<text x=\"85\" y=\"55\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">「dd」と打つ</text>\n<rect x=\"30\" y=\"65\" width=\"100\" height=\"30\" rx=\"6\" fill=\"none\" stroke=\"#60a5fa\"/>\n<text x=\"80\" y=\"84\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ノーマルなら</text>\n<text x=\"80\" y=\"96\" font-size=\"9\" fill=\"#c47070\" text-anchor=\"middle\" font-weight=\"normal\">1行削除</text>\n<rect x=\"210\" y=\"65\" width=\"100\" height=\"30\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"260\" y=\"84\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">インサートなら</text>\n<text x=\"260\" y=\"96\" font-size=\"9\" fill=\"#6ab08d\" text-anchor=\"middle\" font-weight=\"normal\">文字を挿入</text>\n<text x=\"170\" y=\"128\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">同じキー入力でもモードで結果が変わる</text>\n</svg>"}'),

  ('linux-q172', 'viエディタの考え方',
   'テキストエディタで「保存する」という操作は、実際には何をしていることになるか。',
   NULL::text,
   '["画面上（メモリ上）で編集していた変更内容を、ディスク上のファイルとして書き込む","画面上の表示内容を、印刷用のデータに変換する","ディスク上のファイルの内容を、いったんすべて画面上に読み込み直す","編集していた内容を、ネットワーク経由で別のコンピュータへ送信する"]',
   0, '[0]', 'single',
   '{"asked":"「保存」という操作の本質を問う問題。","why_asked":"viに限らず、エディタ全般で「保存」が何をしているかを仕組みから理解しているか確認する基本の論点。","kid":"文字を打っている間、その変更はまだコンピュータの一時的な作業スペース（メモリ）の中にだけある。保存というボタンを押すと、その内容がようやくディスクの中のファイルとして書き込まれる。","eg":"たとえるなら、下書き用紙（メモリ）に鉛筆で書いている状態から、それを清書してノート（ディスク）に書き写す作業のようなもの。清書するまでは、下書き用紙が失われると内容も消えてしまう。","terms":[["メモリ","作業中の内容を一時的に置いておく場所。電源が切れると内容は消える"],["ディスク","ファイルとして内容を長期間保存しておく場所"]],"think":"エディタで文字を打っている間、その変更は一時的にメモリという場所に置かれているだけで、まだディスク上のファイルには反映されていない。もしこの状態で保存せずに終了したり、コンピュータの電源が落ちたりすると、メモリ上の内容は失われ、ディスク上のファイルは編集前のままになる。「保存」という操作は、このメモリ上にある変更内容を、消えないディスク上のファイルへ実際に書き込む操作を指している。","vs":"「保存しなくても変更はすでに反映されている」という誤解に注意。保存を実行するまでは、変更内容はまだ一時的な場所にあるだけで、ディスク上のファイルには反映されていない。","opt":["正解。メモリ上の変更内容を、ディスク上のファイルとして書き込む操作である。","印刷用データへの変換は、保存とは別の操作である。","ファイルを読み込み直すのは、保存とは逆方向の操作（開く操作）である。","ネットワーク経由の送信は、保存とは別の操作（送信・アップロードなど）である。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">保存の正体</text>\n<rect x=\"20\" y=\"45\" width=\"100\" height=\"34\" rx=\"6\" fill=\"#1a2e26\" stroke=\"#60a5fa\"/>\n<text x=\"70\" y=\"63\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">メモリ上の変更</text>\n<defs><marker id=\"ahxz0f3p\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"125\" y1=\"62\" x2=\"190\" y2=\"62\" stroke=\"#60a5fa\" marker-end=\"url(#ahxz0f3p)\"/>\n<rect x=\"195\" y=\"45\" width=\"110\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"250\" y=\"63\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ディスク上のファイル</text>\n<text x=\"170\" y=\"105\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">「保存」とは、いま画面上で編集している内容を</text>\n<text x=\"170\" y=\"118\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ファイルとしてディスクに書き込む操作</text>\n</svg>"}'),

  ('linux-q173', 'viエディタの考え方',
   '通常のGUIエディタの「Ctrlキーを押しながらのショートカット」と比べて、viの「モードを切り替えてから操作する」やり方にはどんな利点があるとされるか。',
   NULL::text,
   '["キーボードから手を離したり修飾キーを押さえたりせず、多くの操作をキーだけで完結できる","モードを使う方が、覚えるべきキーの組み合わせの数が常に少なくて済む","モードを使う方式は、マウスと組み合わせたときにだけ本領を発揮する","モードを使う方式では、そもそも保存や終了といった操作自体が不要になる"]',
   0, '[0]', 'single',
   '{"asked":"モード切り替え方式のショートカットに対する利点を問う問題。","why_asked":"モードという仕組みが「不便な古い遺物」ではなく、実務上の合理性を持っていることを理解しているか確認する。","kid":"Ctrlを押しながら別のキーを押す、というのは指を大きく動かす必要がある。viはモードを切り替えるだけで、あとは1本指でキーを順番に押していくだけで多くの操作ができる。","eg":"たとえるなら、両手で違うボタンを同時に押し続ける操作より、片手で順番にボタンを押していく操作の方が、慣れると素早く楽にできることがある。","terms":[["修飾キー","CtrlやShiftのように、他のキーと組み合わせて別の意味を持たせるキー"]],"think":"Ctrlのような修飾キーを使う方式では、目的の操作のたびに複数の指を同時に押さえる動作が必要になる。一方viのモード方式では、一度モードを切り替えてしまえば、あとは単独のキーを順番に押していくだけで、移動・削除・コピーといった多くの操作をこなせる。この「修飾キーを押さえ続けなくてよい」という点が、キーボードだけで素早く操作したい人にとっての利点として語られる。","vs":"「モード方式は単に古くて不便」という決めつけに注意。不便に感じる場面もある一方で、修飾キーを使わずに済むという明確な合理性がある。","opt":["正解。キーボードから手を離したり修飾キーを押さえたりせず、多くの操作をキーだけで完結できる。","覚える組み合わせの数が常に少なくなるとは限らず、利点の中心はキー操作の効率にある。","マウスとの組み合わせを前提とした利点ではなく、キーボードだけで完結する点が利点である。","保存や終了といった操作自体は、モード方式でも変わらず必要である。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">GUIのショートカットとの違い</text>\n<rect x=\"20\" y=\"45\" width=\"130\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"85\" y=\"63\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">GUI: Ctrlを押しながら</text>\n<rect x=\"190\" y=\"45\" width=\"130\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#60a5fa\"/>\n<text x=\"255\" y=\"63\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">vi: モードで区別</text>\n<text x=\"170\" y=\"105\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">キーボードから手を離さず、修飾キーも</text>\n<text x=\"170\" y=\"118\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">押さずに操作を切り替えられる</text>\n</svg>"}'),

  ('linux-q174', '仮想化とクラウドの基礎',
   '1台の物理サーバーの上で、複数の仮想マシンを同時に動かせるのはなぜか。',
   NULL::text,
   '["ハイパーバイザーというソフトウェアが、物理的な資源を各仮想マシンに分け与えているから","仮想マシンはハードウェアをまったく使わず、完全にソフトウェアだけで動作しているから","物理サーバーの中には、仮想マシンの数と同じだけ物理的なCPUが内蔵されているから","仮想マシンは順番に1台ずつしか動かせず、実際には同時には動いていないから"]',
   0, '[0]', 'single',
   '{"asked":"1台の物理サーバー上で複数の仮想マシンが動く仕組みを問う問題。","why_asked":"仮想化の基本的な仕組み（ハイパーバイザーの役割）を理解しているか確認する導入的な論点。","kid":"ハイパーバイザーというソフトが、1つの物理サーバーが持っているCPUやメモリを、複数の仮想マシンに切り分けて配る仕事をしている。","eg":"たとえるなら、1つの厨房（物理サーバー）を、時間帯や場所を区切って複数の屋台（仮想マシン）に貸し出す差配人のようなもの。厨房自体は1つでも、差配人がうまく割り振ることで複数の屋台が同時に営業できる。","terms":[["ハイパーバイザー","物理的な資源を複数の仮想マシンに分け与える、仮想化を実現するソフトウェア"],["仮想マシン(VM)","ハイパーバイザーによって作られる、独立したコンピュータのように振る舞う環境"]],"think":"物理サーバーが持っているCPUやメモリといった資源は、本来は1つのOSがまるごと専有するものだった。ハイパーバイザーは、この資源を時間や領域で細かく分割し、複数の仮想マシンそれぞれに「自分専用の資源があるかのように」見せかける役割を持つ。各仮想マシンは自分がその資源を独占していると思い込んで動作するが、実際には裏でハイパーバイザーが複数の仮想マシンの間をうまく切り替えたり分け合わせたりしている。","vs":"「仮想マシンはハードウェアを使わない」という誤解に注意。仮想マシンも最終的には物理的なCPUやメモリを使って計算しており、ハイパーバイザーがその使い方を調整しているだけである。","opt":["正解。ハイパーバイザーが物理的な資源を各仮想マシンに分け与えているから。","仮想マシンも最終的には物理的なハードウェアの資源を使って動作している。","仮想マシンの数だけ物理的なCPUが用意されているとは限らない。少ない物理資源を分け合っている。","ハイパーバイザーの働きにより、複数の仮想マシンは実際に並行して動作できる。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"16\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">ハイパーバイザーの役割</text>\n<rect x=\"60\" y=\"78\" width=\"60\" height=\"26\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"90\" y=\"95\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">VM-A</text>\n<rect x=\"140\" y=\"78\" width=\"60\" height=\"26\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"170\" y=\"95\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">VM-B</text>\n<rect x=\"220\" y=\"78\" width=\"60\" height=\"26\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"250\" y=\"95\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">VM-C</text>\n<rect x=\"30\" y=\"45\" width=\"280\" height=\"25\" rx=\"6\" fill=\"#1a2333\" stroke=\"#60a5fa\"/>\n<text x=\"170\" y=\"62\" font-size=\"9.5\" fill=\"#60a5fa\" text-anchor=\"middle\" font-weight=\"normal\">ハイパーバイザー(資源を分け合わせる)</text>\n<rect x=\"30\" y=\"108\" width=\"280\" height=\"20\" rx=\"6\" fill=\"none\" stroke=\"#2a2f3f\"/>\n<text x=\"170\" y=\"122\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">物理サーバー(ハードウェア)</text>\n</svg>"}'),

  ('linux-q175', '仮想化とクラウドの基礎',
   'クラウドサービスで借りる「サーバー」の正体として、最も適切な説明はどれか。',
   NULL::text,
   '["クラウド事業者の物理サーバー上で動く、仮想マシンを間借りしているもの","常に、利用者専用の物理サーバーを1台まるごと購入している状態のこと","実体をまったく持たない、完全に仮想的で計算資源を使わない存在のこと","利用者自身のパソコンの中に、そのまま複製されて動いているもの"]',
   0, '[0]', 'single',
   '{"asked":"クラウドサーバーの正体を問う問題。","why_asked":"「クラウド」という言葉のイメージ先行を解消し、仮想化の話とクラウドの話をつなげる。","kid":"クラウドで借りる「サーバー」は、見た目は1台の専用サーバーのようだけど、実際にはクラウド事業者が持っている大きな物理サーバーの上で動く、仮想マシンの1つを間借りしていることが多い。","eg":"たとえるなら、賃貸マンションの1部屋を借りるようなもの。建物（物理サーバー）自体は大家（クラウド事業者）が所有していて、自分はその中の一区画（仮想マシン）を使わせてもらっている。","terms":[["クラウドサーバー","クラウド事業者の物理サーバー上で動く仮想マシンを、利用者が借りて使う仕組み"]],"think":"「クラウド」という言葉から、実体の無いふわふわしたものをイメージしがちだが、実際にはどこかに存在する物理的なコンピュータ（データセンターの物理サーバー）が土台になっている。前の設問で学んだハイパーバイザーが、その物理サーバーの資源を複数の利用者向けの仮想マシンに分け与えており、クラウドサービスの「サーバーを借りる」という体験は、この仮想マシンの1つを間借りする形で実現されている。","vs":"「クラウド＝物理的な実体が無い」という誤解に注意。裏側には必ずどこかの物理的なデータセンターと物理サーバーが存在し、その上に仮想化の仕組みが乗っている。","opt":["正解。多くの場合、クラウド事業者の物理サーバー上で動く仮想マシンを間借りしている。","専用の物理サーバー1台をまるごと購入するプランも存在するが、一般的なクラウドサーバーの主流の形ではない。","実体を持たないというのは誤りで、最終的には物理的な資源を使っている。","利用者のパソコンの中で動いているのではなく、事業者側のデータセンターで動いている。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">クラウドサーバーの正体</text>\n<text x=\"85\" y=\"60\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">見た目は</text>\n<text x=\"85\" y=\"75\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">1台のサーバー</text>\n<defs><marker id=\"ahiqe7cu\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"150\" y1=\"65\" x2=\"195\" y2=\"65\" stroke=\"#60a5fa\" marker-end=\"url(#ahiqe7cu)\"/>\n<text x=\"260\" y=\"60\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">実際は</text>\n<text x=\"260\" y=\"75\" font-size=\"10\" fill=\"#60a5fa\" text-anchor=\"middle\" font-weight=\"normal\">借りている仮想マシン</text>\n<text x=\"170\" y=\"112\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">クラウド事業者の物理サーバーの上で</text>\n<text x=\"170\" y=\"125\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">動く仮想マシンを間借りしている</text>\n</svg>"}'),

  ('linux-q176', '仮想化とクラウドの基礎',
   'クラウドサービスを利用することの大きな利点として、よく挙げられるものはどれか。',
   NULL::text,
   '["サーバーを自分で所有せず、必要な分だけ借りて、必要に応じて増やしたり減らしたりできること","クラウドを使えば、ネットワークが無い環境でも通信ができるようになること","クラウドサーバーは、常に物理サーバーより高速に計算できることが保証されていること","クラウドを使うと、いかなる場合もサーバー費用が一切かからなくなること"]',
   0, '[0]', 'single',
   '{"asked":"クラウドサービスの利点を問う問題。","why_asked":"「所有から利用へ」というクラウドの本質的な価値を理解しているか確認する。","kid":"自分でサーバーを買って置いておくのではなく、必要なときに必要な分だけ借りて、要らなくなったら返す、ということができる。","eg":"たとえるなら、車を購入して所有する代わりに、必要なときだけレンタカーを借りるようなもの。急に大人数で出かけるときは大きい車を、普段は小さい車を、と柔軟に選べる。","terms":[["所有と利用","自分で買って持ち続けるか、必要な分だけ借りて使うかという2つの考え方"]],"think":"自分でサーバーを買って設置する場合、将来どれくらいの利用者が来るか分からないまま、多めに機材を用意しておく必要があり、余らせても無駄になる。クラウドサービスでは、機材そのものはクラウド事業者が大量に用意しており、利用者は必要な分だけを借りる形になる。利用が増えたときは借りる量を増やし、減ったときは減らす、という調整が柔軟にできる点が、自分で所有する場合には無い利点として語られる。","vs":"「クラウドは常に無料」という誤解に注意。利用した分に応じた費用は発生するのが一般的で、無利用時のコストを抑えられることが利点であり、費用がゼロになるわけではない。","opt":["正解。所有せず、必要な分だけ借りて増減できること。","ネットワーク自体が無い環境で通信ができるようになるわけではない。","速度が常に物理サーバーより優れていると保証されているわけではない。","利用に応じた費用は一般的に発生し、常に無料になるわけではない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">クラウドの利点</text>\n<rect x=\"30\" y=\"45\" width=\"60\" height=\"55\" rx=\"6\" fill=\"none\" stroke=\"#2a2f3f\"/>\n<rect x=\"100\" y=\"55\" width=\"60\" height=\"45\" rx=\"6\" fill=\"none\" stroke=\"#2a2f3f\"/>\n<rect x=\"170\" y=\"65\" width=\"60\" height=\"35\" rx=\"6\" fill=\"none\" stroke=\"#2a2f3f\"/>\n<text x=\"100\" y=\"112\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">所有せず、使った分だけ</text>\n<text x=\"100\" y=\"126\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">増減できる</text>\n<rect x=\"250\" y=\"40\" width=\"70\" height=\"60\" rx=\"6\" fill=\"#1a2e26\" stroke=\"#6ab08d\"/>\n<text x=\"285\" y=\"74\" font-size=\"10\" fill=\"#6ab08d\" text-anchor=\"middle\" font-weight=\"normal\">借りる</text>\n</svg>"}'),

  ('linux-q177', '仮想化とクラウドの基礎',
   '「スケールアップ」と「スケールアウト」の違いは何か。',
   NULL::text,
   '["スケールアップは1台の性能を強化すること、スケールアウトは台数を増やして対応することを指す","スケールアップは台数を増やすこと、スケールアウトは1台の性能を強化することを指す","どちらも同じ意味で、1台の性能を強化することだけを指す","どちらも同じ意味で、台数を増やすことだけを指す"]',
   0, '[0]', 'single',
   '{"asked":"スケールアップとスケールアウトの違いを問う問題。","why_asked":"クラウドで負荷が増えたときの対応方法として、2つの異なる考え方があることを区別できるか確認する。","kid":"スケールアップは「もっと強い1台に買い替える」やり方。スケールアウトは「同じくらいの台数を増やして手分けする」やり方。","eg":"たとえるなら、混雑するレジに対して、スケールアップは「もっと処理の速いレジに交換する」やり方。スケールアウトは「レジの台数を増やして並列に対応する」やり方。","terms":[["スケールアップ","1台あたりの性能(CPUやメモリ)を強化する対応"],["スケールアウト","台数そのものを増やして負荷を分散する対応"]],"think":"サーバーへの負荷が増えて処理が追いつかなくなったとき、対応の方向性は大きく2つある。1つは今動いている1台の性能そのものを強くする方向（スケールアップ）。もう1つは、性能はそのままに台数を増やして、複数台で負荷を分け合う方向（スケールアウト）。クラウドでは、必要なときにサーバーを簡単に増やしたり減らしたりできるため、スケールアウトの方向で対応しやすいという特徴がある。","vs":"「どちらも結局は性能を上げること」という一括りにする誤解に注意。1台を強くするのか、台数を増やして分担するのかという、対応の方向性そのものが異なる。","opt":["正解。スケールアップは1台の性能強化、スケールアウトは台数を増やす対応。","説明が入れ替わっている。台数を増やすのはスケールアウトの方。","スケールアップとスケールアウトは異なる方向の対応であり、同じ意味ではない。","この2つは異なる対応であり、どちらも台数を増やすことだけを指すわけではない。"],"viz":"<svg viewBox=\"0 0 340 160\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"16\" font-size=\"10.5\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">スケールアップ vs スケールアウト</text>\n<rect x=\"50\" y=\"40\" width=\"55\" height=\"26\" rx=\"6\" fill=\"none\" stroke=\"#c9a04a\"/>\n<defs><marker id=\"ahx4mq0z\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#c9a04a\"/></marker></defs><line x1=\"115\" y1=\"53\" x2=\"150\" y2=\"53\" stroke=\"#c9a04a\" marker-end=\"url(#ahx4mq0z)\"/>\n<rect x=\"155\" y=\"34\" width=\"70\" height=\"38\" rx=\"6\" fill=\"none\" stroke=\"#c9a04a\"/>\n<text x=\"170\" y=\"90\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">1台を強くする(アップ)</text>\n<rect x=\"50\" y=\"105\" width=\"36\" height=\"22\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<rect x=\"90\" y=\"105\" width=\"36\" height=\"22\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<rect x=\"130\" y=\"105\" width=\"36\" height=\"22\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"170\" y=\"145\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">台数を増やして分担する(アウト)</text>\n</svg>"}'),

  ('linux-q178', '仮想化とクラウドの基礎',
   '仮想マシンとコンテナを比べたとき、「OSをまるごと持つかどうか」という点でどんな違いがあるか。',
   NULL::text,
   '["仮想マシンはそれぞれが独自のOSをまるごと持つが、コンテナはホストのカーネルを共有する","仮想マシンはホストのカーネルを共有するが、コンテナはそれぞれが独自のOSをまるごと持つ","どちらも独自のOSをまるごと持っており、この点に違いは無い","どちらもOSを一切持たず、アプリケーションだけで完結している"]',
   0, '[0]', 'single',
   '{"asked":"仮想マシンとコンテナのOSの持ち方の違いを復習する問題。","why_asked":"`コンテナの正体`カテゴリで学んだ内容が、仮想化とクラウドの話とつながっていることを確認する。","kid":"仮想マシンは、1台1台が自分専用のOSをまるごと積んでいる。コンテナは、土台となるカーネル(OSの中核)をホストと共有していて、その分だけ身軽になっている。","eg":"たとえるなら、仮想マシンは「1棟まるごと自分専用の家」を持つイメージ。コンテナは「同じ建物（カーネル）の中の、仕切られた部屋」を使うイメージ。","terms":[["カーネル","OSの中核部分。ハードウェアとのやり取りを担う"],["仮想マシン","独自のOSをまるごと持つ、独立度の高い環境"],["コンテナ","ホストのカーネルを共有する、軽量な環境"]],"think":"仮想マシンはハイパーバイザーの上に、それぞれが完全に独立したOS（カーネルを含む）を積んでいる。だから独立性は高いが、その分OSぶんの重さがかかる。コンテナは、ホストが持つ1つのカーネルを複数のコンテナで共有し、その上でアプリケーションの実行環境だけを分離している。カーネルを新たに積む必要が無い分、起動が速く軽量になる。","vs":"「コンテナは軽いVM」という誤解に注意。コンテナはVMを小さくしたものではなく、カーネルを共有するかどうかという、根本的に異なる仕組みで独立性を作っている。","opt":["正解。仮想マシンは独自OSをまるごと持ち、コンテナはホストのカーネルを共有する。","説明が入れ替わっている。独自OSをまるごと持つのは仮想マシンの方。","仮想マシンとコンテナでは、OSの持ち方に明確な違いがある。","どちらもOSの仕組み（少なくともカーネルとのやり取り）を必要としており、完全に無いわけではない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">VMとコンテナ(復習)</text>\n<rect x=\"30\" y=\"40\" width=\"120\" height=\"55\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"90\" y=\"58\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">VM</text>\n<text x=\"90\" y=\"74\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">OSごと持つ</text>\n<text x=\"90\" y=\"88\" font-size=\"8\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">(重い)</text>\n<rect x=\"190\" y=\"40\" width=\"120\" height=\"55\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"250\" y=\"58\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">コンテナ</text>\n<text x=\"250\" y=\"74\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">カーネルは共有</text>\n<text x=\"250\" y=\"88\" font-size=\"8\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">(軽い)</text>\n</svg>"}'),

  ('linux-q179', '仮想化とクラウドの基礎',
   '「物理サーバー → 仮想マシン → クラウド」という流れの中で、一貫して増えていっているものは何か。',
   NULL::text,
   '["自分で持たず、他者から間借りしている度合い","実際に処理できる計算の速さそのものの向上","コンピュータを操作するために必要な専門知識の量","ネットワークに接続せずに使える機能の範囲"]',
   0, '[0]', 'single',
   '{"asked":"仮想化からクラウドへの流れで一貫している変化は何かを問う問題。","why_asked":"このカテゴリで学んだ複数の話（ハイパーバイザー、クラウドの正体、コンテナとの違い）をまとめて振り返る総括的な問題。","kid":"物理サーバーは自分の持ち物。仮想マシンは、ハイパーバイザーが用意した区画を使わせてもらっている状態。クラウドは、その仮想マシンごと他の会社から借りている状態。だんだん「自分の持ち物」の割合が減っていく。","eg":"たとえるなら、「自分の家に住む」→「大家の建物の一室を借りて住む」→「そもそも建物ごと他社が管理している賃貸マンションに住む」というように、自分で所有する範囲がどんどん小さくなっていくイメージ。","terms":[["所有と間借り","自分で持つか、他者の用意したものを使わせてもらうかという区別"]],"think":"物理サーバーの段階では、ハードウェアもソフトウェアもすべて自分たちで所有し管理している。仮想マシンの段階では、ハイパーバイザーが用意した区画（仮想マシン）を使わせてもらう形になり、ハードウェアの管理は間接的になる。クラウドの段階では、その仮想マシンが動く物理サーバーごと、事業者から間借りする形になる。この一連の流れを通して、自分たちで直接所有し管理する範囲がどんどん小さくなり、代わりに他者が用意したものを借りて使う割合が増えていっている。","vs":"「計算速度がどんどん上がっていく話」という誤解に注意。この流れが表しているのは所有形態の変化であり、速度そのものの向上を示すものではない。","opt":["正解。自分で持たず、他者から間借りしている度合いが一貫して増えている。","計算速度は使う機材や契約プランによって決まり、この流れそのものが示す変化ではない。","必要な専門知識の量は、むしろクラウドの管理機能によって減る場合も多く、この流れの一貫した変化ではない。","ネットワークに接続せずに使える範囲は、この流れの中で広がっているわけではない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">「借り物」になっていく流れ</text>\n<text x=\"55\" y=\"60\" font-size=\"10\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">物理</text>\n<defs><marker id=\"ahxf0js7\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"80\" y1=\"55\" x2=\"120\" y2=\"55\" stroke=\"#60a5fa\" marker-end=\"url(#ahxf0js7)\"/>\n<text x=\"160\" y=\"60\" font-size=\"10\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">仮想マシン</text>\n<defs><marker id=\"ah2bkkz6\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"210\" y1=\"55\" x2=\"250\" y2=\"55\" stroke=\"#60a5fa\" marker-end=\"url(#ah2bkkz6)\"/>\n<text x=\"290\" y=\"60\" font-size=\"10\" fill=\"#60a5fa\" text-anchor=\"middle\" font-weight=\"normal\">クラウド</text>\n<text x=\"170\" y=\"100\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ハードウェア→ハイパーバイザー上のVM→</text>\n<text x=\"170\" y=\"113\" font-size=\"8\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">そのVMごと事業者から借りる、という順で借り物が増える</text>\n</svg>"}'),

  ('linux-q180', 'スワップメモリと仮想メモリの仕組み',
   '物理メモリ(RAM)が足りなくなりそうなとき、Linuxはどうやって急場をしのごうとするか。',
   NULL::text,
   '["ディスクの一部をメモリの代わりとして使う「スワップ」という仕組みに、一部のデータを退避させる","メモリを消費しているプロセスを、確認なしにすべて強制終了する","足りない分のメモリを、自動的にネットワーク経由で他のコンピュータから借りてくる","足りなくなった時点で、コンピュータの電源が自動的に落ちるようになっている"]',
   0, '[0]', 'single',
   '{"asked":"メモリ不足時のLinuxの対応（スワップ）を問う問題。","why_asked":"このカテゴリの入り口として、スワップという仕組みが存在する動機を確認する。","kid":"メモリがいっぱいになりそうなとき、あまり使っていないデータをディスクの方に一時的に避難させて、メモリに空きを作る。この避難先がスワップと呼ばれる。","eg":"たとえるなら、机の上（メモリ）が散らかって置き場所が無くなったとき、今すぐ使わない書類を引き出し（ディスク）にしまって、机の上に作業スペースを空けるようなもの。","terms":[["スワップ","メモリが足りないときに、ディスクの一部を代わりに使う仕組み"],["物理メモリ(RAM)","通常、プログラムが実際に読み書きする高速な作業スペース"]],"think":"メモリはプログラムがデータを高速に読み書きするための作業スペースだが、容量には限りがある。もし今すぐ使わないデータまでメモリに置き続けようとすると、本当に今必要なデータのための空きが無くなってしまう。そこでLinuxは、しばらく使われていなさそうなデータを一時的にディスクの方へ移すことで、メモリに空きを作り出す。この退避先として使われるディスク上の領域がスワップである。","vs":"「メモリが足りなくなると必ず処理が止まる」という誤解に注意。スワップという仕組みによって、ある程度までは処理を継続できるようになっている（ただし後の設問で見るように代償もある）。","opt":["正解。ディスクの一部をメモリの代わりとして使うスワップに、一部のデータを退避させる。","メモリ不足だけを理由に、確認なくすべてのプロセスを強制終了するわけではない。","他のコンピュータからメモリを直接借りてくるような仕組みは通常存在しない。","メモリ不足で即座に電源が落ちるわけではなく、まずスワップで対応しようとする。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">メモリが足りなくなると</text>\n<rect x=\"60\" y=\"40\" width=\"220\" height=\"24\" rx=\"6\" fill=\"none\" stroke=\"#c47070\"/>\n<rect x=\"60\" y=\"40\" width=\"220\" height=\"24\" rx=\"6\" fill=\"#2e1a1a\" stroke=\"#2a2f3f\"/>\n<text x=\"170\" y=\"57\" font-size=\"10\" fill=\"#c47070\" text-anchor=\"middle\" font-weight=\"normal\">RAM満杯</text>\n<defs><marker id=\"ahvtlzzv\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#c9a04a\"/></marker></defs><line x1=\"170\" y1=\"70\" x2=\"170\" y2=\"95\" stroke=\"#c9a04a\" marker-end=\"url(#ahvtlzzv)\"/>\n<rect x=\"90\" y=\"100\" width=\"160\" height=\"24\" rx=\"6\" fill=\"none\" stroke=\"#c9a04a\"/>\n<text x=\"170\" y=\"117\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ディスクの一部を借りて急場をしのぐ</text>\n</svg>"}'),

  ('linux-q181', 'スワップメモリと仮想メモリの仕組み',
   '「スワップ領域」の正体は何か。',
   NULL::text,
   '["メモリの代わりとして使うために確保された、ディスク上の場所","メモリチップの中に別途用意された、予備のメモリ専用の領域","インターネット上のクラウドに用意された、外部のバックアップ領域","CPUの内部に直接組み込まれた、超高速な特別な記憶領域"]',
   0, '[0]', 'single',
   '{"asked":"スワップ領域の実体を問う問題。","why_asked":"前の設問の「ディスクに退避させる」という説明を、具体的な場所の話として定着させる。","kid":"スワップ領域は、ハードディスクやSSDの中に、メモリの代わりとして使うために取り分けてある場所のこと。","eg":"たとえるなら、家の中に「普段使わない物を置いておく倉庫スペース」を確保しておくようなもの。倉庫（ディスク）は普段の作業スペース（メモリ）とは別の場所にある。","terms":[["スワップ領域","ディスク上に確保された、メモリの代わりに使うための場所"]],"think":"メモリとディスクは、コンピュータの中の別々の部品である。スワップという仕組みは、この2つの部品のうちディスクの一部を、メモリの役割を一時的に肩代わりする場所として使う、という考え方に基づいている。スワップ領域という言葉は、このディスク上に確保された「肩代わり用の場所」そのものを指している。","vs":"「スワップは特別な追加メモリチップ」という誤解に注意。スワップはあくまでディスク上の場所であり、メモリチップそのものが増えるわけではない。","opt":["正解。メモリの代わりとして使うために確保された、ディスク上の場所である。","メモリチップの中に用意された領域ではなく、ディスク上に確保された領域である。","通常のスワップはコンピュータ内部のディスクであり、インターネット上の外部領域を指すものではない。","CPU内部の特別な記憶領域ではなく、ディスク上の一般的な記憶領域である。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">スワップ領域の正体</text>\n<rect x=\"30\" y=\"45\" width=\"100\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#60a5fa\"/>\n<text x=\"80\" y=\"66\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">メモリ(RAM)</text>\n<rect x=\"210\" y=\"45\" width=\"100\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#c9a04a\"/>\n<text x=\"260\" y=\"63\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ディスクの</text>\n<text x=\"260\" y=\"77\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">一部(スワップ)</text>\n<text x=\"170\" y=\"105\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">スワップはメモリの代わりに使う、</text>\n<text x=\"170\" y=\"118\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ディスク上の場所のこと</text>\n</svg>"}'),

  ('linux-q182', 'スワップメモリと仮想メモリの仕組み',
   'メモリの代わりとして使うスワップが、メモリそのものより処理が遅くなりやすいのはなぜか。',
   NULL::text,
   '["ディスクは、メモリに比べてデータの読み書きにかかる時間が大きく長いから","スワップ領域は、常に暗号化された状態で保存されているから","スワップを使うと、CPUの動作クロックが自動的に下げられるから","スワップ領域は、ネットワークの外部にあるサーバー上に置かれているから"]',
   0, '[0]', 'single',
   '{"asked":"スワップが遅くなる理由を問う問題。","why_asked":"「メモリの代わりになるなら同じくらい速いはず」という誤解を、部品の速度差から正す。","kid":"メモリはデータの出し入れがとても速い部品だけど、ディスクはそれよりずっと出し入れに時間がかかる部品。スワップはそのディスクを使っているので、メモリに比べると遅くなる。","eg":"たとえるなら、机の上の書類（メモリ）を取るのは一瞬だけど、離れた倉庫（ディスク）まで書類を取りに行くのは時間がかかる、というようなもの。","terms":[["ディスク","ハードディスクやSSDのこと。メモリに比べてデータの読み書きに時間がかかる部品"]],"think":"メモリとディスクは、そもそもデータを読み書きする速さがまったく違う部品として作られている。メモリは電気的に瞬時にデータを読み書きできるように設計されているのに対し、ディスクはその何倍、何十倍という時間がかかる。スワップはこの遅いディスクをメモリの代わりに使う仕組みなので、スワップにデータを置いたり取り出したりするたびに、通常のメモリ操作よりずっと長い時間がかかってしまう。","vs":"「スワップも結局メモリと同じ速さのはず」という誤解に注意。スワップはあくまでディスクという別の部品を借りているだけであり、メモリ本来の速さを再現しているわけではない。","opt":["正解。ディスクはメモリに比べて読み書きにかかる時間が大きく長いから。","暗号化の有無が遅さの主な原因ではない。読み書きの速度差そのものが原因。","CPUのクロックが自動的に下げられるという仕組みではない。","スワップ領域は通常コンピュータ内部のディスクであり、ネットワーク越しの外部サーバーではない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">スワップが遅い理由</text>\n<rect x=\"30\" y=\"45\" width=\"100\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#60a5fa\"/>\n<text x=\"80\" y=\"66\" font-size=\"9.5\" fill=\"#60a5fa\" text-anchor=\"middle\" font-weight=\"normal\">メモリ: 速い</text>\n<rect x=\"210\" y=\"45\" width=\"100\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#c47070\"/>\n<text x=\"260\" y=\"66\" font-size=\"9\" fill=\"#c47070\" text-anchor=\"middle\" font-weight=\"normal\">ディスク: 遅い</text>\n<text x=\"170\" y=\"105\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ディスクはメモリより桁違いに</text>\n<text x=\"170\" y=\"118\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">アクセスが遅い部品</text>\n</svg>"}'),

  ('linux-q183', 'スワップメモリと仮想メモリの仕組み',
   'メモリが足りない状態が続き、スワップへの読み書きばかりが繰り返されて、本来の処理がほとんど進まなくなる現象を何と呼ぶか。',
   NULL::text,
   '["スラッシング","デッドロック","キャッシュミス","フラグメンテーション"]',
   0, '[0]', 'single',
   '{"asked":"スワップに頼りすぎた結果起きる現象の名前を問う問題。","why_asked":"スワップが「万能の解決策」ではなく、頼りすぎると弊害があることを理解しているか確認する。","kid":"メモリが全然足りていないと、あっちのデータをスワップに逃がして、こっちのデータをまたメモリに戻して、を延々と繰り返すだけになり、肝心の作業がほとんど進まなくなってしまう。この状態をスラッシングと呼ぶ。","eg":"たとえるなら、机が狭すぎて、書類を出し入れする作業ばかりに追われてしまい、肝心の仕事がまったく進まない状態。","terms":[["スラッシング","スワップへの読み書きばかりが繰り返され、処理がほとんど進まなくなる現象"]],"think":"スワップは一時的にメモリの不足を補う仕組みだが、そもそもメモリが必要な量に対して大きく足りていない状態が続くと、次々とデータをスワップへ出し入れする作業自体に時間を取られてしまう。ディスクへの読み書きは前の設問で見たとおり時間がかかるため、この出し入れが頻発すると、本来の計算処理に使われるはずの時間がどんどん食いつぶされていく。この、退避作業ばかりが延々と続いて実際の処理がほぼ止まってしまう状態をスラッシングと呼ぶ。","vs":"他の選択肢と混同しないこと。デッドロックは複数のプロセスが互いに待ち合って止まる現象、キャッシュミスは求めるデータがキャッシュに無い状態、フラグメンテーションはディスクやメモリの空き領域が細切れになる現象で、いずれもスワップの多用による現象ではない。","opt":["正解。スワップへの読み書きばかりが繰り返され、処理がほとんど進まなくなる現象をスラッシングと呼ぶ。","デッドロックは複数のプロセスが互いに待ち合って止まる現象で、スワップの多用とは別の話。","キャッシュミスは求めるデータがキャッシュに見つからない状態を指し、スワップの多用による現象ではない。","フラグメンテーションは空き領域が細切れになる現象で、スワップの多用そのものを指す言葉ではない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">スラッシング</text>\n<rect x=\"60\" y=\"45\" width=\"90\" height=\"30\" rx=\"6\" fill=\"none\" stroke=\"#c9a04a\"/>\n<text x=\"105\" y=\"64\" font-size=\"8\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">スワップ読み書き</text>\n<defs><marker id=\"ahlywqzc\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#c47070\"/></marker></defs><line x1=\"150\" y1=\"55\" x2=\"190\" y2=\"55\" stroke=\"#c47070\" marker-end=\"url(#ahlywqzc)\"/>\n<defs><marker id=\"ahce4fc9\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#c47070\"/></marker></defs><line x1=\"190\" y1=\"70\" x2=\"150\" y2=\"70\" stroke=\"#c47070\" marker-end=\"url(#ahce4fc9)\"/>\n<rect x=\"195\" y=\"45\" width=\"90\" height=\"30\" rx=\"6\" fill=\"none\" stroke=\"#c47070\"/>\n<text x=\"240\" y=\"64\" font-size=\"8.5\" fill=\"#c47070\" text-anchor=\"middle\" font-weight=\"normal\">処理が進まない</text>\n<text x=\"170\" y=\"105\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">ディスクの読み書きばかりが増えて、</text>\n<text x=\"170\" y=\"118\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">本来の処理がほとんど進まなくなる現象</text>\n</svg>"}'),

  ('linux-q184', 'スワップメモリと仮想メモリの仕組み',
   '「仮想メモリ」という考え方が指しているものとして、最も適切なものはどれか。',
   NULL::text,
   '["各プロセスに、自分専用の連続したメモリ空間があるかのように見せる仕組み","スワップ領域だけで構成された、実在しない架空のメモリ","複数のプロセスが1つのメモリ番地を同時に取り合う仕組み","メモリの容量を、実際より大きく表示するだけの見た目上の機能"]',
   0, '[0]', 'single',
   '{"asked":"仮想メモリという考え方の意味を問う問題。","why_asked":"スワップと混同されやすい「仮想メモリ」という言葉を、正しい意味で区別できるか確認する。","kid":"本当は複数のプロセスが同じ物理メモリを分け合って使っているのに、それぞれのプロセスからは「自分だけの、まとまったメモリ空間がある」ように見えるようにしている。この見せかけの仕組み全体を仮想メモリと呼ぶ。","eg":"たとえるなら、共同のオフィスなのに、それぞれの社員には「自分専用の広い机がある」と感じさせるように、うまく配置と管理を工夫しているようなもの。","terms":[["仮想メモリ","各プロセスに専用のメモリ空間があるかのように見せる仕組み全体"],["プロセス","実行中のプログラムの1つ1つ"]],"think":"複数のプロセスが同時に動いているとき、もし各プロセスが物理メモリの実際の番地を直接奪い合っていたら、管理が複雑になり、互いのデータを誤って上書きする危険も出てくる。そこでLinuxは、各プロセスに対して「あなた専用の、0番地から始まる連続したメモリ空間がありますよ」という見せかけを用意する。実際にはこの見せかけの空間（仮想アドレス）は、裏側で実際の物理メモリの様々な場所や、場合によってはスワップ領域にまで対応づけられている。この「見せかけの、専用に見えるメモリ空間」という考え方全体を仮想メモリと呼ぶ。","vs":"「仮想メモリ＝スワップのこと」という誤解に注意。スワップは仮想メモリの仕組みを支える一部の要素（メモリが足りないときの退避先）にすぎず、仮想メモリという考え方そのものはもっと広い、アドレスの見せかけ全体を指す。","opt":["正解。各プロセスに専用のメモリ空間があるかのように見せる仕組みである。","スワップ領域だけで構成されているわけではなく、物理メモリとの対応づけ全体を含む仕組みである。","各プロセスは互いに干渉せず、専用の空間があるかのように扱われるよう管理されている。","容量の見た目を大きく偽装するだけの機能ではなく、実際のアドレスの対応づけの仕組みである。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">仮想メモリという考え方</text>\n<rect x=\"40\" y=\"45\" width=\"90\" height=\"30\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"85\" y=\"64\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">プロセスA専用</text>\n<rect x=\"210\" y=\"45\" width=\"90\" height=\"30\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"255\" y=\"64\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">プロセスB専用</text>\n<text x=\"170\" y=\"100\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">各プロセスには、自分専用のメモリ空間が</text>\n<text x=\"170\" y=\"113\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">あるかのように見せている</text>\n</svg>"}'),

  ('linux-q185', 'スワップメモリと仮想メモリの仕組み',
   '仮想メモリ上のアドレスと、実際の物理メモリ上のアドレスを対応づける仕組みを何と呼ぶか。',
   NULL::text,
   '["ページング","ルーティング","キャッシング","ミラーリング"]',
   0, '[0]', 'single',
   '{"asked":"仮想アドレスと物理アドレスの対応づけの仕組みの名前を問う問題。","why_asked":"前の設問で説明した仮想メモリの「対応づけ」という動作に、具体的な名前を結びつける。","kid":"仮想メモリの住所と、実際のメモリの住所を結びつける対応表の管理の仕組みを、ページングと呼ぶ。","eg":"たとえるなら、私書箱の番号（仮想アドレス）と、実際の郵便局の棚の場所（物理アドレス）を結びつける対応表を管理する仕組みのようなもの。","terms":[["ページング","仮想アドレスと物理アドレスを、一定の大きさの単位(ページ)で対応づける仕組み"]],"think":"前の設問で見たとおり、各プロセスは自分専用に見えるメモリ空間（仮想アドレス）を持っているが、これは実際の物理メモリの番地とそのままイコールではない。この仮想アドレスと物理アドレスを、一定の大きさの区画（ページ）ごとに結びつけて管理する仕組みがページングである。この対応づけがあるおかげで、あるページの中身を必要に応じてスワップへ逃がしたり、物理メモリの別の場所に移し替えたりといった柔軟な操作が可能になる。","vs":"他の選択肢と混同しないこと。ルーティングはネットワークの経路選択、キャッシングはデータを高速な場所に一時保存する仕組み、ミラーリングは同じデータを複製して保持する仕組みで、いずれもメモリアドレスの対応づけを指す言葉ではない。","opt":["正解。仮想アドレスと物理アドレスを対応づける仕組みをページングと呼ぶ。","ルーティングはネットワークの通信経路を選ぶ仕組みで、メモリアドレスの対応づけとは別の話。","キャッシングはデータを高速な場所に一時保存する仕組みで、アドレスの対応づけそのものではない。","ミラーリングは同じデータを複製して保持する仕組みで、アドレスの対応づけとは別の話。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"sans-serif\">\n<text x=\"170\" y=\"18\" font-size=\"11\" fill=\"#e8eaf0\" text-anchor=\"middle\" font-weight=\"normal\">ページングという対応づけ</text>\n<rect x=\"30\" y=\"45\" width=\"100\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#6ab08d\"/>\n<text x=\"80\" y=\"66\" font-size=\"9.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">仮想アドレス</text>\n<defs><marker id=\"ah5r69f0\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><line x1=\"135\" y1=\"62\" x2=\"195\" y2=\"62\" stroke=\"#60a5fa\" marker-end=\"url(#ah5r69f0)\"/>\n<text x=\"165\" y=\"55\" font-size=\"8\" fill=\"#60a5fa\" text-anchor=\"middle\" font-weight=\"normal\">対応表</text>\n<rect x=\"200\" y=\"45\" width=\"110\" height=\"34\" rx=\"6\" fill=\"none\" stroke=\"#8892a4\"/>\n<text x=\"255\" y=\"66\" font-size=\"8.5\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">実際の物理アドレス</text>\n<text x=\"170\" y=\"105\" font-size=\"9\" fill=\"#8892a4\" text-anchor=\"middle\" font-weight=\"normal\">この対応づけの仕組みをページングと呼ぶ</text>\n</svg>"}')

) AS v(source_ref, category_name, question_text, code, options,
       correct_index, correct_indices, question_type, explanation_data)
  ON c.name = v.category_name AND s.slug = 'linux-basics'
ON CONFLICT (subject_id, source_ref) DO NOTHING;

COMMIT;
