BEGIN;

INSERT INTO public.questions
  (subject_id, category_id, source_ref, question_text, code, options,
   correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, v.source_ref, v.question_text, v.code, v.options::jsonb,
       v.correct_index, v.correct_indices::jsonb, v.question_type, '', v.explanation_data::jsonb, 1
FROM public.subjects s
JOIN public.categories c ON c.subject_id = s.id
JOIN (VALUES

  ('linux-q186', 'よく使うコマンドの覚え方（ファイル操作）',
   'ファイルやディレクトリの一覧を表示する `ls` というコマンド名は、英語の何という単語の略か。',
   NULL::text,
   '["list（一覧を出す、の意味）", "look system（システムを見る、の意味）", "link string（文字列をつなげる、の意味）", "load session（作業状態を読み込む、の意味）"]',
   0, '[0]', 'single',
   '{"asked": "lsコマンドの名前の由来（listの略であること）を問う問題。", "why_asked": "由来を知っていれば、フラグを一つずつ暗記しなくても『一覧を出すコマンドだ』と自然に思い出せる。", "kid": "lsは英語のlist（一覧）を短くした名前。だから打つと、そこにあるファイルの一覧がずらっと出てくる。", "eg": "本棚の中身を『リストアップして』と頼まれたら一覧を書き出すように、lsも『このフォルダの中身をリストアップして』と頼んでいるようなコマンド。", "terms": [["ls", "list（一覧）の略。ディレクトリの中身を一覧表示するコマンド"], ["ディレクトリ", "ファイルをまとめて入れておく入れ物。フォルダと同じもの"]], "think": "英語の単語のまま覚えようとすると、フラグ（-lや-aなど）が増えるたびに丸暗記が増えていく。でも名前がlistの略だと知っていれば、『一覧を出すコマンド』という軸がぶれない。", "vs": "同じ『中身を見る』でも`cat`はファイルの中身そのものを表示するコマンドで、`ls`はファイル名の一覧を表示するコマンド。見るものの粒度が違う。", "opt": ["正解。list（一覧）の略。ファイル名の一覧を表示することからこの名前になった。", "look systemという言葉は一般的な英語表現ではなく、lsの由来としても知られていない。", "link stringも一般的な由来ではない。文字列をつなげる操作はlsの役割ではない。", "load sessionも一般的な由来ではなく、作業状態の読み込みはlsの役割ではない。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">ls</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">l</tspan>ist</text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">一覧を出す</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">l から list、一覧を出すコマンド</text></svg>"}'),

  ('linux-q187', 'よく使うコマンドの覚え方（ファイル操作）',
   '今いる場所（カレントディレクトリ）を移動するときに使う `cd` というコマンド名は、英語の何という言葉の略か。',
   NULL::text,
   '["change directory（ディレクトリを変える、の意味）", "copy data（データをコピーする、の意味）", "create data（データを作る、の意味）", "check directory（ディレクトリを確認する、の意味）"]',
   0, '[0]', 'single',
   '{"asked": "cdコマンドの名前の由来（change directoryの略であること）を問う問題。", "why_asked": "動詞＋対象という組み立てのパターンを知っておくと、他のコマンド名も由来から読み解きやすくなる。", "kid": "cdはchange directory（ディレクトリを変える）を短くした名前。今いる場所を、別のディレクトリに変える、そのままの意味。", "eg": "家の中で『リビングから寝室に移動して』と言われて部屋を移るように、cdは『今の場所から別のフォルダに移動して』というコマンド。", "terms": [["cd", "change directory（ディレクトリを変える）の略"], ["カレントディレクトリ", "今シェルがいる場所（作業ディレクトリ）"]], "think": "change（変える）＋directory（場所）という組み立てだと分かれば、他のコマンド名も同じパターンで読み解きやすくなる。", "vs": "`pwd`は『今どこにいるか』を確認するだけで移動はしない。`cd`は実際に場所を変える点が違う。", "opt": ["正解。change directory（ディレクトリを変える）の略。今いる場所を別のディレクトリに変えるコマンド。", "copy dataという言葉はcdの由来ではない。ファイルの複製は別のコマンド（cp）の役割。", "create dataという言葉もcdの由来ではない。新しいものを作る操作はcdの役割ではない。", "check directoryも一般的な由来ではない。確認だけで移動しない操作は`pwd`に近い。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">cd</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">c</tspan>hange <tspan fill=\"#60a5fa\" font-weight=\"700\">d</tspan>irectory</text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">ディレクトリを変える</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">c-d で change directory</text></svg>"}'),

  ('linux-q188', 'よく使うコマンドの覚え方（ファイル操作）',
   '今シェルがどのディレクトリにいるかを表示する `pwd` というコマンド名は、英語の何という言葉の略か。',
   NULL::text,
   '["print working directory（作業中のディレクトリを表示する、の意味）", "password（合言葉、の意味）", "path with directory（パス付きのディレクトリ、の意味）", "print with data（データ付きで表示する、の意味）"]',
   0, '[0]', 'single',
   '{"asked": "pwdコマンドの名前の由来（print working directoryの略であること）を問う問題。", "why_asked": "綴りの似たpasswordと混同しやすいので、正しい由来を押さえておくと取り違えを防げる。", "kid": "pwdはprint working directory（今作業しているディレクトリを表示する）の略。", "eg": "地図アプリで『現在地はここです』と表示されるように、pwdは『あなたが今シェルの中でどこにいるか』を教えてくれる。", "terms": [["pwd", "print working directory（作業中ディレクトリを表示する）の略"], ["working directory", "今シェルが作業の基準にしている場所"]], "think": "print（表示する）・working（作業中の）・directory（場所）の3つの単語を順につなげただけと分かれば、綴りをそのまま覚える必要がなくなる。", "vs": "pwdと似た綴りのpasswordと混同しやすいが、pwdはパスワードとは無関係。あくまで『今いる場所を表示する』コマンド。", "opt": ["正解。print working directory（作業中のディレクトリを表示する）の略。", "綴りが似ているpasswordと混同しやすいが、pwdコマンドはパスワードの入力や確認とは無関係。", "path with directoryという言葉は一般的な由来ではない。", "print with dataという言葉も一般的な由来ではない。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">pwd</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"42\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">p</tspan>rint <tspan fill=\"#60a5fa\" font-weight=\"700\">w</tspan>orking</text><text x=\"120\" y=\"58\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">d</tspan>irectory</text><text x=\"120\" y=\"76\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">今いる作業場所を表示</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">p-w-d で print working directory</text></svg>"}'),

  ('linux-q189', 'よく使うコマンドの覚え方（ファイル操作）',
   'ファイルを複製するときに使う `cp` というコマンド名は、英語の何という言葉の略か。',
   NULL::text,
   '["copy（複製する、の意味）", "control panel（操作盤、の意味）", "check point（確認地点、の意味）", "compile（変換する、の意味）"]',
   0, '[0]', 'single',
   '{"asked": "cpコマンドの名前の由来（copyの略であること）を問う問題。", "why_asked": "単純な由来だが、`chmod`や`chown`のようなch系コマンドと並べて覚えると整理しやすい。", "kid": "cpはcopy（複製する）を短くした名前。元のファイルはそのまま残して、同じ中身のファイルをもう1つ作る。", "eg": "コンビニのコピー機で書類を複製するように、cpはファイルを複製するコマンド。", "terms": [["cp", "copy（複製する）の略。ファイルを複製するコマンド"]], "think": "動詞copyをそのまま2文字に縮めただけ、という一番シンプルなパターン。", "vs": "`mv`は元のファイルを別の場所に移すだけで複製は残らない。`cp`は元のファイルも残ったまま複製が増える点が違う。", "opt": ["正解。copy（複製する）の略。元のファイルを残したまま同じ中身のファイルをもう1つ作る。", "control panelという言葉はcpの由来ではない。操作盤のようなものはcpの役割ではない。", "check pointという言葉もcpの由来ではない。確認や記録はcpの役割ではない。", "compileという言葉もcpの由来ではない。変換や翻訳はcpの役割ではない。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">cp</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">c</tspan>opy</text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">複製する</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">c-p で copy</text></svg>"}'),

  ('linux-q190', 'よく使うコマンドの覚え方（ファイル操作）',
   'ファイルを別の場所に移したり、名前を変えたりするときに使う `mv` というコマンド名は、英語の何という言葉の略か。',
   NULL::text,
   '["move（移動する、の意味）", "modify version（版を変更する、の意味）", "make virtual（仮想的に作る、の意味）", "merge value（値を統合する、の意味）"]',
   0, '[0]', 'single',
   '{"asked": "mvコマンドの名前の由来（moveの略であること）を問う問題。", "why_asked": "『名前を変える』操作もmvが担う理由を、moveという由来から理解できるかを問う。", "kid": "mvはmove（移動する）を短くした名前。ファイルを別の場所に運ぶ、そのままの意味。", "eg": "家具を部屋の隅から別の場所に動かすように、mvはファイルを別の場所に動かすコマンド。", "terms": [["mv", "move（移動する）の略。ファイルを別の場所に移動するコマンド"]], "think": "『同じ場所のまま名前だけ変える』という操作も、実は『同じ場所へ移動して、違う名前で置き直す』こととして扱われる。だから改名にもmoveが使われる。", "vs": "`cp`は元のファイルを残したまま複製を作るが、`mv`は元の場所からファイルが無くなり、移動先だけに残る点が違う。", "opt": ["正解。move（移動する）の略。ファイルを別の場所に移動するコマンド。名前を変える操作も『同じ場所への移動』として扱われる。", "modify versionという言葉はmvの由来ではない。バージョン管理はmvの役割ではない。", "make virtualという言葉もmvの由来ではない。仮想的な何かを作る操作ではない。", "merge valueという言葉もmvの由来ではない。値を統合する操作ではない。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">mv</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">m</tspan>ove</text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">移動する（名前を変えるのも移動の一種）</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">m-v で move</text></svg>"}'),

  ('linux-q191', 'よく使うコマンドの覚え方（ファイル操作）',
   '新しいディレクトリ（フォルダ）を作るときに使う `mkdir` というコマンド名は、英語の何という言葉を短くしたものか。',
   NULL::text,
   '["make directory（ディレクトリを作る、の意味）", "mark directory（ディレクトリに印を付ける、の意味）", "merge directory（ディレクトリを統合する、の意味）", "move directory（ディレクトリを移動する、の意味）"]',
   0, '[0]', 'single',
   '{"asked": "mkdirコマンドの名前の由来（make directoryの略であること）を問う問題。", "why_asked": "make（作る）＋directory（場所）という組み立てを知っておくと、似た名前の`rmdir`（remove directory）にも応用できる。", "kid": "mkdirはmake directory（ディレクトリを作る）を短くした名前。新しいフォルダを1つ作る、そのままの意味。", "eg": "新しい引き出しを1つ作るように、mkdirは新しいフォルダを1つ作るコマンド。", "terms": [["mkdir", "make directory（ディレクトリを作る）の略"]], "think": "make（作る）とdirectory（場所）をつなげて短くしただけ、というシンプルな組み立て。", "vs": "ファイルを作るのは`touch`のような別のコマンドで、mkdirはあくまでディレクトリ（入れ物）を作る点が違う。", "opt": ["正解。make directory（ディレクトリを作る）の略。新しいフォルダを1つ作るコマンド。", "mark directoryという言葉はmkdirの由来ではない。印を付ける操作ではない。", "merge directoryという言葉もmkdirの由来ではない。統合する操作ではない。", "move directoryという言葉もmkdirの由来ではない。移動する操作ではない。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">mkdir</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">m</tspan>ake <tspan fill=\"#60a5fa\" font-weight=\"700\">d</tspan>irectory</text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">ディレクトリを作る</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">mk-dir で make directory</text></svg>"}'),

  ('linux-q192', 'よく使うコマンドの覚え方（ファイル操作）',
   'ファイルの中身をそのまま表示するときによく使われる `cat` というコマンド名は、英語の何という言葉の略か。',
   NULL::text,
   '["concatenate（つなぎ合わせる、の意味）", "category（分類、の意味）", "catch（つかまえる、の意味）", "catalog（目録、の意味）"]',
   0, '[0]', 'single',
   '{"asked": "catコマンドの名前の由来（concatenateの略であること）を問う問題。", "why_asked": "『catはファイルの中身を表示するコマンド』とだけ覚えると、なぜ猫（cat）と同じ綴りなのか分からず暗記になる。concatenateという由来を知ると、『つなげる』が本来の役割で、表示はその結果に過ぎないと分かる。", "kid": "catはconcatenate（複数のものをつなぎ合わせる）の略。元々は複数のファイルをつなげて1つの流れとして出力するためのコマンドで、ファイルが1つのときはその中身がそのまま画面に出る、という結果になる。", "eg": "紙を何枚も貼り合わせて1本の長い紙にするように、catは複数のファイルをつなげて1つの流れとして出力する。ファイルが1枚だけなら、その1枚がそのまま出てくるように見える。", "terms": [["concatenate", "『つなぎ合わせる』という意味の英単語。catの由来"], ["cat", "concatenateの略。複数のファイルをつなげて出力するコマンド"]], "think": "con-cat-enateという単語の真ん中に『cat』という文字列が隠れている。この部分がそのままコマンド名になった。", "vs": "`less`はファイルを1画面ずつゆっくり読むためのコマンドで、catのように複数ファイルをつなげる用途ではない点が違う。", "opt": ["正解。concatenate（つなぎ合わせる）の略。複数のファイルをつなげて出力する働きに由来する。", "categoryという言葉はcatの由来ではない。分類する操作はcatの役割ではない。", "catchという言葉もcatの由来ではない。何かをつかまえる操作ではない。", "catalogという言葉もcatの由来ではない。目録を作る操作ではない。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">cat</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\">con<tspan fill=\"#60a5fa\" font-weight=\"700\">c</tspan><tspan fill=\"#60a5fa\" font-weight=\"700\">a</tspan><tspan fill=\"#60a5fa\" font-weight=\"700\">t</tspan>enate</text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">つなぎ合わせる</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">con-cat-enate の cat 部分</text></svg>"}'),

  ('linux-q193', 'よく使うコマンドの覚え方（プロセス・検索・権限）',
   '今動いているプロセスの一覧を表示する `ps` というコマンド名は、英語の何という言葉の略か。',
   NULL::text,
   '["process status（プロセスの状態、の意味）", "print string（文字列を表示する、の意味）", "package system（パッケージの仕組み、の意味）", "permission set（権限の設定、の意味）"]',
   0, '[0]', 'single',
   '{"asked": "psコマンドの名前の由来（process statusの略であること）を問う問題。", "why_asked": "由来が分かれば『プロセスの今の状態を見るコマンド』という役割がそのまま思い出せる。", "kid": "psはprocess status（プロセスの状態）を短くした名前。今動いているプロセスが、それぞれどんな状態かを一覧で見せてくれる。", "eg": "教室の出席確認のように、psは『今動いているプロセス』を一人ずつチェックして状態を教えてくれるようなコマンド。", "terms": [["ps", "process status（プロセスの状態）の略"], ["プロセス", "今動いているプログラムの実体"]], "think": "process（プロセス）とstatus（状態）の頭文字をそのまま取っただけ、というシンプルな組み立て。", "vs": "`kill`はプロセスを終了させる側のコマンドで、psは状態を見るだけで何も操作しない点が違う。", "opt": ["正解。process status（プロセスの状態）の略。今動いているプロセスの一覧と状態を表示する。", "print stringという言葉はpsの由来ではない。文字列を表示する専用のコマンドではない。", "package systemという言葉もpsの由来ではない。パッケージ管理の仕組みとは別物。", "permission setという言葉もpsの由来ではない。権限の設定はpsの役割ではない。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">ps</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">p</tspan>rocess <tspan fill=\"#60a5fa\" font-weight=\"700\">s</tspan>tatus</text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">プロセスの状態</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">p-s で process status</text></svg>"}'),

  ('linux-q194', 'よく使うコマンドの覚え方（プロセス・検索・権限）',
   '動いているプロセスを終了させるときに使う `kill` というコマンドの名前について、最も正確な説明はどれか。',
   NULL::text,
   '["「終了させる」という英語の意味そのままの名前で、特定の単語の頭字語ではない", "process kill listenerの略で、プロセスを監視する仕組みの名前である", "kernel initiated logの略で、ログを記録する仕組みの名前である", "key input lockの略で、キー入力を止める仕組みの名前である"]',
   0, '[0]', 'single',
   '{"asked": "killコマンドの名前が頭字語ではなく英語の意味そのままであることを問う問題。", "why_asked": "他のコマンドの多くは頭字語なので、killも何かの略だと思い込みやすい。由来のパターンが1つではないと知っておくと、無理な語呂合わせをせずに済む。", "kid": "killは英語で『終了させる』という意味そのままの言葉で、他の多くのコマンドのような頭字語（頭文字の組み合わせ）ではない。プロセスを終了させるという役割が、そのまま名前になっている。", "eg": "『ストップ』という言葉がそのまま『止める』を意味するように、killも特別な略語ではなく、そのままの意味で名付けられている。", "terms": [["kill", "動いているプロセスに終了の合図（シグナル）を送るコマンド。名前は英語の意味そのまま"], ["シグナル", "プロセスに送る短い合図。killコマンドは既定でSIGTERMという合図を送る"]], "think": "すべてのコマンド名が頭字語だと決めつけると、killのような『そのままの意味』のコマンドに出会ったときに変な語呂合わせを探してしまう。由来には両方のパターンがあると知っておく。", "vs": "SIGTERMとSIGKILLという2種類の合図の違いは`ジョブ管理とシグナル`の回で扱った通り。killコマンドは既定でSIGTERMを送るが、状況に応じて別の合図を指定することもできる。", "opt": ["正解。killは英語の『終了させる』という意味そのままの名前で、頭字語ではない。", "process kill listenerという言葉は一般的な由来として知られていない。", "kernel initiated logという言葉も一般的な由来として知られていない。", "key input lockという言葉も一般的な由来として知られていない。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">kill</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#c9a04a\">kill（動詞そのまま）</tspan></text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">終了させる、頭字語ではない</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">由来は「略語」ばかりとは限らない</text></svg>"}'),

  ('linux-q195', 'よく使うコマンドの覚え方（プロセス・検索・権限）',
   '文字列のパターンで行を検索する `grep` というコマンド名の由来として、最も広く知られているものはどれか。',
   NULL::text,
   '["古いエディタ(ed)で使われていた「g/re/p」という操作（global・regular expression・print）に由来する", "get repeated patternの略で、繰り返しのパターンを取得するという意味である", "green paperの略で、初期のマニュアルの紙の色に由来する", "great performanceの略で、高速な検索性能をアピールした名前である"]',
   0, '[0]', 'single',
   '{"asked": "grepコマンドの名前の由来（edエディタの「g/re/p」操作に由来するという説）を問う問題。", "why_asked": "grepという名前だけ見ると意味不明だが、由来を知ると『全体から・パターンで・表示する』という機能そのものが名前になっていると分かり、忘れにくくなる。", "kid": "grepは、昔のedというテキストエディタで使われていた「g/re/p」という操作コマンドに由来すると広く言われている。gはglobal（全体に）、reはregular expression（正規表現）、pはprint（表示する）の頭文字で、『ファイル全体から正規表現に合う行を探して表示する』という意味。", "eg": "「g/re/p」という呪文のような操作の名前が、そのまま独立したコマンド名として定着したイメージ。", "terms": [["正規表現", "文字列のパターンを表す書き方。『数字が3つ並ぶ』のような柔軟な条件を指定できる"], ["grep", "Global Regular Expression Printに由来するとされる、パターンで行を検索するコマンド"]], "think": "g（global）・re（regular expression）・p（print）という3つの部品がつながって1つのコマンド名になった、という成り立ちで覚える。", "vs": "`テキスト処理の基本`の回で扱った通り、grepは『文字列で行を絞り込む』ことに特化したコマンド。ここではその名前の由来だけを扱う。", "opt": ["正解。edエディタの「g/re/p」操作（global regular expression print）に由来するというのが広く知られた説。", "get repeated patternという言葉は一般的な由来として知られていない。", "green paperという言葉も一般的な由来として知られていない。", "great performanceという言葉も一般的な由来として知られていない。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">grep</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"42\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">g</tspan>lobal <tspan fill=\"#60a5fa\" font-weight=\"700\">r</tspan>egular</text><text x=\"120\" y=\"58\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">e</tspan>xpression <tspan fill=\"#60a5fa\" font-weight=\"700\">p</tspan>rint</text><text x=\"120\" y=\"76\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">edエディタの操作「g/re/p」に由来</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">g-re-p で global regular expression print</text></svg>"}'),

  ('linux-q196', 'よく使うコマンドの覚え方（プロセス・検索・権限）',
   '条件に合うファイルをディレクトリツリーの中から探し出す `find` というコマンドの名前について、最も正確な説明はどれか。',
   NULL::text,
   '["「探す」という英語の意味そのままの名前で、特定の単語の頭字語ではない", "file index nodeの略で、inode番号を検索する仕組みの名前である", "fast internal directoryの略で、高速化の仕組みを表す名前である", "filter and indexの略で、絞り込みと索引付けを表す名前である"]',
   0, '[0]', 'single',
   '{"asked": "findコマンドの名前が頭字語ではなく英語の意味そのままであることを問う問題。", "why_asked": "killと同じく、findも頭字語ではなく単語そのままという由来のパターンを押さえる。", "kid": "findは英語で『探す』という意味そのままの言葉。ディレクトリツリーの中を探して、条件に合うファイルを見つけ出す、という役割がそのまま名前になっている。", "eg": "宝探しで『見つけた！』と言うときの『見つける』が、そのままコマンド名になっているようなイメージ。", "terms": [["find", "ディレクトリツリーの中から条件に合うファイルを探すコマンド。名前は英語の意味そのまま"]], "think": "killと同じパターンで、動詞の意味がそのままコマンド名になっている例。頭字語探しに固執しないことが大事。", "vs": "`ファイル検索とfind/xargsの考え方`の回で扱った通り、findは『探す』専門のコマンドで、見つけたものへの処理はxargsのような別のコマンドに渡す。", "opt": ["正解。findは英語の『探す』という意味そのままの名前で、頭字語ではない。", "file index nodeという言葉は一般的な由来として知られていない。inodeの検索を専門とするコマンドでもない。", "fast internal directoryという言葉も一般的な由来として知られていない。", "filter and indexという言葉も一般的な由来として知られていない。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">find</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#c9a04a\">find（動詞そのまま）</tspan></text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">探す、頭字語ではない</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">killと同じく由来は単語そのまま</text></svg>"}'),

  ('linux-q197', 'よく使うコマンドの覚え方（プロセス・検索・権限）',
   'ファイルの権限（rwx）を変更するときに使う `chmod` というコマンド名は、英語の何という言葉を短くしたものか。',
   NULL::text,
   '["change mode（モードを変える、の意味）", "check module（モジュールを確認する、の意味）", "change model（型式を変える、の意味）", "control mode（モードを制御する、の意味）"]',
   0, '[0]', 'single',
   '{"asked": "chmodコマンドの名前の由来（change modeの略であること）を問う問題。", "why_asked": "『モード』という言葉が権限の許可状態を指すと知っておくと、chmodという名前から役割がすぐ思い出せる。", "kid": "chmodはchange mode（モードを変える）の略。ここでいう『モード』とは、そのファイルの読み書き実行の許可状態のこと。", "eg": "信号機が『赤・青・黄』というモードを切り替えるように、chmodはファイルの『誰が読み書き実行できるか』というモードを切り替える。", "terms": [["chmod", "change mode（モードを変える）の略"], ["モード", "ここではファイルの読み書き実行の許可状態のこと"]], "think": "change（変える）＋mode（状態）とつながっていると分かれば、権限を『モード』という1つの状態として扱っていることも自然に理解できる。", "vs": "権限そのものの仕組み（rwxや所有者/グループ/その他の考え方）は`権限とユーザー`の回で扱った通り。ここではコマンド名の由来だけを扱う。", "opt": ["正解。change mode（モードを変える）の略。ファイルの読み書き実行の許可状態を変えるコマンド。", "check moduleという言葉はchmodの由来ではない。モジュールの確認はchmodの役割ではない。", "change modelという言葉もchmodの由来ではない。型式を変える操作ではない。", "control modeという言葉もchmodの由来ではない。制御というより『変更』が本来の意味。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">chmod</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">c</tspan>hange <tspan fill=\"#60a5fa\" font-weight=\"700\">m</tspan>ode</text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">許可状態（モード）を変える</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">ch-mod で change mode</text></svg>"}'),

  ('linux-q198', 'よく使うコマンドの覚え方（プロセス・検索・権限）',
   'ファイルの所有者を変更するときに使う `chown` というコマンド名は、英語の何という言葉を短くしたものか。',
   NULL::text,
   '["change owner（所有者を変える、の意味）", "check online（オンライン状態を確認する、の意味）", "change output（出力を変える、の意味）", "control owner（所有者を制御する、の意味）"]',
   0, '[0]', 'single',
   '{"asked": "chownコマンドの名前の由来（change ownerの略であること）を問う問題。", "why_asked": "`chmod`と名前の作りが同じ（ch+対象）と気づけば、まとめて覚えやすい。", "kid": "chownはchange owner（所有者を変える）の略。そのファイルが『誰のものか』という情報を書き換える。", "eg": "持ち主の名札を書き換えるように、chownはファイルの持ち主（所有者）を書き換えるコマンド。", "terms": [["chown", "change owner（所有者を変える）の略"], ["所有者", "そのファイルを誰が持っているかという情報"]], "think": "`chmod`と同じ『ch（change）＋対象』という組み立て。対象が『mode（モード）』か『owner（所有者）』かの違いだけ。", "vs": "`chmod`は権限（誰が読み書き実行できるか）を変えるコマンドで、`chown`は持ち主そのものを変えるコマンド。変える対象が違う。", "opt": ["正解。change owner（所有者を変える）の略。ファイルの持ち主の情報を書き換えるコマンド。", "check onlineという言葉はchownの由来ではない。オンライン状態の確認はchownの役割ではない。", "change outputという言葉もchownの由来ではない。出力の変更はchownの役割ではない。", "control ownerという言葉もchownの由来ではない。制御というより『変更』が本来の意味。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">chown</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">c</tspan>hange <tspan fill=\"#60a5fa\" font-weight=\"700\">o</tspan>wner</text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">所有者を変える</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">ch-own で change owner</text></svg>"}'),

  ('linux-q199', 'よく使うコマンドの覚え方（プロセス・検索・権限）',
   '複数のファイルを1つにまとめるときに使う `tar` というコマンド名は、英語の何という言葉に由来するか。',
   NULL::text,
   '["tape archive（磁気テープへの保管、の意味）", "total archive（すべてをまとめた保管、の意味）", "transfer archive（転送用の保管、の意味）", "temporary archive（一時的な保管、の意味）"]',
   0, '[0]', 'single',
   '{"asked": "tarコマンドの名前の由来（tape archiveであること）を問う問題。", "why_asked": "`圧縮とアーカイブの基本`の回で、tarは『まとめる』作業を担うと学んだ。なぜtarという名前なのかを知ると、その役割の由来まで一段深く理解できる。", "kid": "tarはtape archive（磁気テープに保管する）に由来する。昔、データをまとめてテープ装置に書き出すために作られたコマンドで、その名残で今も『複数のファイルを1つにまとめる』役割を担っている。", "eg": "大昔、コンピュータのデータは磁気テープという長いテープに順番に書き込んで保存していた。tarはそのテープにまとめて書き出すための道具として生まれた名前。", "terms": [["tar", "tape archive（磁気テープへの保管）に由来するコマンド"], ["アーカイブ", "複数のファイルを1つにまとめること"]], "think": "tape（テープ）＋archive（保管）という、当時の記憶装置の名残がそのままコマンド名になっている。今はテープに保存することはほぼ無いが、名前だけが今も使われ続けている。", "vs": "`圧縮とアーカイブの基本`で扱った通り、『まとめる（アーカイブ）』作業と『小さくする（圧縮）』作業は別物。tarは元々まとめる側の道具として生まれた。", "opt": ["正解。tape archive（磁気テープへの保管）に由来する。当時の記憶装置にまとめて書き出すための道具として生まれた。", "total archiveという言葉はtarの由来ではない。", "transfer archiveという言葉もtarの由来ではない。", "temporary archiveという言葉もtarの由来ではない。"], "viz": "<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"21\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">tar</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">t</tspan>ape <tspan fill=\"#60a5fa\" font-weight=\"700\">a</tspan>rchive</text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">磁気テープへの保管</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">t-ar で tape archive</text></svg>"}')


) AS v(source_ref, category_name, question_text, code, options,
       correct_index, correct_indices, question_type, explanation_data)
  ON c.name = v.category_name AND s.slug = 'linux-basics'
ON CONFLICT (subject_id, source_ref) DO NOTHING;

COMMIT;