BEGIN;

INSERT INTO public.questions
  (subject_id, category_id, source_ref, question_text, code, options,
   correct_index, correct_indices, question_type, explanation, explanation_data, initial_wrong_weight)
SELECT s.id, c.id, v.source_ref, v.question_text, v.code, v.options::jsonb,
       v.correct_index, v.correct_indices::jsonb, v.question_type, '', v.explanation_data::jsonb, 1
FROM public.subjects s
JOIN public.categories c ON c.subject_id = s.id
JOIN (VALUES

  ('linux-q220', 'よく使うコマンドの覚え方（基本操作の続き）',
   'ファイルやディレクトリを削除する `rm` というコマンド名は、英語の何という単語の略か。',
   NULL::text,
   '["remove（取り除く）", "reduce（減らす）", "return（戻す）", "restore（復元する）"]',
   0, '[0]', 'single',
   '{"asked":"rmコマンドの名前の由来を問う問題。","why_asked":"由来を知っていれば、フラグを一つずつ暗記しなくても『取り除くコマンドだ』と自然に思い出せる。","kid":"rmは英語のremove（取り除く）を短くした名前。だから打つと、そのファイルが取り除かれて消える。","eg":"部屋の片付けで『これ、除けといて』と頼まれたら片付けて無くすように、rmも『このファイルを取り除いて』と頼んでいるコマンド。","terms":[["rm","remove（取り除く）の略。ファイルやディレクトリを削除するコマンド"]],"think":"英単語をそのまま覚えようとするとフラグが増えるたびに丸暗記も増えていく。でも名前がremoveの略だと知っていれば『取り除くコマンドだ』という軸がぶれない。","vs":"似た響きの`reduce`（減らす）と混同しやすいが、rmは『無くす』動作であって、量を『減らす』動作ではない。","opt":["正解。remove（取り除く）の略。ファイルやディレクトリを取り除いて消すことからこの名前になった。","reduce（減らす）という言葉は一般的な英語表現だが、rmの由来としては知られていない。","return（戻す）も一般的な由来ではない。ファイルを戻す操作はrmの役割ではない。","restore（復元する）も一般的な由来ではなく、むしろrmは復元とは逆の削除を行う。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"76\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"54\" y=\"59\" font-family=\"monospace\" font-size=\"20\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">rm</text><text x=\"104\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"120\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">r</tspan>e<tspan fill=\"#60a5fa\" font-weight=\"700\">m</tspan>ove</text><text x=\"120\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">取り除く</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">r + m から remove、取り除くコマンド</text></svg>"}'),

  ('linux-q221', 'よく使うコマンドの覚え方（基本操作の続き）',
   '空のファイルを作ったり、ファイルの更新日時だけを今の時刻に変えたりする `touch` というコマンドの名前は、何に由来するか。',
   NULL::text,
   '["ファイルに軽く触れる、という意味あいから来ている", "textとtouchを組み合わせた略語である", "temporary（一時的な）を短くした略語である", "test outputの頭文字を並べた略語である"]',
   0, '[0]', 'single',
   '{"asked":"touchコマンドの名前の由来を問う問題。","why_asked":"touchは頭字語ではなく普通の英単語の意味そのものが由来という、また別のパターンとして押さえておく回。","kid":"touchは英語で『触れる』という意味。ファイルに軽く触れるだけで、中身は変えずに『最後にいつ触ったか』という時刻の記録だけを今に更新する、というイメージのコマンド。","eg":"本棚の本を1冊手に取ってすぐ戻すと、中身は変わらないけど『最近手に取った本』として記録が残るのと似ている。中身はそのまま、触った記録だけが更新される。","terms":[["touch","『触れる』という意味の英単語がそのまま名前になったコマンド。ファイルが無ければ空のファイルを作り、あれば更新日時だけを更新する"]],"think":"『空ファイルを作るコマンド』とだけ覚えると本来の役割を見失う。本来は『ファイルの更新日時に触れて今の時刻にする』ことが主な役割で、無いファイルに触れようとした結果として空のファイルが作られる、という順番で理解すると腹落ちしやすい。","vs":"`cat`と違い、touchはファイルの中身には一切触れない。変わるのは更新日時という『管理情報』だけ。","opt":["正解。『触れる』という意味の英単語がそのまま由来。ファイルに軽く触れて更新日時を今にする、というイメージ。","textとtouchを組み合わせた略語という由来は一般的には知られていない。","temporaryの略という由来も一般的には知られておらず、touchは一時ファイル専用のコマンドでもない。","test outputの頭文字という由来も一般的には知られていない。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"96\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"64\" y=\"59\" font-family=\"monospace\" font-size=\"16\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">touch</text><text x=\"124\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"140\" y=\"52\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\">touch = 触れる</text><text x=\"140\" y=\"68\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">更新日時だけ今にする</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">中身はそのまま、触った記録だけ更新</text></svg>"}'),

  ('linux-q222', 'よく使うコマンドの覚え方（基本操作の続き）',
   'ファイルの中身を1画面ずつ表示するページャーコマンド `less` は、先に存在した同種のコマンド `more` に対して、どういう洒落から名付けられたか。',
   NULL::text,
   '["「less is more（少ないほうが豊かだ）」ということわざをもじって名付けられた", "less（減らす）はファイルサイズを圧縮する機能から名付けられた", "less（劣った）は`more`より機能が少ない初期版という意味で名付けられた", "less（〜未満）はファイルサイズの上限を表す言葉として名付けられた"]',
   0, '[0]', 'single',
   '{"asked":"lessコマンドの名前の由来（moreとの洒落）を問う問題。","why_asked":"lessはmoreの後継として作られた経緯があり、名前の洒落まで知っていると『moreより高機能』という関係性が腑に落ちる。","kid":"`more`は先にあった『1画面ずつ表示するコマンド』。その後、より高機能な後継が作られたとき、英語のことわざ『less is more（少ないほうが豊かだ）』にかけて、あえて`less`と名付けられた。","eg":"『足るを知る』ということわざのように、名前だけ見ると控えめだが、実際には`more`より前後にスクロールできるなど機能が豊かになっている、という逆説的なネーミング。","terms":[["less","moreの後継として作られた高機能なページャー。ことわざ『less is more』をもじった名前"],["ページャー","ファイルの中身を1画面ずつ区切って表示するプログラムの総称"]],"think":"名前だけを直訳すると『少ない』なので、機能も少なそうに見えてしまう。しかし実際は前方にも後方にもスクロールできるなど`more`より高機能で、名前は洒落によるものだと知っていれば、直感に反する部分を無理に暗記しなくて済む。","vs":"`more`は前にしか進めない（後方スクロールができない）ことが多いのに対し、`less`は前後どちらにもスクロールできる。名前の印象と機能の豊かさが逆転している点がこのコマンドの面白さ。","opt":["正解。『less is more（少ないほうが豊かだ）』ということわざをもじり、moreより高機能な後継としてあえてlessと名付けられた。","圧縮機能は関係がなく、lessはページャー（表示用コマンド）であり圧縮ツールではない。","『劣った初期版』という説は事実と逆で、lessはmoreより高機能な後継として作られた。","ファイルサイズの上限を表す言葉という由来は一般的には知られていない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"30\" y=\"24\" width=\"90\" height=\"40\" rx=\"8\" fill=\"none\" stroke=\"#8892a4\" stroke-width=\"1.4\"/><text x=\"75\" y=\"50\" font-family=\"monospace\" font-size=\"16\" fill=\"#8892a4\" text-anchor=\"middle\">more</text><text x=\"170\" y=\"48\" font-size=\"12\" fill=\"#8892a4\" text-anchor=\"middle\">先に存在</text><rect x=\"220\" y=\"24\" width=\"90\" height=\"40\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.8\"/><text x=\"265\" y=\"50\" font-family=\"monospace\" font-size=\"16\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">less</text><line x1=\"75\" y1=\"64\" x2=\"265\" y2=\"64\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"90\" font-size=\"11.5\" fill=\"#c9a04a\" text-anchor=\"middle\">\"less is more\" のもじり</text><text x=\"170\" y=\"110\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">後継なのに、あえて控えめな名前</text></svg>"}'),

  ('linux-q223', 'よく使うコマンドの覚え方（基本操作の続き）',
   '2つのファイルを比べて、どこが違うかを表示する `diff` というコマンドの名前は、何をそのまま短くしたものか。',
   NULL::text,
   '["difference（違い）", "different（異なる）", "divide（分割する）", "define（定義する）"]',
   0, '[0]', 'single',
   '{"asked":"diffコマンドの名前の由来を問う問題。","why_asked":"diffは非常に頻繁に使う操作の名前で、Gitの差分表示にもそのまま概念が受け継がれている基本コマンド。","kid":"diffはdifference（違い）を短くした名前。2つのファイルを見比べて、その『違い』だけを教えてくれるコマンド。","eg":"2枚の間違い探しの絵を見比べて『ここが違うよ』と指摘してくれる人がいるとしたら、diffコマンドはまさにその役目をファイルに対して行っている。","terms":[["diff","difference（違い）の略。2つのファイルを比較し、異なる行だけを表示するコマンド"]],"think":"名前が『違い』そのものだと知っていれば、細かい出力形式を丸暗記しなくても『2つを比べて違いだけ教えてくれるコマンドだ』という軸で使い方を推測できる。","vs":"`diff`は『どこが違うか』を教えるだけで、ファイル自体を書き換えることはしない。書き換えを伴うマージ作業とは役割が別。","opt":["正解。difference（違い）の略。2つのファイルの違いだけを表示することからこの名前になった。","differentも近い意味の単語だが、コマンド名の由来として一般に言われているのはdifferenceの略という説明。","divide（分割する）は一般的な由来ではなく、diffはファイルを分割する機能ではない。","define（定義する）も一般的な由来ではない。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"90\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"61\" y=\"59\" font-family=\"monospace\" font-size=\"17\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">diff</text><text x=\"118\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"134\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">diff</tspan>erence</text><text x=\"134\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">違い</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">2つのファイルの違いだけを表示</text></svg>"}'),

  ('linux-q224', 'よく使うコマンドの覚え方（基本操作の続き）',
   '与えた文字をそのまま画面に表示する `echo` というコマンドの名前は、どういうイメージから来ているか。',
   NULL::text,
   '["声が壁に反射して返ってくる「こだま（エコー）」のイメージ", "たまごを意味するeggを短くしたイメージ", "電気信号を意味するelectricを短くしたイメージ", "入り口を意味するentranceを短くしたイメージ"]',
   0, '[0]', 'single',
   '{"asked":"echoコマンドの名前の由来を問う問題。","why_asked":"シェルスクリプトの中で最も頻繁に使うコマンドの一つで、名前のイメージを知っていると『入れたものがそのまま返ってくる』という動作を直感的に覚えられる。","kid":"echo（こだま）は、声が壁に当たって跳ね返ってくる現象のこと。echoコマンドも、渡した文字をそのまま画面に跳ね返して表示する、というイメージで名付けられている。","eg":"山に向かって『ヤッホー』と叫ぶと、そのまま『ヤッホー』と返ってくるこだまと同じで、echoコマンドに文字を渡すと、その文字がそのまま画面に返ってくる。","terms":[["echo","こだま（エコー）という意味の英単語。入力した文字列をそのまま出力するコマンド"]],"think":"『こだまのように、渡したものがそのまま返ってくる』というイメージを持っておくと、シェルスクリプトの中で変数の中身を確認したいときなど、echoを使う場面が自然に思い浮かぶようになる。","vs":"`cat`はファイルの中身を表示するコマンドだが、echoはファイルではなく直接渡した文字列や変数の中身を表示する点が違う。","opt":["正解。声がこだま（エコー）のように跳ね返ってくるイメージから、渡した文字をそのまま返す・表示するコマンドとして名付けられた。","egg（たまご）とは無関係。echoとeggは綴りが似ているだけの別の単語。","electric（電気の）とも無関係。","entrance（入り口）とも無関係。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><text x=\"90\" y=\"46\" font-family=\"monospace\" font-size=\"16\" fill=\"#e8eaf0\" text-anchor=\"middle\">echo “yahoo”</text><path d=\"M170 50 L220 50\" stroke=\"#60a5fa\" stroke-width=\"1.5\" marker-end=\"url(#a1)\"/><defs><marker id=\"a1\" markerWidth=\"6\" markerHeight=\"6\" refX=\"5\" refY=\"3\" orient=\"auto\"><path d=\"M0,0 L6,3 L0,6 Z\" fill=\"#60a5fa\"/></marker></defs><text x=\"260\" y=\"46\" font-family=\"monospace\" font-size=\"16\" fill=\"#e8eaf0\" text-anchor=\"middle\">yahoo</text><line x1=\"16\" y1=\"70\" x2=\"324\" y2=\"70\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"96\" font-size=\"11.5\" fill=\"#c9a04a\" text-anchor=\"middle\">こだま（echo）のように、そのまま跳ね返す</text><text x=\"170\" y=\"114\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">渡した文字列をそのまま画面に出す</text></svg>"}'),

  ('linux-q225', 'よく使うコマンドの覚え方（基本操作の続き）',
   '長いコマンドに短い別名を付けられる `alias` というコマンドの名前は、英語の何という単語をそのまま使ったものか。',
   NULL::text,
   '["alias（別名・あだ名）", "allies（同盟者）", "align（整列させる）", "always（常に）"]',
   0, '[0]', 'single',
   '{"asked":"aliasコマンドの名前の由来を問う問題。","why_asked":"aliasは英単語の意味そのものが機能と完全に一致している、非常にわかりやすいパターンの例。","kid":"aliasは『別名・あだ名』という意味の英単語がそのまま名前になっている。よく使う長いコマンドに、短い『あだ名』を付けられるコマンド。","eg":"友達を本名ではなくあだ名で呼ぶように、`ls -la`のような長いコマンドに`ll`のような短い呼び方（あだ名）を付けておくと、毎回長く打たなくて済む。","terms":[["alias","『別名・あだ名』という意味の英単語がそのまま使われたコマンド。長いコマンドに短い別名を付けられる"]],"think":"名前が意味そのものなので、フラグの丸暗記より先に『これはあだ名を付けるコマンドだ』という一言を覚えておけば、細かい使い方は後からでも自然に推測できる。","vs":"`history`（履歴を見る）とは役割が違い、aliasは『コマンドに新しい呼び方を追加する』ためのもので、過去に打ったコマンドを振り返るためのものではない。","opt":["正解。alias（別名・あだ名）という英単語がそのまま名前になっている。","allies（同盟者）はaliasと綴りが似ているが別の単語で、由来ではない。","align（整列させる）も別の単語で、aliasの由来ではない。","always（常に）も別の単語で、aliasの由来ではない。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"100\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"66\" y=\"59\" font-family=\"monospace\" font-size=\"15\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">alias</text><text x=\"128\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"144\" y=\"52\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\">alias = 別名</text><text x=\"144\" y=\"68\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">長いコマンドに短いあだ名</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">意味そのままの名前</text></svg>"}'),

  ('linux-q226', 'よく使うコマンドの覚え方（基本操作の続き）',
   'これまで打ったコマンドの一覧を表示する `history` というコマンドの名前は、英語の何という単語をそのまま使ったものか。',
   NULL::text,
   '["history（履歴・歴史）", "highest（最も高い）", "hidden story（隠された話）", "high speed（高速）"]',
   0, '[0]', 'single',
   '{"asked":"historyコマンドの名前の由来を問う問題。","why_asked":"aliasやsortと同じく『意味そのままの名前』の例をもう一つ押さえておくことで、頭字語系との区別がつきやすくなる。","kid":"historyは『履歴・歴史』という意味の英単語がそのまま名前になっている。これまで打ったコマンドの『歴史』を一覧で見せてくれる。","eg":"日記を読み返すと過去に何をしたか振り返れるように、historyコマンドを打つと、これまでシェルに打ち込んだコマンドの記録を振り返ることができる。","terms":[["history","『履歴・歴史』という意味の英単語がそのまま使われたコマンド。過去に実行したコマンドの一覧を表示する"]],"think":"名前が『歴史』そのものだと知っていれば、細かいオプションを覚えていなくても『過去に打ったコマンドを振り返るコマンドだ』という軸がぶれない。","vs":"`alias`は『これから使う短い呼び方』を作るコマンドで、historyは『過去に実際に打ったもの』を振り返るコマンド。向いている方向（未来か過去か）が逆。","opt":["正解。history（履歴・歴史）という英単語がそのまま名前になっている。","highest（最も高い）はhistoryと綴りの響きが少し似ているが別の単語で、由来ではない。","hidden story（隠された話）という洒落めいた由来は一般的には知られていない。","high speed（高速）とも無関係。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"106\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"69\" y=\"59\" font-family=\"monospace\" font-size=\"14\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">history</text><text x=\"134\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"150\" y=\"52\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\">history = 履歴</text><text x=\"150\" y=\"68\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">打ったコマンドを振り返る</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">過去に打ったコマンドの記録</text></svg>"}'),

  ('linux-q227', 'よく使うコマンドの覚え方（ディスク・マウント）',
   'ディスクをファイルシステムのツリーに取り付ける `mount` というコマンドの名前は、どういうイメージから来ているか。',
   NULL::text,
   '["何かを台に「据え付ける・取り付ける」というイメージ", "山（マウンテン）に登るというイメージ", "たくさんの量を「積み上げる」というイメージ", "モニター（画面）を接続するというイメージ"]',
   0, '[0]', 'single',
   '{"asked":"mountコマンドの名前の由来を問う問題。","why_asked":"『マウント』という言葉自体が『山』のイメージにつられやすいが、実際は『据え付ける』という別の意味が由来という、直感に反する引っかけ。","kid":"mountは英語で『何かを台や壁に据え付ける』という意味。写真をアルバムに『マウントする（貼り付ける）』という使い方があるように、ディスクをファイルシステムのツリーに『据え付ける』作業だから、この名前が使われている。","eg":"絵や写真を台紙に貼り付けて飾ることを『マウントする』と言うように、USBメモリなどのディスクをコンピュータのディレクトリツリーという『台紙』に貼り付けて使えるようにする作業がmount。","terms":[["mount","『据え付ける』という意味の英単語。ディスクをディレクトリツリーの特定の場所に接続し、使えるようにする操作"]],"think":"『マウント』と聞くと山（マウンテン）を連想しがちだが、コマンドの由来は登山ではなく『据え付ける』という意味。台紙に写真を貼るイメージを持っておくと、ディスクを『どこに据え付けるか』という発想が自然に理解できる。","vs":"`ln`（リンクを作る）と混同しやすいが、mountはディスクという記憶装置そのものをツリーに接続する操作で、lnは既にあるファイルに別の名前を付ける操作。扱う対象の粒度が違う。","opt":["正解。『据え付ける・取り付ける』という意味の英単語が由来。ディスクをディレクトリツリーに据え付ける操作をこう呼ぶ。","山（マウンテン）に登るという意味とは無関係で、この由来は一般的には知られていない。","積み上げるという意味とも無関係。","モニター接続という意味とも無関係。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"100\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"66\" y=\"59\" font-family=\"monospace\" font-size=\"15\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">mount</text><text x=\"128\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"144\" y=\"52\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\">mount = 据え付ける</text><text x=\"144\" y=\"68\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">台紙に写真を貼るイメージ</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">ディスクをツリーに据え付ける</text></svg>"}'),

  ('linux-q228', 'よく使うコマンドの覚え方（ディスク・マウント）',
   '据え付けたディスクを取り外す `umount` というコマンドの名前は、どのように成り立っているか。',
   NULL::text,
   '["否定を表す un と mount を組み合わせ、発音しやすいよう un の n を省いた形", "unique（唯一の）と mount を組み合わせた略語", "under（下に）と mount を組み合わせた略語", "update（更新する）と mount を組み合わせた略語"]',
   0, '[0]', 'single',
   '{"asked":"umountコマンドの名前の成り立ちを問う問題。","why_asked":"「なぜun-mountではなくumountとnが1つ少ないのか」は一度知ると忘れない、名前の成り立ちの豆知識。","kid":"英語で『〜しない・逆にする』を表す接頭辞`un`と、据え付けるという意味の`mount`をくっつけると、本来は`unmount`になる。でも発音しやすくするために`n`が1つ省かれて`umount`という名前になっている。","eg":"『取り外す』という意味そのままだが、`un`＋`mount`をそのまま繋げると発音しにくいので、間の子音を1つ削って呼びやすくした、という省略のされ方。","terms":[["umount","un（否定）＋mount（据え付ける）が由来。nを1つ省略した形で『取り外す』という意味になる"]],"think":"『mountの反対＝取り外し』という関係さえ分かっていれば、`umount`という見慣れない綴りも『unmountの省略形』だと気づける。逆に、mountの意味を知らずにumountだけ暗記しようとすると綴りを間違えやすい。","vs":"`mount`が『据え付ける（取り付ける）』なのに対し、`umount`はその逆で『取り外す』。対になる操作として1セットで覚えると忘れにくい。","opt":["正解。un（否定）＋mountの組み合わせで、発音しやすいようnを1つ省いてumountという綴りになっている。","unique（唯一の）とは無関係。","under（下に）とも無関係。","update（更新する）とも無関係。umountはディスクの中身を更新する操作ではない。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><text x=\"170\" y=\"38\" text-anchor=\"middle\" font-size=\"13\" fill=\"#8892a4\">un + mount</text><rect x=\"120\" y=\"52\" width=\"100\" height=\"32\" rx=\"4\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.5\"/><text x=\"170\" y=\"74\" text-anchor=\"middle\" font-size=\"16\" font-family=\"monospace\" fill=\"#e8eaf0\">umount</text><text x=\"170\" y=\"100\" text-anchor=\"middle\" font-size=\"12\" fill=\"#8892a4\">= nを1つ省略した「取り外す」</text></svg>"}'),

  ('linux-q229', 'よく使うコマンドの覚え方（ディスク・マウント）',
   '同じファイルを指す別の名前（リンク）を作る `ln` というコマンドの名前は、何の略か。',
   NULL::text,
   '["link（つなげる）", "line（線を引く）", "length（長さ）", "local（その場所の）"]',
   0, '[0]', 'single',
   '{"asked":"lnコマンドの名前の由来を問う問題。","why_asked":"`リンクという考え方`のカテゴリで仕組み（ハードリンク・シンボリックリンク）は学んだ前提で、ここではコマンド名の由来という別角度に絞る回。","kid":"lnはlink（つなげる）の略。1つのファイルに、別の名前という『つながり』を作るコマンド。","eg":"1人の人に本名とニックネームの両方があっても同一人物であるように、lnコマンドで作った別名も、元のファイルと『つながっている』同じ実体を指す。","terms":[["ln","link（つなげる）の略。ファイルに別の名前（リンク）を作るコマンド"]],"think":"名前がlink（つなげる）の略だと知っていれば、『新しいファイルを複製している』のではなく『同じものへのつながりを増やしている』という仕組みのイメージにも自然につながる。","vs":"`cp`（コピー）と混同しやすいが、cpは中身をまるごと複製した別の実体を作るのに対し、lnは実体はそのままで『名前のつながり』だけを増やす。","opt":["正解。link（つなげる）の略。ファイルに別の名前というつながりを作ることからこの名前になった。","line（線を引く）は似た響きだが由来ではない。","length（長さ）も由来ではない。","local（その場所の）も由来ではない。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"72\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"52\" y=\"59\" font-family=\"monospace\" font-size=\"20\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">ln</text><text x=\"100\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"116\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">l</tspan>i<tspan fill=\"#60a5fa\" font-weight=\"700\">n</tspan>k</text><text x=\"116\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">つなげる</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">l + n から link、別名でつなげる</text></svg>"}'),

  ('linux-q230', 'よく使うコマンドの覚え方（ディスク・マウント）',
   'ディスクの区画（パーティション）を操作する `fdisk` というコマンドの `f` は、もともと何を指していたか。',
   NULL::text,
   '["当時のハードディスクを指す「fixed disk」の f", "ファイル（file）の f", "高速（fast）の f", "全体（full）の f"]',
   0, '[0]', 'single',
   '{"asked":"fdiskコマンドの名前の由来（fixed diskのf）を問う問題。","why_asked":"名前の中の1文字の由来は特に忘れやすいが、当時の時代背景（ハードディスクをfixed diskと呼んでいたこと）を知ると記憶に残りやすい。","kid":"昔はハードディスクのことを『fixed disk（固定されたディスク）』と呼んでいた（持ち運びできるフロッピーディスクと区別するため）。fdiskはその『fixed disk』を操作するコマンドとして名付けられた。","eg":"当時は取り外しできるフロッピーディスクが主流で、コンピュータに固定されたハードディスクは特別に『fixed（固定）』と呼ばれていた。fdiskはその固定ディスクの区画を管理するための道具として生まれた。","terms":[["fdisk","fixed disk（固定ディスク）が由来。ディスクの区画（パーティション）を作成・編集するコマンド"],["パーティション","1つのディスクを複数の区画に区切って、それぞれを別々の領域として扱う仕組み"]],"think":"『f』だけを見ても由来は分からないが、『fixed disk』という当時の呼び方を知っていれば、なぜこのコマンドがディスクの区画を扱うのかという役割まで一緒に腹落ちする。","vs":"`mkfs`（ファイルシステムを作る）と混同しやすいが、fdiskは『ディスクをいくつの区画に分けるか』を決める作業で、mkfsはその区画の中に『ファイルシステムという棚』を作る作業。順番はfdiskが先、mkfsが後。","opt":["正解。fixed disk（固定ディスク）が由来。当時のハードディスクを指す呼び方から名付けられた。","file（ファイル）の略という説明は一般的には知られていない。","fast（高速）の略という説明も一般的には知られていない。","full（全体）の略という説明も一般的には知られていない。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"92\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"62\" y=\"59\" font-family=\"monospace\" font-size=\"16\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">fdisk</text><text x=\"120\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"136\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">f</tspan>ixed disk</text><text x=\"136\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">固定ディスク（＝ハードディスク）</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">ディスクの区画を操作する道具</text></svg>"}'),

  ('linux-q231', 'よく使うコマンドの覚え方（ディスク・マウント）',
   'ディスクの区画にファイルシステムを新しく作る `mkfs` というコマンドの名前は、何の略か。',
   NULL::text,
   '["make file system（ファイルシステムを作る）", "make full storage（フルストレージを作る）", "mark file safe（ファイルに安全マークを付ける）", "move file system（ファイルシステムを移動する）"]',
   0, '[0]', 'single',
   '{"asked":"mkfsコマンドの名前の由来を問う問題。","why_asked":"`mk`という接頭辞（makeの略）は他のコマンド名にも使われる頻出パターンなので、ここで押さえておく。","kid":"mkfsはmake file system（ファイルシステムを作る）の略。区切られたディスクの区画の中に、ファイルを整理して置くための『棚（ファイルシステム）』を新しく組み立てるコマンド。","eg":"引っ越し先の空き部屋（区画）に、まだ何も置かれていない状態から、本棚や収納棚（ファイルシステム）を新しく組み立てて設置するようなイメージ。","terms":[["mkfs","make file system（ファイルシステムを作る）の略。区画の中にファイルシステムを新規作成するコマンド"],["mk","makeの略。他のコマンド名（mkdirなど）にも使われる接頭辞"]],"think":"`mkfs`は`mk`（make）＋`fs`（file system）という2つの略語の組み合わせだと分解できれば、単体の暗記ではなく部品の組み合わせとして覚えられる。","vs":"`fdisk`（区画そのものを作る）とは順番が違う。fdiskで区画（部屋）を区切ってから、mkfsでその中に棚（ファイルシステム）を作る、という2段階の後半にあたる。","opt":["正解。make file system（ファイルシステムを作る）の略。区画にファイルシステムを新規作成するコマンド。","full storage（フルストレージ）は一般的な由来ではない。","mark file safe（安全マークを付ける）は一般的な由来ではない。","move file system（移動する）とも異なり、mkfsは移動ではなく新規作成を行う。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"98\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"65\" y=\"59\" font-family=\"monospace\" font-size=\"15\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">mkfs</text><text x=\"128\" y=\"48\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">mk</tspan>e = make</text><text x=\"128\" y=\"66\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#c9a04a\" font-weight=\"700\">fs</tspan> = file system</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">区画の中にファイルシステムを新規作成</text></svg>"}'),

  ('linux-q232', 'よく使うコマンドの覚え方（ディスク・マウント）',
   'コンピュータに接続されているディスクの一覧を表示する `lsblk` というコマンドの名前は、何の組み合わせか。',
   NULL::text,
   '["ls（一覧を出す）と block devices（ブロックデバイス）の組み合わせ", "list（一覧）と black（黒）の組み合わせ", "less（少ない）と block（塊）の組み合わせ", "local（その場所の）と block（塊）の組み合わせ"]',
   0, '[0]', 'single',
   '{"asked":"lsblkコマンドの名前の由来を問う問題。","why_asked":"既に覚えた`ls`（list）の知識を土台に、新しいコマンド名を分解して読む練習になる回。","kid":"lsblkは、おなじみの`ls`（一覧を出す）と、ディスクなどの記憶装置を指す`block devices`を組み合わせた名前。つまり『ブロックデバイス（ディスク）の一覧を出す』コマンド。","eg":"`ls`が『このフォルダの中身の一覧を出して』なら、`lsblk`は『このコンピュータに繋がっているディスクの一覧を出して』という、対象を絞った兄弟コマンドのようなもの。","terms":[["lsblk","ls（一覧を出す）＋block devices（ブロックデバイス）の略。接続されているディスクの一覧を表示する"],["ブロックデバイス","データを一定の大きさのかたまり（ブロック）単位で読み書きする記憶装置。ハードディスクやUSBメモリなど"]],"think":"`ls`の意味を先に知っていれば、`lsblk`は『新しく覚える単語』ではなく『知っている単語＋新しい単語の組み合わせ』として楽に読み解ける。Linuxのコマンド名にはこの『既存の接頭辞＋新しい対象』というパターンが多い。","vs":"`ls`はファイルやディレクトリの一覧、`lsblk`はディスクという記憶装置そのものの一覧。『何の一覧を出すか』という対象が違うだけで、`ls`という発想の枠組みは共通している。","opt":["正解。ls（一覧を出す）とblock devices（ブロックデバイス）の組み合わせで、接続中のディスクの一覧を表示する。","black（黒）とは無関係で、単なる綴りの偶然の類似。","less（少ない）とも無関係。","local（その場所の）とも無関係。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"100\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"66\" y=\"59\" font-family=\"monospace\" font-size=\"14\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">lsblk</text><text x=\"130\" y=\"48\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">ls</tspan> = 一覧を出す</text><text x=\"130\" y=\"66\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#c9a04a\" font-weight=\"700\">blk</tspan> = block devices</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">接続中のディスクの一覧を出す</text></svg>"}'),

  ('linux-q233', 'よく使うコマンドの覚え方（ディスク・マウント）',
   'ディスクを丸ごとコピーしたり、決まった大きさのデータの塊を1つずつ変換・コピーしたりする `dd` というコマンドの名前について、正しい説明はどれか。',
   NULL::text,
   '["由来にはっきりした定説がなく、複数の説がある珍しいコマンドである", "disk duplicate（ディスク複製）の略であると公式に決められている", "double drive（二重駆動）の略であると公式に決められている", "data delete（データ削除）の略であると公式に決められている"]',
   0, '[0]', 'single',
   '{"asked":"ddコマンドの名前の由来について問う問題。","why_asked":"すべてのコマンド名に確実な由来があるわけではない、という例外もあると知っておくと、無理に丸暗記しようとしなくて済む。","kid":"多くのコマンドには『これが由来』とはっきり言える語源があるが、`dd`は例外的に、由来がはっきりしていない珍しいコマンド。『convert and copyの頭文字を並べ替えた』『IBMの古い言語のコマンド名を真似た』など、複数の説が語られている。","eg":"多くのコマンド名は『これが答え』という一つの由来があるクイズのようなものだが、`dd`だけは『諸説あります』としか言えない、由来不明の言葉のようなもの。","terms":[["dd","ディスクやファイルをブロック単位でそのままコピー・変換するコマンド。名前の由来には複数の説があり、定説がない"]],"think":"『すべてのコマンド名に必ずはっきりした由来がある』と思い込むと、`dd`のような例外に出会ったときに無理に暗記しようとしてしまう。『由来がはっきりしないものもある』と知っておくだけで、それ以上追いかけなくてよいと判断できる。","vs":"`cp`（copy、ファイルをコピーする）と役割が近いように見えるが、`dd`はファイルという単位ではなく、ディスクの中身をブロック単位でそのまま複製できる点が違い、ディスク全体の複製やバックアップに使われる。","opt":["正解。ddは由来にはっきりした定説がなく、複数の説が語られている珍しいコマンドである。","disk duplicateの略であるという公式な定説は存在しない（説の一つとして語られることはある）。","double driveの略であるという公式な定説も存在しない。","data deleteの略であるという公式な定説も存在せず、ddは削除ではなくコピー・変換のためのコマンドである。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"60\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#c9a04a\" stroke-width=\"1.6\"/><text x=\"46\" y=\"59\" font-family=\"monospace\" font-size=\"20\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">dd</text><text x=\"92\" y=\"58\" font-size=\"15\" fill=\"#8892a4\" text-anchor=\"middle\">?</text><text x=\"108\" y=\"46\" font-size=\"11.5\" fill=\"#c9a04a\" text-anchor=\"start\">由来は諸説あり</text><text x=\"108\" y=\"64\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">定説なし（例外的なコマンド）</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">全てのコマンド名に定説があるわけではない</text></svg>"}'),

  ('linux-q234', 'よく使うコマンドの覚え方（ネットワーク診断）',
   '通信相手までデータがどんな経路をたどっているかを1台ずつ調べる `traceroute` というコマンドの名前は、何の組み合わせか。',
   NULL::text,
   '["trace（たどる）と route（経路）の組み合わせ", "track（追跡する）と router（ルーター）の組み合わせ", "transfer（転送する）と remote（遠隔の）の組み合わせ", "test（試す）と router（ルーター）の組み合わせ"]',
   0, '[0]', 'single',
   '{"asked":"tracerouteコマンドの名前の由来を問う問題。","why_asked":"trace＋routeという2つの単語がそのまま合体しているだけの、比較的読み解きやすい名前の例。","kid":"tracerouteはtrace（たどる）とroute（経路）を組み合わせた名前。通信相手にたどり着くまでにどんな経路（どの中継地点）を通っているかを、1つずつたどって調べるコマンド。","eg":"宅配便の荷物がどの配送センターを経由して届いたかを、伝票の履歴で1つずつ確認するようなもの。tracerouteは通信データが通った『経由地』を順番に教えてくれる。","terms":[["traceroute","trace（たどる）＋route（経路）の組み合わせ。通信データが通る経路を中継地点ごとに調べるコマンド"]],"think":"名前が『経路をたどる』という意味そのものだと知っていれば、単に『繋がるかどうか』を見るだけでなく『どこを経由しているか』を見るコマンドだと役割を推測できる。","vs":"`ping`（応答があるかどうかを確認するだけ）と混同しやすいが、pingは相手に届くかどうかの確認、tracerouteは届くまでの経路（中継地点）を1つずつ調べる点が違う。","opt":["正解。trace（たどる）とroute（経路）の組み合わせ。通信データが通る経路を1つずつたどって調べる。","track（追跡する）とrouter（ルーター）の組み合わせという由来は一般的には知られていない。","transferとremoteの組み合わせも由来ではない。","testとrouterの組み合わせも由来ではない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"140\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"86\" y=\"59\" font-family=\"monospace\" font-size=\"14\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">traceroute</text><text x=\"168\" y=\"48\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">trace</tspan> = たどる</text><text x=\"168\" y=\"66\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#c9a04a\" font-weight=\"700\">route</tspan> = 経路</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">通信経路の中継地点を1つずつたどる</text></svg>"}'),

  ('linux-q235', 'よく使うコマンドの覚え方（ネットワーク診断）',
   'ドメイン名からIPアドレスを調べる `nslookup` というコマンドの名前は、何の略か。',
   NULL::text,
   '["name server lookup（ネームサーバーを調べる）", "network status lookup（ネットワーク状態を調べる）", "new server lookup（新しいサーバーを調べる）", "next step lookup（次の手順を調べる）"]',
   0, '[0]', 'single',
   '{"asked":"nslookupコマンドの名前の由来を問う問題。","why_asked":"`DNSの仕組み`のカテゴリで学んだ『名前解決』『DNSサーバー』の知識と、コマンド名の由来を結びつけて理解する回。","kid":"nslookupはname server lookup（ネームサーバーを調べる）の略。ドメイン名をIPアドレスに変換してくれる係（ネームサーバー、つまりDNSサーバー）に、直接『このドメイン名のIPアドレスは何ですか』と尋ねるコマンド。","eg":"電話帳の受付に『この人の電話番号を教えてください』と直接尋ねに行くように、nslookupはDNSサーバー（ネームサーバー）に直接『このドメイン名のIPアドレスを教えて』と尋ねる。","terms":[["nslookup","name server lookup（ネームサーバーを調べる）の略。DNSサーバーに直接問い合わせてドメイン名の名前解決結果を確認するコマンド"],["ネームサーバー","ドメイン名とIPアドレスの対応表を管理しているサーバー。DNSサーバーとも呼ばれる"]],"think":"『DNSの仕組み』で学んだ『名前解決を行うサーバー（ネームサーバー）』という言葉を知っていれば、nslookupの`ns`部分が何を指しているかがすぐに分かる。既に持っている知識と名前の由来が繋がる好例。","vs":"`ping`は相手に届くかどうかの確認だが、nslookupは『名前解決の結果そのもの』を直接確認するコマンドで、確かめている対象が違う。","opt":["正解。name server lookup（ネームサーバーを調べる）の略。DNSサーバーに直接問い合わせるコマンド。","network status lookupという由来は一般的には知られていない。","new server lookupという由来も一般的には知られていない。","next step lookupという由来も一般的には知られていない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"110\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"71\" y=\"59\" font-family=\"monospace\" font-size=\"13\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">nslookup</text><text x=\"140\" y=\"48\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">ns</tspan> = name server</text><text x=\"140\" y=\"66\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\">lookup = 調べる</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">DNSサーバーに直接問い合わせる</text></svg>"}'),

  ('linux-q236', 'よく使うコマンドの覚え方（ネットワーク診断）',
   'nslookupと同じくドメイン名の名前解決を調べられる `dig` というコマンドの名前は、何の略か。',
   NULL::text,
   '["domain information groper（ドメイン情報を探る者）", "digital information gateway（デジタル情報の玄関口）", "direct internet gate（直接インターネットの門）", "data input generator（データ入力の生成器）"]',
   0, '[0]', 'single',
   '{"asked":"digコマンドの名前の由来を問う問題。","why_asked":"digは日常語（掘る）としても馴染みがあるため、実際の由来（略語）とのギャップを押さえておく回。","kid":"digはdomain information groper（ドメイン情報を探る者）の略。groper（グローパー）は『手探りで探す人』という意味で、まるで土を掘って情報を探り出すようなイメージからdigという略称になっている。","eg":"日常の英語で`dig`は『掘る』という意味だが、コマンド名としては『ドメインの情報を掘り出す・探り出す』道具、というイメージで結びつけて覚えると自然。","terms":[["dig","domain information groper（ドメイン情報を探る者）の略。DNSに問い合わせて名前解決の詳しい情報を調べるコマンド"]],"think":"『dig＝掘る』という日常語のイメージと、由来である『domain information groper』の頭文字を組み合わせて覚えると、綴りと意味の両方が記憶に残りやすい。","vs":"`nslookup`と役割は近いが、digの方がより詳しい情報（DNSサーバーからの生の応答内容など）を確認するのに向いているとされ、後発のより高機能なコマインドとして使われることが多い。","opt":["正解。domain information groper（ドメイン情報を探る者）の略。","digital information gatewayという由来は一般的には知られていない。","direct internet gateという由来も一般的には知られていない。","data input generatorという由来も一般的には知られていない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"64\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"48\" y=\"59\" font-family=\"monospace\" font-size=\"19\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">dig</text><text x=\"98\" y=\"46\" font-size=\"11.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">d</tspan>omain <tspan fill=\"#60a5fa\" font-weight=\"700\">i</tspan>nformation</text><text x=\"98\" y=\"62\" font-size=\"11.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">g</tspan>roper（探る者）</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">ドメイン情報を掘り出す道具</text></svg>"}'),

  ('linux-q237', 'よく使うコマンドの覚え方（ネットワーク診断）',
   'そのドメイン名が誰によって登録されているかを調べる `whois` というコマンドの名前は、どのように成り立っているか。',
   NULL::text,
   '["「Who is（誰ですか）」という英語の問いかけの文をそのまま名前にした", "web host information systemの頭文字を並べた略語", "wide host input systemの頭文字を並べた略語", "world host indexの頭文字を並べた略語"]',
   0, '[0]', 'single',
   '{"asked":"whoisコマンドの名前の由来を問う問題。","why_asked":"頭字語ではなく『問いかけの文そのもの』が名前になっている、ユニークなパターンの例。","kid":"whoisは英語の疑問文「Who is（誰ですか）」がそのままくっついて名前になっている。『このドメイン名は一体、誰のものですか？』と尋ねるコマンドだから、この名前になっている。","eg":"知らない人の家の表札を見て『これは誰の家だろう』と尋ねるように、whoisはドメイン名に対して『これは誰が登録した名前ですか』と尋ねている。","terms":[["whois","「Who is（誰ですか）」という疑問文がそのまま名前になったコマンド。ドメイン名の登録者情報を調べる"]],"think":"頭字語だと思って無理に単語を分解しようとすると迷子になるが、『Who is』という文がそのままくっついただけだと知っていれば、綴りをそのまま読み下すだけで意味が分かる。","vs":"`nslookup`や`dig`は『ドメイン名がどのIPアドレスか』という名前解決を調べるのに対し、whoisは『そのドメイン名は誰が登録しているか』という登録者情報を調べる。調べている対象がそもそも違う。","opt":["正解。「Who is（誰ですか）」という疑問文がそのまま名前になっている。","web host information systemという由来は一般的には知られていない。","wide host input systemという由来も一般的には知られていない。","world host indexという由来も一般的には知られていない。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"80\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"56\" y=\"59\" font-family=\"monospace\" font-size=\"16\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">whois</text><text x=\"108\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"124\" y=\"52\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\">Who is ...?</text><text x=\"124\" y=\"68\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">誰が登録した名前ですか</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">問いかけの文そのものが名前</text></svg>"}'),

  ('linux-q238', 'よく使うコマンドの覚え方（ネットワーク診断）',
   '自分のコンピュータに付けられた名前を表示する `hostname` というコマンドの名前は、何をそのまま組み合わせたものか。',
   NULL::text,
   '["host（コンピュータ）と name（名前）", "home（自宅）と network（ネットワーク）", "high（高い）と standard（標準）", "hold（保持する）と node（節点）"]',
   0, '[0]', 'single',
   '{"asked":"hostnameコマンドの名前の由来を問う問題。","why_asked":"ネットワークの世界で『ホスト』という言葉がコンピュータそのものを指す、という前提知識を確認する回。","kid":"ネットワークの世界では、通信に参加している1台1台のコンピュータを『host（ホスト）』と呼ぶ。hostnameは、そのホスト（自分のコンピュータ）に付けられた『名前』をそのまま表示するコマンド。","eg":"パーティーの主催者（ホスト）に名札が付いているように、ネットワークに参加している1台1台のコンピュータにも『ホスト名』という名札が付いている。hostnameはその名札を確認するコマンド。","terms":[["hostname","host（コンピュータ）＋name（名前）の組み合わせ。自分のコンピュータに付けられた名前を表示・設定するコマンド"],["ホスト","ネットワークに接続され、通信に参加している1台1台のコンピュータを指す言葉"]],"think":"『ホスト＝ネットワークに参加している1台のコンピュータ』という言葉の意味を先に知っていれば、hostnameが何を表示するコマンドかは名前を見ただけで分かる。","vs":"`whois`（ドメイン名の登録者を調べる）と混同しやすいが、hostnameは自分自身のコンピュータの名前を確認するコマンドで、他人のドメインの情報を調べるコマンドではない。","opt":["正解。host（コンピュータ）とname（名前）の組み合わせ。自分のコンピュータの名前を表示する。","home（自宅）とnetwork（ネットワーク）の組み合わせという由来は一般的には知られていない。","high（高い）とstandard（標準）の組み合わせという由来も一般的には知られていない。","hold（保持する）とnode（節点）の組み合わせという由来も一般的には知られていない。"],"viz":"<svg viewBox=\"0 0 340 140\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"110\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"71\" y=\"59\" font-family=\"monospace\" font-size=\"13\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">hostname</text><text x=\"140\" y=\"48\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">host</tspan> = コンピュータ</text><text x=\"140\" y=\"66\" font-size=\"12\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#c9a04a\" font-weight=\"700\">name</tspan> = 名前</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">自分のコンピュータの名前を表示</text></svg>"}'),

  ('linux-q239', 'よく使うコマンドの覚え方（ネットワーク診断）',
   'ネットワークの設定を確認・変更する `ip` というコマンドの名前は、何の略か。',
   NULL::text,
   '["internet protocol（インターネットの通信の約束事）", "internal process（内部処理）", "input port（入力の窓口）", "instant ping（即時のping）"]',
   0, '[0]', 'single',
   '{"asked":"ipコマンドの名前の由来を問う問題。","why_asked":"`ネットワークの基礎`で学んだ『IPアドレス』の`IP`と、コマンド名としての`ip`が同じ由来であることを結びつける回。","kid":"ipはinternet protocol（インターネットの通信の約束事）の略。コンピュータ同士が通信するときの住所であるIPアドレスや、通信の設定そのものを確認・変更するコマンドだから、この名前になっている。","eg":"手紙のやり取りには『宛先の書き方』という共通のルールがあるように、インターネットの通信にも『internet protocol』という共通のルールがある。ipコマンドは、そのルールに関わる自分のコンピュータの設定（住所であるIPアドレスなど）を確認・変更する道具。","terms":[["ip","internet protocol（インターネットの通信の約束事）の略。ネットワークの設定（IPアドレスなど）を確認・変更するコマンド"],["IPアドレス","internet protocolのルールに従って、ネットワーク上の1台1台のコンピュータに割り振られる住所のような番号"]],"think":"『ネットワークの基礎』で学んだIPアドレスの`IP`と、このコマンドの`ip`は同じ由来（internet protocol）。既に知っている知識とコマンド名がそのまま一致するので、新しく覚えることは実質ない。","vs":"`hostname`は自分のコンピュータの『名前』を扱うコマンドだが、ipは『住所（IPアドレス）』や通信の設定を扱うコマンドで、扱っている情報の種類が違う。","opt":["正解。internet protocol（インターネットの通信の約束事）の略。IPアドレスなどネットワークの設定を扱う。","internal process（内部処理）という由来は一般的には知られていない。","input port（入力の窓口）という由来も一般的には知られていない。","instant ping（即時のping）という由来も一般的には知られていない。"],"viz":"<svg viewBox=\"0 0 340 130\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"16\" y=\"28\" width=\"56\" height=\"48\" rx=\"8\" fill=\"none\" stroke=\"#3b82f6\" stroke-width=\"1.6\"/><text x=\"44\" y=\"59\" font-family=\"monospace\" font-size=\"20\" font-weight=\"600\" fill=\"#e8eaf0\" text-anchor=\"middle\">ip</text><text x=\"92\" y=\"58\" font-size=\"15\" fill=\"#60a5fa\" text-anchor=\"middle\">&#8594;</text><text x=\"108\" y=\"46\" font-size=\"12.5\" fill=\"#e8eaf0\" text-anchor=\"start\"><tspan fill=\"#60a5fa\" font-weight=\"700\">i</tspan>nternet <tspan fill=\"#60a5fa\" font-weight=\"700\">p</tspan>rotocol</text><text x=\"108\" y=\"66\" font-size=\"11\" fill=\"#8892a4\" text-anchor=\"start\">通信の約束事</text><line x1=\"16\" y1=\"92\" x2=\"324\" y2=\"92\" stroke=\"#2a2f3f\" stroke-width=\"1\"/><text x=\"170\" y=\"112\" font-size=\"10.5\" fill=\"#8892a4\" text-anchor=\"middle\">IPアドレスと同じ由来</text></svg>"}')

) AS v(source_ref, category_name, question_text, code, options,
       correct_index, correct_indices, question_type, explanation_data)
  ON c.name = v.category_name AND s.slug = 'linux-basics'
ON CONFLICT (subject_id, source_ref) DO NOTHING;

COMMIT;
