BEGIN;
UPDATE public.questions SET options='["シンギュラリティ", "ムーアの法則", "AI効果", "チューリングポイント"]'::jsonb WHERE source_ref='g-kentei-b-q4' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["αβ法（枝刈り）", "誤差逆伝播法", "主成分分析", "ブートストラップ法"]'::jsonb WHERE source_ref='g-kentei-b-q6' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["Cyc（サイク）", "AlphaGo", "ImageNet", "GPT"]'::jsonb WHERE source_ref='g-kentei-b-q9' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["サポートベクターマシン", "k-means法", "主成分分析", "ナイーブベイズ分類器"]'::jsonb WHERE source_ref='g-kentei-b-q14' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["バイアスとバリアンス", "次元の呪い", "データリーケージ", "コールドスタート問題"]'::jsonb WHERE source_ref='g-kentei-b-q15' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["標準化（正規化）", "アノテーション", "データ拡張", "次元削減"]'::jsonb WHERE source_ref='g-kentei-b-q17' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["確率的勾配降下法", "主成分分析", "k近傍法", "焼きなまし法"]'::jsonb WHERE source_ref='g-kentei-b-q20' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["早期終了", "ドロップアウト", "バッチ正規化", "データ拡張"]'::jsonb WHERE source_ref='g-kentei-b-q22' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["回帰結合層", "畳み込み層", "全結合層", "プーリング層"]'::jsonb WHERE source_ref='g-kentei-b-q24' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["残差接続", "ドロップアウト", "プーリング", "データ拡張"]'::jsonb WHERE source_ref='g-kentei-b-q25' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["データ拡張", "転移学習", "アノテーション", "次元削減"]'::jsonb WHERE source_ref='g-kentei-b-q26' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["注意機構", "プーリング", "ドロップアウト", "バッチ正規化"]'::jsonb WHERE source_ref='g-kentei-b-q28' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["基盤モデル", "エキスパートシステム", "決定木", "混同行列"]'::jsonb WHERE source_ref='g-kentei-b-q35' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["ゼロショット", "アノテーション", "データ拡張", "ホールドアウト"]'::jsonb WHERE source_ref='g-kentei-b-q36' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["データクレンジング", "デプロイ", "ハイパーパラメータ探索", "バックプロパゲーション"]'::jsonb WHERE source_ref='g-kentei-b-q38' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["適合率", "再現率", "学習率", "エポック数"]'::jsonb WHERE source_ref='g-kentei-b-q40' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
UPDATE public.questions SET options='["バイアス", "ハルシネーション", "過学習", "次元の呪い"]'::jsonb WHERE source_ref='g-kentei-b-q47' AND subject_id=(SELECT id FROM public.subjects WHERE slug='g-kentei-b');
COMMIT;
